### ISSUE TITLE
Allow adding additional attribute lines to password entries

### ISSUE THREAD

**Issue by bluesuncat** [keepassxreboot/keepassxc#9323]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

When creating a user account for an online service, one common strategy against spam and data brokers is to use a throwaway email address. However, that means I now have two keepass entries for every service, one for the login and one for the mail account.
A related issue, exists with storing the security questions some services require.

In theory, one could use the additional attributes in keepass to save the email login or security questions manually, but it is not any more convenient then additional entries.

One solution would be to provide the user with an option to add additional fields to an entry, or perhaps even set the default for the lines per entry determined by the group.

Alternatively, linking entries may be a idea as well, allowing the user to quickly switch tot eh registration email entry from the login entry (and reverse)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

![c](https://user-images.githubusercontent.com/126112804/232154304-70f66100-652a-4f8e-830c-6e71822ccb20.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

This would make password management for accounts related to each other a lot easier and if implemented in a way that allows users to freely customize the default entries, it could also cover security questions and related data, without having to dump it all into the comment field.

**Comment by droidmonkey** [comment]
#8228
