### ISSUE TITLE
Reveal password/notes shows html encoded characters instead of parsed ones

### ISSUE THREAD

**Issue by coert** [keepassxreboot/keepassxc#9327]
## Overview
When you press the eye icon of the password or notes (if hidden) view in the General tab, the password will show the html-encoded characters (\&gt;, \&lt;, etc.) instead of the parsed ones (>,<, etc.). This is very confusing when looking up a password or notes.

## Steps to Reproduce
1. create a password like: "1>2<3&4"
2. press the eye icon in the General tab
3. it will show: "1\&gt;2\&lt;3\&amp;4"

## Expected Behavior
It should show: "1>2<3&4"

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
Update to 2.7.4
