### ISSUE TITLE
Use a font like Courier New for passwords when toggled to visible

### ISSUE THREAD

**Issue by tylermercer** [keepassxreboot/keepassxc#9329]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Use a font that disambiguates similar characters, such as Courier New, for passwords when toggled to visible.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Sometimes I need to log in to an account on another device, such as a public or shared computer. Installing KeePassXC on the new device is undesirable (obviously), so I toggle the password to visible and enter it manually. But the font used makes this very hard. I have taken to copying it into Notepad or another code editor to make it easier to read.

**Comment by phoerious** [comment]
We are using a non-proportional font already. This is simply a regression bug that was already fixed in the upcoming release.
