### ISSUE TITLE
KeePassXC not opening or crashing silently on Windows 10

### ISSUE THREAD

**Issue by adammillere** [keepassxreboot/keepassxc#933]
## Expected Behavior

KeePassXC should open upon double clicking the executable or a kdbx file.

## Current Behavior

The application does not open, and provides no evidence of a failure (through an error message or otherwise).

## Possible Solution

Unfortunately not too sure, perhaps a dependency issue?

## Steps to Reproduce (for bugs)

1. Attempt to open KeePassXC on Windows 10

## Context

I wish I had more information on this honestly everyone, but there just doesn't seem to be much in the way of logging that I know of. This application was working perfectly prior to a recent reinstall of Windows and it hasn't opened since the first time I closed it.

This occurs with both 32 and 64 bit versions, as well as portable and installed versions respectively. The keepassxc-cli is able to extract passwords from it fine as well, and the official KeePass2 client also works fine with this database file.

## Debug Info

(I am going to just write in what I know since that's about all I have)

KeePassXC - 2.2.0
Revision: Not sure

Libraries:
- Not sure

Operating system: Windows 10 Build 15063
CPU architecture: x86_64
Kernel: NT

Enabled extensions:
- None that I know of, other than TOTP key generation

**Comment by droidmonkey** [comment]
Its a result of latent file from single instance. The fix is to delete the file from your temp directory.
