### ISSUE TITLE
Challenge Response stops being recognized after computer restart

### ISSUE THREAD

**Issue by UmBottesWillen** [keepassxreboot/keepassxc#9331]
## Overview
After freshly installing KeePassXC 2.7.4 through apt, using it and the restarting the machine, KeePassXC stops recognizing my challenge response YubiKey.

The issue persists even after performing `apt purge` - `apt install`, so I suspect a broken config file or the like.

The YubiKey is working as expected otherwise. The autotype in Slot 1 of the YubiKey is working in Ubuntu as expected and the key is used to unlock KeePassXC on my Windows machine.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC through the Advanced Packaging Tool (apt)
2. Open a `kdbx` database that is protected with a challenge response
3. Restart the computer
4. Repeat steps 2 and 3 until issue arrises (5 restarts at most in my case)

## Expected Behavior
If the YubiKey is connected, KeePassXC should either automatically detect it or detect it once the `Refresh` button is pressed

## Actual Behavior
The YubiKey is not automatically detected. If the `Refresh` button is pressed, the drop down menu flashes for just a split second, similar to how my working KeePassXC installation flashes on my Windows machine, if no YubiKey is connected.

## Context
Hardware used: Dell Latitude 5430
OS: Ubuntu 20.04.6 LTS 64bit
Desktop Env: GNOME v3.36.8
Windowing System: X11
APT version: 2.0.9 (amd64)

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.6 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-69-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by droidmonkey** [comment]
You likely need to install the yubikey udev rules

**Comment by UmBottesWillen** [comment]
Sorry for only getting back to you now.
To my knowledge, I have udev rules installed.
```
> sudo udevadm --version
245

> dpkg -s libu2f-udev
Package: libu2f-udev
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 26
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Multi-Arch: foreign
Source: libu2f-host
Version: 1.1.10-1
Depends: udev
```

**Comment by droidmonkey** [comment]
No, it is `libyubikey-udev`. https://packages.ubuntu.com/kinetic/libyubikey-udev

**Comment by UmBottesWillen** [comment]
Thanks. While it was unsuccessful at first, after installing the library, restarting the machine, purging and reinstalling KeePassXC, opening and closing the application multiple times and additionally installing `libpam-yubico`, KeePassXC finally started recognizing my YubiKey.
