### ISSUE TITLE
[FR] Add TOTP as second factor for unlocking the database

### ISSUE THREAD

**Issue by DominiqueSite** [keepassxreboot/keepassxc#9333]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Database security can be improved by implementing support for TOTP as a second factor. Hardware keys are expensive and key files provide less security than a TOTP client on a different device.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
-

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I want to use [Aegis](https://github.com/beemdevelopment/Aegis) as a second factor for unlocking my database.

**Comment by droidmonkey** [comment]
This is not possible. TOTP requires a place to store the secret to verify the value. You cannot do this with a client-side only application.
