### ISSUE TITLE
Fetching password through secret service fails if "Confirm when passwords are retrieved" is checked

### ISSUE THREAD

**Issue by phuhl** [keepassxreboot/keepassxc#9334]
## Overview
When having the option "Confirm when passwords are retrieved by clients" is checked in the Secret service tab and I want to access a password (in my case through emacs' secrets.el) a confirmation prompt should pop up. Instead nothing happens and the client recieves an "org.freedesktop.Secret.Error.IsLocked".

![image](https://user-images.githubusercontent.com/16835755/233057236-45a04b81-6f7d-4264-a3cf-974fe8e12339.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable a database "MyDb" with an entry "MyPassword" to be queriable through secret service
2. In Emacs run:
    ```
    (require 'secrets nil t)
    (secrets-open-session)
    (secrets-unlock-collection "MyDb")
    (secrets-get-secret  "MyDb" "MyPassword")
    ```
3. Error org.freedesktop.Secret.Error.IsLocked

## Expected Behavior
A prompt should appear that let's me accept the access request. If I accept, in emacs the password should be retrieved.

## Actual Behavior 
Emacs recieves IsLocked.

## Context
When turning the "Confirm when passwords are retrieved by clients" toggle off, the before-mentioned steps succeed and retrieve the password.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.9
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.2.10-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: river
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is very likely on emacs side and not supporting the approval workflow. Support for secret service is incredibly varied, we have found a few clients that did not implement the protocol correctly or only a small portion of the protocol. KeePassXC follows the standard as best as we can.

I recommend opening a ticket with emacs.

**Comment by phuhl** [comment]
Ok, I see. I am looking at the secret service protocol to make out where the issue might lie within the secrets.el Emacs module. I did not really find anything regarding the approval workflow. Could you point me to the name as in the spec?

**Comment by phuhl** [comment]
Nevermind, you are right, the bug was in secrets.el. Closing

**Comment by phuhl** [comment]
Just fyi if anybody has a similar issue, here is the upstream ticket I opened: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62952
