### ISSUE TITLE
Add option to copy full details of a record into clipboard 

### ISSUE THREAD

**Issue by yaronuliel** [keepassxreboot/keepassxc#9338]
## Summary
In many cases, you might want to extract specific record details.
It would be helpful to add a way to copy full details of the record into clipboard using the context menu or a shortcut.

And extension of this feature might allow the theh user to set different templates in the the app settings, for example:

| Name | Template | Require all details to be non-blank | 
| -- | -- |--|
| Site Credentials | `URL: {{url}}\nUser: {{user}}\nPassword: {{password}}` | Yes |
| Site with TOTP | `URL: {{url}}\nUser: {{user}}\nPassword: {{password}}\nTOTP Token: {{totp_token}}` | No |

Having these templates will add 2 buttons to the `Copy` menu of the record

## Examples

Running the feature will add somethings like the following text to your clipboard for X seconds (same copy functionality used by other clipboard operations in KeepassXC)

```
URL: https://somesite.example.com/login/
Username: demo@example.com
Password: Th3Passw0rd1#5
```

## Context
You might want to send login details to some coleague using tools such as https://onetimesecret.com or https://1ty.me/ 
In my case, as a developer, I often need to pass confidential information that I store on a keepass database to other people, and I do this process manually by copy-pasting each parameter

**Comment by yaronuliel** [comment]
bump

**Comment by droidmonkey** [comment]
You can do this already with Auto-Type.  Define a custom sequence and Auto-Type the data. This is a very niche feature for use by clipboard, and we won't be implementing it, unfortunately. You can also setup something using keepassxc-cli in a script to pull the entry data and format it into something you can use.
