### ISSUE TITLE
After Linux Mint update, database no longer locks after laptop lid closed (Ubuntu LM & Snap Keepassxc)

### ISSUE THREAD

**Issue by noisystuff** [keepassxreboot/keepassxc#9342]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. With Keepassxc database open, close the laptop lid
2. Later open laptop lid and enter Linux login password
3. Keypass database still open

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Keepassxc configured to lock when laptop lid closed (this used to happen, but it stopped working when I upgraded LM; more below).

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After closing laptop lid then later re-opening it (and logging back into LM) Keepassxc database is unlocked.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Using snap version of Keepassxc version 2.7.4 with Ubuntu Linux Mint 20 (x86, 64 bits), everything worked as expected - close lid and database locked when lid was re-opened - but since updating to Linux Mint 21.1 the database does not get locked. I've tried disabling and re-enabling the lock feature, then removing and reinstalling Snap Keepassxc, then removing / purging then reinstalling, but it will not lock the database when the lid's closed. It's not a time-related issue; I can close the lid at night, remove the DC feed to the laptop, then open it in the morning and log in, with Keepassxc still being open. I've considered all the settings in Linux and cannot think of any that could be changed to alter this behavior, so I'm guessing it's an issue with LM; any ideas of what I can next try would be most welcome.
NB Laptop is a Dell XPS 17 9700

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION : 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to make sure the desktop env can send the appropriate dbus signal based on freedesktop.org standards. Additionally, you should switch to our Flatpak distribution.

**Comment by noisystuff** [comment]
Hi
Thank you for the info. I only used snap for mumble and Keepassxc, so I removed snap and instead installed them from Flatpak. Closing the laptop lid now logs me out of the Keepassxc database, so all is now cool again! :-)
Kind regards,
Briain
