### ISSUE TITLE
KeePass XC ignores subdirectories in URL

### ISSUE THREAD

**Issue by Julius-Babies** [keepassxreboot/keepassxc#9344]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have a webserver where the services are in different subdirectories.
My phpMyAdmin is located at /phpmyadmin and Guacamole is located at /guacamole.
I created password records for both services which the path to the service.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC Browser Extension recommends the passwords for this subdirectory.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC Browser Extension recommends the passwords for this domain.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: all
Desktop Env: all
Windowing System: -

**Comment by varjolintu** [comment]
This is a duplicate issue. For now there's no way to force a certain path for the credentials.
