### ISSUE TITLE
Keepassxc download for windows 11 is still missing the MSCV runtime

### ISSUE THREAD

**Issue by TauPan** [keepassxreboot/keepassxc#9345]
Try installing the appropriate runtime library (x64) from here: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

_Originally posted by @phoerious in https://github.com/keepassxreboot/keepassxc/issues/7564#issuecomment-1074842970_
            
I still have to do this in a fresh windows 11 to install keepassxc. Why was the issue closed?

There's a commit that fixes it but it doesn't seem to be part of any branch or release.

**Comment by droidmonkey** [comment]
You have to install it separately we can't do that as part of the msi, it is literally impossible

**Comment by TauPan** [comment]
OK.

But how about a hint on the download page, so people don't have to look on GitHub to find the workaround?

(The chrome add-on for the original KeePass2 is so annoying to work with. KeepassXC is superior by far so lowering the barrier here might help a lot. I've been using it in Linux for years and I was puzzled that it's so hard to install on Windows.)

**Comment by droidmonkey** [comment]
![Screenshot_20230421_071133_Edge.png](https://user-images.githubusercontent.com/2809491/233622105-58c734da-da09-484d-be3d-092994c4d655.png)

**Comment by TauPan** [comment]
Was that there before? I didn't see it.

**Comment by phoerious** [comment]
Yes
