### ISSUE TITLE
drag and drop for moving entries between groups

### ISSUE THREAD

**Issue by Hanter492** [keepassxreboot/keepassxc#9346]
The drag and drop option for moving entries between groups does not work.
I think it would also be good to add some option to move individual entries in the settings of the entry, but that's another thing.

Linux Debian 11 Gnome 44
KeePassXC - V 2.7.4
Rew: 63b2394
Dist: AppImage 2.7.4 and debian 2.7.4

**Comment by droidmonkey** [comment]
This is a qwayland bug (assuming you are using it) not a bug in keepassxc.

**Comment by schiessle** [comment]
I have the same issue with Fedora 38, GNOME 44 using X11. So it can't be a wayland issue only.

**Comment by RedHatTurtle** [comment]
Me too, same issue on OpenSuse Tumbleweed with the package distributed in the default repository

KeePassXC - Version 2.7.4
Revision: 63b2394

**Comment by Hanter492** [comment]
@droidmonkey Can you look at this issue again or explain how to fix it?

**Comment by droidmonkey** [comment]
It is not our issue. Submit a bug report at https://bugreports.qt.io or submit one with your desktop environment. Given the limited sampling above this could be a Gnome 44 problem.
