### ISSUE TITLE
Generating password as a hash of the master password and service name

### ISSUE THREAD

**Issue by andrei-akopian** [keepassxreboot/keepassxc#9347]
## Summary
I have learned about a new way of generating passwords. You take your master password, add the name/url of the service/website you are planning to use that password for and hash it. This method has the advantage that you can log into your account, even if you can't access your password manager (eg. if you are logging into your account from a friend's computer).

## Examples
Due to my terrible programming skills, please bear with this python code. There is space for extra tabs (next to Password and Passphrase) in the password generator window, and I suggest putting it there. 

```python
import hashlib

masterpassword=input("MasterPassword: ") # M@sterP@$$w0rd
serviceURL=input("Service URL: ") # www.collegeboard.org

#supposedly sha3 is the best
print(hashlib.sha3_256((masterpassword+serviceURL).encode()).hexdigest())
#Your new password is 7fa1ebb68f8bdfa3a67fb40186d70c2872358788fe409942a7ecc3a87f3dbb0a
```

## Context
As a student, I am often on my school computer and have to log into school related accounts. Yes, entering your master password on a school computer is not ideal, but I could use a secondary master password, anything is better then having to use a weaker password or opening the password manager form your phone (what if something doesn't work on the phone?) and retyping the password.

Note, whatever implementation you are going to use, please make sure it can be easily downloaded or run in the web browser using JavaScript and make it very clear where you can safely get a version of the algorithm.

**Comment by droidmonkey** [comment]
This is called stateless password management and is generally not a good idea. There are lots of reasons why, and you can find them with a quick Google search. This is definitely not something we would support.
