### ISSUE TITLE
Permit to add AndroidApp1,2... easily in GUI

### ISSUE THREAD

**Issue by tenzap** [keepassxreboot/keepassxc#9348]
## Summary
Keepass2android app supports some additional attributes like KP2A_URL, KP2A_URL_1
These can be added manually on the entry and are also supported by KeepassXC to check alternative domains that the entry works on.

In addition to that, on Android, Keepass2Android makes uses of AndroidApp1, AndroidApp2... attributes to find the app(s) corresponding to an entry.

These additional attributes can already be added manually in KeePassXC, but the thing that is a bit complex is to find the applicationId of the app.

Such an attribute is formatted this way:

Key: `AndroidAppX`(where X is incremental)
Value: `androidapp://<applicationId>`

## Examples
For [github app](https://play.google.com/store/apps/details?id=com.github.android), this would be: 
Key: `AndroidApp1`
Value: `androidapp://com.github.android`

Now on how this could be implemented, I'm unsure. A proposal could be:
![image](https://user-images.githubusercontent.com/46226844/233770038-f0efbc6e-45c8-459d-8f18-79e4e9839b1d.png)
Where the field would be filled with `com.github.android` and with a button to search for the appId on google play for example based on the value in the "Title:" of the entry. When clicking this button, it would list a few apps with their appIds to select from.

This would then reflect with a new line "AndroidApp1" in the Advanced section
![image](https://user-images.githubusercontent.com/46226844/233770084-c591c927-59cf-40bf-8dfe-b7c018298cc8.png)

## Additional info

KP2A_URL_1,2... can also contain an `androidapp://appId` value which could be displayed in the "Android App:" line (below "URL:") too if there is no AndroidApp1 attribute.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Searching the appId & adding it manually is cumbersome, some helper tool would be nice.

Note that there may be multiple apps for a same entry. For example, for an Amazon entry, there could be:
- com.amazon.mShop.android.shopping
- com.amazon.venezia
- ...

**Comment by droidmonkey** [comment]
We won't add this feature, we aren't a mobile app. Both keepassdx and keepass2android add these fields when the entry is used in an app.

**Comment by tenzap** [comment]
Since I always copy my DB from computer to phone (I don't trust app synchronisation) I edit the database on the computer and have to manually put AndroidApp1 there.
This feature would have been nice to have. BTW, AndroidApp1 edition is alse requested here https://github.com/keepassxreboot/keepassxc/issues/5502#issuecomment-973296033

**Comment by droidmonkey** [comment]
Yah that is a better feature to get behind
