### ISSUE TITLE
Auto-type broken in release 2.7.4 ?

### ISSUE THREAD

**Issue by Saroumane** [keepassxreboot/keepassxc#9349]
## Overview
Auto-type function disappeared in release 2.7.4

## Steps to Reproduce
1. Use keepassxc 2.6.6 with Ubuntu 22.10. Auto-type (with a global hotkey) is working perfectly.
2. Upgrade OS to Ubuntu 23.04. keepassxc is upgraded to 2.7.4
3. Auto-type is not working anymore, and the auto-type settings tab has vanished from the UI.

## Expected Behavior
I expect auto-type to work as usual in release 2.7.4
I expect to see the auto-type settings tab in the UI.

## Actual Behavior
Auto-type broken. See below.
![image](https://user-images.githubusercontent.com/22261137/233774287-ab09ed42-5171-4c44-b27e-64bda456cb6c.png)

## Context
Auto-type saves me a lot of time. This feature differentiates keepassxc from a simple password vault.
Please fix this major regression

Note :  the auto-type settings for each login/password entry of the database are still there, but they are useless as there is no way to trigger the auto-type, no global hotkey can be defined.)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 23.04
Desktop Env: Gnome
Windowing System: Wayland

Edit :
I see that keepassxc 2.7.4 has been released in October, 2022. It seems unlikely that this bug would have gone unnoticed for such a long time. So I reported a bug downstream in Ubuntu Launchpad : https://bugs.launchpad.net/ubuntu/+source/keepassxc/+bug/2017338

**Comment by droidmonkey** [comment]
You can't use autotype on Wayland

**Comment by Saroumane** [comment]
Thank you for your quick answer, but I don't understand. I have been using Gnome/Wayland together with keepassxc's autotype for years. It worked flawlessly until I upgraded to keepassxc 2.7.4 together with Ubuntu 23.04.
Something must have changed ? Could it be that before release 2.7.4, keepassxc was running inside XWayland ? And you recently made keepassxc a native wayland application ?

**Comment by droidmonkey** [comment]
Yah that's exactly what it looka like happened (Ubuntu no longer runs X11 at all). Perhaps Ubuntu 23.04 no longer deploys X11 backend by default. You'll have to add it back in and switch to X11 to keep using Auto-Type. 

> And you recently made keepassxc a native wayland application ?

That's not really a thing. We use qt as our ui layer and qt can switch between wayland and x11.

**Comment by Saroumane** [comment]
Nah, I can't go back to X11.
Meanwhile I found a workaround, I just  uninstalled keepassxc deb package and switched to snap package (KeePassXC - Version 2.8.0Revision: 988bb9c). 
Auto-type is back. Please don't break it there :)

**Comment by Saroumane** [comment]
> Yah that's exactly what it looka like happened (Ubuntu no longer runs X11 at all). Perhaps Ubuntu 23.04 no longer deploys X11 backend by default. You'll have to add it back in and switch to X11 to keep using Auto-Type.
> 
> > And you recently made keepassxc a native wayland application ?
> 
> That's not really a thing. We use qt as our ui layer and qt can switch between wayland and x11.

Oh, that's the key point. So the workaround is even easier. I just have to fool keepassxc to make it thinks he runs in X11

`$ XDG_SESSION_TYPE="x11" /usr/bin/keepassxc`

And that's it, Auto-type works again.

**Comment by droidmonkey** [comment]
Yeah, but any app you want to use Auto-Type with also must be running on X11 backend. We didn't break this...
