### ISSUE TITLE
Global Hotkey for 'Add new entry' / Automatically Expand 'Password Generator'

### ISSUE THREAD

**Issue by peternm22** [keepassxreboot/keepassxc#935]
## Expected Behavior
When pressing a certain global hotkey (which would be configurable in the options), the 'Add new entry' dialog box should popup. When the dialog box pops up, the password generator should already be expanded and ready to go.

## Current Behavior
Currently if you want to add a new entry (without using a browser plugin), you have to manually open KeePassXC, then open the 'Add new entry' dialog, and then click the password generator button.

## Context
This would make it a bit simpler to create new entries for new accounts on websites (or elsewhere). The quicker/easier a password manager is, the more likely people will use it.

**Comment by TheZ3ro** [comment]
Currently adding global hotkey is very painful. I plan to fix that in the future
