### ISSUE TITLE
Snap on Kubuntu - Fonts not visible

### ISSUE THREAD

**Issue by sbadux** [keepassxreboot/keepassxc#9352]
## Overview
![immagine](https://user-images.githubusercontent.com/28478027/233826653-b42fc01d-2234-4838-ba20-aafc26d3ea5d.png)

## Steps to Reproduce
Install the keepass snap package on kubuntu 23.04

## Expected Behavior
Fonts should be visibile

## Actual Behavior
Fonts are not visible

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)
Graphics Platform: X11
Processors: 16 × 12th Gen Intel® Core™ i5-1240P

**Comment by droidmonkey** [comment]
We don't support the snap, please use flatpak
