### ISSUE TITLE
keepassxc-cli: be able to add multiline notes

### ISSUE THREAD

**Issue by hydrargyrum** [keepassxreboot/keepassxc#9353]
## Summary

I'm using keepassxc-cli's interactive mode (`keepassxc-cli open DB`) to avoid entering the db password everytime, when using the `add` command, it's not possible to pass multi-line notes.

Maybe support escaping newlines? Or handle quotes? Or alternatively have a new command `set-notes` that allows multiline text.

## Examples

```
add foo --notes "foo
bar"
```
fails

same as
```
add foo --notes "foo\nbar"
```
## Context
Trying to import a `pass` database into keepassxc

**Comment by satyanash** [comment]
@hydrargyrum This is already supported, based on this line: https://github.com/keepassxreboot/keepassxc/blob/4dcd41975d9be75f2e18b533d5443edfbc3752c7/src/cli/Add.cpp#L110

Just escape the escape as such:

```shell
Passwords> add "MyEntry" --notes "this is the first line\\nthis is the second line"
Successfully added entry MyEntry.
Passwords> show MyEntry
Title: MyEntry
UserName: 
Password: 
URL: 
Notes: this is the first line
this is the second line
Uuid: {17ab141e-70cf-4e14-ba4f-e4aea23071be}
Tags: 
```

**Comment by hydrargyrum** [comment]
woah thanks, right what i needed
