### ISSUE TITLE
Record is deleted without confirmation dialog to be displayed

### ISSUE THREAD

**Issue by t5810m** [keepassxreboot/keepassxc#9357]
## Steps to Reproduce
1. Create dummy entry
2. Delete the entry

## Expected Behavior
Confirmation dialog of any kind to be displayed which will inform - warn the user that entry will be deleted.

## Actual Behavior
Record is deleted without warning.

## Context
I first noticed this behavior on version 2.7.0. 
I removed the app, I download the latest version. 
I restarted my computer (Windows 10 x64)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Check your settings, you may have disabled the warning. We send items to the recycle bin of your database by default. Make sure that is enabled as well for your database, Database Menu -> Database Settings.
