### ISSUE TITLE
Prevent scrolling of the entire page when pointing to a multiline text box

### ISSUE THREAD

**Issue by nvllz** [keepassxreboot/keepassxc#9358]
## Overview
When you focus on a text box, say 'Additional Attributes' in Edit Entry > Advanced tab, you can scroll the whole page no matter where you're pointing. It seems to be a problem when you have a custom attribute with multiline text and want to scroll to the bottom line. For me, it often ends up scrolling not only that text box, but the entire screen to the bottom. So I have to scroll the page back to the top. This may apply to other screens as well, and is a bit inconvenient.

## Steps to Reproduce
1. Edit Entry > Advanced
2. Create a new additional attribute, fill the context box with several lines until the vertical scrollbar appears.
3. Scroll down while pointing at the box. Based on your experience, you may expect only this text box to scroll, but when it reaches the bottom of the text area, the rest of the page will also scroll down.

## Expected Behavior
I want the program to prevent the entire page from scrolling when the user's cursor is inside a multiline (with a visible scrollbar) text box.

## Actual behavior
When the scrollbar reaches the bottom and the user continues to scroll down while pointing at the text box, the entire page starts to scroll up.

**Comment by droidmonkey** [comment]
Hmmmmm what you are describing is behavior implemented by Qt, not us. Therefore I am inclined to say that it is the _expected behavior_ based on the platform you are on (Mac, win, linux). We won't be implementing a change here as a result. 

If you think this behavior is not expected we recommend filing a bug report at https://bugreports.qt.io
