### ISSUE TITLE
Add favicon download button next to URL field in entry edit

### ISSUE THREAD

**Issue by peternm22** [keepassxreboot/keepassxc#936]
## Expected Behavior
When adding a new entry, have a checkbox underneath the URL to "Download Favicon". KeePassXC would remember whether or not this box was checked for future entries. If this checkbox is checked, the Favicon would automatically be downloaded when the new entry is added.

## Current Behavior
When created a new entry, if you want to download the Favicon you need to first enter the URL. Then click Icon, and then click 'Download Favicon'.

## Context
If someone wants to use favicons for their entries, chances are they will want to do it every time they want to add a new entry. No reason for extra steps to do this.
I see there is a similar feature request to have an item in the Tools menu to download all Favicons, so this feature request is slightly different.

**Comment by droidmonkey** [comment]
This will not happen since we are taking the position that any network action is due to deliberate user request.

**Comment by oxysoft** [comment]
Please re-open this and make it a configurable option. I hate having to switch tab to click "Download favicon" every single time.

**Comment by droidmonkey** [comment]
I'd rather add a button next to the url field that triggers a favicon download.

**Comment by oxysoft** [comment]
I'm okay with that compromise!
