### ISSUE TITLE
Display messed up in strange manner

### ISSUE THREAD

**Issue by matthiasschroder** [keepassxreboot/keepassxc#9360]
## Overview
When KPXC has been open for a while the contents of the main window gets messed up in a strange way. It looks as if the characters of the individual strings are displayed one above the other. Makes it very difficult to read.

When this happens I can not take a screenshot of the window, trying to take a screenshot of part of the window shows the contents of the  window behind the KPXC window.

## Steps to Reproduce
1. Start KPXC
2. Leave it running for a while (presumably in the background)
3. Bring XPXC main window in foreground and unlock it.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to get a clear main window in which I can identify the individual entries

## Actual Behavior
I get a window in which the strings are unreadable.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 13 (mostly betas)
Hardware: M1 Pro

**Comment by droidmonkey** [comment]
This was a bug in macos that went away, I think with 13.1

**Comment by matthiasschroder** [comment]
Well I'm currently running macOS 13.4 b2, and the issue is still there. I don't recall any 13.x version in which the issue was not present.

**Comment by droidmonkey** [comment]
Sorry, this is a qt bug, not macOS bug.  #8758
