### ISSUE TITLE
Auto-Type settings missing on Ubuntu 23.04

### ISSUE THREAD

**Issue by SirCorono** [keepassxreboot/keepassxc#9363]
Hi

I recently updated two PCs to Ubuntu 23.04. The first one worked perfectly, on the second one, KeepassXC shows a strange behavior.
In the settings, there should be a Auto-Type tab. This tab is missing:
![image](https://user-images.githubusercontent.com/32664586/234373705-4067f116-e872-470c-ae60-73c158711115.png)

On the other PC, this tab still exists. 
The other thing I detected is that the boarder is white, even in dark mode. This also is different to the other PC, there it is completely dark.

Does anyone has an idea what the problem can be and how to solve it? I already tried uninstall/reinstall and also deleted all config files I could find. Nothing helped.

**Debug info**
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Ubuntu 23.04
CPU architecture: x86_64
Kernel: linux 6.2.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

Operating System: Ubuntu 23.04
Desktop Env: Gnome
Windowing System: Wayland

Thanks

**Comment by phoerious** [comment]
Auto-Type does not work on Wayland.

**Comment by neremin** [comment]
It does work on Ubuntu 22.04 Wayland though. This might be a way around wayland limitations: https://keepass.info/help/kb/autotype_wayland.html

**Comment by droidmonkey** [comment]
/dev/uinput requires root permissions.

**Comment by droidmonkey** [comment]
> It does work on Ubuntu 22.04 Wayland though. 

You are being tricked. All your apps you auto-typed into, including KeePassXC, were actually running on an X11 server and being rendered through xwayland bridge. It would seem that Ubuntu 23.04 removed that from the deployment.

**Comment by lennybacon** [comment]
I had it running on Ubuntu 24.04. After update to 24.10 the option went missing.
