### ISSUE TITLE
Export single entry.

### ISSUE THREAD

**Issue by DunklesKaltesNichts** [keepassxreboot/keepassxc#9364]
Hi

i am currently testing some password managers and have received a list of requirements from my boss.

how do i export a single entry, which I can then hand over as a printout to internal or external employees?

In Keepass I can select a single entry and print only this entry.

regards

**Comment by droidmonkey** [comment]
That is not a simple feature yet. We plan to implement it.

Today, you would have to create a new database, drag and copy the entry, then export the new database as html for printing.
