### ISSUE TITLE
Password shown is not well formatted 

### ISSUE THREAD

**Issue by patopat** [keepassxreboot/keepassxc#9365]
Hi,

The password shown is not well formatted.

The right password :
![image](https://user-images.githubusercontent.com/20794916/234582409-d0e96179-94c1-48f8-a891-5c9ad44acb65.png)

Not displayed correctly :
![image](https://user-images.githubusercontent.com/20794916/234582190-0444fe1f-c936-4c9b-8c49-bef2706544af.png)

KeePassXC - Version 2.7.3
Revision: d8483d3

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Operating System: Windows

Regards,
Pat

**Comment by droidmonkey** [comment]
Upgrade to 2.7.4
