### ISSUE TITLE
Failure to save database does not allow the program to quit

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#9367]
## Overview

For some reason - and this might be the occasion for a further bug report - the database is not saving. Eventually I received a message from the program saying that multiple times the database had failed to get saved. I was offered the chance to disable 'safe' saving. I took that option. The database saved. But now I cannot quit the program. When I select 'quit' from the file menu, nothing happens.

## Steps to Reproduce
Perhaps the following.
1. Have repeated problems saving.
2. Disable safe saving.
3. Try to quit.

## Expected Behavior
I should be able to quit.

Also: it might be an idea to tell the user that the disabling-of-safe-saving is permanent (in the sense that the setting will _stay_ changed unless and until the user changes it back).

## Actual Behavior
I cannot quit.

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Operating System: Windows 10

**Comment by droidmonkey** [comment]
This is not reproducible
