### ISSUE TITLE
Ubuntu 22.04: Google drive not showing up in file selector

### ISSUE THREAD

**Issue by Schuasda** [keepassxreboot/keepassxc#9368]
## Overview
It worked fine once, but now when i want to "open existing database" my Google Drive does not show in the sidebar.
Drive is properly connected and works fine with the Files app. When i copy the database file to a local folder Keepassxc can open it just fine. Also opening from the recent databases files does not work.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Connect Google via Online accounts feature in Ubuntu 22.04
2. Open Keepassxc
3. Click "Open existing database"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The connected Google Drive should show up in the sidebar of the file selector

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Google Drive is not showing at all

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu 22.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.19.0-41-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Are you using the snap distribution?

**Comment by Schuasda** [comment]
> Are you using the snap distribution?

No, I added the Ubuntu PPA and installed via apt

**Comment by phoerious** [comment]
Whether virtual file systems like that show depends heavily on the virtual file system implementation. This is not really something we can fix. Even if it shows up, the actual file path is very often some temporary location with cryptic names, giving you a different file path every time you restart your computer.

**Comment by droidmonkey** [comment]
Someone really needs to develop a proper GDrive and OneDrive client for Linux. The current GFuse implementation is horrific and the integration with the file managers is not good either. Linux is the only operating system where the access to cloud files is done through temporary runtime locations......

**Comment by Schuasda** [comment]
> This is not really something we can fix.

Very sad. It is weird that it worked once directly after the first keepassxc install, though.

**Comment by HenrikHolst** [comment]
> Someone really needs to develop a proper GDrive and OneDrive client for Linux. The current GFuse implementation is horrific and the integration with the file managers is not good either. Linux is the only operating system where the access to cloud files is done through temporary runtime locations......

For GDrive there is the excellent [Overgrive](https://www.overgrive.com/)

**Comment by Mugane** [comment]
> > Someone really needs to develop a proper GDrive and OneDrive client for Linux. The current GFuse implementation is horrific and the integration with the file managers is not good either. Linux is the only operating system where the access to cloud files is done through temporary runtime locations......
> 
> For GDrive there is the excellent [Overgrive](https://www.overgrive.com/)

Except why on Earth would anyone pay a third party for this when they are paying Google for the cloud service? GOOGLE needs to provide a free solution, period.
