### ISSUE TITLE
Search for password

### ISSUE THREAD

**Issue by ItTakesTwo** [keepassxreboot/keepassxc#937]
It would be helpful if you could search for passwords to find accounts that need to be updated in case of a compromised password that has been used multiple times.

**Comment by magkopian** [comment]
Well, if the same password wasn’t used multiple times on different places to begin with that wouldn’t be a problem, would it? So, with that in mind I'd like to suggest a different feature. What about providing a way of showing all the entries which share the same password in the database, so the user can easily find and update them before it's too late?

One of the big advantages of using a password manager, is that it gives you the ability of having different strong passwords for every single thing, with basically zero additional effort.

**Comment by TheZ3ro** [comment]
Seems related to #551

**Comment by ItTakesTwo** [comment]
That's absolutely corrent magkopian. A function to show duplicates is fine with me.
Yes that feature would be a duplicate to https://github.com/keepassxreboot/keepassxc/issues/551 so I guess my issue can be considered as such.

**Comment by rigglemania** [comment]
There's also another use case for searching for password that I recently ran into. I was informed from an external source that one of my passwords was compromised, and it gave me the first few and last characters of the compromised password but not the originating source (i.e. it came from a password dump). Now I don't reuse passwords at all, so a duplicate finder is of no help. What I was looking for was to be able to find the site/account associated with that compromised password so I could then change the password.

**Comment by droidmonkey** [comment]
In the upcoming v2.4 you can search for passwords using: ```password:"search string"```. You can use wildcards and regex as well.

**Comment by jmevel** [comment]
> In the upcoming v2.4 you can search for passwords using: `password:[search string]`. You can use wildcards and regex as well.

Is it still supposed to work with version 2.6.6?
I'm searching for `password:[*]` but no results...

### EDIT
Ok turns out it's not `password[search string]` but `password:string` 
(note that I don't know how to search a string with a space except maybe with a Regex)

**Comment by droidmonkey** [comment]
Use quotes around the search term: p:"search term"

**Comment by martin3000** [comment]
It seems that p:abc also finds p:abcdef.
How can I avoid that and do an exact search?

**Comment by droidmonkey** [comment]
Prepend a +

**Comment by martin3000** [comment]
god bless you mate!
