### ISSUE TITLE
KeepassXC crashed while trying to use the browser plugin on a closed database

### ISSUE THREAD

**Issue by delize** [keepassxreboot/keepassxc#9370]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have Closed KeepassXC Database
2. Load webpage with browser plugin enabled
3. Click Browser Plugin to fill info
4.  Unlock database
5. Click browser plugin
6. Crash

## Expected Behavior
To not crash and autofill data entries

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC crashed with the following exception:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000077700000018
Exception Codes:       0x0000000000000001, 0x0000077700000018

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [15948]
```

## Context
Have been running KeepassXC for days without a reboot, but generally, that shouldn't matter. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
keepRevision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

[keepassxc-crash.log](https://github.com/keepassxreboot/keepassxc/files/11351785/keepassxc-crash.log)

**Comment by droidmonkey** [comment]
Do you have the full crash report?
