### ISSUE TITLE
KeePassXC determines TouchID capability somewhat unpredictably

### ISSUE THREAD

**Issue by ChristopherSchultz** [keepassxreboot/keepassxc#9372]
I have a MacBook Pro with a fingerprint reader. When keepassxc detects that TouchID is an option, it allows me to unlock the database quickly using it and it works as expected.

The issue is when I switch back and forth between lid-open-laptop-use and external KVM with the lid closed. Sometimes touchID is offered when it's not really an option (because the lid is closed).

When launching keepassxc when the laptop is connected to an external KVM and the lid is closed, keepassxc correctly detects that TouchID is not available and does not offer it as an option. If I disconnect from the KVM and open the lid, TouchID is actually available yet keepassxc does not detect it and offer it as an authentication option.

When launching keepassxc when the laptop is standalone with the lid open, keepassxc offers TouchID and no other options, which is fine. But when re-attaching to the KVM and closing the lid, keepassxc continues to offer TouchID as the primary authentication option. You have to click "cancel" and then enter the password.

I've been trying to get this down to a 100% reproducible scenario but I'm having trouble with nailing it down. Sorry :/

**Comment by droidmonkey** [comment]
We did not design touchid integration to be dynamic to lid state. This is reported in another issue and is on our radar to fix.

**Comment by ChristopherSchultz** [comment]
Glad to hear it's on the radar. Would you mind posting a link to that other issue so I can track it? (I did try to search before filing this issue!)

**Comment by droidmonkey** [comment]
It's your previous issue: https://github.com/keepassxreboot/keepassxc/issues/8105

**Comment by ChristopherSchultz** [comment]
🤭
