### ISSUE TITLE
System Error: VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by sandalle** [keepassxreboot/keepassxc#9373]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
https://github.com/keepassxreboot/keepassxc/issues/7564 is still an issue on a fresh install of Windows 10 (22H2 Build 19045.2846) and fresh install of KeePassXC (KeePassXC-2.7.4-Win64).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Wipe computer
2. Install latest version of Windows 10
3. Install KeePassXC
4. Cannot start KeePassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Required DLLs/packages should be installed along with KeePassXC.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Have to download and install https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 (after finding https://github.com/keepassxreboot/keepassxc/issues/7564 ).

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4-Win64
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 22H2
Desktop Env: Windows
Windowing System: Windows

**Comment by droidmonkey** [comment]
This is not possible with msi

**Comment by ernstki** [comment]
This, #7564, #8240, and possibly other issues are all pointing at the same recurring problem. I also ran into this on a fresh Windows 10 Home (22H2) installation, with the latest updates.

_I_ understand what you're saying about "not possible with msi," but my understanding's based on decades of experience with Windows' eccentricities. New and non-technical users are going to be stuck without any recourse, absent some guidance from the "Downloads" page or the documentation.

Installing the [VC runtime package](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist) that several of the other issues mention _is_ one solution, but could I make a respectful recommendation that this be mentioned in the README, the download page, [the Docs/FAQ page](https://keepassxc.org/docs/), or the [Getting Started guide for Windows](https://keepassxc.org/docs/KeePassXC_GettingStarted#_microsoft_windows)? None of those places mention anything about "vcruntime" at the moment.

**Comment by michaelk83** [comment]
The download page for Windows does state "Requires MSVC Support Libraries" under the download button, and links to the installer for it. But it is visually very easy to miss.

**Comment by phoerious** [comment]
I added an FAQ entry. A download link was already on the website. For most users, the package should already be installed, for some it's missing, especially if you have a fresh Windows installation.

**Comment by ernstki** [comment]
> download page for Windows does state "Requires MSVC Support Libraries" under the download button

_\*sigh\*_, it does indeed.

I think I got off-base because I saw "DOWNLOAD FOR WINDOWS 11," said "I have Windows 10, that's not for me," and immediately headed for "Older releases," the GitHub releases page. There's nothing you can do to account for _every_ kind of moronic user behavior, though!

With a FAQ entry, this is more than sufficient. Thanks to you all for your efforts, and apologies for my poor visual acuity when it came to the big, obvious "Requires [MSVC Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe)" link on the main download page.

**Comment by phoerious** [comment]
The button should change to Windows 10 if you are on Windows 10. But the two are only distinguishable if you are using a Chrome-based browser.

**Comment by droidmonkey** [comment]
Can we just put both down? Download for Windows 11/10?

**Comment by phoerious** [comment]
That's too long. With 11 it already breaks weirdly in certain mobile sizes.

**Comment by JohnLGalt** [comment]
Win 10/11? Or else a Windows logo? I've seen lots of sites now using logos instead of words....

**Comment by ernstki** [comment]
> The button should change to Windows 10 if you are on Windows 10. But the two are only distinguishable if you are using a Chrome-based browser.

As you can well imagine, I am in the minority of users who insist on using a non-mainstream browser (Firefox), with countermeasures in place to frustrate browser fingerprinting. So, I think I'm an outlier. It probably works fine for 98% of your visitors.

The amount of work that goes into the tiniest things like a download button—for the web site of a volunteer-run project—is not lost on me, however, and this attention to detail is noticed and appreciated!

**Comment by schmengler** [comment]
As an addition, it is possible to install KeePass XC from the Microsoft App Store. There the only hint is hidden within a paragraph in the description:

> This program requires Microsoft Visual C++ Redistributable to be installed.

It would help if this a) stands out more and b) an explanation for app store users how to install, e.g. add the link there too

**Comment by droidmonkey** [comment]
We can't do anything else on the store itself, unfortunately. Microsoft controls that experience and it's plain text ONLY.
