### ISSUE TITLE
Show additional attributes in the entries list

### ISSUE THREAD

**Issue by ygoe** [keepassxreboot/keepassxc#9374]
## Summary
Some user accounts require the use of a user name that is not the e-mail address. If I have two of those accounts at the same service, I end up having two entries with different user names I don't recognise, but I would recognise my e-mail address. Unfortunately, the e-mail address still isn't a default field for entries, so it has to be added as an additional field on the advanced page. That additional field cannot be seen in the entries list, though, so I can't tell the two entries apart in the list without inspecting their details.

KeePass lets me add such additional attributes to the list view and I use them often. It still keeps me away from KeePassXC if usability is degraded so much.

## Examples
![grafik](https://user-images.githubusercontent.com/868315/235357384-9a93dfce-d116-4b33-ade2-6c3729323e69.png)

This redacted screenshot of KeePass shows the additional column with the e-mail address set for one visible entry. The others use an e-mail address as user name, but the one does not. For cases where I have multiple accounts for the same service, the e-mail address column is needed to distinguish them.

**Comment by droidmonkey** [comment]
This is a duplicate request #1493. You should just add the email to the entry title to tell them apart. This also makes it work well when auto-type and browser extension.

**Comment by ygoe** [comment]
Hm, I'll have to try that. In KeePass it would not work because the e-mail address part in the entry name would not match the website title, so I wouldn't find it. Another disadvantage is that I have to enter the address twice which asks for trouble.

The other issue is an old one that doesn't look like it would be interesting for the developers to implement.

**Comment by droidmonkey** [comment]
We have our built in browser integration (plus browser extension) that solves these problems. Also our Auto-Type selection dialog is far superior to KeePass2. Take a look at our user guide for more information.
