### ISSUE TITLE
Move Up/Down shortcut feature not working

### ISSUE THREAD

**Issue by Opening-Button-8988** [keepassxreboot/keepassxc#9375]
Fedora Workstation 37, Gnome 43.4, Wayland, Keepassxc 2.7.4

`Ctrl+Alt+Up/Down` does not move entries up or down. Expected behavior is for entries to move up and down. Clicking on "Move Up/Down" manually works, it's the shortcuts that don't work.

Keyboard works, shortcuts for other applications works. Ctrl+Alt+Up/Down is not being used by any other applications or my system.

Any ideas?

**Comment by sewe2000** [comment]
It works as expected on Arch Linux

**Comment by droidmonkey** [comment]
Yah I tested this on all platforms and it works fine.

**Comment by Opening-Button-8988** [comment]
@droidmonkey The issue still persists for me. Any ideas on how I can fix it?

**Comment by droidmonkey** [comment]
Unfortunately no, but there doesn't seem to be any fault with our program. It is highly localized to your environment.

**Comment by michaelk83** [comment]
Could it be that you have sort enabled on the entries list? Try clicking the column headers a few times until there is no sort arrow there. See e.g. #9265

**Comment by Opening-Button-8988** [comment]
@michaelk83 I thought of this already and tested it with no luck. Even when I have custom sorting, it doesn't let me move entries. I recently updated to Fedora 38 and Gnome 44 which interestingly fixed some other issues I was having. Unfortunately this issue persists.

**Comment by Opening-Button-8988** [comment]
@droidmonkey 

Just thought I'd let you know that this is still an active bug. I've since reinstalled to a different system (completely different, not just an upgrade). I believe you have erroneously concluded that this issue is only for me. It could be related to Wayland.

**Comment by droidmonkey** [comment]
Not much I can say, if it is not reproducible, it is not fixable. We aren't doing anything special here.

**Comment by Opening-Button-8988** [comment]
> Not much I can say, if it is not reproducible, it is not fixable. We aren't doing anything special here.

I understand, but my install isn't special. I'm using Fedora 39 with Gnome using Wayland, with keepassxc installed via dnf. My keyboard shortcuts are default and I don't have any weird extensions changing this. My installation process was about as default as it gets.

**Comment by Murdoc13** [comment]
OS: Debian GNU/Linux 12 (bookworm) x86_64
DE: GNOME 43.9
WM: Mutter

Looks like shortcuts <Control><Alt>Down and <Control><Alt>Up used by Gnome for switch-to-workspace-down and switch-to-workspace-up

```
murdoc@battlestation:~$ gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-down
['<Control><Alt>Down']
murdoc@battlestation:~$ gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-up
['<Control><Alt>Up']
```

Upd: disabling these shortcuts solved problem for me
