### ISSUE TITLE
Make some application settings available as database settings.

### ISSUE THREAD

**Issue by Opening-Button-8988** [keepassxreboot/keepassxc#9376]
Issue: application settings are persistent across databases
Solution: Make some application settings specific to single database

There are a bunch of settings that are listed under Application Settings, which I now realize the purpose of which is to differentiate it from Database settings which is database specific. The problem here is that some application settings should be database settings (ie. saved within a database). Case in point, `Lock databases after inactivity of n.` This setting i is an application setting, and thus all databases will close after the specified time. What if I want one database to close after 10 minutes, and another to close after 1 hour? 

There are other examples. Basically all of the application settings under Security are a significant problem. Many of the settings under General are perhaps even bigger problems. The save options could potentially cause unaware users to no longer automatically backup or save their changes/databases, leading to data loss. While I was only vaguely aware that Database settings and Application settings were different, I didn't realize until recently that application settings were global while database settings were saved within the database. This is something that users should be aware of, and some of these settings should be available both globally and locally. As there are many settings, I won't go through each of them. Rather, I would like to see this reviewed. It's hard to make any specific recommendations because I don't know how this would be implemented.

I really think that the differentiation between application settings and database settings is rather obscure and not easily known to the user. I have been using KeepassXC for 5 years, and I read the documentation just a few weeks ago, and I only just discovered this (not entirely keepassxc's fault). I think a possible solution would be to keep all settings on a single page, and add a "persistent" or "global" option alongside each setting, for accessibility.

Also, under "Database" context menu, there is "Database Settings" and "Database Security", which are both accessible from the same place. To reduce confusion, perhaps remove Database Security. And I suggested above, integrate database settings with application settings.

As a specific feature request: sorting by columns should be saved per database. When I sort by a column, it reflects those changes across other databases, which is annoying. Come to think of it, this is probably the most annoying aspect of this problem.

**Comment by Opening-Button-8988** [comment]
Apologies if this was written poorly, I was still learning the difference between database settings and application settings as I was writing this.

**Comment by droidmonkey** [comment]
This is a duplicate request #891
