### ISSUE TITLE
keepassxc on auto-type , database window is shown

### ISSUE THREAD

**Issue by rovantiel** [keepassxreboot/keepassxc#9377]
version is 2.7.4

When selecting auto-type , all database entries are shown in a window

in settings , Always ask before performing auto-type is OFF

Tried in Firefox and edge    ( windows 11 )

I tried database entries with and without url's given

Expected the userid and password filled in

**Comment by droidmonkey** [comment]
Please read the user guide, you need to define window associations.

**Comment by rovantiel** [comment]
where do i define window associations ?

**Comment by droidmonkey** [comment]
Read the user guide please https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type

**Comment by rovantiel** [comment]
thanks for closing so quick

**Comment by rovantiel** [comment]
Windows association still does not work 
The user guide does not well explain , how this should be set

**Comment by droidmonkey** [comment]
For browsers you should use the browser extension.  Sometimes it is hard to have a consistent window title from browsers.

**Comment by rovantiel** [comment]
yes , on both browsers in use , I have installed the extension
What do you mean by window title ?  URL ?

**Comment by michaelk83** [comment]
Window title is what you see in the title bar - the very top of the window.

**Comment by rovantiel** [comment]
Still no success 
I try to login at bol.com

window title is :   bol.com | Account | Inloggen
