### ISSUE TITLE
Ubuntu - Keepassxc freeze when connecting to existing Database on Nextcloud

### ISSUE THREAD

**Issue by hublex** [keepassxreboot/keepassxc#9378]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. install keepassxc
2. open existing database - the database is safed on nextcloud 

## Expected Behavior
open the database on nextcloud

## Actual Behavior
keepasscs is frozen

## Context
If the database is safed on my computer, than I am able to open it 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - ".7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu
Desktop Env: Gnome I quess

**Comment by droidmonkey** [comment]
Please copy and paste the entire about dialog information.

**Comment by hublex** [comment]
Thank you for your answer. I got it to solve by installing nextcloud. It wasn't working with the pre installed nextcloud the one where you can add the different accounts, like Google... And ONA account was nexcloud Login there was working, also using my files Wich are on my nexcloud but the KeePass didn't work through that.

**Comment by droidmonkey** [comment]
Ok this is definitely a bug in that implementation, not keepassxc. We have this recorded in another issue already.
