### ISSUE TITLE
Windows Magnifier Issue

### ISSUE THREAD

**Issue by DougOH** [keepassxreboot/keepassxc#9379]
## Overview
I have a vision issue and use the Windows 10 magnifier to zoom in on the screen.  When using it over the KeePassXC window it doesn't work right.

## Steps to Reproduce

1.  I just open the magnifier (small window) over the KP window.
2.  Move the magnifier window around.
3.  The image under the magnifier disappears.
4. 
5. 

## Expected Behavior
All other app windows show up larger and easier to read/see. 

## Actual Behavior
I get no image in magnifier

## Context
KeePassXC v2.7.4 
Windows 10 Pro

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You will need to wait for 2.7.5, we added a simple view menu option to enable screencapture. Alternatively, you can start keepassxc with the following command line flag: `--allow-screencapture`
