### ISSUE TITLE
Multiple profiles for password generations

### ISSUE THREAD

**Issue by Mi1an** [keepassxreboot/keepassxc#9381]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I would like to have a few different profiles named by myself in the password generator. Every profile should have a custom set of rules how to generate a new password.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
https://i.imgur.com/m3QveXT.png

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It will be easier to handle a password regeneration when my passwords are expiring in multiple organizations of which every single one has a different policies for a password.
I encountered multiple password policies for example:
The password can contain at max 15 characters.
The password can contain only numbers and alphabet characters.
The password can not contain < and & character.
The password must be at least 11 characters long.
The password must be at least 8 characters long.
The password can not contain () and [].
etc...
So it will be easier to have these profiles with pre-defined set of password policies for every organization.

**Comment by droidmonkey** [comment]
That is a duplicate request
