### ISSUE TITLE
Toolbar doesn't return to main GUI after 'Movable toolbar' setting is disabled

### ISSUE THREAD

**Issue by bitcoincustomcreations** [keepassxreboot/keepassxc#9384]
Cannot get toolbar to reattach to main window in MacOS. I have reset defaults, reinstalled software and no resolution. The main window is able to be dragged indipendantly. When moving the toolbar, it also drags the main window.

**Comment by droidmonkey** [comment]
Re-enable movable toolbar then move it back into place. Then disable movable toolbar again:

![image](https://user-images.githubusercontent.com/2809491/236181826-c090a716-6582-4428-ba22-970380fa6d85.png)

![image](https://user-images.githubusercontent.com/2809491/236181850-61f992f5-95f6-48e0-988d-b901b252478e.png)

We need to move the toolbar back into the mainwindow when that setting is disabled.

**Comment by droidmonkey** [comment]
Also, should just add this setting and the icon vs text setting to the toolbar right click menu

**Comment by bitcoincustomcreations** [comment]
I gave this a try and was unable to resolve the issue. Here is a screen recording to see what is happening

https://user-images.githubusercontent.com/130699320/236252135-e6441deb-1e9b-4872-9d37-2e335eda22f7.mov

**Comment by droidmonkey** [comment]
Press OK after clicking the checkbox. Drag the toolbar from the far left side, see my images and arrows

**Comment by bitcoincustomcreations** [comment]
Got it now. Thank you!
