### ISSUE TITLE
Bug when prompted for the session password on Windows

### ISSUE THREAD

**Issue by vincentdnl** [keepassxreboot/keepassxc#9386]
## Steps to Reproduce
1. On Windows 10 or 11, unlock a database with your database password
2. When you are prompted for the system session password (the one from the Windows session), press ESC
3. The password manager opens anyway

## Expected Behavior
The password does not open when I press ESC when prompted for the system session password

## Actual Behavior
It does open

## Context
Tried this on Windows 10 and 11.

## Version
KeePassXC - VERSION 2.7.4

## Operating System
Windows 10, Windows 11

## Note
Congrats to the maintainers for doing such an awesome tool! 🙏

**Comment by droidmonkey** [comment]
All you did was not enable quick unlock
