### ISSUE TITLE
Creating a database with an empty string as password doesn't work.

### ISSUE THREAD

**Issue by mhidro** [keepassxreboot/keepassxc#9387]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Can't create a database with an empty password, removing the password from a database also doesn't work although the popup message does not make clear why. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Create a new database, don't enter anything in the password field. 
2.  No dice.
 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It should be possible, as opening databases with empty passwords created by Keepass2 works just fine.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by phoerious** [comment]
You have to add at least one key, otherwise your contents will be unencrypted. This is by design. You can open databases without passwords, but you cannot create them.
