### ISSUE TITLE
EntryView hangs while sorting with thousands of rows

### ISSUE THREAD

**Issue by Tormen** [keepassxreboot/keepassxc#9390]
I noticed that for me KeepassXC is becoming very sluggish when searching.
Probably because of size of DB.

And it always is the problem that it directly starts searching when the first character is typed.
But I rarely (never?) want so search only 1 character.

Could you:
* default (for everyone without setting) the minimum search string length to 2 chars (so no search for just one char will be done/possible)
* add a setting allowing to specify also 3 chars minimum search string lengths (the search will only be issued if the search term as at least so many characters)

* delay (for everyone without setting) the search ALWAY by 150/200ms while waiting for another character to be typed into the search box.
And only if NO new character appears (or backspace is pressed to correct), then issue the search 
This could be a neat solution as transparent and probably no drawbacks for no-one as 150/200ms is close to nothing in terms of waiting time... 

... Or increase search performance somehow ... but this is probably the most difficult to achieve.

?

Thanks a lot in advance for any consideration !

Also happy to provide funds for this development. 200 quid ?

**Comment by droidmonkey** [comment]
We already wait 300ms before a search happens between typing characters. What version of keepassxc are you using and how many entries do you have in your database?

**Comment by Tormen** [comment]
KeepassXC 2.7.4
2397 entries

**Comment by Tormen** [comment]
I made a video showing the problem:
https://paste.c-net.org/WarriorsBalance

I can type fast and I am typing "steam" alway in one word quickly into the search box.
But you can see what happens.
EVERY time it hangs after the first typed character and then at some point "unhangs" and continues...
Then maybe I have to change the type of this to become a BUG ? (or repost as a BUG) if you wish ?

Please advise.

Thanks a lot in advance!

PS: Once you see me using copy+paste and THEN it works as expected: it directly searches and very quickly displays the steam result ... WITHOUT hanging after the first typed character!

**Comment by droidmonkey** [comment]
Hmmm, that's not an overly large number of entries. I would expect this kind of delay to happen at 10,000 to 50,000 entries. We can certainly optimize search more than it is but almost everyone has a relatively low number of entries it wouldn't make a difference in performance. 

Can you provide your computer specs please?

**Comment by Tormen** [comment]
Macbook Pro 2019 16" - 2,6 GHz 6-Core Intel Core i7 and the CPU is not the problem as the HANGING is ALWAYS only after the 1st character for 1-3 sec and then it moves on.

Like visible in the video.

Very consistent. Problem appeared at some point within KeepassXC.
Problem there since at least 6months more likely 9months.

So from all you told me it smells like a bug ... we would need to have debug output somehow I suppose to see really what happens after the first char is received and before the 2nd char is treated.

Because as I said: I am typing steam really quick(ly) !
But always the s is taken and then something must happen and then the rest...

Only if I paste steam at ONCE then it works as expected...

**Comment by droidmonkey** [comment]
OK I created a database with 10,000 entries using completely random data. I replicated this problem. It appears to be happening on the list rendering in the entry view, NOT the search. When you type the first letter `s` you end up "finding" thousands of entries which are then all rendered into the list view. 

It would also appear that our typing delay is not long enough to prevent this from happening

**Comment by Tormen** [comment]
Wao. Thanks A LOT !
Then maybe my suggestion to prevent 1 char searches ?
Not sure if there can be ever a use-case for a 1 char search.

**Comment by phoerious** [comment]
> OK I created a database with 10,000 entries using completely random data. I replicated this problem. It appears to be happening on the list rendering in the entry view, NOT the search.

If it were the search, it should hang on each keystroke, not only on the first.

**Comment by droidmonkey** [comment]
Here is the result of a CPU profiling. The sorting feature is what is causing the massive delay. When you return a result of thousands, this sorting takes seconds. This has really nothing to do with searching, you just happen to see this issue when searching. This also happens if you have a group that has thousands of entries in it.

![image](https://user-images.githubusercontent.com/2809491/236623968-c2194f69-3691-4785-b0e6-43f9f081424c.png)

This might be an easy fix, we are instantiating a QCollator on every comparison which is what is causing the problems.

**Comment by droidmonkey** [comment]
Yup confirmed, that immediately solves the problem. I found a couple more optimization points I will make for 2.7.5.

**Comment by Tormen** [comment]
Impressive work !!!
Thank you very much !!!

This was - as mentioned - for so many month now a painpoint for me (until I finally reached out here).

A big big thank you and wao again !

**Comment by Tormen** [comment]
Hi @droidmonkey , I just wanted to say: It works like charm now !!!  (v2.7.5)

Sooooooooo cool :) :) :)

Merci !!!

**Comment by droidmonkey** [comment]
That's awesome thank you for the report!
