### ISSUE TITLE
Insecure Two-Factor-Authentication settings modification

### ISSUE THREAD

**Issue by CyberCtzn** [keepassxreboot/keepassxc#9391]
## Overview
Having set up a YubiKey for my Two-Factor-Authentication i noticed that a confirmation through the set up second-factor is not required when making changes to security-settings within that KeePassXC-Database.

## Steps to Reproduce
1. In Database-settings/Security set up a YubiKey Challenge-Response
2. Create a new Entry
3. Confirm with YubiKey Challenge-Response
4. Go back to Database-settings/Security
5. Remove YubiKey Challenge-Response

## Expected Behavior
Imperative authentication through YubiKey Challenge-Response when making security-related changes to database settings.

## Actual Behavior
No Two-Factor-Authentication required, while it is set up.

## Context
This is a similar but different issue like [9339](https://github.com/keepassxreboot/keepassxc/issues/9339). 

KeePassXC - 2.7.4
Operating System: Linux

**Comment by droidmonkey** [comment]
It's the same as the linked issue "change password"
