### ISSUE TITLE
KeepassXC version 2.7.4 does not show button "Auto fill"

### ISSUE THREAD

**Issue by cledefa49** [keepassxreboot/keepassxc#9392]
In the tool bar of KeepassXC, this button is no more present
I look into the parameters, but do not find how to show it

Previously I used the 2.3.4 version and this button is present and really very convinient.

Is this an evolution of the application or is me that misunderstoud something ?

By the way, very sorry about my english ...

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: /Linux
Desktop Env: Debian 11 and 12/Wayland

**Comment by droidmonkey** [comment]
You cannot use Auto-Type when KeePassXC is running under Wayland. You have to either start KeePassXC on an X11 server or change your entire desktop env to use X11.

**Comment by cledefa49** [comment]
OK, that's an explanation.
Can I expect this could change in a future release ?
Thanks in advance

**Comment by droidmonkey** [comment]
Not any time soon. Search our issues for autotype and wayland and you'll see some robust discussions on the topic.
