### ISSUE TITLE
Long master password breaks KeePassXC

### ISSUE THREAD

**Issue by ijhchess** [keepassxreboot/keepassxc#9394]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
512 character password breaks KeePassXC.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Generate 512 character password including A-Z, a-, 0-9, Extended Ascii, and all the other options for characters found on your keyboard
2. Make this the master password
3. Try to login; you are now locked out of your database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Database unlocks just fine
## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Database fails to unlock

## Context
[NOTE]: # ( Give us any additional information you may have. )
I changed the master password of my database to a 512 character password with every option available in the KeePassXC password generator selected, including the extended ASCII character type. However, when I tried to unlock the database with the password (which I had saved), I got an error saying invalid credentials were provided. I created a new database with this same password, and I ran into the same problem; however, when I went thru the exact same steps to create another test database with a shorter master password (16 characters), everything worked just fine. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
How did you save the password? Did you paste it into notepad? You likely lost the extended ascii characters if that is the case.

**Comment by ijhchess** [comment]
The first time I ran into this, I had pasted it into Notepad; however, every other time, I was copying from what I had pasted into Notepad both to set the password and to try to log in, so I'm not sure if that is the problem as any lost ascii characters should've been duplicated both when I set the password and when I tried to unlock the database?

**Comment by droidmonkey** [comment]
Cannot replicate at all, pretty sure you ended up messing up the copy/paste of the password.

I created the following password (512 characters):
```
7{û[CÒªV··âµÁ°3QY$¨Ù»0[nïIwkÑJzéX\e¹µ¢jáÒº«²#úÞ¾Ã.výÂø&qÒslÌcÅF×;ÿ=%ÿýðËÕv<nrPöð¹Fö"E%¢iú¤R¶´úÜ;8(Zç«¸>$wgwe§)jKkø{àÔ{±±o|0Çßß´`Cfñ'ð0h¥àm°Ó]xí÷fu9¹ÞaØóç}]ÓõNÀ²°õÁ_²L=Æ¦.!Ð¼à3°9l0õ»ãTÒåÇÞ}NòK¾!£¾¾'~ª3BÓÈ¦¦äö«YÔjY³®_áÙxCñeîSSf½IìÈÈSCbïp~$ÉÝÏp,pîxò,)?1i^ùvs¯J`KvS:x0ÉÕP(¨¬¼ý[õ#_há{uGS,¸1XJ!S¤ºo®ûÜ¼®©Fèü9ÚBû59Ó²7Ü^ºà*ÚÔÈJsß*/à-a¿h¤øÈDç<Õ&±*_3ÞNJ&2@sjmÇ³U³Å;¡SÝ¾°y'Y>¯îo5Óa*GÖÎÒSë®qñ{?÷Å#r×«/³ôeÌmÓ-{$waô!+ÂgwÍÐ±ÂGÜËzÎ¦´×¥/wë]¨b6kPS¾ùýGZUÄÖ,©y96,§ö°JÌúêwHCLÕß\ÄÙßî$üÛñ}Nþádmá0ãQßÅ0î*IáÇA×ù1$Ç9Kú^¶øðëÄ5À"~ýòZsËz´¥i@
```

set it to the database, then locked and unlocked it without issue.
