### ISSUE TITLE
database open resolves to `/run/user/1000/doc/`

### ISSUE THREAD

**Issue by pkoevesdi** [keepassxreboot/keepassxc#9395]
## Overview
File openings from mounted shares resolve to `/run/user/1000/doc/` instead of the mount folder

## Steps to Reproduce
1. Mount an NFS share, i.e. under `/media/uder/share/` (other protocols not tested)
2. open a kdbx database inside KeePassXC from there
3. reboot the computer (maybe logoff or unmount is enough)
4. remount the share under same path `/media/uder/share/`
5. openKeePassXC
6. try to reopen "last used database"

## Expected Behavior
Database is found and opens

## Actual Behavior
KeePassXC complaining about database not found

## Context
Ubuntu 22.04

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC 2.7.4
Revision: 7729648
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: ???

**Comment by pkoevesdi** [comment]
Here are some hints about this: https://forum.snapcraft.io/t/home-path-is-translated-into-run-user-1000/15415/5

**Comment by pkoevesdi** [comment]
This issue only results from my workaround around this issue: #1775

**Comment by pkoevesdi** [comment]
This is no issue when using an AppImage instead of a snap, there the path resolves as given.

**Comment by droidmonkey** [comment]
This is just how snaps work. There is nothing we can do to change this behavior, unfortunately. We do recommend using the flatpak instead.
