### ISSUE TITLE
Support database open and unlock using GPG private keys

### ISSUE THREAD

**Issue by brianddk** [keepassxreboot/keepassxc#9399]
## Summary

There are plenty of [gpg based password managers](https://www.passwordstore.org/#extensions), but none of them seem to have the same extensive feature-set that KeepassXC has.  I think that securing the database with a GPG encrypted keyfile would make sense.  

## Examples

My thoughts would be to add a checkbox near the keyfile dialog to simply say:

- [ ] GPG Keyfile

If the user checks the GPG-Keyfile control, then the keyfile is assumed to be GPG encrypted.  When the database needs to unlock, the encrypted keyfile would be fed through GPG to decrypt it for use as a keyfile in memory.  There could be a configuration option to stuff the GPG executible bin path in a config setting, environmental variable, or just assume it's called `gpg` in the path.

## Context

My main problem with keyfiles is that it provides an at-rest thing that an attacker to target that once pocessed would give them complete access to the keystore.  By providing the user the ability to tag a keyfile as a `gpg-keyfile` then the need to secure the keyfile at rest is removed.

**Comment by droidmonkey** [comment]
This isn't supported by any other keepass client and really doesn't add much security. You are far better off just using a strong master password or a yubikey. This would take quite a lot of work to integrate successfully and the population of users would be very small. For those reasons we would not support this.

**Comment by michaelk83** [comment]
Just out of curiosity, would it not already be possible to use to use a GPG-encrypted file as the keyfile directly, *without* the extra checkbox and decryption step? (I realize this wouldn't make a lot of sense, but technically, it should work?)

@brianddk You could emulate your use case with the extra decryption step using external GPG tools. On Linux, `/tmp/` and `/run/` are already stored in memory by default, so you can place the decrypted keyfile there, temporarily. Then delete it when it's no longer needed.

edit: Just noticed your https://github.com/keepassxreboot/keepassxc/issues/1210#issuecomment-1537018034 , which is related.

**Comment by brianddk** [comment]
> would it not already be possible to use to use a GPG-encrypted file as the keyfile directly, _without_ the extra checkbox and decryption step?

Yes, as you mentioned, if the FIFO stream capabilities are fixed then this can be done through the shell, at least with BASH) using bash [process substitution](https://tldp.org/LDP/abs/html/process-sub.html).  Would look like this.

```
keepassxc-cli db-create --set-key-file <(gpg -d keyfile.gpg) example.kdbx
```

That is how I originally tried to solve this.
