### ISSUE TITLE
Memory access violation after merging databases

### ISSUE THREAD

**Issue by hofesh** [keepassxreboot/keepassxc#940]
![image](https://user-images.githubusercontent.com/24584850/30293073-f8a3497c-9740-11e7-8e14-79859f067e54.png)

After modifying an existing DB, then merging it with the original and then searching for the modified entry - the application crashes with a memory access violation as seen above.

## Steps to Reproduce
[sample.zip](https://github.com/keepassxreboot/keepassxc/files/1293795/sample.zip)
### create sample files using these steps (or download the attached sample files):
1. create a new DB with a single entry. Fill all field with stub values.
2. save as "test.kdbx"
3. close and re-open the DB.
4. modify the entry by prepending "111 " to it's name.
5. Save as "test-111.kdbx" and close the DB.

### Activate the bug:
1. open test.kdbx
2. File -> Merge Database
3. Select and open test-111.kdbx
4. Click the search box
5. Type "1"
6. Application crashes.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16278

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by louib** [comment]
@hofesh was able to reproduce, thanks for the report!

**Comment by hofesh** [comment]
@louib thanks for the quick fix!
