### ISSUE TITLE
Windows Security not respected

### ISSUE THREAD

**Issue by Natan-Gorecki** [keepassxreboot/keepassxc#9405]
## Overview
![image](https://user-images.githubusercontent.com/52935895/236883047-9e791522-c7e8-4445-89aa-3a56f4f9d0a4.png)
When I close window (through Close or Cancel button), I still have access to the database. Looks like bug, otherwise Windows authentication is invoked pointless.

## Steps to reproduce
1. Open KeePassXC.
2. Choose database.
3. Enter password and specify key file path.
4. Click unlock button.
5. Windows Security prompt is shown - click Cancel button.

## Expected Behavior
The database should be blocked.

## Actual Behavior
I have access to the database.

## Context
I was able to reproduce it on Win10 and Win11. Here is my current context.

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
All you did was not enable quick unlock.

**Comment by Natan-Gorecki** [comment]
@droidmonkey Sorry for beeing not precise. I added steps to reproduce.
I have enabled database quick unlock (Touch ID / Windows Hello).

**Comment by JohnLGalt** [comment]
As DM said:  Step 5 is not _blocking_ access to the database. Step 5 is simply disabling quick unlock.

That initial Windows Hello prompt (when opening the database) is simply to either _enable_ QuickUnlock via Windows Hello **by clicking OK** after supplying your credentials / face unlock / fp unlock, or _disable_ QuickUnlock by clicking Cancel.

Once you enter your password / keyfile location / physical key, **that** is what unlocks the database, and until you shutdown KPXC completely, it will have access to the database.

**Comment by Natan-Gorecki** [comment]
That makes sense now. Thanks for clarification.
As [docs](https://keepassxc.org/docs/KeePassXC_GettingStarted) say:

> On Windows you will be prompted to authenticate to Windows Hello on the initial database unlock. This is required to access the hardware certificate store that encrypts your credentials.
