### ISSUE TITLE
multi-user feature

### ISSUE THREAD

**Issue by eoli3n** [keepassxreboot/keepassxc#9407]
https://keepass.info/help/base/multiuser.html

> With KeePass 2.x, a database can be stored on a shared network drive and used by multiple users. When attempting to save, KeePass first checks whether the file on disk has been modified since it was loaded. If yes, KeePass asks whether to synchronize or overwrite the file (see image on the right).

In a small team, most users are Windows users and will use classic Keepass2 db.
If I open that DB with keepassxc, can I expect it to work as described in the keepass documentation ?

If the DB is created with keepassxc clients, and all users use keepassxc, can I expect it to work as described in the keepass documentation ?

**Comment by eoli3n** [comment]
It seems that the merge function is implemented : https://github.com/keepassxreboot/keepassxc/issues/1002

**Comment by droidmonkey** [comment]
Yes we do the same thing and are completely interoperable with keepass 2
