### ISSUE TITLE
Do you have plan to support webdav?

### ISSUE THREAD

**Issue by xclidongbo** [keepassxreboot/keepassxc#9409]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Because there are multiple devices, such as computers and mobile phones, there is such a demand

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Because there are multiple devices, such as computers and mobile phones, there is such a demand

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Because there are multiple devices, such as computers and mobile phones, there is such a demand

**Comment by droidmonkey** [comment]
No we don't plan to support this. Every OS let's you mount a webdav folder natively.
