### ISSUE TITLE
keepassxc on auto-type , database window is shown

### ISSUE THREAD

**Issue by rovantiel** [keepassxreboot/keepassxc#9410]
version is 2.7.4

When selecting auto-type , all database entries are shown in a window

in settings , Always ask before performing auto-type is OFF

Tried in Firefox and edge ( windows 11 )

I tried database entries with and without url's given

Expected the userid and password filled in

Tried 2 different browsers + extension

And tried to enter the window name  : same result .

Still several webpages show the database window instead of filling the user and password

**Comment by JohnLGalt** [comment]
When entering URLs for entries, try not using any subdomains, just scheme, 2nd and top level domains.

So, instead of https://www.keepassxc.org, use https://keepassxc.org, which will associate that entry with all subdomains of keepassxc.org.

**Comment by rovantiel** [comment]
I tried : still the same result

**Comment by droidmonkey** [comment]
Hello, please read our documentation. You need to setup window associations for entries to allow autotype to find them properly. If no entries are found then we show all entries so you can search for the one you want to use.

**Comment by rovantiel** [comment]
that is , what I also tried : window association . still failing
in this case f.e.    for bol.com : the window is :  bol.com | Account | Inloggen

**Comment by rovantiel** [comment]
who closed this record , and why ??
I am still not able to use keepassXC as described

**Comment by droidmonkey** [comment]
There is nothing wrong with Auto-Type, this worked perfectly fine...

Window Title Association = `bol.com | Account | Inloggen *`

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/bd168be6-1c8f-456a-8b00-7556f5d0769f)

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/3969b44b-ceec-47d4-a107-a2aa3f328c02)

**Comment by vraravam** [comment]
This is still not fixed. I'm on keepassxc 2.7.5 on macos Ventura
The web page where I am trying to fill in the login info: 
<img width="1275" alt="Screenshot 2023-06-19 at 7 40 00 PM" src="https://github.com/keepassxreboot/keepassxc/assets/69629/89b554f9-1da7-4c02-ad7d-7cbfa10848b9">

What I have setup for auto-type for that web page:
![Screenshot](https://github.com/keepassxreboot/keepassxc/assets/69629/a4cb0db5-6a8b-4af5-b8e4-7709abbe4e1d)

What shows up when I try the global shortcut is a new keepassxc window showing all entries in the whole database.

**Comment by droidmonkey** [comment]
You need to add a * to the end to account for the browser name in the window title.

**Comment by vraravam** [comment]
I tried that just now - in fact added `*` at both the beginning and at the end of the "window title"  - but, no luck

Edit: This was working till a few days ago, but no longer works. I don't think anything else has changed

**Comment by droidmonkey** [comment]
Generally speaking, code doesn't randomly break.  The window title is likely wrong overall, as in the website changed its title.
