### ISSUE TITLE
KeePass remains open after locking the session

### ISSUE THREAD

**Issue by PushPopAddtht** [keepassxreboot/keepassxc#9413]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
step 2: 
![image](https://github.com/keepassxreboot/keepassxc/assets/133326547/7f5a491f-d2dc-4e3e-aa4c-7a2424f80f67)
step 4:
![image](https://github.com/keepassxreboot/keepassxc/assets/133326547/88beb768-1cd7-4a5a-98e4-21112b14d465)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock your KeePass.
2. Select the user to modify.
3. Open the user modification window.
4. Click on generating a new password (as if you wanted to change it).
5. Lock the computer session.
6. Unlock the session.
7. KeePass is still open

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Update to 2.7.4 this is fixed
