### ISSUE TITLE
Unintended behaviour in portable mode (windows os)

### ISSUE THREAD

**Issue by objuice** [keepassxreboot/keepassxc#9414]
Unintended behaviour in portable mode (windows os)

Dear KeePassXC team

I downloaded your app (KeePassXC) for evaluation on windows as follows:

KeePassXC for Windows - Version 2.7.4
Portable ZIP (64-bit, Windows 10 / 11)

I liked its modern looking interface and compatibility with the ORIGINAL keepass database, but unfortunately it is not operating in a portable fashion as intended – it creates the following two files and leaves them behind – so it has to be configured again and again (per machine / user).

%appdata%\KeePassXC\keepassxc.ini
%localappdata%\KeePassXC\keepassxc.ini

As a workaround a launcher is solving the problem but it is less elegant than a native way.

If the exec (KeePassXC.exe) looked for (%~dp0 keepassxc.ini) at launch it will operate 100% in a portable fashion with no extra batches or launchers.

Please look into this and may be implement a fix in your next release. THANKS

**Comment by droidmonkey** [comment]
Make sure you extract the entire contents of the zip file to your desired directory. We detect a zero byte file named `.portable` in the same directory as keepassxc.exe. Once detected we will write config files to the `config` subdirectory of the portable install.

**Comment by JohnLGalt** [comment]
I can confirm, having used the portable for at least a couple of years now, that nothing is written anywhere outside the directory it is extracted to.

**Comment by objuice** [comment]
Thanks droidmonkey for the hint, it was (.portable) file missing - the problem solved after I re-created it.
I made (.portable) non zero bytes because it gets deleted by cleaners that look for empty files.
Thanks for the help and have a great day - the case should be considered closed.
