### ISSUE TITLE
Drag and drop broken

### ISSUE THREAD

**Issue by juhi24** [keepassxreboot/keepassxc#9415]
## Overview
Cannot rearrange anything by drag and drop. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database with entries.
2. Drag an entry to another spot on the list OR to a different group OR drag a group to rearrange them

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Entries/groups are rearranged.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Entries/groups remain in original order.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Similar to #5636, but I did not try reinstalling.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394
Qt - 5.15.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a gnome bug
