### ISSUE TITLE
I still can't open URLs with 2.7.5 AppImage

### ISSUE THREAD

**Issue by vphantom** [keepassxreboot/keepassxc#9419]
## Overview

I can't find the original ticket number in here (does not seem to be related to #5942) but I think being unable to open URLs in recent versions is a known issue. I could open them fine in 2.7.1 but cannot in 2.7.4 and still can't in 2.7.5 with the same message from both on `stderr`:

```text
/opt/brave.com/brave/brave: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_spawn_async_with_fds
```

Even though it mentions my browser on the left it seems to be actually caused by either the AppImage build or how `libgio` is initialized on the KeePassXC/AppImage side.  I miss being able to open URLs. 😉

## Steps to Reproduce
1. Launch KeePassXC 2.7.1 AppImage on Linux
2. Try to open a URL, which succeeds
3. Launch KeePassXC 2.7.4 or 2.7.5 AppImage on same Linux box
4. Try to open a URL, which fails

## Expected Behavior

Launching the URL in a new tab in my browser, which is what 2.7.1 did. I tried all 3 versions today in preparing this ticket to make sure it's not system-related.

## Actual Behavior

Focus does switch to my browser, however no new tab, just this one error message on the `stderr` of KeePassXC.

## Context

Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

KeePassXC - Version 2.7.5
Revision: 9d0537b
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.16.0-0.bpo.2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
#8721

Please track there
