### ISSUE TITLE
Remove allow-screencapture check from Linux builds

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#9420]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
We check for the allow-screencapture command line flag on Linux even though it isn't defined as a flag. This throws a warning in the console. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by Organic-Marble** [comment]
I assume this refers to the message "QCommandLineParser: option not defined: "allow-screencapture"" I'm getting in the terminal after today's update. Also, the screenshot option in the View menu mentioned here https://9to5linux.com/keepassxc-2-7-5-password-manager-adds-new-option-to-allow-screenshots-botan-3-support is not present.
