### ISSUE TITLE
Segmentation fault in keepassxc-proxy at version 2.7.4-2

### ISSUE THREAD

**Issue by JulianGoeltz** [keepassxreboot/keepassxc#9421]
## Overview
Version 2.7.4-2 on arch produces Segmentation fault for keepassxc-proxy

## Steps to Reproduce
1. Install `keepassxc` at version 2.7.4-2 (newest available on arch)
2. run `keepassxc-proxy`

## Expected Behavior
Run without segfault

## Actual Behavior
Immediate segfault

## Context
* version `keepassxc-2.7.4-1` does not segfault
* maybe this is a problem of the packaging

```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.9
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.3.2-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

Operating System: Linux (archlinux)
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
This would be a packaging problem, not on our end
