### ISSUE TITLE
chash on opening database from history/on google drive - when modified in another way

### ISSUE THREAD

**Issue by Tetack** [keepassxreboot/keepassxc#9424]
## Overview
[TIP]:  # crash on unlocking database with android mobile if database changed in (google) drive 
[NOTE]: # crash of keepass on android when trying to unlock database on android - and when the database get modified by another source and saved on google drive. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open database on android (let it lock by itself)
2. open database on MAc - update information and save (and automaticlly make it push to google drive
3. (re-open database on the android - type password or fingerprint unlock
4. the database get crash - 'default secure/check.
5. 

## Expected Behavior
[NOTE]: # proper opening expected.
in case of re-opening a new file and select it (not in history) to the full path of drive  as it was new - it open properly

## Actual Behavior
[NOTE]: # the database and programm crash on opening

## Context
[NOTE]: # check above :)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2,7,4
Revision: 63b2394

[NOTE]: #  
Operating System:  macOS monterey + android 
Desktop Env:  
Windowing System:

**Comment by droidmonkey** [comment]
We don't have an android app. You'll have to file this report with the app owner.
