### ISSUE TITLE
Cannot unlock database

### ISSUE THREAD

**Issue by zhum** [keepassxreboot/keepassxc#9425]
## Overview

I'm using 2.6.6 from package on Ubuntu 22.04.2 LTS. I cannot unlock the database. If I enter CORRECT password, then nothing happens and the database remains closed. If I enter incorrect password, I get an error and the database is still closed (as expected). I don't use key file or hardware key. I'm ready to debug it via strace or any other instruments or via debug release, but I need instructions...

## Steps to Reproduce
I'm not sure it can be reproduced on other computers, because I don't see any complains. So I suspect the problem is on my side, but I don't know how to debug it.
1. Install ubuntu 20.04.2 x86, update apt database, install keepassxc package.
2. Start keepassxc from the menu or console.
3. Sync database file from other working installation.
4. Try to open the database file in keepassxc (Open existing database, enter password).

## Expected Behavior
Database is opened, a list of entries is displayed.

## Actual Behavior
Nothing happens, the same window with password prompt is displayed.

## Context
KeePassXC - 2.6.6.
Revision: 9c108b9

Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
You can try using the flatpak distribution to get to version 2.7.5

**Comment by zhum** [comment]
This works, thank you!
