### ISSUE TITLE
[I18N] Issues in application settings

### ISSUE THREAD

**Issue by meskobalazs** [keepassxreboot/keepassxc#9426]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
[ApplicationSettingsWidgetGeneral.ui](https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/ApplicationSettingsWidgetGeneral.ui) has some hard to localize strings

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I'd expect that the contents of `rememberLastDatabasesSpinbox` and `showExpiredEntriesOnDatabaseUnlockOffsetSpinBox` widgets are localizable as a single string.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Currently the translator must be mindful about the extra spaces used in the string concatenation, and what is even worse, one can't reorder the parts of the string, if that makes more sense in the target language.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5 (current `develop` branch)

**Comment by michaelk83** [comment]
`showExpiredEntriesOnDatabaseUnlockOffsetSpinBox` sounds like #7787, which is covered in more detail in #7791.
`rememberLastDatabasesSpinbox` sounds separate.

**Comment by droidmonkey** [comment]
Yah I thought this was a duplicate. Closing this one
