### ISSUE TITLE
KeePassXC-2.7.5-x86_64.AppImage

### ISSUE THREAD

**Issue by nlime** [keepassxreboot/keepassxc#9428]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

does not open the url, does not download icons, does not update

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 
[](url)
[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate

**Comment by nlime** [comment]
Duplicate of what?

**Comment by nlime** [comment]
the problem is not solved
