### ISSUE TITLE
Adding a GUI prompt for the cli 'show' command

### ISSUE THREAD

**Issue by Ramblurr** [keepassxreboot/keepassxc#943]
## Feature Request

Much like #587 it would be great if the 'show' command of the cli tool had the option to use a gui prompt.

This would allow for use of the command line tool in scripts (for example, mail fetching, or backup scripts) where a password is needed.

## Current Behavior

Currently only the `list` and `clip` commands  have the gui password option (`-g`).

## Possible Solution

#587 could be used as a model for adding this feature.

## Debug Info

KeePassXC - 2.2.0 (fedora 26 packages)

**Comment by TheZ3ro** [comment]
In the next 2.3.0 version (now live in the `develop` branch) the GUI prompt will be removed entirely since the cli interface will not carry and load all Qt graphics library.

**Comment by louib** [comment]
@Ramblurr a `--key-file` option has been added to all the CLI commands dealing with a database, so you could use the `show` command from a script.
