### ISSUE TITLE
KeepassXC 2.7.5 crashes on close with macOS

### ISSUE THREAD

**Issue by NFM-8** [keepassxreboot/keepassxc#9430]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database
2. Unlock the databse
3. Close KeepassXC

## Expected Behavior
No crash

## Actual Behavior
Crash

## Context
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               KeePassXC [3265]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassxc.keepassxc
Version:               2.7.5 ()
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-05-16 18:07:19.0672 +0300
OS Version:            macOS 13.3.1 (22E772610a)
Report Version:        12
Anonymous UUID:        975E2022-4B22-9D16-8CB3-5D314EC0DFA3

Time Awake Since Boot: 3300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000207e75411c0
Exception Codes:       0x0000000000000001, 0x00000207e75411c0

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [3265]

VM Region Info: 0x207e75411c0 is not in any region.  Bytes after previous region: 1751932735937  Bytes before following region: 103320147193408
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x1a5c1eca4 lookUpImpOrNilTryCache + 36
1   libobjc.A.dylib               	       0x1a5bffb98 class_getMethodImplementation + 40
2   Foundation                    	       0x1a6fa0358 _NSKVONotifyingOriginalClassForIsa + 32
3   Foundation                    	       0x1a6fc1080 _NSKeyValueObservationInfoGetObservances + 264
4   Foundation                    	       0x1a6fb1d28 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 240
5   Foundation                    	       0x1a6fdc000 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 64
6   Foundation                    	       0x1a6ff552c _NSSetObjectValueAndNotify + 284
7   libqcocoa.dylib               	       0x1065b5404 0x1065a8000 + 54276
8   libqcocoa.dylib               	       0x1065b5694 0x1065a8000 + 54932
9   QtGui                         	       0x1042323fc QGuiApplicationPrivate::~QGuiApplicationPrivate() + 448
10  QtWidgets                     	       0x10336bc88 QApplicationPrivate::~QApplicationPrivate() + 12
11  QtCore                        	       0x103e70cf8 QObject::~QObject() + 1984
12  QtWidgets                     	       0x10336de60 QApplication::~QApplication() + 892
13  KeePassXC                     	       0x1024cf8f8 0x1024c4000 + 47352
14  dyld                          	       0x1a5c3bf28 start + 2236

Thread 1:
0   libsystem_pthread.dylib       	       0x1a5f8ed8c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1a5f8ed8c start_wqthread + 0

Thread 3:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	       0x1a5f5eff0 __select + 8
1   CoreFoundation                	       0x1a609c1e8 __CFSocketManager + 636
2   libsystem_pthread.dylib       	       0x1a5f93fa8 _pthread_start + 148
3   libsystem_pthread.dylib       	       0x1a5f8eda0 thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x1a5f8ed8c start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1a5f53f14 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1a5f66240 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1a5f5cb78 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x1a5f54290 mach_msg + 24
4   CoreFoundation                	       0x1a60728b8 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a6071198 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a607058c CFRunLoopRunSpecific + 612
7   AppKit                        	       0x1a93ba508 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x1a5f93fa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x1a5f8eda0 thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x00000001f5cf2d29   x2: 0x00000207e75411a0   x3: 0x0000000000000003
    x4: 0x00005ffe94ab5570   x5: 0x0000000000000020   x6: 0x000000016d93b3e8   x7: 0x0000000000000003
    x8: 0x00000001f5cf2000   x9: 0x000000000000000a  x10: 0x000000000000000a  x11: 0x000000000000001f
   x12: 0x000000000000000f  x13: 0x000000015afe2b50  x14: 0x010000020141d001  x15: 0x000000020141d000
   x16: 0x00000001a5bffb70  x17: 0x000000020242af30  x18: 0x0000000000000000  x19: 0x00000207e75411a0
   x20: 0x0000000000000007  x21: 0x00000001f5cf2d29  x22: 0x0000000000000000  x23: 0x000000016d93ac80
   x24: 0x0000000000000000  x25: 0x000000016d93ad08  x26: 0x000000020057d000  x27: 0x00006000007b09f0
   x28: 0x0000000000000000   fp: 0x000000016d93ac40   lr: 0xe00e0001a5bffb98
    sp: 0x000000016d93ac20   pc: 0x00000001a5c1eca4 cpsr: 0x20001000
   far: 0x00000207e75411c0  esr: 0x92000005 (Data Abort) byte read Translation fault

Binary Images:
       0x1024c4000 -        0x10298bfff org.keepassxc.keepassxc (2.7.5) <e602766d-d89d-3980-91e1-08495b39fc35> /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
       0x102ac4000 -        0x102afbfff org.qt-project.QtSvg (5.15) <7aa9d5c8-6ac1-353a-9e85-dd0b63081614> /Applications/KeePassXC.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x102a7c000 -        0x102a83fff libqrencode.4.dylib (*) <ac721acd-68e4-30a8-8e9c-e24dbd1de256> /Applications/KeePassXC.app/Contents/Frameworks/libqrencode.4.dylib
       0x102a94000 -        0x102a97fff org.qt-project.QtConcurrent (5.15) <8b9b0470-afc6-3005-808e-e3fd755a5f86> /Applications/KeePassXC.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x102aa8000 -        0x102aaffff libargon2.1.dylib (*) <1376eff0-6549-3a26-8a87-be3d5d04dc51> /Applications/KeePassXC.app/Contents/Frameworks/libargon2.1.dylib
       0x102c80000 -        0x102d83fff org.qt-project.QtNetwork (5.15) <4ad824ba-4e8b-3e2a-8d51-e93b1c6d9381> /Applications/KeePassXC.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x103360000 -        0x10376ffff org.qt-project.QtWidgets (5.15) <cab80705-7fe7-309e-9124-33fb9c170e73> /Applications/KeePassXC.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x1038e8000 -        0x103b93fff libbotan-2.19.dylib (*) <62a1766b-590b-3e0d-a02e-c1c653a480c2> /Applications/KeePassXC.app/Contents/Frameworks/libbotan-2.19.dylib
       0x102b48000 -        0x102b5bfff libminizip.1.dylib (*) <b48ef015-ed24-3ac7-b4ae-cb2d0a51557c> /Applications/KeePassXC.app/Contents/Frameworks/libminizip.1.dylib
       0x102b6c000 -        0x102b77fff org.qt-project.QtMacExtras (5.15) <7e1608f9-4727-31ac-945e-91b7e4323351> /Applications/KeePassXC.app/Contents/Frameworks/QtMacExtras.framework/Versions/5/QtMacExtras
       0x104204000 -        0x10466ffff org.qt-project.QtGui (5.15) <96dc5bca-9e0c-3faf-b248-5f62b7514c68> /Applications/KeePassXC.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x103c78000 -        0x1040fbfff org.qt-project.QtCore (5.15) <a2f1815a-cdbc-3037-a3d6-d37ab4a5981b> /Applications/KeePassXC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x102bc0000 -        0x102be3fff libpng16.16.dylib (*) <203679f8-5349-340a-adcd-d8e4fc0152ed> /Applications/KeePassXC.app/Contents/Frameworks/libpng16.16.dylib
       0x102ddc000 -        0x102e47fff libpcre2-16.0.dylib (*) <59c863d4-6c8f-3859-9da8-399f2513aba9> /Applications/KeePassXC.app/Contents/Frameworks/libpcre2-16.0.dylib
       0x102f10000 -        0x102fb3fff libzstd.1.dylib (*) <9cc1e4e5-da83-3b83-a1b9-b4f1ccc5d596> /Applications/KeePassXC.app/Contents/Frameworks/libzstd.1.dylib
       0x102b24000 -        0x102b27fff libgthread-2.0.0.dylib (*) <dc034cc9-a009-38ad-b973-d35321a5a83f> /Applications/KeePassXC.app/Contents/Frameworks/libgthread-2.0.0.dylib
       0x1030ec000 -        0x1031dbfff libglib-2.0.0.dylib (*) <dc0e4c75-bd38-34f7-b69c-00c33ce68d60> /Applications/KeePassXC.app/Contents/Frameworks/libglib-2.0.0.dylib
       0x102bf4000 -        0x102bfffff libintl.8.dylib (*) <95dbe1d0-4dd8-3502-abb6-0b08ff7b4e0f> /Applications/KeePassXC.app/Contents/Frameworks/libintl.8.dylib
       0x102fcc000 -        0x10303ffff libpcre2-8.0.dylib (*) <2a661909-9b11-3fd4-b022-97709debc0e7> /Applications/KeePassXC.app/Contents/Frameworks/libpcre2-8.0.dylib
       0x104798000 -        0x104883fff libsqlite3.0.dylib (*) <ada54b19-7e02-347a-a99a-9d82072de19a> /Applications/KeePassXC.app/Contents/Frameworks/libsqlite3.0.dylib
       0x1065a8000 -        0x10665bfff libqcocoa.dylib (*) <471e0dc3-1a05-335e-8212-e1626e3031b9> /Applications/KeePassXC.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x10320c000 -        0x10326ffff org.qt-project.QtDBus (5.15) <15a2b1a1-ba7b-3f29-b958-c79c87a02d37> /Applications/KeePassXC.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x103294000 -        0x10330ffff libfreetype.6.dylib (*) <c7a12bf3-9fdc-3e3d-a6ea-88ad852b8851> /Applications/KeePassXC.app/Contents/Frameworks/libfreetype.6.dylib
       0x1066ac000 -        0x1066d7fff org.qt-project.QtPrintSupport (5.15) <aaaf7245-d5c5-36ae-8a2f-966cddd6df10> /Applications/KeePassXC.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x109370000 -        0x109393fff libqmacstyle.dylib (*) <9e19b38b-06fa-3e46-a3a8-878db28ab4f4> /Applications/KeePassXC.app/Contents/PlugIns/styles/libqmacstyle.dylib
       0x10979c000 -        0x1097a7fff libqsvgicon.dylib (*) <1bdc9f1c-64b2-37bc-8d87-667ba2b9b07e> /Applications/KeePassXC.app/Contents/PlugIns/iconengines/libqsvgicon.dylib
       0x109d0c000 -        0x10a1cbfff libkeepassxc-autotype-cocoa.so (*) <0551a812-4378-395c-b19e-6a8dfc0a5742> /Applications/KeePassXC.app/Contents/PlugIns/libkeepassxc-autotype-cocoa.so
       0x109800000 -        0x10980bfff libobjc-trampolines.dylib (*) <80f14f3d-d099-3693-a8e0-eb9a526b1790> /usr/lib/libobjc-trampolines.dylib
       0x109c24000 -        0x109c2bfff com.apple.CloudDocsFileProvider (1.0) <26e33c5a-f76f-3570-8782-d0dc2d61ff00> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/CloudDocsFileProvider.bundle/Contents/MacOS/CloudDocsFileProvider
       0x109c08000 -        0x109c0ffff libqgif.dylib (*) <c46947a3-77c6-35af-a27a-452e80d81d60> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqgif.dylib
       0x109c58000 -        0x109c63fff libqicns.dylib (*) <1452a387-03db-3550-baab-3d89a33aa3a0> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqicns.dylib
       0x109c3c000 -        0x109c43fff libqico.dylib (*) <97f41fcf-b017-348c-9027-20e8e84da0fc> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqico.dylib
       0x109c94000 -        0x109c9ffff libqjpeg.dylib (*) <9618d860-1d2a-32d2-9e60-b62e27e459c9> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqjpeg.dylib
       0x122d44000 -        0x122d7ffff libjpeg.8.dylib (*) <fab24eae-3511-36b2-9850-98f2a3737006> /Applications/KeePassXC.app/Contents/Frameworks/libjpeg.8.dylib
       0x109c74000 -        0x109c7bfff libqmacheif.dylib (*) <08f03c40-a1ac-30eb-8121-e2dcb9fad298> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqmacheif.dylib
       0x109bf0000 -        0x109bf7fff com.apple.FileProviderOverride (855.100.378) <782f062d-b9d5-3e62-9ce7-b68d197712a2> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/FileProviderOverride.bundle/Contents/MacOS/FileProviderOverride
       0x109cb4000 -        0x109cd3fff com.apple.findersync.fileprovideroverride.FinderSyncCollaborationFileProviderOverride (13.3) <99856966-e77f-3294-a16a-e59a7e494572> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride
       0x122dac000 -        0x122db3fff libqmacjp2.dylib (*) <e9f59c82-6d51-3674-96fc-891572ac7482> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
       0x122dc4000 -        0x122dcbfff libqpdf.dylib (*) <afb46f65-f828-30cc-9d65-3a6558512c1c> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqpdf.dylib
       0x123304000 -        0x1237ebfff org.qt-project.QtPdf (5.15) <7efae184-f13b-30c1-bbbd-888230688e36> /Applications/KeePassXC.app/Contents/Frameworks/QtPdf.framework/Versions/5/QtPdf
       0x122ddc000 -        0x122de3fff libqsvg.dylib (*) <2e65b929-d5b8-3f91-9f0e-48de94c4f492> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqsvg.dylib
       0x122df4000 -        0x122dfbfff libqtga.dylib (*) <3569d754-21d5-3942-a877-2d4388abbf47> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqtga.dylib
       0x122e28000 -        0x122e33fff libqtiff.dylib (*) <e83fcf8a-a811-3668-842c-3848afbc2a98> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqtiff.dylib
       0x122eb8000 -        0x122f17fff libtiff.6.dylib (*) <390266e4-00ad-3e3b-9934-19cffa775b9e> /Applications/KeePassXC.app/Contents/Frameworks/libtiff.6.dylib
       0x122e0c000 -        0x122e13fff libqwbmp.dylib (*) <fc6cc2e5-2e04-3bc3-b4f9-e6add4856b52> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqwbmp.dylib
       0x122e44000 -        0x122e4bfff libqwebp.dylib (*) <93d2b72a-5b3a-3fd6-a3d4-e831b6b89a73> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqwebp.dylib
       0x122d94000 -        0x122d9bfff libwebpmux.3.dylib (*) <ee3b9c16-4971-3532-a9b4-5a32d852ac41> /Applications/KeePassXC.app/Contents/Frameworks/libwebpmux.3.dylib
       0x122e5c000 -        0x122e5ffff libwebpdemux.2.dylib (*) <993fe602-6fe6-3c51-b311-e0bdf293a124> /Applications/KeePassXC.app/Contents/Frameworks/libwebpdemux.2.dylib
       0x122f7c000 -        0x122fbbfff libwebp.7.dylib (*) <dd897bb3-f04d-35cf-855d-36e8db1c13a2> /Applications/KeePassXC.app/Contents/Frameworks/libwebp.7.dylib
       0x122e6c000 -        0x122e6ffff libsharpyuv.0.dylib (*) <0a8fa354-0831-37ce-b46f-63550079589c> /Applications/KeePassXC.app/Contents/Frameworks/libsharpyuv.0.dylib
       0x1a5bf0000 -        0x1a5c35f3f libobjc.A.dylib (*) <25a3d3ea-8a9e-3a8f-becc-0199e4ed6f94> /usr/lib/libobjc.A.dylib
       0x1a6f8c000 -        0x1a7951fff com.apple.Foundation (6.9) <b7d67e5a-dce2-3f6b-b2b8-895a3669e3ec> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x1a5c36000 -        0x1a5cc453b dyld (*) <ac277a36-1808-327a-8761-cca585421212> /usr/lib/dyld
       0x1a5f8d000 -        0x1a5f99fff libsystem_pthread.dylib (*) <b401cfb3-8dfe-32db-92b3-ba8af0f8ca6e> /usr/lib/system/libsystem_pthread.dylib
       0x1a5f53000 -        0x1a5f8cfe7 libsystem_kernel.dylib (*) <7acbd9bc-d056-310e-858d-81b116cf6d28> /usr/lib/system/libsystem_kernel.dylib
       0x1a5ff3000 -        0x1a64ccfff com.apple.CoreFoundation (6.9) <b4fdaece-9727-3969-b014-27f7f24c8e01> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1a9257000 -        0x1aa165fff com.apple.AppKit (6.9) <cc3e5215-4cd7-364c-8750-6eb7002720ce> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                  768K        4 
CG image                           144K        5 
ColorSync                          592K       26 
CoreAnimation                      128K        8 
CoreGraphics                        32K        2 
CoreUI image data                  880K       11 
Foundation                          48K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           257.3M       47 
MALLOC guard page                  192K        9 
MALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Memory Tag 255                    1536K       96 
STACK GUARD                       56.1M        6 
Stack                             10.6M        6 
VM_ALLOCATE                        144K        9 
__AUTH                            1363K      289 
__AUTH_CONST                      21.2M      487 
__CTF                               824        1 
__DATA                            6362K      520 
__DATA_CONST                      25.2M      539 
__DATA_DIRTY                      1487K      168 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       807.1M       51 
__OBJC_RO                         66.2M        1 
__OBJC_RW                         2011K        1 
__TEXT                           458.8M      554 
dyld private memory                272K        2 
mapped file                      486.0M       43 
shared memory                     1008K       22 
===========                     =======  ======= 
TOTAL                              3.1G     2920 
TOTAL, minus reserved VM space     2.2G     2920 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Duplicate

**Comment by NFM-8** [comment]
Duplicate of [#9423](https://github.com/keepassxreboot/keepassxc/issues/9423)
