### ISSUE TITLE
Possible security issue?

### ISSUE THREAD

**Issue by kkolesar** [keepassxreboot/keepassxc#9431]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I am not sure if it is a bug, maybe more possible security issue. 

When edit/adding new record and leave it open (not save), dababase is not locked after inactivity time. Program open dialogue window to save/discard record, stops there and database stays open and accessible to everyone.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add New entry / Edit entry
2. Add/Change record and wait until dialogue window appears with 'You are editing an entry. Discard changes and lock anyway?'
3. Click Cancel -> Cancel -> Discard
4. Database stays open

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Save open record as TMP record and close databes without any dialogues after inactivity time.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Database stays open if you click discard changes.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

KeePassXC 2.7.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

Windows 10

**Comment by droidmonkey** [comment]
Duplicate report, thank you
