### ISSUE TITLE
Window not visible in Teamviewer or VNC

### ISSUE THREAD

**Issue by Matzeeee** [keepassxreboot/keepassxc#9437]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
if i start keypassxc the main window is not visible in a teamviewer or VNC window on an other PC.
I only see the icon the taskbar.
With windows remote desktop it works fine.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: 
Windowing System:

**Comment by phoerious** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by Matzeeee** [comment]
ok.
I was not aware that the screen capture flag is also necessary for remote desktop.
Thank you.
