### ISSUE TITLE
Make window active / foreground when opening a second time

### ISSUE THREAD

**Issue by pganssle** [keepassxreboot/keepassxc#9438]
## Summary
When KeepassXC is already open and you try to open it a second time (e.g. via the Menu / Task bar), the tile blinks but the application stays in the background. A second instance is not opened. Ideally the application would instead be brought to the foreground.

## Context
I often have KeepassXC open but buried in a sea of other windows. Ideally, I would be able to hit `[⊞ Win]` to trigger the menu to open and have KeepassXC brought to the foreground / made the active window (which is what would happen if KeepassXC were not already open). What happens instead (at least with Cinnamon on Arch Linux) is that the KeepassXC tile on the menu bar starts blinking, but the application stays in the background. This is helpful in locating where KeepassXC is on the menu bar, but it should be possible to trigger making it the foreground window (for context, if you have two profiles open in Google Chrome and in profile A you switch to the open profile B, focus will jump to the B window and B will be foregrounded).

I have not tried this with Windows or Mac, so I am not sure what the behavior is there.

**Comment by droidmonkey** [comment]
I thought this already happens

**Comment by droidmonkey** [comment]
Yes just tested and this works fine.

**Comment by pganssle** [comment]
@droidmonkey Is this something that was fixed recently? This has never worked for me on Cinnamon on Arch Linux.

**Comment by droidmonkey** [comment]
I can't speak for certain Linux distros, but it works on Mac, windows, fedora, and ubuntu

**Comment by pganssle** [comment]
I've tested this out now on Arch Linux with Cinnamon and a Debian-based distribution using Gnome and both show the same pathological behavior.

Here it is on Arch/Cinnamon (make sure that your mouse isn't hovering over the video when you watch it, the video player controls are hiding the bottom of the screen for me):

[KeepassXC-Screencap-Cinnamon.webm](https://github.com/keepassxreboot/keepassxc/assets/1377457/0f5d4b00-c1ed-4a4c-aac4-939c555705f4)

Here is the "Debug Info" from that installation
<details>
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.3.4-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0
</details>

Here it is on Debian/Gnome:

[KeepassXC-Screencap-Gnome.webm](https://github.com/keepassxreboot/keepassxc/assets/1377457/a2cbb566-6c13-4941-865f-1c5424d5f0cf)

And the Debug Info from that installation:

<details>
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Debian GNU/Linux rodete
CPU architecture: x86_64
Kernel: linux 6.1.25-1rodete1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
</details>

In both environments, triggering KeePassXC causes my cursor to be "loading" when I mouse over the tray until I've closed KeePassXC.  In Cinnamon only, it makes the window blink in the tray.

I'll note that when I try to launch it a second time from a pinned tray icon, it seems to work intermittently, here's a screen capture of that:

[KeepassXC-Screencap-Cinnamon-TrayIcon.webm](https://github.com/keepassxreboot/keepassxc/assets/1377457/60b8fced-390a-4507-bb64-c3f1cac2637b)

**Comment by droidmonkey** [comment]
What you are experiencing is a failure at the desktop environment level, not keepassxc. You might have a setting enabled that limits the ability of windows to "gain their own focus".

**Comment by pganssle** [comment]
> What you are experiencing is a failure at the desktop environment level, not keepassxc. You might have a setting enabled that limits the ability of windows to "gain their own focus".

I don't know what this setting would be. I certainly didn't configure it myself on _both_ computers.

From testing, most applications spawn a new instance when I do this. Thunderbird and VLC don't spawn new instances. VLC does nothing (not even the blinking window thing) and Thunderbird is able to give itself focus. I'd be happy to change my settings if that would solve the problem, but I think the fact that Thunderbird can apparently do the right thing combined with the fact that this is almost certainly the default behavior on multiple desktop environments makes me think that this is something that _can_ be solved by KeePassXC and that would be a benefit to average Linux users.

**Edit**: Audacity is also able to give itself focus.

**Comment by droidmonkey** [comment]
Is it something that we would solve or is it qt to solve. We just tell qt to give the window focus / activate it. The fact that VLC also fails points to a qt failure. VLC uses Qt.

**Comment by Wombosvideo** [comment]
Totally unrelated to KeePassXC: Tauri apps also have this issue (that is, at least for me on Ubuntu 22.04). They also blame the window manager.
