### ISSUE TITLE
Transfer of Passwords onto Android via QR Code

### ISSUE THREAD

**Issue by Algoritter** [keepassxreboot/keepassxc#9439]
## Summary
I need a way to transfer long and complicated passwords from my KeepassXC Database onto my Android Mobile Phone, without internet , without USB stick, just by using my camera. I do know that the password can remain in the clipboard of the google-keyboard, but that is another matter..

## Examples
- maybe a right-click on the key with: Show Password as QR-Code
- alternative: a Button in the Toolbar

## Context
 I do **not want to open a 3rd party tool** to copy and paste my password for generating a password in a secure way.
I have found that I can use **Inkscape** for generating me a QR code on my **local pc**. However, other people might use an online generator to get around this. No need to say that the password will leave the computer then. So why not integrate it into a program I already trust?

P.S: I have been looking for this kind of feature for a long time. I am curious why we do not have it yet.

**Comment by droidmonkey** [comment]
Duplicate
