### ISSUE TITLE
Frequently used entries easy access solutions

### ISSUE THREAD

**Issue by GitHubinatrix** [keepassxreboot/keepassxc#9441]
I have ~200 entries and counting - but no way of keeping those 5 used daily with those 5 others used weekly in one group of popular ones. [Unless I want to disrupt my system of groups creating chaos or keep copies of entries which in time will inevitably lead to differences emerging among supposedly the same entries due to user errors]

Hence in odder for users to see a handy and quickly accessible short list of frequently used entries I propose such additions and workarounds:

**1]** Make it possible to save Search results as virtual groups in the panel on the left side of main window

**2]** Make it possible to mark any entry as a special one - and show all of such in a Recycle Bin like group while also making that group the default one to be shown whenever a database is re-opened

**3]** Make it possible to mark any entry as a special one - and show all of such in root folder of this database

**4]** Make it possible to mark any entry as a special one - and show all of such in a virtual "group" which would be accessed after pressing of a button; and make switches within that "group" which would go between showing content from currently focused database or from all opened databases

**5]** Add a new column showing the YES / TRUE and NO / FALSE state for entries on lists in every group showing the YES / TRUE and NO / FALSE state for all entries on lists in every group

**Comment by droidmonkey** [comment]
You likely need to update to 2.7.5 because all of this is already possible
