### ISSUE TITLE
Password font is ambiguous for l and I on Mac OS

### ISSUE THREAD

**Issue by tazle** [keepassxreboot/keepassxc#9442]
## Overview
Password font is ambiguous for I and l on Mac OS.
<img width="301" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/681203/f2aa6304-737d-4111-862d-925b7028a710">

## Steps to Reproduce
1. Use Mac 
2. Try to read back password with I and l in it.

## Expected Behavior
I and l can be told apart.

## Actual Behavior
Need to paste the password in e.g. Emacs in order to tell I and l apart.

## Context
Related to https://github.com/keepassxreboot/keepassxc/issues/1771 but the solution there (configure system-wide monospace font) does not seem to be available on Mac.

# ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.3
CPU architecture: arm64
Kernel: darwin 22.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

**Comment by droidmonkey** [comment]
Update to 2.7.5, that was a bug

**Comment by tazle** [comment]
Excellent, thank you!
