### ISSUE TITLE
KeePassXC 2.7.5: attachments and URL's still cannot open from AppImage

### ISSUE THREAD

**Issue by nohing** [keepassxreboot/keepassxc#9443]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

It's not possible to open attachments and URL's from the AppImage of KeePassXC 2.7.5, 2.7.4 and 2.7.3
It works only with 2.7.1
When will this bug be fixed?
Am I forced to use 2.7.1 forever?  
Isn't there a way to fix this bug?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect when I click on attachments and urls that they open, but they don't.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Attachments and urls do not open when I click on them

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.5
Revision: REVISION 9d0537b

KeePassXC - VERSION 2.7.4
Revision: REVISION 63b2394

KeePassXC - VERSION 2.7.3
Revision: REVISION d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 21
Desktop Env: Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Duplicate

**Comment by nohing** [comment]
what do you mean with "duplicate"?
