### ISSUE TITLE
2.7.5 - attachments and urls do not open

### ISSUE THREAD

**Issue by nohing** [keepassxreboot/keepassxc#9445]
I cannot open attachments ans urls from KeePassXC 2.7.5 AppImage.
This problem persists since KeePassXC 2.7.3
Why don't you fix it?

**Comment by michaelk83** [comment]
Please use the search before spamming new issues. This is tracked in #8721.

> Why don't you fix it?

Because they have plenty of other work to do. They'll get to it when they get to it, unless someone contributes a PR.
(And specifically for this particular problem with AppImage, the fix may not be simple.)

**Comment by droidmonkey** [comment]
If you open another issue on this topic we will issue a ban. Please respect our requests to keep our issue board clean.

**Comment by nohing** [comment]
Fine, ban me.
thank you very much, you're so kind.
