### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by DarkPark** [keepassxreboot/keepassxc#9447]
## Summary
It would be nice to have a regular deb package.
Plain linux-x86_64 binary is very good as well.

**Comment by droidmonkey** [comment]
We don't manage distro specific packages. Please request this from your distro manager.

**Comment by phoerious** [comment]
Use our PPA if you want Debian packages.

**Comment by DarkPark** [comment]
@phoerious thanks for the tip but it's rather strange that there is no public info about it (looked through wiki and main site)
have to google to find it

**Comment by droidmonkey** [comment]
It's right on our download page....

https://keepassxc.org/download/#linux

**Comment by DarkPark** [comment]
yep
sorry, missed it
thanks

**Comment by DarkPark** [comment]
Sadly this PPA is not usable in Debian (unmet dependencies). I've tried all the Ubuntu versions.
