### ISSUE TITLE
2.7.5 not downloadable on MS Store

### ISSUE THREAD

**Issue by ehrw** [keepassxreboot/keepassxc#9448]
Can't find the 2.7.5 update on MS Store. Tested on two computers.
The release notes are posted on the page but no update is found.

**Comment by phoerious** [comment]
Microsoft always takes awfully long to approve new versions. Will be there eventually.

**Comment by droidmonkey** [comment]
I just checked, it is in the store right now

**Comment by ehrw** [comment]
> I just checked, it is in the store right now

Really, did you download it and saw the version number?
I still don't see it on any of my devices. The past few updates have been available instantly. It is a bank holiday this week so perhaps the approval process is slower.

**Comment by droidmonkey** [comment]
It's fully approved and published. There is not much else I can do from my end. I just downloaded the package that gets pushed from the store, it is 2.7.5 https://store.dmapps.us/KeePassXC-2.7.5-Win64.msi

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/ff92c6c7-561f-4e1a-9473-50f00c7a0155)

**Comment by ehrw** [comment]
Yep, couldn't be much clearer than that. Probably gradual rollout. Didn't know MS did that on the store too with minor version updates. Thanks for the swift responses!
