### ISSUE TITLE
Ctrl+Shift+C doesn't show/hide passwords

### ISSUE THREAD

**Issue by Lysrin** [keepassxreboot/keepassxc#9450]
This was an issue I was having in 2.7.4 and is now the same in 2.7.5. The shortcut key combo for show/hide usernames works fine. The one for show/hide passwords doesn't work for me.

**Comment by droidmonkey** [comment]
We removed that shortcut purposefully. Use the view menu

**Comment by Lysrin** [comment]
Oh that's unfortunate. That was a very useful one for me. Why keep the username view shortcut active but remove the password one? Some security issue?

I suggest that if the intention is to actually remove the passwords shortcut on purpose, the View menu should be updated in the application so that it no longer shows the shortcut as an option. That is confusing and looks like a bug.
