### ISSUE TITLE
Remove Ctrl+Shift+C shortcut from View menu

### ISSUE THREAD

**Issue by Lysrin** [keepassxreboot/keepassxc#9451]
Based on the response for closed issue #9450, I suggest that if the intention is to actually remove the passwords shortcut on purpose, the View menu should be updated in the application so that it no longer shows the shortcut key combo as an option. 

That is confusing and looks like a bug when the key combo doesn't work.

**Comment by droidmonkey** [comment]
I just tested this feature and it worked perfectly...

**Comment by Lysrin** [comment]
I'm sorry, but now I'm confused. I thought you said you purposely removed the shortcut key combo for viewing passwords. That is what was stated when #9450 was closed... So how could it work perfectly?

**Comment by droidmonkey** [comment]
I was mistaken. It is working and it wasn't removed. I think we re-added it after moving to the view menu.

**Comment by Lysrin** [comment]
Okay then. Wonder why it isn't working for me. I usually install the new version of KeePassXC over my existing install. Perhaps that is causing an issue? I'll try a fresh install and see if that makes any difference.

**Comment by Lysrin** [comment]
Nope same result. Ctrl+Shift+B for show/hide usernames works fine. Ctrl+Shift+C for show/hide passwords does nothing. Weird.
I guess if I'm the only one experiencing it, it will have to remain as an oddity for me! :)
