### ISSUE TITLE
Add Export and Import buttons for Application Settings

### ISSUE THREAD

**Issue by kaseeen** [keepassxreboot/keepassxc#9452]
Does the portable version of this software have a way to export the settings that have been adjusted? I want the new version to seamlessly inherit my settings from the old version

**Comment by zewebdev1337** [comment]
https://keepass.info/help/base/configuration.html

**Comment by michaelk83** [comment]
> https://keepass.info/help/base/configuration.html

That's for a different software. KeePassXC website is at https://keepassxc.org/ , user guide is at https://keepassxc.org/docs/KeePassXC_UserGuide

**Comment by zewebdev1337** [comment]
> > https://keepass.info/help/base/configuration.html
> 
> That's for a different software. KeePassXC website is at https://keepassxc.org/ , user guide is at https://keepassxc.org/docs/KeePassXC_UserGuide

absolutely correct, I just quickly eyed the paths shown and deemed it good, thanks for pointing that out

**Comment by droidmonkey** [comment]
Portable version config files are located in the `config` folder where you have it extracted. I assume you are on Windows. 

I am switching this to a feature request to add an Export/Import button.

**Comment by MarkWieczorek** [comment]
It would be extremely useful to have an option to export/import the application settings for the desktop app. 

Image setting up about 10 new devices for your family. Or setting up default settings for the members of your enterprise. This is a huge amount of time!

**Comment by droidmonkey** [comment]
If you are on Windows, you can access the config files rather easily, just put this path into Windows Explorer: `%APPDATA%/keepassxc/`

**Comment by MarkWieczorek** [comment]
I'm on MacOS and Linux.

**Comment by droidmonkey** [comment]
Linux is `~/.config/keepassxc/` and macOS is `~/Library/Application Support/KeePassXC/`

**Comment by ekasprzak** [comment]
Linux Flatpak is:

`~/.var/app/org.keepassxc.KeePassXC/config/keepassxc`

(Adding proposed import/export button would be still a nice addition).


And BTW - why "LastActiveDatabase" is in 
`.../cache/keepassxc/keepassxc.ini`
 and not in
 `.../config/keepassxc/keepassxc.ini`)
@droidmonkey?

**Comment by droidmonkey** [comment]
Anything with a path is meant to be local to your computer hence cache. It is also ephemeral setting.
