### ISSUE TITLE
abex.os.keepassxc.proto.KeePass......

### ISSUE THREAD

**Issue by welshkyle123** [keepassxreboot/keepassxc#9454]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

abex.os.keepassxc.proto.KeePass......
runelite plugin not accessing passwords, despite browser integration etc. works fine on my desktop but  not on my windows laptop.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. don't know, i've installed it as suggested i believe 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
it should bring up my passwords

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it brings up the above error code

## Context
[NOTE]: # ( Give us any additional information you may have. )
thank you for helping

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION most recent as of 19/05/2023
Revision: REVISION 

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon idk what  these mean, sorry
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
This isn't a product we are responsible for

**Comment by welshkyle123** [comment]
> This isn't a product we are responsible for

ah ok, sorry i'm not  really sure who to contact

**Comment by droidmonkey** [comment]
Probably this project https://github.com/runelite/runelite
