### ISSUE TITLE
More Prominent File Manager

### ISSUE THREAD

**Issue by tgwaste** [keepassxreboot/keepassxc#9455]
One of the best features about this app is the ability to keep files under Advanced -> Attachments.
It would be awesome if that were more prominent.  Have a tab (on the left) just for Files and give the list the whole window.

I know it'll probably never happen but I just love that feature.

**Comment by droidmonkey** [comment]
The kdbx format is not optimized for file storage and is really not a good idea to encourage it. Attachments are meant for very small files, text and images, not storage. Use cryptomator or veracrypt for these purposes.
