### ISSUE TITLE
how to maintain keepass continuously connected to the database

### ISSUE THREAD

**Issue by 1alexman1** [keepassxreboot/keepassxc#9457]
Hello,
I installed last version keepasxc 2.7.5 and also browser integration. Each time I need in browser for credentials, I see the keepass icon disable(not connected to database), and if I click on it, I receive:
Error!Not connected to keepasxc

Everything works ok if I open keepass and connect to database.
My question is: how to maintain keepass continuously connected to the database?

**Comment by droidmonkey** [comment]
You need to have keepassxc running in order to use the browser extension. This is just how it works.
