### ISSUE TITLE
Windows 11 KeePassXC 2.7.5 does not unload Keys from OpenSSH-Agent

### ISSUE THREAD

**Issue by rkl110** [keepassxreboot/keepassxc#9458]
When using Windows KeePassXC 2.7.5 to autoload my SSH-Keys to Pagent und OpenSSH-Agent on Windows 11. KeePassXC does not unload the Key from Windows, if I do not lock the database before a shutdown. After a reboot the key still persist in the agent and I'm able to connect to server without unlocking KeePassXC.

If I only load the key to OpenSSH-Agent the key gets removed correctly.

**Comment by droidmonkey** [comment]
This is likely because the ssh agent is being killed before keepassxc is being killed. There is nothing we can do about that. Unfortunately you'll have to lock the database before you shutdown to ensure the key is removed.
