### ISSUE TITLE
update to 2.7.5 causes "api-ms-win-core-kernel32-legacy-ansi-|1-1-0.dll is missing"

### ISSUE THREAD

**Issue by nunyaku** [keepassxreboot/keepassxc#9459]
using windows 8.1, ver 2.7.4-Win64-LegacyWindows, worked fine for months. been a few weeks since last boot, saw needed update to 2.7.5, attempted update but then,

the actual error: (
KeePassXC.exe - System Error
The program can't start because api-ms-win-core-kernel32-legacy-ansi-|1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.
)

am able to uninstall, then reinstall via original installer still on sys, KeePassXC-2.7.4-Win64-LegacyWindows.msi and all works fine. still cannot update though, just error above again.

can anyone please assist? dunno if actual bug, or perhaps something to do with legacy ver, something else? nunya is notoriously bad at making computer do what nunyaku want done... do not really need update, unless security flaw.

**Comment by varjolintu** [comment]
See: https://github.com/keepassxreboot/keepassxc/issues/7564#issuecomment-1078262880

**Comment by nunyaku** [comment]
thank you varjolintu! was unaware this was related to other dll issues, am not too clear on what dll even is or why my sys continues to run into "this or that dll is missing", but much appreciation for helping!
