### ISSUE TITLE
Windows Security Login Bug

### ISSUE THREAD

**Issue by Lefpadlog** [keepassxreboot/keepassxc#9460]
When you enter you main pasword correctly and you click the cancel butten at the Windows Security Login, you will still sing in. This bug isn't that important but is still good to know that it exists.

I noticed this bug just in the newest version.

The "Abbrechen" button is the "cancel" button, just in german
![image](https://github.com/keepassxreboot/keepassxc/assets/117570754/12520251-0db0-4c30-9fe6-fbe9e3206b76)

**Comment by droidmonkey** [comment]
That just does not enable quick unlock.
