### ISSUE TITLE
keepassxc unlock took ages

### ISSUE THREAD

**Issue by ma-gu-16** [keepassxreboot/keepassxc#9467]
Hi,

 ive just downloaded the current KeepassXC previously ive used "original" Keepass2 on Windows 11

i opened my kbxc password file with an seperate keyfile. KeepassXC open the file but it takes like more then minute to open.

at keepass2 it took me less then a second... i mean it wasnt noticeable. 

i guess something is wrong ? 

i already change the database security to 500ms.  but it seems nothing changed. 

i have the same result with an other keepass file without extra "key" to encrypt. 

i hope some can help.

**Comment by Kobi-Blade** [comment]
Cannot reproduce, I have my database set to 5 seconds (decryption time) and takes 3~5 seconds tops to open the database on 2.7.5.

**Comment by ma-gu-16** [comment]
i just created a new one. with only 1 password in it.. same .... more then a minute to open :(  (EDIT: while i wrote this it was like 3 minutes to open )

**Comment by ma-gu-16** [comment]
Im on 2.7.5 as well and i used the chrome plugin. if this is relevant.

**Comment by phoerious** [comment]
Check your encryption settings. If opening the database takes so long, then your key derivation settings are off. You most likely chose too many rounds.

**Comment by ma-gu-16** [comment]
> Check your encryption settings. If opening the database takes so long, then your key derivation settings are off. You most likely chose too many rounds.


i have:
compression on 
databaseformat KDBX 4
decryption time 1.0s  (even if i go with lowest nothing changed.)

transform rounds 41
memory 64mbit
paralleism  2 threads

**Comment by droidmonkey** [comment]
Unfortunately, there is nothing we can do without reproducing it on our end. I recommend reinstalling or trying a previous release version to see if this is something we introduced recently.

**Comment by ma-gu-16** [comment]
Now ive changed these settings. 
250mb memory 
4 threads 
5 transform rounds 

its amazing, same long time, but now it stoped after like 3 minutes. and the datebase is still locked. i have to reunluck, after third try it opended (after 3-4 minutes)

**Comment by ma-gu-16** [comment]
```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000
```



**WORKS WELL maybe a second to open.**

**Comment by droidmonkey** [comment]
Perhaps you are affected by #9429

This was caused by a circular reference between entries.

**Comment by ma-gu-16** [comment]
> Perhaps you are affected by #9429
> 
> This was caused by a circular reference between entries.

nope,  no memory consume at all... cpu was like 0.01% and memory very low like 60mb. 
same stats as with version 2.7.4 but unlock is super fast.

**Comment by droidmonkey** [comment]
Are you able to build and debug using visual studio? If not, we unfortunately cannot offer advice for that, it is rather involved.

**Comment by ma-gu-16** [comment]
> Are you able to build and debug using visual studio? If not, we unfortunately cannot offer advice for that, it is rather involved.

thank you, i will skip this version and try next one. maybe some on will figure it out. cant belive its just me ;-)
