### ISSUE TITLE
Can't repair database

### ISSUE THREAD

**Issue by talkingeyes1** [keepassxreboot/keepassxc#9470]
I have a KeepassXC database that I created a few weeks ago with version 2.7.4 after pulling out of LastPass.  I loaded all of my approx. 100 passwords and updated all of them with new passwords.  Now since I upgraded to KeePassXC 2.7.5 my database won't open I know I'm typing the correct password and it says that the credentials are invalid or db is corrupt.  I uninstalled 2.7.5 and re-sinstalled 2.7.4 but still get an error.  Created a new database and tried to import for corrupt one but then I get a message that it is not a KeePassXC database.  I looked at some articles online and it said to select the "repair" option under import but there is no repair option, just a import from KeePass 1 db, csv or Password1 db.  How do I repair the .kdbx database.  I had only been using the db for a few weeks and did not have a chance to make a backup and I don't have my passwords anywhere else so I need to recover this db.

**Comment by droidmonkey** [comment]
How are you storing your database file? Unfortunately, without a backup, there is nothing we can do to assist you. Since you can not open the file even with your original version, it is incredibly unlikely to be induced by 2.7.5. 

P.S.- the repair feature in keepass is a lie. It doesn't actually do anything relevant. If your database is actually corrupt, then there is nothing we can do to fix it.

**Comment by coditis** [comment]
You can search your filesystem for `{YOUR_DB_NAME}.old.kdbx`. KeePassXC has a feature that backs up your database before saving it, but I can't recall if it's turned on by default.

I had this happen to me once, but it was my hard drive's fault and I was able to recover the file by opening a backup.

**Comment by nandgator** [comment]
If I know the master key, can I use a hex editor to fix corrupted file? How long is the header of a kdbx v4 file?

**Comment by droidmonkey** [comment]
Start here: https://github.com/keepassxreboot/keepassxc/blob/develop/src%2Fformat%2FKdbxReader.cpp

Then go to kdbx4reader.cpp to see how the header is read. Kdbx4 has a dynamic header size and layout.
