### ISSUE TITLE
Moving entry to a different folder by »drag'n drop« stopped working when using Xorg rather than Wayland

### ISSUE THREAD

**Issue by wirepatch** [keepassxreboot/keepassxc#9473]
## Overview
Using the mouse to move an entry from a selected folder to the left sided tree is being blocked showing a stopping sign

## Steps to Reproduce

1. Select a folder in the folders tree view to the left
2. Select an entry from the entries to the right
3. Drag the entry to a different folder on the left sided tree view.

## Expected Behavior
The entry should be moved from the originally selected folder to the new one.

## Actual Behavior
Step three is being blocked by showing a stop sign preventing the entries relocation

## Context

KeePassXC - Version 2.7.5
Revision: 9d0537b

Operating System: Fedora Linux 38, install by rpm package, snap doesn't work either
Desktop Env: Gnome / Qt 5.15.9
Windowing System: X11 (Works with Wayland)

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/9269#issuecomment-1510439546
