### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by Sturm-Crow** [keepassxreboot/keepassxc#9474]
When attempting to update it goes from copying files to the below error message:

"The installer has encountered and unexpected error installing this package. This may indicate a problem with this package. The error code is 2349"

## Steps to Reproduce
1. run the installer 
2. select download location
3. enter admin credentials
4. Click ok, after message about needing to reboot system as part of the install process.
5. Error happens.

## Expected Behavior
I expected the installer to install the new version.

## Actual Behavior
installer aborts with error message

**Comment by droidmonkey** [comment]
This seems unique to you, recommend re-downloading the installation package. You can also use the portable version if it just doesn't work for you. Also make sure you close all your browsers and keepassxc prior to installation.
