### ISSUE TITLE
KeePassXC quit unexpectedly | macOS.

### ISSUE THREAD

**Issue by JohnDoe401** [keepassxreboot/keepassxc#9475]
## Overview
When i close the app macos gives me this error message: **KeePassXC quit unexpectedly**

## Steps to Reproduce
Just close KeePassXC with the x icon or command + Q

## Expected Behavior
KeePassXC closed without any error message

## Actual Behavior
macOS error message: KeePassXC quit unexpectedly

## Context
macOS version 11.7.5 | Big Sur
[Release 2.7.4] runs fine with no errors.

[NOTE]: # 
KeePassXC - Version 2.7.5

[NOTE]: # 
Operating System: macOS

_It's my first time opening an issue i hope it will be helpful._

**Comment by izoratti** [comment]
same here on MacOS Ventura 13.3.1 Intel
https://gist.github.com/izoratti/0ed114991be6095a8bfda212c5275e4b

**Comment by droidmonkey** [comment]
Duplicate, look at the pinned issues
