### ISSUE TITLE
Menubar options disappearing when hovering neighbor options

### ISSUE THREAD

**Issue by fabiocbarbosa** [keepassxreboot/keepassxc#9476]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I noticed this after upgrading to Fedora 38. No other major settings updates. Also, I tried other themes options (including platform-native - attached screencast).

I keep getting this error in the logs:
`keepassxc[42305]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

[96078efe-cb77-47c0-8196-309e57ed5fb8.webm](https://github.com/keepassxreboot/keepassxc/assets/62552478/c417800e-223d-45fb-8ced-aba6e4136619)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click on any menu-bar option
2. Move mouse to hover neighbor
3. Menu options/modal disappears 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Menu options/modal is kept open when hovering through neighbor options

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Menu options/modal disappears

## Context
[NOTE]: # ( Give us any additional information you may have. )
Any screen or db, locked or not
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Fedora Linux 38 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.2.15-300.fc38.x86_64
**Gnome: 44.1**
**Windowing System: Wayland**

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Please file a bug report with Qt or Fedora. The menu code is not in keepassxc.
