### ISSUE TITLE
Steam trade confirmations support

### ISSUE THREAD

**Issue by C0rn3j** [keepassxreboot/keepassxc#948]
Since it looks like [Steam Guard is going to make it to KPXC](https://github.com/keepassxreboot/keepassxc/issues/594), I'd love if steam trade confirmations could make it into it too.

WinAuth(GPLv3) [already has this implemented](https://github.com/winauth/winauth#new-features), but it is Windows only and frankly I'd enjoy a native solution.

**Comment by weslly** [comment]
Unfortunately, this one would require using Steam API and seems way out of scope for this project.

**Comment by phoerious** [comment]
I agree that this is out of scope of the main project. Maybe we will visit this issue again if and when we have a proper plugin infrastructure.
