### ISSUE TITLE
Cannot open KeeppassXC after update to 2.7.5

### ISSUE THREAD

**Issue by franzmeersdonk** [keepassxreboot/keepassxc#9480]
cannot open keepassXC anymore after update to 2.7.5

1. updated keepassXC to 2.7.5
2. try to open keepassXC

## Actual Behavior
cannot open KeePassXC, do not have access to my passwords
"Du kannst das Programm „KeePassXC“ nicht öffnen, da dieses Programm auf diesem Mac nicht unterstützt wird."

## Context
downgrade does not work either

KeePassXC - 2.7.5

Operating System: macOS 13.4
Macbook Pro 2017 13"

**Comment by droidmonkey** [comment]
Close all browsers and reinstall

**Comment by Wandmalfarbe** [comment]
@franzmeersdonk You might want to download the *Intel Mac* version, not the *Apple Silicon Mac* version (on the download page https://keepassxc.org/download/ in the panel *See more options*). The automatic download suggested `KeePassXC-2.7.5-arm64.dmg` but I needed `KeePassXC-2.7.5-x86_64.dmg`.
