### ISSUE TITLE
Provide a setting for screenshot security

### ISSUE THREAD

**Issue by chitinlink** [keepassxreboot/keepassxc#9483]
## Summary
Please provide a setting in the program to disable [screenshot security](https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security). 

## Example
The setting could live in the **Settings** > **Security** > **Convenience** section.

## Context
I'm aware I can launch KeePassXC using the command-line flag, but I'd rather have the program start at system startup.

**Comment by droidmonkey** [comment]
Update to 2.7.5...

We are not going to introduce a setting since that defeats the purpose of the security feature. Use the command line switch to make it "permanent" or the new View menu option to allow it temporarily.

**Comment by chitinlink** [comment]
For anyone else looking, I don't believe there's a way to have KeePassXC start at system startup with the command line flag, but you can add it to its shortcut:

![image](https://github.com/user-attachments/assets/516ebc50-af12-4e19-a28e-4a1e4a3399fe)

This way whenever it's started from the start menu, it will have screenshots enabled. I believe this change gets reverted every time KeePassXC updates, however.
