### ISSUE TITLE
Incomplete error message (unresolved printf placeholders) for malformed string in imported CSV file

### ISSUE THREAD

**Issue by blueentity** [keepassxreboot/keepassxc#9486]
## Overview
When importing passwords from a CSV file which contains a malformed string a justified error message is shown.
This error message intends to show column and row of the offending string, but shows printf() placeholders %1, %2 instead.

## Steps to Reproduce
1. Start import of attached CSV file: [Import_Error.csv](https://github.com/keepassxreboot/keepassxc/files/11582564/Import_Error.csv)
2. On page "Import CSV fields" the justified but incomplete error message is shown:
![Import_Error](https://github.com/keepassxreboot/keepassxc/assets/15192738/63326865-74c6-4b48-a78b-04d29bf6df8f)

## Expected Behavior
The error message should specify the offending location within the CSV file, e.g. "malformed string: (row,col) 2,25".

## Actual Behavior
The error message contains unresolved printf() placeholders: "malformed string: (row, col) %2,%3".

## Context
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
This is already resolved in pending PR that complete replaces this workflow

**Comment by blueentity** [comment]
Just out of curiosity: can you give me a hint, which PR will contain the fix?

**Comment by droidmonkey** [comment]
It's this branch still under development 

https://github.com/keepassxreboot/keepassxc/tree/feature%2F1pux-import
