### ISSUE TITLE
keepassxc snap is broken for Ubuntu 20.04

### ISSUE THREAD

**Issue by aki-k** [keepassxreboot/keepassxc#9487]
## Overview
keepassxc snap is broken for Ubuntu 20.04

## Steps to Reproduce
1. snap install keepassxc 

## Expected Behavior
keepassxc snap would install

## Actual Behavior
i get the following error message: 
```
- Ensure prerequisites for "keepassxc" are available (cannot install prerequisite "kde-frameworks-5-99-qt-5-15-7-core20": no snap revision available as specified)
```
## Context
trying to install keepassxc snap on Ubuntu 20.04

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

snap find keepassxc
Name             Version  Publisher       Notes  Summary
keepassxc        2.7.4    keepassxreboot  -      Community-driven port of the Windows application “KeePass Password Safe”

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Mate
Windowing System: X11/VNC

**Comment by droidmonkey** [comment]
Please use flatpak, we are no longer supporting snaps.
