### ISSUE TITLE
KeePassXC not visible in Microsoft Store Library after installation (Windows 11)

### ISSUE THREAD

**Issue by Bruceforce** [keepassxreboot/keepassxc#9489]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I installed KeePassXC from the Microsoft Store for all devices of my family members and myself to avoid the typical Windows-User questions like "what exactly do I need to download to update the software?". A few days ago I was curious why the KeePassXC Browser extension told me that I was using an "old" version (2.7.4) while there is 2.7.5 available. I went to the library in Microsoft Store and KeePassXC was not listed here, but when I open the store site manually it shows "installed". However there seemed to be no way of updating rather than uninstalling and re-installing (which I then did).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC from the Microsoft Store
2. Check library in Microsoft Store
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should be visible in the Microsoft Store library and allow to trigger manual updates if they are available.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC is not visible in the Microsoft Store library and therefore cannot be updated.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I was curious if this is on my system only. So I installed another application (Netflix) which immediately showed up in the library. I also tested this on a freshly set-up Windows 11 VM without Microsoft account and had the same issue.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Seems this is BY DESIGN. Thanks Microsoft. 

https://windowsreport.com/windows-11-store-app-update/

**Comment by Bruceforce** [comment]
@droidmonkey I see why you are closing this. However I'm pretty sure that the windows store app I had installed not told me that there is a new version available. I only noticed this by the "little star icon" in the browser App. 

Wouldn't it at least be possible to have a "warning" or similar for the store app users that they need to take care of updates by themselves or use the msi Installer Version instead of the store version. Otherwise some people might not even know that there are updates available.

Also I'm not sure if this should be closed at all since this is still an issue other might also have. Although you cannot easily fix this. However of course it's up to you how you handle that kind of stuff.

**Comment by droidmonkey** [comment]
There is no 'fix' to this that involves the store. It will NOT notify you of an update nor provide one. We already have an update notification in keepassxc itself and the browser extension. 

The only fix to this is to add an auto-update installer mechanism to keepassxc itself... which we are really not keen on doing
