### ISSUE TITLE
KeepassXC doesn't respect system theme in Antergos xfce

### ISSUE THREAD

**Issue by ThosV** [keepassxreboot/keepassxc#949]
See title. Pretty self explanatory. 

## Expected Behavior

I have the system theme set to Adwaita Dark and it should match that. 

## Current Behavior

Keepassxc remains in it's default theme. 

## Steps to Reproduce (for bugs)

1. Install Antergos xfce
2. Install Keepass (from the main repo or git, neither works)
3.
4.

## Context

Not a huge biggie, just kind of jarring.

## Debug Info

KeePassXC - 2.2.0
Revision: 

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: 4.12.12-1-ARCH

Enabled extensions:
- N/A

**Comment by phoerious** [comment]
Are you using the AppImage or Snap Package? Those can't use your system theme by design. If you want better integration, please install KeePassXC from your package manager.

**Comment by ThosV** [comment]
I tried that as well and it didn't work either. Same problem.

**Comment by phoerious** [comment]
If the package was compiled natively for your platform (which the Arch packages are), it should pick up your system theme. If it doesn't, you have a general theming problem on your system and there isn't much we can do about it.

Since Adwaita is a GTK+ theme, I would assume that you are somehow missing a proper Qt theme (maybe try adwaita-qt or something).

**Comment by flip-bs** [comment]
I finded a solution **not to resolve** but to bypass this issue 
Launch keepasscx with a specific theme like this (in this case Adwaita-Dark)
```
keepassxc -style Adwaita-Dark
```
Or add a `export QT_STYLE_OVERRIDE=adwaita-dark` in your .bashrc this will affect all qt5's app.

it's work for my Arch-Linux xfce

![capture d ecran_2018-01-26_15-54-05](https://user-images.githubusercontent.com/10530469/35445164-0442cae2-02b1-11e8-9798-1fcc07569c3b.png)

**Comment by Piraty** [comment]
> Or add a export QT_STYLE_OVERRIDE=adwaita-dark in your .bashrc 
This only works if a qt-compatible adwaita is installed.

Besides that, you could either use `qt5ct` or place sth. like `export QT_STYLE_OVERRIDE=gtk2` in `~/.initrx` to achieve a [uniform look for Qt and Gtk applications](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications).

**Comment by droidmonkey** [comment]
I'm considering this fixed.
