### ISSUE TITLE
window hidden when screengrab or vnc

### ISSUE THREAD

**Issue by timsoftgit** [keepassxreboot/keepassxc#9494]
running 2.7.5 on windows 10 64bit v22H2 the application is invisible to "printscreen" method of copying screen to clipboard. It is also invisible to a tightvnc client, making it impossible to remote control for support, or create step-be-step instructions by taking screen-grabs.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

Also check out the view menu...

**Comment by timsoftgit** [comment]
many thanks for the pointer to the command-line option. and view option. I was looking for such a thing but missed it.
