### ISSUE TITLE
keepassxc 2.7.5 snap fails to launch on RHEL7 / CentOS 7

### ISSUE THREAD

**Issue by pjperry** [keepassxreboot/keepassxc#9495]
## Overview
After updating to keepassxc version 2.7.5 in snapd, keepassxc failed to start:

# snap refresh
keepassxc 2.7.5 from Jonathan White (keepassxreboot) refreshed
WARNING: There is 1 new warning. See 'snap warnings'.
[root@quad virusmails]# snap warnings
last-occurrence:  today at 21:15 BST
warning: |
  snap "kde-frameworks-5-102-qt-5-15-8-core22" has bad plugs or slots:
  kde-frameworks-5-102-0+p22-qt-5-15-core22 (invalid slot name:
  "kde-frameworks-5-102-0+p22-qt-5-15-core22")

## Steps to Reproduce
1. On RHEL7 / CentOS 7, install and configure snapd
2. Restart PC
3. Install keepassxc from snap store
4. Attempt to launch keepassxc

## Expected Behavior
keepassxc runs as expected

## Actual Behavior
keepassxc fails to start

## Context
Reverting (downgrading) back to version 2.7.4 fixes the issue
I can find no way to install version 2.7.4 from the snap store for a new install.
Please can version 2.7.4 be made available in a separate channel in snap store for installation on RHEL7

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 1689

Operating System: RHEL 7 / CentOS 7
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
You should switch to flatpak. YMMV with snap, as demonstrated here.

**Comment by droidmonkey** [comment]
I just tested from Fedora 37 and it worked fine. That warning means nothing. Try running with `snap run keepassxc`

**Comment by pjperry** [comment]
Still doesn't work - the error is:

[phil@xps-rhel7 ~]$ snap run keepassxc
QThread::start: Thread creation error (Operation not permitted) 

Thank you for the advice - I will investigate flatpak options.
