### ISSUE TITLE
Always ask before performing Auto-Type doesn't work

### ISSUE THREAD

**Issue by randrewy** [keepassxreboot/keepassxc#9499]
## Overview
I've tried to achieve the opposite of [Why does KeepassXC auto-type prompt me to select entry when I only have one entry?](https://superuser.com/questions/1625364/why-does-keepassxc-auto-type-prompt-me-to-select-entry-when-i-only-have-one-entr) by enabling `Always ask before performing Auto-Type` option, and what I expected was a prompt appearing every time I click the key icon/hit the shortcut.

## Steps to Reproduce
1. Enable `Always ask before performing Auto-Type` option
2. Go to website with a password stored
3. Click key-icon on login field

## Expected Behavior
A window appear to select credentials (even if there is only one matching result)

## Actual Behavior
Credentials are immediately filled

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
That isn't autotype, that is the browser integration

You need to go to the entry that supplies those credentials, open it for editing, go to the properties tab, delete the custom data for the browser plugin. 

At some point you either saved this entry using the browser plugin which auto-grants access, or you chose to allow and remember access.

**Comment by randrewy** [comment]
Thanks a lot! Exactly what I wanted.
