### ISSUE TITLE
Time for a minor release?

### ISSUE THREAD

**Issue by adatum** [keepassxreboot/keepassxc#950]
Is there any chance of issuing a new minor release soon? It's been ~3 months since the last (major) release of v2.2.0. Since then a lot of work has been committed and merged (33 closed issues so far for the v.2.2.1 milestone).

For example, I've been (im)patiently waiting for a release with #703 which is already done.

Previous minor releases were more frequent. I don't object to longer release cycles, but there are lots of goodies and bug fixes ready to be shipped and enjoyed!

**Comment by droidmonkey** [comment]
Its being buttoned up right now. Unfortunately Travis decided to update and broke our CI. Once fixed we'll be merging the last batch of PR's for 2.2.1.
