### ISSUE TITLE
Looking for a 2.7.5 Version fix for macOS quits unexspectedly on exit 

### ISSUE THREAD

**Issue by aeroxx9** [keepassxreboot/keepassxc#9502]
Is there way to use the 2.7.5 version for old mac os intel (2018) or do I have to wait for a new release? hope this thread is not a problem﻿  
//
            Hi,
I am seeing this as well.

It has not been seen with the 2.7.4 Version.
Is it possible to provide a Download-Link for the previous version? 

Kind regards,
Andreas

_Originally posted by @andreasgremm in https://github.com/keepassxreboot/keepassxc/issues/9423#issuecomment-1550421333_

**Comment by droidmonkey** [comment]
Go to our releases page to download prior versions.
