### ISSUE TITLE
Show OTP in main entry menu

### ISSUE THREAD

**Issue by avidseeker** [keepassxreboot/keepassxc#9503]
## Summary
Clicking on an entry shows up username, password, URL, notes, etc.

It would be useful if the main entry also shows up TOTP instead of having to 1) exit the entry 2) right click 3) select totp 4) select show totp. 

## Examples
This is how Bitwarden shows the entry:
![image](https://github.com/keepassxreboot/keepassxc/assets/67508272/c66ef720-7494-4d8a-a658-bab9f6269143)

## Context
[NOTE]: This is primarily for filling out passwords in Mobile phones by looking at the screen of KeePassXC database.

**Comment by droidmonkey** [comment]
Update to 2.7.5, already been implemented

**Comment by avidseeker** [comment]
Maybe you misunderstood my suggestion. I'm suggesting to include the OTP box in the entry overview here:

![image](https://github.com/keepassxreboot/keepassxc/assets/67508272/200c17d4-39a1-438e-ab8f-e763db533f6c)


Info:

```
$ pacman -Q keepassxc
keepassxc 2.7.5-2
```

**Comment by droidmonkey** [comment]
This is editing an entry. Your entry overview is the preview panel at the bottom of the main view. We won't show TOTP values while editing an entry

**Comment by avidseeker** [comment]
Oh, I see. I have this collapsed long time ago and forgot it's there.

It would be convenient then to include "copy" buttons besides "Display current TOTP value" and "Display password" buttons.
