### ISSUE TITLE
REGEX interpretation

### ISSUE THREAD

**Issue by sap7772000zilla** [keepassxreboot/keepassxc#9504]
Hello.
First I must confess that I don't know if this is bug or new feature, so if I labeled this post wrongly please accept my apologies and apply the proper label.

I migrated from KeePass and noticed that URLs that contain REGEX expression are not interpreted and in the target app the fields receive the REGEX formula instead of the converted value
Here's a truncated example containing solely the part that doesn't work, I marked this with the first **...** after **cmd://**:
cmd://... -system={T-REPLACE-RX:/{Title}/(.{3}).*/$1/} -client={T-REPLACE-RX:/{Title}/.*(.{3})/$1/} 
My **Title** field contains a string like this **XXX 123** so my expectation is that my app will receive **XXX** in field **_system_** and **123** in the field **_client_**
In reality field **system** receives **{T-REPLACE-RX:/{Title}/(.{3}).*/$1/}** and field **client**, you guessed already, **{T-REPLACE-RX:/{Title}/.*(.{3})/$1/}** and my app doesn't make any sense out of the input.
Needless to say that the above works in KeePass.

I have more than 20 entries like this all containing the same URL but different **Titles** and that is very convenient; I use them for work.
Thank you.

**Comment by droidmonkey** [comment]
We do not support this syntax and we will not support it outside of auto type. Add the desired title as an advanced attribute and include it directly using `{S:attrname}`

**Comment by droidmonkey** [comment]
Also #7293
