### ISSUE TITLE
Copy Attribute sub-menu is unusable on Windows systems with mixed DPI displays on lower DPI display.

### ISSUE THREAD

**Issue by krittinen** [keepassxreboot/keepassxc#9505]
## Overview

On a Windows 10 22H2 system using two mixed DPI displays (1920x1080 100%, 2560x1440 125%) the entries in the Copy Attribute sub-menu are too large for the actual panel on the lower DPI display, as such some menu items are unreachable (There should be a 'Numero' entry under 'Nombre')

![image](https://github.com/keepassxreboot/keepassxc/assets/7507064/58649036-ee99-429b-b6cf-6c3f5e2f0a2c)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set both displays to different DPI settings (ie: 125% and 100%)
2. Open KeePassXC and move the window to the display with lower DPI
3. Right click on any password entry and navigate to the Copy Attribute sub-menu

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I can see and select all the entries in the sub-menu.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The font size is too big and some entries are outside the actual panel and can't be selected.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 22H2 19045.2965

**Comment by droidmonkey** [comment]
This isn't something we can fix, it is a qt bug

**Comment by michaelk83** [comment]
Try setting `QT_SCALE_FACTOR` environment variable.
https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options
