### ISSUE TITLE
Start/Stop HttpServer not just from settings!

### ISSUE THREAD

**Issue by aadrian** [keepassxreboot/keepassxc#951]
Please add Start/Stop HTTPServer functionality - not just from the Settings.

## Expected Behavior

Please add menu item to the Tray Icon to be able to Start/Stop the HttpServer.
Please add a toolbar Icon(action) for this in the Main Window too.
Also please add a shortcut for this operation.

## Current Behavior

Right now, the user needs to go to "Settings"/"Browser Integration" and toggle the checkbox with "Enable HTTPServer" in order to be able to use the browser integration; than use the passwords with the Browser, and than toggle it back if one wants to have it running on demand only.

## Context

Having the HTTP Server to run only only on demand with a simple shortcut, increases security.
Since this usecase (start server, user password, stop server) is too tedious, most users are not using it.

Thanks in advance.

**Comment by phoerious** [comment]
There is no real security benefit to be gained from turning it on and off all the time. The API is only exposed via localhost. So unless you have multiple concurrent users on your machine, it's only you who can talk to KeePassXC over HTTP.

**Comment by aadrian** [comment]
> The API is only exposed via localhost. 

It's quite hard to audit all processees that run on localhost :) . 
Especially considering that many of them are not open source.

>> Since this usecase (start server, user password, stop server) is too tedious, most users are not using it.

> It'd also be interesting where you got that data from.

The above steps take a few seconds to perform. Having only one shortcut would take only a fraction of a second, and it would be also discoverable for all users (the menu item and toobar icon).

On most machines where I deployed this software (toghether with sync software), users  haven't activated it :) , even if it was explained in the training materials that they can use it, activate and deactivate it back.

**Comment by phoerious** [comment]
Only because something can listen on localhost, it doesn't mean it can access your database. It still needs the protocol encryption key and if your database is locked, also your database master key. Of course, those data can be obtained, but not because KeePassXC is listening on localhost, but because the potentially malicious program is already running on your computer.

So instead of turning the server on and off all the time, you should rather configure a sensible lock timeout.

**Comment by aadrian** [comment]
> So instead of turning the server on and off all the time, you should rather configure a sensible lock timeout.

Thank you.
