### ISSUE TITLE
set new expiry presets

### ISSUE THREAD

**Issue by Redstylt** [keepassxreboot/keepassxc#9510]
Hello ,

It would be great to be able to make new expiry presets. 
For example, my IT has made my password expire after 25 days... It's a real pain to calculate the expiry date each time.

Thanks! Great programme otherwise.

**Comment by michaelk83** [comment]
#6800
However, you can use the 3 weeks preset as a close approximation.

**Comment by droidmonkey** [comment]
Why change it early? Just let the password expire and then change it when you next log in. 

You should also point your IT staff to the NIST recommendation of having NO password expiration. It's literally the dumbest thing you can do if you are enforcing good passwords.
