### ISSUE TITLE
Add "Copy SSH public key to clipboard" to entry context menu

### ISSUE THREAD

**Issue by ZJaume** [keepassxreboot/keepassxc#9511]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Be able to copy the SSH public key directly from context menu instead of opening the entry and going to the SSH section. Maybe also having a shortcut could be useful. But at least in my case, I don't use it often enough to be necessary. Having the context menu option, would be sufficient.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Go to an entry in the database that has an SSH key attached, do right-click to open the context menu and go to the bottom, where SSH options are, and click "Copy SSH public key to clipboard".

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
For people who gain access to new SSH servers frequently, copying the public key faster is something useful.

**Comment by droidmonkey** [comment]
That is a very specific feature and we generally do not add those types of things. It clutters the ui and is extra code. Instead, we recommend you use existing features like additional attributes. 

Go to the advanced tab when editing the entry, create a new attribute named Public Key, and paste the value you want there. Now it will show up in the right click menu to copy.

**Comment by ZJaume** [comment]
I didn't know I could do that. That's also a nice solution, thanks!

**Comment by Mazwak** [comment]
I looked for this feature and found this issue.

The UI, in this case right-click menu, has entries when an SSH Key is available.

- Add to SSH Agent
- Remove from SSH Agent

I don’t see why "Copy public SSH Key" is excluded.

I’m not against adding an attribute, but I’m not very fond of copy-pasting the public key there.
It would be nice to use a variable, like %SSH_PUBLIC_KEY%.

I still prefer an integrated solution, maybe an SSH sub-menu in the context menu.
