### ISSUE TITLE
QR Code Reader to Enter Main Pwd

### ISSUE THREAD

**Issue by G-i-o** [keepassxreboot/keepassxc#9514]
[TIP]:  Add option to enter the main pwd by scanning a QR code.

[NOTE]: There are many ways to get a long pwd by memorizing a short one. The problem remains typing it in.
By KP having a QR reading capability/option when opening the database, one could create the long pwd on another device, like phone, on the spot and transfer it via QR code.

Technically, one could already do that with KDE Connect, for instance, but it would go through the clipboard and one would have to remember to clear it and it might not be the safest way.

Example:

- Open KP on the desktop and select the database.
- Create the passowrd on the mobile and have it ready in QR form (There are QR apps that offer the explict option not to store the QR).
- Click on the KP to select the QR reader to open the database. The camera should activate.
- Pass your mobile on the camera. KP should accept the QR as password, validate it and open the database.

Thank You.

**Comment by droidmonkey** [comment]
We are not going to interface with a camera. This is a hard no from me, sorry.

**Comment by G-i-o** [comment]
I understand. Thank You anyhow.
