### ISSUE TITLE
Pwd as Backup Option to Keyfile (and viceversa)

### ISSUE THREAD

**Issue by G-i-o** [keepassxreboot/keepassxc#9515]
[NOTE]: 
Currently, among the options, one could access a KP database by either entering a pwd or a keyfile or both.
However, it is not possible to have a pwd as backup of a keyfile (or viceversa).

If I want to use a very strong pwd to lock the database but can't afford to retype it each time, I can use a keyfile. However, if the keyfile is lost or corrupted, I would lose the access forever.

Instead, having a strong backup pwd, would still allow me to access the database.

**Comment by droidmonkey** [comment]
This is not a feature of the KDBX standard and we will not deviate from the standard. We do recommend that you get a hardware key such as a Yubikey instead of using a key file. You can make duplicate keys and keep one in a safe place as abackup.

**Comment by G-i-o** [comment]
OK. My bad day with FRs. 😢️

No problem. Keep up the good work! 🙏️

**Comment by G-i-o** [comment]
Just a marginal note......I try to avoid as far as possible buying new hardware, especially first-hand. I worked for a recycling company and discarded electronics is a nightmare.
Also, would not solve the issue. If I lose the or damage the key when I'm travelling or otherwise don't have access to the backup one, I would be locked out of the database anyhow.

I will just keep making strong pwds on the mobile and transfer them with KDE Connect, remembering to clear the clipboard. Not ideal  but acceptable.

Thank You for your suggestion, though. Your work is appreciated.

**Comment by droidmonkey** [comment]
You're welcome! Don't hesitate to write a FR, you can also start a discussion thread with all your ideas in one place and we can promote them to FRs if they work for us.

**Comment by G-i-o** [comment]
Will do. Thank You! 🙏️
