### ISSUE TITLE
Windows install fails: Invalid Drive

### ISSUE THREAD

**Issue by embediver** [keepassxreboot/keepassxc#9518]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
This is the exact same behaviour reported in issue #7597.

I get this when trying to install the latest release (2.7.5-Win64) on my system.
In my case I had KeePassXC installed previously on a HDD which failed and thus is no longer available.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC on a drive different to the system partition
2. Remove drive/partition with KeePassXC install
3. Try to install KeePassXC again while there is no drive with the letter of the previous install
4. Error shuld pop up (I didn't test if this is actually reproducable, since I would have to fire up a fresh win10 vm...)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC install works as expected when installing/reinstalling.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When launching the KeePassXC msi installer, a message box prompts _"Invalid Drive: [drive letter]:/"_.
After that the installer states _"KeePassXC Setup Wizard ended prematurely"_ [Finish].

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Commit: 9d0537bdab70c49b6e0f551e1cda30e01b3d413a

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by embediver** [comment]
I managed to install KeePassXC without error, after hitting uninstall for a KeePassXC entry left in the System Settings.

Don't know if this is still considered a bug, but I would atleast consider improving the error message somehow.

**Comment by droidmonkey** [comment]
This is behavior of the installer not our program. Anything using msi will do the same thing.

**Comment by NamelessVoice** [comment]
If this happens after manually moving the installed files to a different drive and removing the original drive:

To work around this, you can use the registry editor to find the uninstall information for KeepassXC, which will be inside 
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{D6D6D43E-C39C-4518-80DC-2A480473DBF4}`

I'm not sure if that UUID is the same across all computers - if not, just do a search for an entry for KeepassXC in the above folder.

Correct the InstallLocation to point to the correct drive/location, then the installer/uninstaller will work agian.
