### ISSUE TITLE
Use a smaller preview pane in compact mode

### ISSUE THREAD

**Issue by jtagcat** [keepassxreboot/keepassxc#9519]
## Expected Behavior
At minimum 5 notes in the right-hand side list are shown.

Here's with `QT_SCALE_FACTOR=0.75`
![image](https://github.com/keepassxreboot/keepassxc/assets/38327267/1e763503-4da8-4359-abb8-0fc2b85ded46)

I'd prefer 0.75, but can't be used as it renders the app unusable on external displays: https://github.com/keepassxreboot/keepassxc/issues/8758#issuecomment-1311363556

## Actual Behavior
![image](https://github.com/keepassxreboot/keepassxc/assets/38327267/69a4e6c7-37ee-49b1-881c-87597d30d574)

## Context
- Is an issue on 12" and 14" laptops, both FHD. Isn't an issue on 21"+ FHD monitors.
- Arch, sway (Wayland).
- Both screenshots use compact mode.

```
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.3.4-arch1-1
```

**Comment by droidmonkey** [comment]
You can drag it down further. FHD is 1920x1080 pixels regardless of the screen size.

**Comment by michaelk83** [comment]
Also you can set separate scaling factors for different screens with `QT_SCREEN_SCALE_FACTORS`.
https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options
Or maybe use a separate link to run on the external screen without setting `QT_SCALE_FACTOR`.

**Comment by jtagcat** [comment]
> You can drag it down further. FHD is 1920x1080 pixels regardless of the screen size.

I can't. It's at the minimum height. If you drag it more, it will get hidden completely.

https://github.com/keepassxreboot/keepassxc/assets/38327267/1cf62283-972c-4fa2-9141-535a004a42a7

> Also you can set separate scaling factors for different screens with `QT_SCREEN_SCALE_FACTORS`. [keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options](https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options)

It does not work. Laptop screen acts the same as external monitors with QT_SCALE_FACTOR. It is then unusable on all screens.

![image](https://github.com/keepassxreboot/keepassxc/assets/38327267/fc03722f-da18-4a9c-8bfe-045342c987ec)

> Or maybe use a separate link to run on the external screen without setting `QT_SCALE_FACTOR`.

It runs as a service, all further opens will return `Another instance of KeePassXC is already running.`. It opens a new window, ignoring any scaling.

**Comment by droidmonkey** [comment]
You definitely have a screen scale factor problem. Our app is twice the size it should be given the scaling of your taskbar (maybe even 3 times). Look at your environment variables and set them appropriately. You will likely have to add the Qt env vars in your .bash_profile or similar.

Do one of the following at the end of your `~/.bash_profile`:
```
export QT_SCALE_FACTOR=1
export QT_SCREEN_SCALE_FACTORS="1;1;1"
```

Although in my testing QT_SCREEN_SCALE_FACTORS generally breaks the UI whereas QT_SCALE_FACTOR does not.

**Comment by jtagcat** [comment]
I had global `QT_WAYLAND_FORCE_DPI=physical`, removing it, it works. (cc @izaera?)

Although, when scale factor is exactly 1, it has gigantic icons on the left:

![image](https://github.com/keepassxreboot/keepassxc/assets/38327267/3d1ecb0c-d542-411b-9fd3-4d3e5ef0fc97)

When any valid screen (with `QT_SCREEN_SCALE_FACTORS` or `QT_SCREEN_SCALE`) has a non-1 factor, it looks normal on all displays (including where screen scale is 1).

Having a non-1 on one screen is what I want anyway, so worksforme. You might want to track the obese group item height nevertheless.

Thank you!

**Comment by jtagcat** [comment]
Deleted comment to remove edit history:

> You can drag it down further. FHD is 1920x1080 pixels regardless of the screen size.

I can't. It's at the minimum height. If you drag it more, it will get hidden completely.

(video removed)

> Also you can set separate scaling factors for different screens with `QT_SCREEN_SCALE_FACTORS`. [keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options](https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options)

It does not work. Laptop screen acts the same as external monitors with QT_SCALE_FACTOR. It is then unusable on all screens.

![image](https://github.com/keepassxreboot/keepassxc/assets/38327267/fc03722f-da18-4a9c-8bfe-045342c987ec)

> Or maybe use a separate link to run on the external screen without setting `QT_SCALE_FACTOR`.

It runs as a service, all further opens will return `Another instance of KeePassXC is already running.`. It opens a new window, ignoring any new scaling environment.

**Comment by izaera** [comment]
@jtagcat I stopped using KeepassXC (in favor of Bitwarden) so I'm afraid I cannot provide any feedback. Sorry :-(

However, if you really need someone to test this it in Sway I can install it and try. Just ping me in that case :+1:
