### ISSUE TITLE
Clarify database history settings

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc#952]
Does unticking the "Max. history items" checkbox disable history items or _trimming_ of history items?

## Expected Behavior

The label should explain what unticking it does, and it should be trivial to disable history completely. For example, this could be a sub-form:

```
[v] Store history
  [v] Max. items: [10]
  [v] Max. size: [6 MiB]
```

## Context
I'm trying to minimise the size of the database for revision control. Currently it's not possible to set max history size to 0, and I don't know if setting max history items to 0 disables it or (like many other programs) acts like infinity.

**Comment by louib** [comment]
@l0b0 I **think** the max items is per entry, but the max size is for the database, so we might want to clarify that as well.
