### ISSUE TITLE
The password cannot be entered using keepassxc on the login screen for some software 

### ISSUE THREAD

**Issue by Nexus3932** [keepassxreboot/keepassxc#9520]
- The password cannot be entered using keepassxc on the login screen for some software because the autofill function is disabled for such software
- Unable to use the global input function to enter the account password in the Genshin Impact login interface. Once the shortcut key is used, the game will be cut back

**Comment by droidmonkey** [comment]
We do not support using keepassxc on a login screen to your computer. You must be logged in / unlocked to use the program.
