### ISSUE TITLE
Segmentation fault in keepassxc-proxy 

### ISSUE THREAD

**Issue by esemeniuc** [keepassxreboot/keepassxc#9522]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I try to run keepassxc-proxy (version 2.7.5-2 on Arch), I get a segmentation fault

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use keepassxc for a while with Firefox 113.0.2 and extension 1.8.6.1
2. Eventually extension stops working. Trying to resync, I get ` Key exchange was not successful. `
3. Manually run `keepassxc-proxy`, see there is a segfault

## Expected Behavior
Normally access keepassxc like I have used for the past 4 years

## Actual Behavior
Segfault in proxy.

## Context
GDB output:
```
Reading symbols from /home/eric/.cache/debuginfod_client/9ea6f6cd40efd140da393aa39ffe75292e3d7832/debuginfo...

warning: Can't open file /usr/lib/libglib-2.0.so.0.7600.2 during file-backed mapping note processing
[New LWP 2355111]
[New LWP 2355110]

warning: Section `.reg-xstate/2355111' in core file too small.

warning: Build-id of /usr/lib/libQt5Network.so.5 does not match core file.

warning: Build-id of /usr/lib/libssl.so.3 does not match core file.

warning: Build-id of /usr/lib/libcrypto.so.3 does not match core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/bin/keepassxc-proxy /home/eric/.mozilla/native-messaging-hosts/org.keepass'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/2355111' in core file too small.
#0  0x00007f163011f2da in std::basic_istream<char, std::char_traits<char> >::sentry::sentry (this=0x7f162c9fec37, __in=..., __noskip=true) at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/istream.tcc:50
50	/usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/istream.tcc: Bad file descriptor.
[Current thread is 1 (Thread 0x7f162c9ff6c0 (LWP 2355111))]
(gdb)
```

I can provide the dump file over private channels. Note: I am running gcc12 due to bugs in 13. KeepassXC might be compiled for gcc13?
```
➜  ~ pacman -Q | grep gcc
gcc 12.2.1-4
gcc-libs 12.2.1-4
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.1.31-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
Please report to your package manager (Arch), they screwed up the packaging. Switch to Flatpak for a better experience overall.

**Comment by esemeniuc** [comment]
@droidmonkey could you explain what is wrong? Is there a missing file?

**Comment by droidmonkey** [comment]
We are not responsible for Arch linux packaging. It looks like they have a completely botched compile of the proxy.

**Comment by esemeniuc** [comment]
I reverted back to GCC 13, fixes the issue
