### ISSUE TITLE
Improve colorful locked icon for system tray

### ISSUE THREAD

**Issue by soredake** [keepassxreboot/keepassxc#9523]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download 2.7.5, icon is not good.
2. Download 2.7.4, icon is good.

## Expected Behavior
Have good icon like in 2.7.4 and older.

## Actual Behavior
New icon is not good.

## Context
New icon:
![Screenshot 2023-06-03 195325](https://github.com/keepassxreboot/keepassxc/assets/5204968/944ee52b-46f3-43ec-96e4-52419e23f598)
![Screenshot 2023-06-03 195411](https://github.com/keepassxreboot/keepassxc/assets/5204968/28b60a20-ee9e-4614-8849-f735908366f0)

Old icon:
![Screenshot 2023-06-03 200000](https://github.com/keepassxreboot/keepassxc/assets/5204968/ab606f54-5f2e-497e-8a82-1e10a446544d)
![Screenshot 2023-06-03 200007](https://github.com/keepassxreboot/keepassxc/assets/5204968/e8995825-43a8-4328-8f5e-31103c96ff4a)

KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
What is your screen resolution?

**Comment by soredake** [comment]
1920x1080 on 24" monitor.

**Comment by droidmonkey** [comment]
It's really the colorless icon that doesn't look that great. I think your screenshots show the green icon looks better as the new one.

**Comment by soredake** [comment]
For me the old icon looks better, not the new one.

**Comment by droidmonkey** [comment]
Closing this in favor of #9432
