### ISSUE TITLE
Password pointer to another entry in the db.

### ISSUE THREAD

**Issue by lessfoobar** [keepassxreboot/keepassxc#9525]
At work we have over 20 services that we use on a regular basis and they all have their own OTP token. We use SAML and LDAP for auth which speak with Kerberos. Every 3 months I have to change my password (company policy) this way I have to edit my password 20 times for each entry. My feature request is so that I can have a single entry and if my password is empty on all the other entries I can give this entry as reference so that the password is taken from that entry. This way I can have my TOTP codes on separate entries and one password to change every 3 months.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_entry_cross_reference

Also you can clone an entry and add references when you do that
