### ISSUE TITLE
installed the latest version 2.7.5, can't open application

### ISSUE THREAD

**Issue by Jim773** [keepassxreboot/keepassxc#9528]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

After the software is installed successfully, the application cannot be displayed, only the taskbar has an icon

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
![image](https://github.com/keepassxreboot/keepassxc/assets/135567888/1fc71634-a6df-4eb5-89c9-b1cf63dedf13)

2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.5
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: 
Windowing System: win10 21h2

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security
