### ISSUE TITLE
Escape key should close password generator

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc#953]
## Expected Behavior

Close the password generator when pressing <kbd>Esc</kbd>.

## Current Behavior

Nothing happens.

## Steps to Reproduce (for bugs)

1. Click Tools → Password Generator.
2. Press <kbd>Esc</kbd>.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: 4.12.12-1-ARCH

**Comment by phoerious** [comment]
Related to #907

**Comment by droidmonkey** [comment]
This no longer works as of 2.5.0
