### ISSUE TITLE
Upgrading or uninstalling/reinstalling via homebrew causes error "Operation not permitted @ rb_sysopen - /Applications/KeePassXC.app"

### ISSUE THREAD

**Issue by decodering** [keepassxreboot/keepassxc#9530]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

![image](https://github.com/keepassxreboot/keepassxc/assets/20130935/4c0dc2a9-70a3-460b-a6ef-62b93ec77825)

![image](https://github.com/keepassxreboot/keepassxc/assets/20130935/09bbb825-73f4-42e2-84df-67a0191931f5)

Upgrading, uninstalling or reinstalling via homebrew causes the error "Operation not permitted @ rb_sysopen - /Applications/KeePassXC.app" when trying to upgrade keepassxc to the latest version via `homebrew upgrade --cask`. Commands were run on:
* Brew version:
  * Homebrew 4.0.20-22-g9155746
  * Homebrew/homebrew-core (git revision 3a4d62846a2; last commit 2023-02-16)
  * Homebrew/homebrew-cask (git revision f7c0fa4386; last commit 2023-02-16)
* See keepassxc and mac version below

Further info on file permissions

<img src="https://github.com/keepassxreboot/keepassxc/assets/20130935/c5d454a2-95be-4e22-873b-a4fa4ce812b1" width="500">

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open mac terminal
2. Type into the terminal `brew upgrade --cask keepassxc` or `brew reinstall keepassxc`
3. The aforementioned error appears. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Keepassxc upgrades successfully to the current latest version (2.7.5) via homebrew.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Homebrew errors out.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: -

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS ventura (13.4 (22F66))

**Comment by decodering** [comment]
I did eventually find a simple workaround via the context clues of the error in the `brew reinstall` command, which was to manually delete / uninstall the application file the mac way:

1. Open the mac Applications folder in finder
2. Make sure to exit KeepassXC first otherwise the next step will error out
3. Graphically uninstall keepassxc as you would any other mac app typically by dragging the keepassxc icon into your bin
4. Run the `brew reinstall keepassxc` or `brew upgrade --cask keepassxc` commands again and it should work this time
5. Clear your mac bin permanently

Curious for others more knowledgable on the issue / have encountered this before as to if this fix is the recommended route. Googling official guidance on uninstalling keepassxc or upgrading it via homebrew always mentions to just upgrade normally via cask, but can't find references of this error occuring or how to handle it if it does.

**Comment by droidmonkey** [comment]
This isn't a keepassxc problem and we don't maintain the homebrew package. Glad you figured it out though.
