### ISSUE TITLE
KeepassXC Entries exist but not visible

### ISSUE THREAD

**Issue by jborduas67** [keepassxreboot/keepassxc#9532]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Currently I have a KeepassXC file on the Windows drive shared and my colleagues are able to modify and see the entries but from my hand, the file content seems empty and invisible.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open the file savec and shared on Windows drive
2.  There is no entries visible
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I should see the content and all entries

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No entries visible

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: REVISION ?

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Windows
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You are not opening the correct file or you are opening a cached file.

**Comment by jborduas67** [comment]
The same file is used by 5 persons and I know it is the right file...  What is the cached file mean here?

**Comment by jborduas67** [comment]
@droidmonkey see above

**Comment by droidmonkey** [comment]
If you are unlocking a database then you have the credentials to it and anything inside will be visible. If you unlock an older copy of that database then newly added entries won't be visible. I have no insight into your file storage solution but it comes down to opening the correct database file. There is nothing special after that.
