### ISSUE TITLE
View > Compact Mode doesn't work anymore.

### ISSUE THREAD

**Issue by Quintovir** [keepassxreboot/keepassxc#9534]
## Overview
I've always used keepassxc in Compact Mode. A just updated my system and now the entries and icons are really big. Before updating my system, my 35+ groups could all fit on the screen without needing to scroll down and I could view all entries in a group without scrolling down most of the time.

![Screenshot_20230606_070718_EDITED](https://github.com/keepassxreboot/keepassxc/assets/28264543/ee859cab-7ac5-41fd-9be0-5fbd1e2362b0)

## Steps to Reproduce
Update to KeePassXC - Version 2.7.5.

## Expected Behavior
Compact Mode should work and make the text and icons of groups and entries small.

## Actual Behavior
There is no visual change whether you have Compact Mode enabled or not.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

[NOTE]: # ( Pick choices based on your environment )
Operating system: Manjaro Linux
CPU architecture: x86_64

Kernel: linux 6.1.31-2-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0

**Comment by droidmonkey** [comment]
Screenshot?

**Comment by Quintovir** [comment]
I've added a screenshot.

**Comment by droidmonkey** [comment]
Ok thought so, you need to either remove an environment variable or add one. Please post the output of `env | grep QT_`

**Comment by Quintovir** [comment]
```
$ env | grep QT_
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
QT_AUTO_SCREEN_SCALE_FACTOR=0
```

**Comment by droidmonkey** [comment]
You need to remove that second env var

**Comment by Quintovir** [comment]
I did both:
`env --unset=QT_AUTO_SCREEN_SCALE_FACTOR`
`sudo env --unset=QT_AUTO_SCREEN_SCALE_FACTOR`

But it still shows up in `env | grep QT_` results.

**Comment by droidmonkey** [comment]
It may be in your ~/.bash_profile or ~/.bashrc or similar. You'll have to log off and log in for everything to apply properly

**Comment by Quintovir** [comment]
I rebooted the PC but it still hasn't gone back to compact.
I searched my home and root folder (including hidden files) and the only files where `QT_AUTO_SCREEN_SCALE_FACTOR=0` appears are in `.bash_history` and some file in `.mozilla/`

**Comment by droidmonkey** [comment]
It probably exists in your /etc folder as the default for all accounts. You can also just add: `export QT_AUTO_SCREEN_SCALE_FACTOR=` to your .bashrc or .bash_profile

**Comment by Quintovir** [comment]
One of my games stopped working and after a little bit of searching I found that the problem might be corrupted system files. I ran fsck on a live USB and now both the game and keepassxc work properly.
