### ISSUE TITLE
Suggestion: Windows Hello prompt within short amount of time for different database unlockings

### ISSUE THREAD

**Issue by tricoos** [keepassxreboot/keepassxc#9535]
When unlocking multiple databases shortly after another with Windows Hello protection enabled I am prompted again and again for the same Windows Hello key - this is not a safety feature, but an annoyance if it is asked for within 30 seconds of the last unlocking, because if I know it now it surely know it 10 seconds later.

I suggest to add an additional option to set a time for not asking for this key like "[ ] Do not ask again within [   ] seconds"

**Comment by droidmonkey** [comment]
Unfortunately that is not possible. We never have access to the key which is why you get prompted in the first place. This would have to be a feature at the windows kernel level, but it is not.

**Comment by tricoos** [comment]
@droidmonkey I would have thought of something like this:
IF TouchID Windows Hello has been enabled AND another database was just unlocked X seconds before do not use Touch ID/Windows Hello
Not looking at "when Windows did it", but "when you did it" so temporarily disabling the check in KeePassXC - I don#t understand why this would have to be done at the Windows kernel level if I can simply disable the option in KeePassXC in general.

**Comment by droidmonkey** [comment]
You should investigate using auto open. That is in place to solve these problems. Check out the documentation. 

We are also making changes to the UI for 2.8.0 so you can disable quick unlock for select databases. That sounds like what you want.

**Comment by droidmonkey** [comment]
You should investigate using auto open. That is in place to solve these problems. Check out the documentation. 

We are also making changes to the UI for 2.8.0 so you can disable quick unlock for select databases. That sounds like what you want.

**Comment by michaelk83** [comment]
@tricoos That prompt is triggered for one of two reasons: either to store your credentials for that particular database, so that they can be used by Quick Unlock afterwards, or to retrieve the credentials to Quick Unlock the database. Either way, this a per-database operation. The prompt is an OS-native prompt, and KeePass doesn't have access to the PIN or other information that you enter in that prompt. So it has to be prompted again for each database.
