### ISSUE TITLE
Tags have disappeared from the UI

### ISSUE THREAD

**Issue by tasso85** [keepassxreboot/keepassxc#9536]
## Overview
The tags which should be displayed in the lower left part of the main UI are not present anymore, and there seem not be an option to show them again.

## Steps to Reproduce
I cannot provide steps as I don't remember doing anything in particular to make them disappear.

## Expected Behavior
The tags should be visible in the lower left part of the main UI as shown in the docs.

## Actual Behavior
The tags are not visible.

## Context
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Drag the separator up, the horizontal bar between groups and tags.

**Comment by tasso85** [comment]
... Now I feel really dumb. Thanks, it was really that easy.

Sorry for the wrong report, I really didn't notice the bar to be dragged.
