### ISSUE TITLE
Advanced Settings Tick Box Missing on MacOS

### ISSUE THREAD

**Issue by mcqj** [keepassxreboot/keepassxc#9537]
## Overview
On MacOS, the advanced tick box in settings is missing and so advanced settings are unavailable.

## Steps to Reproduce
Simply open the settings dialog bu clicking toolbar button.

## Expected Behavior
I expect to see and advanced tickbox in the bottom left of the dialog as per documentation.

## Actual Behavior
advanced tickbox is simply not there.

## Context
<img width="803" alt="Screenshot 2023-06-07 at 11 09 08" src="https://github.com/keepassxreboot/keepassxc/assets/5565612/31658503-3435-4e0c-8ad2-19ef5ac1e68e">

KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.8
Debugging mode is disabled.

Operating system: macOS 13.3
CPU architecture: arm64
Kernel: darwin 22.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
That is in the database settings. Database-> database security

**Comment by mcqj** [comment]
Thanks for the response. I can't even access database settings, it's greyed out. I presumed that's greyed out because I don't have advanced settings turned on.

**Comment by mcqj** [comment]
<img width="238" alt="Screenshot 2023-06-07 at 11 19 56" src="https://github.com/keepassxreboot/keepassxc/assets/5565612/094d8104-60f0-4a04-96b1-4790b521ce4d">

**Comment by droidmonkey** [comment]
I recommend reinstalling, something is fundamentally broken. Make sure all browsers are closed before you do.

**Comment by mcqj** [comment]
Thanks - seems to be sorted now.
