### ISSUE TITLE
restart keepassxc after upgrading on windows

### ISSUE THREAD

**Issue by soredake** [keepassxreboot/keepassxc#9538]
## Summary
It would be nice if keepassxc can start keepassxc after upgrading from old version to new, right now installer will close keepassxc before upgrade but will not start it again after installation is done.

## Examples
1) Do `winget install -h -e --id KeePassXCTeam.KeePassXC -v 2.7.3`
2) Start keepassxc.
3) Do `winget upgrade -h KeePassXCTeam.KeePassXC`
4) KeePassXC is not restart after upgrade is done.

## Context
KeePassXC don't have built-in updater, so i use winget to update keepassxc, it's annoying that i need to start it again manually after every update, same with chocolatey package.

**Comment by droidmonkey** [comment]
We do start after install, the installer may be preventing that with flags provided after install. We don't control that, the maintainer of the winget package would.

**Comment by soredake** [comment]
@droidmonkey there are no additional options passed to installer aside from [default two](https://github.com/microsoft/winget-cli/blob/4233493b20200f3f798c92637950f73599fd998a/src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp#L772) (`/quiet /norestart`)

I've installed 2.7.3 from winget, them downloaded 2.7.5 installer and run it with `.\KeePassXC-2.7.5-Win64.msi /quiet`, keepassxc is NOT started in silent install mode, please reopen.

**Comment by droidmonkey** [comment]
This is by design, hence silent/quiet. This is not something we control it is a fundamental feature of MSI

**Comment by soredake** [comment]
> This is not something we control it is a fundamental feature of MSI

Is this really not possible?

I found this:
https://stackoverflow.com/questions/31701696/launching-application-after-silent-install
https://stackoverflow.com/questions/1668274/run-exe-after-msi-installation
https://stackoverflow.com/questions/37045908/how-to-launch-application-after-silent-installation-in-advanced-installer
https://www.advancedinstaller.com/forums/viewtopic.php?t=33673

**Comment by droidmonkey** [comment]
We aren't going to implement a bypass of this, sorry.
