### ISSUE TITLE
Keepassxc Snap doesn't run on ubuntu 16.04

### ISSUE THREAD

**Issue by NIXOYE** [keepassxreboot/keepassxc#954]
when doing 
>snap run keepassxc

I get "snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks"

## Expected Behavior

The application should run
## Current Behavior

The application returns an error
## Steps to Reproduce (for bugs)

1. Install keepassxc using 'snap install keepassxc'
2. Try to run keepassxc with 'snap run keepassxc'

## Debug Info

KeePassXC -tracking:    stable
installed:   2.2.0 (23) 79MB -
refreshed:   2017-06-25 18:25:35 -0400 EDT

Operating system: Ubuntu 16.04

**Comment by droidmonkey** [comment]
You are using it wrong. After you install the snap simply run by typing in ```keepassxc```

**Comment by NIXOYE** [comment]
If I do 'keepassxc' I get "command not found" and if I do sudo snap install keepassxc it tells me keepassxc is already installed. Could it be because I'm on 16.04? Iirc the latest update didn't work from app image or deb on 16.04

**Comment by droidmonkey** [comment]
After you install the keepassxc snap you should have a ```/snap/keepassxc``` directory and ```/snap/bin/keepassxc``` available. It could be that your path does not include the snap bin directory.

**Comment by NIXOYE** [comment]
@droidmonkey I have both directories. Is there something I can do to fix the issue so i can run keepassxc and so it appears in my application menu?

**Comment by droidmonkey** [comment]
what does "echo %PATH% | grep snap" spit out?

**Comment by NIXOYE** [comment]
>echo %PATH% | grep snap: command not found

**Comment by droidmonkey** [comment]
see my edited post

**Comment by NIXOYE** [comment]
>/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

if i do 
>/snap/bin/keepassxc

i get 

>snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks

**Comment by droidmonkey** [comment]
are you logged in as root???

**Comment by NIXOYE** [comment]
no

**Comment by NIXOYE** [comment]
hm. after restarting my computer KeepassXC is now in my applications menu but if i type keepassxc in a terminal it says 'keepassxc: command not found' and the application doesn't launch if I click it in my applications menu

**Comment by droidmonkey** [comment]
This is definitely an issue on your end, your path does not contain the snap bin directory and the snap process is warning you that you are breaking out of containerization.

**Comment by NIXOYE** [comment]
So I'm out of luck i guess?

**Comment by songproducer** [comment]
I'm also experiencing this issue. Can you please reopen?

Get the error:
"snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks"

when running keepassxc at the terminal.

**Comment by droidmonkey** [comment]
This is not keepassxc fault! You are trying to run a snap as root or some other highly privileged account.

**Comment by songproducer** [comment]
Thanks! You're right - and you helped me fix my kernel!

**Comment by droidmonkey** [comment]
Yay glad to have helped

**Comment by NIXOYE** [comment]
How did you fix the issue?

**Comment by songproducer** [comment]
Restored the right kernel by booting into it through advanced options in grub.
