### ISSUE TITLE
Twitter OTP

### ISSUE THREAD

**Issue by CarlozHOdl** [keepassxreboot/keepassxc#9544]
## Overview
Cannot set up OTP on Twitter using KeePassXC

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I normally go to my security settings page on Twitter
2. Turn on the Authentication app
3. Enter the provided code into KeePassXC
4. Generate the OTP code on KeePassXC
5. I paste it on Twitter and it says: "Incorrect. Please try again."

## Actual Behavior
"Incorrect. Please try again."

## Context
Is there a specific algorithm that I should select?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11
Desktop Env: 
![Screenshot 2023-06-10 155039](https://github.com/keepassxreboot/keepassxc/assets/39348227/9ef3f5b0-09df-4f48-be4a-407619ea879a)

**Comment by droidmonkey** [comment]
Sync your computer time

**Comment by CarlozHOdl** [comment]
> Sync your computer time

It worked!! Thank you. 👍
