### ISSUE TITLE
More than one password for a single Entry

### ISSUE THREAD

**Issue by Karbi123** [keepassxreboot/keepassxc#9547]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Many bank websites require two or more passwords - one for login and the other to access profile or to make transactions.
Within the same domain, the URL maybe will be different for accessing the profile. In the scenarios like this, how can I add another password for the same entry? This password is different from the login password.  

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Use additional attributes
