### ISSUE TITLE
Why do I download and install the latest version, but it is still the same version after installation?

### ISSUE THREAD

**Issue by zhl111** [keepassxreboot/keepassxc#9549]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Uninstall the previous version 2.7.4, install 2.7.5, and the result is still 2.7.4

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download the latest version 2.7.5 from the website
2. Prompts me to uninstall the installed version
3. After uninstallation, install the new version

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: 11

**Comment by droidmonkey** [comment]
You did not run the new installer. Upgrading to a new version does not ask you to uninstall. Running the same installer as the version already installed will ask you to repair or uninstall.

**Comment by zhl111** [comment]
1.![image](https://github.com/keepassxreboot/keepassxc/assets/29135984/24aae8a4-be79-4b5a-b916-f60a546abf62)

2.
![image](https://github.com/keepassxreboot/keepassxc/assets/29135984/18141bd5-0f62-4e6c-9aa9-b9d853d84e37)
3.
![image](https://github.com/keepassxreboot/keepassxc/assets/29135984/9a54af56-8a74-4ef5-ab0c-e6f1287a45ce)

**Comment by zhl111** [comment]
I did it again
![image](https://github.com/keepassxreboot/keepassxc/assets/29135984/0d4cd54a-9018-46c1-b256-5998f1292e12)
It was not prompted to uninstall this time，but...still 2.7.4

**Comment by droidmonkey** [comment]
Reboot. You might also be running 2.7.4 as a portable version. I can 100% guarantee that the 2.7.5 installer installs 2.7.5.

**Comment by zhl111** [comment]
thanks，I got It
