### ISSUE TITLE
Stateless Password Manager option

### ISSUE THREAD

**Issue by NIXOYE** [keepassxreboot/keepassxc#955]
Could we get a Stateless password manager option so we can use KeepassXC how https://lesspass.com/#/ works?

**Comment by droidmonkey** [comment]
Based on my reading of the [about lesspass](https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4) page, I don't really understand why you would want to integrate that functionality into KeePass... it kind of defeats the purpose. The whole point of lesspass is that it is clientless.

Why not just use lesspass?

**Comment by TheZ3ro** [comment]
I personally don't think those approach are safe.
Deterministic password managers are simply flawed.

https://tonyarcieri.com/4-fatal-flaws-in-deterministic-password-managers
