### ISSUE TITLE
Autotype option not found in rightclick menu

### ISSUE THREAD

**Issue by sathishkumarsk1993** [keepassxreboot/keepassxc#9550]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Autotype option from the right click menu is not present in this version. Ctrl+shift+V shortcut is also not working. I have relied on this feature to autotype passwords in netbanking websites since they don't allow pasting. Not it is gone, I have to manually type in the password. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right click an entry
2. Autotype option is not there.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I require Autotype option. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Ubuntu 23.04
CPU architecture: x86_64
Kernel: linux 6.2.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
You need to run keepassxc and the target application you want to type into on X11. You are running on Wayland, and autotype is not available on that setup.

**Comment by sathishkumarsk1993** [comment]
Thank you!
