### ISSUE TITLE
Additional Text and methods after modifier characters

### ISSUE THREAD

**Issue by dneuhaus76** [keepassxreboot/keepassxc#9551]
## Summary
We would like some more auto-type flexibility with sequences and pass after modifiers additional text or variables. We use procedures like this to directly jump to fields

## Examples
This way with notepad is only for displaying what the need is...
![image](https://github.com/keepassxreboot/keepassxc/assets/81403092/cba0fce6-5750-4402-bdd9-43676dc79f5c)
![image](https://github.com/keepassxreboot/keepassxc/assets/81403092/dab6200b-c62f-4c45-91ba-a604e7ea6f0d)

## Context
We don't have unsecure ways like scripting keystrokes

**Comment by droidmonkey** [comment]
You need to add a delay, this is a problem with the new Notepad not KeePassXC:

`^f{DELAY 20}{S:FieldA}`

**Comment by dneuhaus76** [comment]
@droidmonkey 
Windows: No, that is not working. I also tried it in other programs like EDGE with no success --> BUT in Winword it was ok.

Linux: It's working like a charm with the same procedure

**Comment by droidmonkey** [comment]
I tested the above on windows using notepad and it worked fine. Make sure you are using version 2.7.5.

**Comment by dneuhaus76** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/81403092/788a30b4-f68c-4e60-965d-183ad94832a1)

I am really sorry, but... Its not working - here once more my steps:

![image](https://github.com/keepassxreboot/keepassxc/assets/81403092/c9fa22b2-eb60-4548-9260-501a3af8233c)

It should have write "Test" somewhere - if you look at my sequence...
Delay was ok, ^f was ok... but "Test" went to nirvana, i assumed that this goes into the search field where the last search "a" was

![image](https://github.com/keepassxreboot/keepassxc/assets/81403092/4461e3a0-5874-4d07-94f4-379a8edc8c2a)

**Comment by droidmonkey** [comment]
This happens because the find popup is actually a new window and that interrupts the auto-type process. This is a fundamental security feature of auto-type. Unfortunately there is nothing we will do about this. You will have to press CTRL+F on your own and then invoke auto-type on the find window.

**Comment by dneuhaus76** [comment]
Ok, thx a lot for the clarification
