### ISSUE TITLE
Problem with this # character in Database Password in Version 2.7.5

### ISSUE THREAD

**Issue by Chrislybaer0** [keepassxreboot/keepassxc#9553]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Using the character "#" in the database password end up with HMAC Error and datatbase cannot be opened.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. setup a new database with a password with the "#" character
2. save and close the database
3. try to reopen the database
4. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
well... it should be opened again

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it says HMAC not equal

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.75
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/
Desktop Env: 
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
If you have to use dead keys or similar to type a # then you will have to reveal the password (click the eye icon or press Ctrl + H) in order to type it correctly. This is a qt bug.
