### ISSUE TITLE
Always show Quick Unlock settings checkbox on Windows and MacOS

### ISSUE THREAD

**Issue by dennisfrett** [keepassxreboot/keepassxc#9554]
## Overview
In the manual page it is explained this can be disabled: "You can disable this feature in the Application Settings under the Security section."

Since I assume biometric authentication is less strong than entering my password, I'd like the option to disable biometric unlock (I'm using macOS Ventura on a 16-inch, 2023 Macbook Pro). I don't see this option in the preferences. 

KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.8
Debugging mode is disabled.

Operating system: macOS 13.4
CPU architecture: arm64
Kernel: darwin 22.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Operating System: macOS

**Comment by droidmonkey** [comment]
If you don't see the setting then that means quick unlock is unavailable on your computer.

**Comment by dennisfrett** [comment]
> If you don't see the setting then that means quick unlock is unavailable on your computer.

Quick Unlock (through biometrics) is certainly available and enabled for KeepassXC on my system. Whenever I lock my database, I can unlock it through TouchID. I just don't seem to be able to disable this. Is there any more debugging information I can provide for this?

**Comment by droidmonkey** [comment]
Make sure you are looking in the right place and also make sure your laptop lid is open when you are looking there:

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/4f6183fe-8cec-404c-901a-bc6e0099d8a4)

**Comment by dennisfrett** [comment]
I can't seem to take a screenshot of KeepassXC, so I'm including pictures I took from the screen. The option you are showing in your screenshot doesn't seem visible to me. However, in the second image you can see I can unlock the database with biometrics after locking the database.

![20230614_140913](https://github.com/keepassxreboot/keepassxc/assets/659950/d73689c1-6bf2-4b7f-8132-55a270dbf757)
![20230614_140925](https://github.com/keepassxreboot/keepassxc/assets/659950/fbe6d5fb-a5d1-4bfe-a144-c240e17997d7)

**Comment by droidmonkey** [comment]
You can use the view menu to temporarily allow screen shots. This appears to be a bug and possibly related to our dynamic detection of the availability of macos biometrics. Does the option appear if you completely quit out of keepassxc then reopen with the laptop lid open?

**Comment by dennisfrett** [comment]
> You can use the view menu to temporarily allow screen shots. This appears to be a bug and possibly related to our dynamic detection of the availability of macos biometrics. Does the option appear if you completely quit out of keepassxc then reopen with the laptop lid open?

Ah yes, then it appears:
![image](https://github.com/keepassxreboot/keepassxc/assets/659950/06de0167-8801-4326-97b1-8a7a9f80b925)

Thanks!
