### ISSUE TITLE
Store RDP and Refer to RDP Credential Entry

### ISSUE THREAD

**Issue by dlauwers** [keepassxreboot/keepassxc#9555]
It would be nice if we could store all our RDP (Remote Desktop) of our Windows Servers/Machines also inside of KeepassXC.
Instead of an URL this would be the IP or Network name of the host.
Also, instead of entering the same username/password, an 'RDP' entry could refer to a password credential entry. This way we could keep the combination username/password only Once, but use it for multiple servers/workstations in the remote desktop setting.
This idea can also be used for VNC, Teamviewer, ...
So that we could manager our Remote Desktop connections together with all the passwords, and that we have a secure way of accessing them by double clicking the RDP Entry to open the session, 
A bit of combining mRemoteNG with KeepassXC ?

Possible ?

**Comment by droidmonkey** [comment]
Create an entry, add your rdp file(s) as attachments, then set your login credentials in username/password/etc.

Now just double click the attachment in the preview pane to launch the RDP and you can auto-type your credentials in. You can also add window associations to auto-type to bind the RDP entries to that login form. This is covered in the user guide.
