### ISSUE TITLE
macOS Touch ID quick unlock: open active unlock dialog right away

### ISSUE THREAD

**Issue by foss-** [keepassxreboot/keepassxc#9557]
macOS 13.4
KeePassXC 2.7.5

## Summary
Thanks so much for adding support on macOS for Touch ID quick unlock.

##Currently
When database is locked and quick unlock enabled in settings, KeePassXC shows a dialog to `Unlock KeePassXC Database` along with two buttons `Unlock Database` and `Cancel`. Pressing `Unlock Database` then opens the macOS dialog indicating it is waiting for Touch ID input.

##Expected
The workflow would be more seamless if instead of showing the dialog where a button has to be selected, both dialogs would be opened simultaneously. That way users could put their finger on Touch ID and unlock the database without further interaction.

Since this process happens rather frequently, this should be a very useful change.

Technically it is possible - 1Password uses this workflow. They have another refinement in their dialog showing a button which allows for entry of Password to unlock the database. In KeePassXC there is no simply way to switch to password currently.

KeePassXC unlock dialog, which would be great to show right away:
![KeePassXC unlock dialog](https://github.com/keepassxreboot/keepassxc/assets/5708172/48ab2db3-3342-496f-85f8-b9a2dfa4f286)

1Password unlock dialog with option to enter Password instead:
![1P unlock dialog](https://github.com/keepassxreboot/keepassxc/assets/5708172/6e04ebf8-2710-4857-baef-c021748225f3)

It is also nice, that 1Password uses less technical wording in that dialog. Maybe that can be adopted as well?

**Comment by droidmonkey** [comment]
This is covered by #9030. Please add a comment about simplifying the text in that issue. Thank you!
