### ISSUE TITLE
Autotype Clipboard Function - aka autotype-clipboard

### ISSUE THREAD

**Issue by akurzawa** [keepassxreboot/keepassxc#9560]
No discussion, lecture, topic closed. This is how the the process development shouldn't look like.

**Comment by droidmonkey** [comment]
Don't copy it to the clipboard just use auto type. If you want arbitrary text typing then use a dedicated program for that like power automate desktop or roboforms. We are not going to implement a feature that takes arbitrary text from the clipboard and types it. That is definitely not in our scope or desired operation.
