### ISSUE TITLE
Problem view settings are not saved - roaming profile

### ISSUE THREAD

**Issue by B2Cert** [keepassxreboot/keepassxc#9561]
## Overview
Hello,

I have a problem with KeepassXC (version 2.7.5). Roaming profiles are used. The view settings are always lost after a logout and login. Other programs do not have this problem. KeePass 1 and 2 did not have this problem either.

Where does KeePassXC store the view settings like table width etc.? In the KeePass database or somewhere else?

## Debug-Info:
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows Server 2016 Version 1607
CPU-Architektur: x86_64
Kernel: winnt 10.0.14393

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
That is stored in local data (%APPDATALOCAL%), you can use a command line flag or environment variable to change this location. Your company must be wiping out your user profile when you log off.

https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options
