### ISSUE TITLE
Bug on macbookpro ventura 13.4

### ISSUE THREAD

**Issue by fred33fra** [keepassxreboot/keepassxc#9562]
Hi There
I have a problem with the last version  2.7.5
<img width="675" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/136809672/0f5f00b6-0748-4da1-9211-dccbec55b5b0">

the application is not supported on my computer.... can you help me ?

many thanks

## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Download the version that corresponds to your processor,  Intel or Mac Silicone
