### ISSUE TITLE
Missing up and down menu entires for moving items

### ISSUE THREAD

**Issue by zanzara** [keepassxreboot/keepassxc#9563]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I miss the up and down arrow-entries  in the context-menu and menu for moving items (to re-order them)

On another system with almost the settings and the **SAME** KeepassXC version 2.7.5  they exists.

Why?  What is wrong?  What do I miss?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
That these keys should exist in the menus

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
They don't exists.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/Cinnamon
Windowing System: X11

This below is a snapshot of the entry menu:  (sry, for non-english version)

![shutter_Menu_keepassxc275](https://github.com/keepassxreboot/keepassxc/assets/7381054/d6073a9c-98f0-4e8b-a522-ad198d4e7f78)

**Comment by droidmonkey** [comment]
Click the sorting header in any column of the entry view until the the arrow disappears. You cannot move entries if they are being sorted.

**Comment by zanzara** [comment]
> Click the sorting header in any column of the entry view until the the arrow disappears. You cannot move entries if they are being sorted.

Ty.  Sry, for posting issue.  Wasn't obviously.
Proposal:  disable menu item only instead of hiding it.

**Comment by droidmonkey** [comment]
Disabling would clutter the menu for folks who prefer sorting and lead to same confusion anyway... why is it disabled?

**Comment by zanzara** [comment]
When it is missing (or hided), then I even wouldn't know that it might exist. 
If it is disabled, then I will think: why is it disabled?!  Could be forced by sorting , by filtering...   
Then I even wouldn't had launched here an "bug" issue (which even wasn't bug in fact)

But I  even have had a look here first https://keepassxc.org/docs/KeePassXC_UserGuide#_keyboard_shortcuts
where I also didn't found the proper shortcut for that functionality.
So in the end, I thought it was by code (which led me do this post here).

Sry, for so much stuff.  But I'm working as a Fullstack-dev, also repsonsible for the UX/UI.
Thx anyway.
