### ISSUE TITLE
Autotype ignores periods

### ISSUE THREAD

**Issue by Gallandaluz** [keepassxreboot/keepassxc#9564]
## Overview
When using Autotype, written username and password do not include the periods.

## Steps to Reproduce
1. Create a new entry, with a period (`.`) in any or both username and password.
2. Execute Autotype from this entry.

## Expected Behavior
The whole username and password are written.

## Actual Behavior
The username and password are written without the periods in them.

## Context
Identified by using Autotype into Firefox (without addon).
Reproduced by using Autotype into Kate (https://apps.kde.org/kate/).
Username or password copied into clipboard through the relevant buttons do include the periods and work as intended.

KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.10
Debugging mode is disabled.

Operating system: EndeavourOS
CPU architecture: x86_64
Kernel: linux 6.1.34-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0

Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
What is your keyboard layout

**Comment by Gallandaluz** [comment]
> What is your keyboard layout

It's an AZERTY keyboard using the French Alternative layout.
```
$ localectl status
System Locale: LANG=fr_FR.UTF-8
    VC Keymap: fr
   X11 Layout: fr
  X11 Variant: oss

```

**Comment by droidmonkey** [comment]
This is either #8966 or #7881

**Comment by Gallandaluz** [comment]
I don't understand the "not planned" comment. I have used Keepassxc for years without having this issue.
The regression may come from a dependency update, since i see it seems to have started without a Keepassxc package update in-between, though i lack the knowledge of the technical process.

Also, out of curiosity, i ran a test typing both manually and through Autotype with `xev -event keyboard` on -- from the behavior, i suspected Autotype works with keyboard events. Despite the layout difference, i notice it does send relevent keys except for the Period, for which it sends the `KP_Delete` key instead:
- [Autotype](https://github.com/keepassxreboot/keepassxc/files/11781738/auto.txt) output
- [Manual](https://github.com/keepassxreboot/keepassxc/files/11781739/manuel.txt) output

**Comment by droidmonkey** [comment]
Not planned is just github being dumb. If this is a dependency issue then there is nothing we could do to fix it.

**Comment by droidmonkey** [comment]
I notice that Auto-Type presses SHIFT_L before trying to type period. Manual typing presses SHIFT_R. I assume that is your dead key or some sort of modifier key for your keyboard map.

**Comment by droidmonkey** [comment]
I notice that Auto-Type presses SHIFT_L before trying to type period. Manual typing presses SHIFT_R. I assume that is your dead key or some sort of modifier key for your keyboard map.

**Comment by Gallandaluz** [comment]
Contrarily to QWERTY, AZERTY requires the Shift modifier to input a Period: <kbd>Shift</kbd>+<kbd>;</kbd>=<kbd>.</kbd>

Manual typing using SHIFT_R instead of SHIFT_L is just me using only my right hand for that key. Typing a Period with the left-hand Shift key works as usual.

**Comment by droidmonkey** [comment]
I'll have to run this through a serious debugging session to understand what is happening

**Comment by droidmonkey** [comment]
I cannot reproduce this at all on Fedora 37 - KDE - with either AZERTY(fr) only or with both AZERTY(fr) and US English as keyboard layouts in any order and with any selection preference.

**Comment by Gallandaluz** [comment]
There's likely a difference in package versions between Fedora and Arch/Endeavour. I'll likely need to keep watch on my end.
___
I kept digging about the dependencies i have updated lately that might be responsible. Though i have yet to find one that might have introduced the regression, i stumbled upon the following code and commentary in **xkeyboard-config** that may explain why a KF_Delete key event is triggered instead of the Period or Semicolon:

     // French uses a comma as decimal separator, but keyboards are labeled with a period
     // Will take effect when KP_Decimal is mapped to the locale decimal separator
     key <KPDL>  { [       KP_Delete,      KP_Decimal,           KP_Delete,           KP_Decimal ] };
> https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/master/symbols/fr#L364

This references the numeric keypad, with is identical in QWERTY and AZERTY, most notably with the separator key which is a Period in both cases. Still, although French keyboards show a Period on that key, the decimal separator in French is not the Period but the Comma.

Coming back to my issue, I tested inputting the Period from both the main keyboard part and from the numeric part:
- from the main keyboard:
```
KeyPress event, serial 25, synthetic NO, window 0x7600001,
    root 0x6cc, subw 0x0, time 198961441, (307,-93), root:(1178,349),
    state 0x10, keycode 62 (keysym 0xffe2, Shift_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x7600001,
    root 0x6cc, subw 0x0, time 198961730, (307,-93), root:(1178,349),
    state 0x11, keycode 59 (keysym 0x2e, period), same_screen YES,
    XLookupString gives 1 bytes: (2e) "."
    XmbLookupString gives 1 bytes: (2e) "."
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x7600001,
    root 0x6cc, subw 0x0, time 198961793, (307,-93), root:(1178,349),
    state 0x11, keycode 59 (keysym 0x2e, period), same_screen YES,
    XLookupString gives 1 bytes: (2e) "."
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x7600001,
    root 0x6cc, subw 0x0, time 198961985, (307,-93), root:(1178,349),
    state 0x11, keycode 62 (keysym 0xffe2, Shift_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

- from the numeric pad:
```
KeyPress event, serial 28, synthetic NO, window 0x7600001,
    root 0x6cc, subw 0x0, time 198963857, (307,-93), root:(1178,349),
    state 0x10, keycode 91 (keysym 0x2e, period), same_screen YES,
    XKeysymToKeycode returns keycode: 59
    XLookupString gives 1 bytes: (2e) "."
    XmbLookupString gives 1 bytes: (2e) "."
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x7600001,
    root 0x6cc, subw 0x0, time 198963921, (307,-93), root:(1178,349),
    state 0x10, keycode 91 (keysym 0x2e, period), same_screen YES,
    XKeysymToKeycode returns keycode: 59
    XLookupString gives 1 bytes: (2e) "."
    XFilterEvent returns: False
```

As you can see, though the keycodes are different, the key names are the same. So this may suggest that the KP_Delete event from the prior test comes from the Autotype using the Period like the KP_Decimal key instead of the key in the main keyboard part.

**Comment by Gallandaluz** [comment]
After some more reading and testing, i managed to fix the issue on my end from KDE's System Settings, by enabling *Keyboard > Advanced > Numeric keypad Delete behavior > Four-level key with abstract separators*.

In the end, it may have started when i jumped distros last month, without me paying attention to the behavior.
Sorry for the burden. Keep on the good work.

**Comment by wismill** [comment]
Does this issue triggers only when NumLock is on? From your `xev` output it looks so (`state 0x10` = `NumLock`, `state 0x11` = `Shift + NumLock`).

If so, when you emits `<LFSH>+<KPDL>`, the active modifiers are `Shift+NumLock`, which maps to the _first_ level of the key (see [`FOUR_LEVEL_KEYPAD` and `FOUR_LEVEL_MIXED_KEYPAD`](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/9e3af2e2204ffadded237ef928d159e86cf8e7ea/symbols/kpdl)), i.e. `KP_Delete`.

I think auto-type should try to use the _lowest_ keycode if multiple ones are available. It would avoid most issues with NumLock, although a better handling of modifiers would fix it for good.

**Comment by Gallandaluz** [comment]
> Does this issue triggers only when NumLock is on?

I don't remember how it acted in a form with NumLock off, but surely not good either. In the Kate file editor, the line was getting erased instead, like with <kbd>Shift</kbd>+<kbd>Del</kbd>.

**Comment by Bischnu** [comment]
Hello,

I have got the same problem which I detailed [here](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/397), thinking it was a problem with xkeyboard-config dependency.
As I have Xfce and not KDE, I can not enable the four-level key with abstract separator option you mentioned.
I do not know if you should re-open the issue or if I should open a new one, as the problem is very similar.

My issue: 
> I have got a problem with KeePassXC autotyping since xkeyboard-config 2.39 update: the dots/periods are sometimes ignored and sometimes typed as “backspaces” when using KeePassXC “auto-type” feature (via a keyboard shortcut, I do not have the browser’s extension installed). I only encountered this issue with oss layout (French alternative). This looks like the same issue as this one on KeePassXC GitHub’s repository, though I am using Artix Linux with Xfce, so I could not try the workaround the person found on KDE.

Operating system and distribution: Artix Linux
Kernel version: 6.3.6
Desktop environment: Xfce (Xfce 4.18)
xkeyboard-config version: 2.39
KeePassXC version: 2.7.5

**Comment by droidmonkey** [comment]
This isn't something we would fix since we are just telling X11 what key to type. We tell it the correct thing, at least as far as we can control.

**Comment by wismill** [comment]
@droidmonkey there is an issue with the handling of the locked modifiers, such as `NumLock`. Please see [my comment](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/397#note_1997411) that explains the issue.

You should:
- Take the lowest keycodes when possible. The alphanum keys have lower keycodes than the keypad ones.
- Check that the key sequence is still valid with the actual active modifiers (in particular the locked ones), before the sequence is pressed.

**Comment by Gallandaluz** [comment]
I didn't have the issue back when i used Xfce until last year, though i don't remember if i had to set anything.
___
Personally, i'd find simpler to use the Period key from the main keyboard part, rather than the numeric pad. But i don't know how it's brought to the app...

**Comment by brouillon** [comment]
Hello,

Same here on a fresh Linux Mint 22 Cinnamon flavor.
I confirm, if NumLock is Off, it works as expected, but NumLock is always On in my workflow :(

> After some more reading and testing, i managed to fix the issue on my end from KDE's System Settings, by enabling _Keyboard > Advanced > Numeric keypad Delete behavior > Four-level key with abstract separators_.
> 
> In the end, it may have started when i jumped distros last month, without me paying attention to the behavior. Sorry for the burden. Keep on the good work.

Equivalent setting in Cinnamon don't fix the issue :(
![Capture d’écran du 2024-08-23 00-09-28](https://github.com/user-attachments/assets/11522d90-d573-4a93-9b05-970eb842f97c)

**Comment by jpggithub** [comment]
See also my explanation on https://github.com/keepassxreboot/keepassxc/issues/9576#issuecomment-2342829205
