### ISSUE TITLE
Search from Root of Folder (Default)

### ISSUE THREAD

**Issue by sanga549** [keepassxreboot/keepassxc#9565]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click any sub-folder under root folder
2. Perform Search Action to find an item in another folder. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The Search bar should default search ALL FOLDERS from the ROOT folder like it does in classic KeePass. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Search is limited to just the sub-folder that happens to be in focus.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I came from KeePass to KeePassXC. I often do multiple searches for records located different folders. Having to re-click the ROOT folder for every search is cumbersome. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.5
Revision: REVISION 9d0537b

[NOTE]: # ( Pick choices based on your environment )

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
N/A
Windowing System: X11/Wayland
N/A

**Comment by droidmonkey** [comment]
Searching the entire database is the default behavior. You must have enabled group bound search at some point. Click the search icon to the left of the search bar to see the menu to disable that.
