### ISSUE TITLE
CSV Group Note Import

### ISSUE THREAD

**Issue by Terminally-Lucky** [keepassxreboot/keepassxc#9567]
Overview:
I would like to request the addition of a new feature in KeePassXC that allows for the import of group notes via CSV. Currently, the CSV import functionality is limited to importing password entries only. This new feature would enable users to automate the import of group notes, which is essential when importing large numbers of passwords that are grouped together.

Context:
The ability to import group notes via CSV is crucial in scenarios where users need to import thousands of passwords organized into various groups. Without this feature, users are required to manually add group notes after the import, which is time-consuming and prone to human error. By automating the import of group notes, users can streamline their workflow and ensure accurate and consistent organization of their password database.

**Comment by droidmonkey** [comment]
This will not be enabled. CSV describes entries only, not groups. You will need to import group notes manually using copy/paste. 

You really shouldn't be using group notes anyway, this is an obscure feature from KeePass original that serves no functional purpose.
