### ISSUE TITLE
Navigation Panel Resizing at shared Folders

### ISSUE THREAD

**Issue by LarsTi** [keepassxreboot/keepassxc#9569]
## Overview
If you export (or Import) a .share file and the path for this file is longer than the space for the filepath, the navigation panel gets resized and is not able to be resized to a bigger value.
![grafik](https://github.com/keepassxreboot/keepassxc/assets/5329497/fac3a187-5f96-484b-abee-812ff556eb29)
![grafik](https://github.com/keepassxreboot/keepassxc/assets/5329497/6a8b293f-15c8-441a-b53c-b58c77c35e63)
![grafik](https://github.com/keepassxreboot/keepassxc/assets/5329497/87ac4728-f785-4cc4-ad63-ec8ba9c794ad)

If you switch to the export folder with long filepath, it resizes to a small navigation panel.
If you switch to the not exported folder, it resizes back to your setting.
If you switch to the export folder with short filepath, it remains correctly sized.

## Steps to Reproduce
1. create a database
2. create a folder to export (long file path)
3. create a folder without export
4. navigate between those two folders

## Expected Behavior
It would be nice, if the width of the navigation panel would stay the same size and the file path is visible as tooltip.
This only seems to be an issue with long file paths.

## Actual Behavior
Keepass resizes the navigation panel, the full path is never readable.

## Context
This happens on switch between exported and not exported folders (i guess it is related to the size of the text-field

KeePassXC - Version 2.7.5
Revision: 9d0537b
Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22621

**Comment by droidmonkey** [comment]
Nice find!
