### ISSUE TITLE
Add menu item for "search"

### ISSUE THREAD

**Issue by szabgab** [keepassxreboot/keepassxc#957]
Running on OSX I don't see a menu item for "Search".
Pressing Command-F jumps to the "Search" box which is good. I think it would be nice to have a menu item with the shortcut to make it easier to learn this shortcut.

```
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
```

**Comment by droidmonkey** [comment]
You have to show the toolbar at this time. There is already an issue addressing this.

**Comment by szabgab** [comment]
Thanks
