### ISSUE TITLE
Windows credential unlock should be mandatory

### ISSUE THREAD

**Issue by gracie95** [keepassxreboot/keepassxc#9572]
I see this option was not mandatory. You can cancel it after entering correct database credentials. IMHO, I think this would be a bit risky if someone got database files and its credentials, then opened them without knowing. At least, with Windows credential unlock, it is still able to prevent from unlocking. If they cancel to input Windows credential, the database should't be unlocked.

**Nota bene: This inspired from KeePassXC.**

**Comment by droidmonkey** [comment]
This offers no protection to the database itself and is not enforceable. We have no idea about the user account on the system. To implicitly trust that the account is somehow associated with the owner of the database is a very poor assumption.
