### ISSUE TITLE
icon "copy password to clipboard" copies wrong data if text selected in notes field

### ISSUE THREAD

**Issue by ShadowProgging** [keepassxreboot/keepassxc#9575]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Clicking the "copy password to clipboard" icon will not copy the password if there is a text
selection in the notes field. the text selection is copied instead of the
password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select text in the notes field with the mouse cursor
2. click icon: 'copy password to clipboard'
3. paste clipboard content in some text editor where you can see it

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
password copied to clipboard

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
the text selection from the notes field is copied to clipboard

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.10
Debugging mode is disabled.

Operating system: EndeavourOS
CPU architecture: x86_64
Kernel: linux 6.3.9-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
We cannot fix this. Unfortunately, because the keyboard shortcut to copy password is the same as copy to clipboard, we cannot distinguish between the two. Since the keyboard shortcut and pressing the actual button are the same trigger behind the scenes, we cannot distinguish it. This is also a duplicate report.
