### ISSUE TITLE
Provide the ability to install KeePassXC without any admin privileges on Windows

### ISSUE THREAD

**Issue by hj-collab** [keepassxreboot/keepassxc#9578]
Hi,

Please make the installer allow user to install KeePassXC with admin privileges or without it. You can check the HeidiSQL installer and how it gives freedom to the user to make the choice. https://www.heidisql.com/download.php?download=installer

**Comment by varjolintu** [comment]
Just use the portable version?

**Comment by hj-collab** [comment]
@varjolintu Have to manually update the installation on every device then.

**Comment by droidmonkey** [comment]
That is the case any way
