### ISSUE TITLE
System Tray Icon is not Visible in Kubuntu 22.04

### ISSUE THREAD

**Issue by ravindragullapalli** [keepassxreboot/keepassxc#9579]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeepassXC system tray icon is not displayed. It is just showing a blank space there.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
System should display the KeepassXC icon

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It shows a blank space

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 
Revision: REVISION

```
KeePassXC - Version 2.7.5
Revision: 6165975
Distribution: Snap

Qt 5.15.8
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 5.15.0-32-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS 

Linux

Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon 

KDE

Windowing System: X11/Wayland 

X11

**Comment by droidmonkey** [comment]
We don't recommend using the snap distribution, switch to flatpak or our ppa.

**Comment by ravindragullapalli** [comment]
I am not able reopen the issue.

I installed it using flatpak, but still there is no icon in system tray

Settings

![image](https://github.com/keepassxreboot/keepassxc/assets/3313079/208c3ea4-cacd-4d42-aa0b-6724c7a8feb4)

System Tray

![image](https://github.com/keepassxreboot/keepassxc/assets/3313079/33a76ef5-92bf-46f3-8f65-468ebcd288e6)

Here is the debug info

KeePassXC - Version 2.7.5
Revision: 9d0537b
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.15.0-32-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

**Comment by ravindragullapalli** [comment]
I had to restart the system. Now it is visible.
Thank you.
![image](https://github.com/keepassxreboot/keepassxc/assets/3313079/18a69583-fc50-4a77-b8e0-cdb00aca0e58)
