### ISSUE TITLE
Retain custom Auto-Type sequence when switched to default

### ISSUE THREAD

**Issue by GitHubinatrix** [keepassxreboot/keepassxc#9580]
Websites are constantly changing which sometimes results with **Auto-Type** sequence not working any more- and rarely becoming not necessary at all. But in order to test this, user must switch to using the default one [or waste time on creating a **Clone Entry** and then deleting it or the original]. But doing so wipes the often painstakingly established **Auto-Type** sequence

Hence I propose **KeePassXC** to stop wiping clear that field and keep it ready for usage once again whenever uses chooses to do so

**Comment by droidmonkey** [comment]
Unfortunately, this is not possible. The way the KDBX format stores the custom auto-type sequence for an entry it is each set or unset. If you want to save a sequence for future use you can either set it as an advanced attribute or create a window association to some random window name and set the sequence there.
