### ISSUE TITLE
AutoType missing after Upgrade to Fedora38

### ISSUE THREAD

**Issue by DSDV** [keepassxreboot/keepassxc#9583]
## Overview
Upgraded KeePassXC while distro upgrade from Fedora37 to 38

## Steps to Reproduce
1.  upgrade KeePassXC

## Expected Behavior
AutoType working / AutoType Tab in Settings

## Actual Behavior
mot working AutoType  / AutoType Tab missing in Settings

## Context
it did not work out of the box in fedora 37 because i found out a dependency was missing. 
So i just installed '`wl-clipboard`' on my systems. (wasnt the first time on manjaro i had to install '`xdotool`')

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing Wayland

**Comment by DSDV** [comment]
I guess it could have some thing to do with: https://github.com/keepassxreboot/keepassxc/issues/2281 
but i think not because it worked before KeePassXC got updated :( 
And my workaround was to install "wl-clipboard"

Also the mentioned MR from the iessue 2281 got denied as far as i can tell (but i am no developer)

**Comment by droidmonkey** [comment]
Auto-Type is not supported on Wayland. You need to run X11. If you choose to keep running Wayland then you will have to run KeePassXC under X11 and any app you want to type into under X11 as well (through XWayland bridge).

**Comment by DSDV** [comment]
Thank you for your answer <3 

But it worked on Fedora37 which was afaik also wayland. 
X11 is deprecated i wont use that. 

But ill look into running Keepass as xwayland tool.
Are you maybe able to elaborate how to do that? 

Also why does kp not support wayland?
Should i think about switching if its not usable anymore on modern systems? Or is it just not yet implemented and support is planed?

**Comment by droidmonkey** [comment]
You definitely were not running pure wayland on Fedora 37 if Auto-Type was available. 

You can read all about this saga in the issue you linked above. Specifically, my comment here: https://github.com/keepassxreboot/keepassxc/issues/2281#issuecomment-922332932

Please search the web for how to run apps on X11 server even though you are using Wayland. I don't see why you would do that though, just use X11 in that case.

**Comment by michaelk83** [comment]
> running Keepass as xwayland tool

The instructions are at https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type . You'll need to install xwayland for that to work, which AFAIK would also install X11. As noted though, your target apps for auto-type will need to run on xwayland (meaning on X11) as well.

**Comment by DSDV** [comment]
@droidmonkey I am sure i ran wayland with fedora 37 because i had to modify firefox to run with xwayland and not wayland so autotype would recognize it. I would never use X11 ... 

sad thing is i ran `$ GDK_BACKEND=x11 keepassxc` and i guess it worked since now keepass is in darkmode again. 
The AutoType Tab in settings and the function itself is still missing. 

So i guess running it with xwayland still does not bring back a missing function :(

**Comment by droidmonkey** [comment]
Xwayland is just the bridge between an X11 server and a wayland compositor. You still need to run all your x11 apps on an x11 server.

**Comment by michaelk83** [comment]
> `GDK_BACKEND=x11` ... still does not bring back a missing function

KeePassXC is not a GDK app (but firefox is). Qt might use some sort of GDK bridge for the rendering, but the rest of the functionality is still Qt. You need the QT setting.

> you must set `QT_QPA_PLATFORM=xcb` or start KeePassXC with the `-platform xcb` command-line flag.

**Comment by DSDV** [comment]
Thank you for your help <3

QT_QPA_PLATFORM=xcb did not work :( 

but -platform xcb did :D 

So i got it working for now. 
My question is now: 

is it planned to add wayland to be usable in the future or do i have to be on a lookout for a keepass alternative?

**Comment by droidmonkey** [comment]
There is no alternative and there are zero products that support auto-type like actions on Wayland. Read the thread I linked above.

**Comment by DSDV** [comment]
ok :( sad to read. 
guess i have to take a look at bitwarden. 
Staying on deprecated software like wayland is no alternative for me. 
Thank you so much for helping to provide a workaround and clarification <3

**Comment by michaelk83** [comment]
Wayland isn't deprecated. But it's lacking some critical functionality for AutoType (at least partly by design). Until that changes, or there is a cross-desktop standard (and deployed support) for the necessary functions at the desktop level, AutoType cannot be (easily?) implemented on Wayland.

**Comment by DSDV** [comment]
no sorry for the confusion. 
X11 is deprecated in my books ;) 

i love wayland. Since things like wayland / pipewire / gnome 40+ etc Linux finaly became a alternative to me <3

Maybe we get lucky and as wayland matures we can use keepass again (: 

anyways i really appreciate your support!

**Comment by michaelk83** [comment]
Perhaps you meant to write **x**wayland in your previous post.

Bitwarden won't give you AutoType on Wayland either. But if you only need to type website credentials, I think the KeePassXC browser extension can fill in credentials without AutoType. (I assume it uses javascript for that.)

**Comment by droidmonkey** [comment]
Correct, the browser extension will work just fine as long as your browser is NOT installed as a flatpak.
