### ISSUE TITLE
macOS KeePassXC - 2.7.5 keep crashing when quit the app

### ISSUE THREAD

**Issue by jakeeri** [keepassxreboot/keepassxc#9586]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC - 2.7.5 keep crashing when quit theapplication

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start the app
2. Close the app

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Normal quit 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Crash occurs when quit the app

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 13.4
Qt 5.15.8
Debugging mode is disabled.

CPU architecture: x86_64
Kernel: darwin 22.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
See the pinned issues...

**Comment by jakeeri** [comment]
Thanks. Didn't see that before. Found IT now. #9423
