### ISSUE TITLE
Make Escape close the window

### ISSUE THREAD

**Issue by elibarzilay** [keepassxreboot/keepassxc#9596]
## Summary

This is a KeePass feature that I really miss: being able to hit Escape to close the window.

Since it does sometime have a function -- like canceling the current search, then it should do this only when there's nothing else to cancel.

## Context

KeePassXC is used as a kind of a system-wide dialog popup, even moreso when it has the ability to minimize itself instead of closing.  For such programs, it is natural to use Escape as a way of dismissing the window.

**Comment by droidmonkey** [comment]
That is an awkward feature, especially since we use ESC in other contexts. We have two shortcuts that hide the window:

 Ctrl + M - Minimize
 Ctrl + Shift + M - Minimize to tray

We won't implement escape to hide the window since it will require a ton of exceptions to make sure it works properly.

**Comment by ebarzilay-godaddy** [comment]
@droidmonkey -- I'm not very familiar with the source (or with QT), but a quick search looks like it won't be too difficult: I'm guessing that the relevant places are those that mention `Key_Escape`, and I see three likely changes in `DialogyWidget.cpp`, `SearchWidget.cpp`, `MainWindow.cpp`, and possibly using some function to query if there is an active `setShortcut` for it.

Would you mind if I try it (which will take a while :) ) or are you sure that the extra code would be unacceptably complicated?

**Comment by droidmonkey** [comment]
Sure you can go for it. I would debate whether this should be a configuration setting or not. Right now pressing escape, I believe, closes the current database. It is also used to cancel opening and cancel quick unlock.
