### ISSUE TITLE
Health check should include a column indicating the length of the password

### ISSUE THREAD

**Issue by restena-sw** [keepassxreboot/keepassxc#9599]
## Summary

Statistics shows a number for the total of "short passwords" (but no possibility to define a policy on what is "short"); but not which passwords are short.
Health check shows individual password entries based on entropy and re-use alerts.

But it is not possible to enumerate individual too-short passwords.

Since the normal view shows a constant number of dots, it is not possible to grasp short passwords in any way. The only way is to open entries one-by-one and look at the stars.

## Context

Our company password policy requires passwords of >=n characters and >=m entropy. It is of course possible to have cases where a password has entropy >=m but length <n which does not conform to policy. 

We have regular controls whether employees' passwords are conforming to the policy; these checks should not reveal the actual password in clear text. Checking minimum entropy is easy by opening Health Check and sort by entropy ascending.

Checking minimum length is much harder, but it wouldn't have to be - if only the length were included in the health check as a separate column.

NB: the MacOS application  "KyPass" does include length and entropy in the reports it generates. But not everybody is a Mac user.

**Comment by droidmonkey** [comment]
You should just look at the "strength" of the password. That is already calculated in the report and a column in the main entry table as well.
