### ISSUE TITLE
View entries as QR codes

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#96]
## Expected Behavior

Based on https://github.com/keepassx/keepassx/pull/187

Add a feature which allows an entry's username and password to be viewed as
QR codes. The QR codes are hidden until a button is clicked, which reveals
them for a limited time, the timeout being settable in the settings dialog.

This is useful for being able to quickly enter long and secure passwords
into mobile devices.

This option can be disabled at compile time.
Also should be good discuss the security of a QR reader on the phone

**Comment by droidmonkey** [comment]
Need to understand the use case. What application reads this qr code on the phone and for what purpose. Seems out of scope to me.

**Comment by TheZ3ro** [comment]
Yep, I was only reporting this from the KeePassX repo for discussing it

**Comment by weatherhead99** [comment]
the idea is simply that I have ~400 entries in a keepassx database, and need to login to a couple of apps on my phone (e.g. twitter, reddit etc). I don't need (or want) a full copy of the database on my phone. But typing in a 40 character password consisting mainly of symbols manually in the phone is a real pain.

This was just something I cooked up when I finally got really frustrated with it.

**Comment by droidmonkey** [comment]
How are you transporting the QR Code information into the login field? Is there some app that accomplishes that on the phone?

**Comment by TheZ3ro** [comment]
I think it's better to have a feature to export the selected entry from the current database instead of this. It's not a secure approach

**Comment by droidmonkey** [comment]
It's an interesting idea, but not currently anything we would want to implement without an end-to-end solution.

**Comment by lbssousa** [comment]
A real use case I have here with original "KeePass + TOTP/QR code plugins" is exposing my TOTP keys in QR code, so I can import them easily to my Google Authenticator app.

**Comment by TheZ3ro** [comment]
@lbssousa that is a different issue. Instead of viewing an entire entry as QR Codes you need to view only the TOTP key as QR Code.

**Comment by vogthenn** [comment]
Referring to @droidmonkey end-to-end solution: Keepass application on Android can create entries from QR Code in a secure way. It really would make sense to revisit this.
