### ISSUE TITLE
Entry not automatically selected after unlock

### ISSUE THREAD

**Issue by dok18** [keepassxreboot/keepassxc#960]
I use Keepassxc with Chromium (chromeIPass/KeePassHTTP) on Xubuntu 17.04 (Xfce). Entry does not get automatically selected after db unlock.

## Expected Behavior
The default entry should be selected and fields should be filled out in the browser.

## Current Behavior
As I already mentioned (https://github.com/keepassxreboot/keepassxc/issues/889#issuecomment-329273917), database window does not popup to unlock the database if Keepassxc is minimized to tray. I "solved" it by not minimizing to tray.

But even if I get asked to unlock the database, the default entry is not selected (nothing is filled out in the browser) after unlock. It works only if the db is already unlocked.

## Debug Info
KeePassXC - Version 2.2.0
Libs:
- Qt 5.9.0
- libgcrypt 1.6.1

OS: Ubuntu 17.04
CPU-Architektur: x86_64
Kernel: linux 4.10.0-19-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Is this when using auto-type or when using the browser plugin?

**Comment by dok18** [comment]
browser plugin.

**Comment by varjolintu** [comment]
This will be fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/104.
