### ISSUE TITLE
Improve KeeShare enabled/disabled UX

### ISSUE THREAD

**Issue by librick** [keepassxreboot/keepassxc#9600]
## Summary
I use KeePassXC; I don't use the KeeShare functionality.
The UX on the KeeShare settings page is confusing. Under the section "Active", I have options to `Allow import` and `Allow export`. Neither of these clearly communicate to me whether KeeShare is enabled or not. They are settings internal to KeeShare. I propose adding a single checkbox to clearly enable/disable KeeShare.

The "Browser Integration" and "SSH Agent" tabs have simple checkboxes that clearly indicate whether they're enabled. The same should be true for the "KeeShare" tab.

The SSH Agent tab clearly indicates whether the agent is enabled:
![Screenshot from 2023-06-30 14-05-28](https://github.com/keepassxreboot/keepassxc/assets/106356608/38763d1d-dd45-4e84-a9f9-4e1302ace0f6)
The Browser Integration tab clearly indicates whether the browser integration is enabled:
![Screenshot from 2023-06-30 14-05-39](https://github.com/keepassxreboot/keepassxc/assets/106356608/4ee805dd-695e-4a88-9133-fe654b92d49f)
The KeeShare tab lacks a similar "Enable KeeShare" checkbox
![Screenshot from 2023-06-30 14-05-15](https://github.com/keepassxreboot/keepassxc/assets/106356608/404bf0a6-af33-4f57-a37e-a9dd53b4c710)

## Proposed Change
I propose adding a new checkbox at the top of the KeeShare settings page with the string "Enable KeeShare" or "Enable KeeShare integration". When this is checkbox is unchecked, the `Allow import` and `Allow export` checkboxes should be disabled. This would more clearly communicate whether KeeShare is enabled without requiring any knowledge of what KeeShare does. Users shouldn't have to know what `Allow import` and `Allow export` means to know if KeeShare is enabled.

## Version
KeePassXC 2.7.4
Debian 12

**Comment by droidmonkey** [comment]
KeeShare is slated to be entirely recoded and this settings page will be entirely removed.
