### ISSUE TITLE
When there are many entries being dragged, the view is too much obstructed.

### ISSUE THREAD

**Issue by feelingnothing** [keepassxreboot/keepassxc#9602]
## Summary
Avoid rendering entries dragging, because it obstructs the view.

#### What to decide:
* Is there a need for dragging an entire entry at all? From the accent color of the selected items and some information along the side of the cursor It is clear WHAT you are dragging WHERE and HOW MANY. WHERE part in the current solution is not that clear.
* If there is need to drag an entry, at what count and what information should be displayed by the cursor? For me the most viable option is the count of them in the selection.

## Context
This is only a half of the window size. And I already block 90% of the groups' viewport.
![screenshot](https://github.com/keepassxreboot/keepassxc/assets/47575622/81ed8bd5-cb9d-4347-81e3-95150fe26591)
##### not a real *real* screenshot, I photoshopped it to provide a clue to what I'm trying to say. Looks 100% the same. It's just that you can't screenshot a part of your cursor (and if you can, I already did it like this)

**Comment by droidmonkey** [comment]
This is a duplicate report. Frankly this is a Qt problem (we think) since the rendering of the dragged items is handled by Qt. 

#6079
