### ISSUE TITLE
MainWindow flashes white prior to being rendered on start

### ISSUE THREAD

**Issue by Dark-Magician** [keepassxreboot/keepassxc#9603]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When KeePassXC is launched, it displays a white background while the GUI is painted, resulting in an [eye-straining white flash](https://e.pcloud.link/publink/show?code=kZ32nfZW2uD2bn0aYJ3JAeNMaloH5mnnVfV).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
There are no particular steps involved besides launching the program.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
There should be no flashes.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC flashes a bright white, blank page.

## Context
[NOTE]: # ( Give us any additional information you may have. )

New installation at default settings.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5 and 2.8.0
Revision: 9d0537b and a5c1298

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 22H2

**Comment by droidmonkey** [comment]
I just tried 4 ways to prevent this and they all produced the same result. I believe this is a Qt problem at this time.

Interestingly, if I set Windows in High Contrast mode then the background "flash" is black/dark.

**Comment by Dark-Magician** [comment]
_Closing the issue was an erroneous click on my part. Please ignore that._

In my experience, turning on Windows High Contrast mode seems to have made the flash more tolerable—quicker and a light-medium gray—but did not resolve it. This commit fixed the same problem in Shotcut:

https://github.com/mltframework/shotcut/commit/a72b757c72ef085bfecebb7e379d1dd05a0667f9

**Comment by droidmonkey** [comment]
Ah interesting hack, I didn't try messing with the opacity. I did try the delay timer though.
