### ISSUE TITLE
Drag and drop entries from one database to another does not work in Ubuntu 23.04

### ISSUE THREAD

**Issue by rcpao** [keepassxreboot/keepassxc#9604]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Ubuntu 23.04 with KeePassXC (either from PPA or snap, both fail)
2. Open/unlock two databases.
3. Highlight two entries from one database and drag it to the tab of the second database.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
In Ubuntu 22.04, the two entries over the tab of the second database would cause it to focus and you could drop your entries into any group.  If you pressed Ctrl before dropping/releasing the mouse button, you could copy instead of move the entries.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
In Ubuntu 23.04, hovering the entries over the tab of the second database does nothing.

## Context
[NOTE]: # ( Give us any additional information you may have. )
none

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

echo $XDG_SESSION_TYPE
x11

**Comment by droidmonkey** [comment]
This Is a duplicate. We have determined this is actually a bug in Gnome 44 and by extension all Qt apps are affected.
