### ISSUE TITLE
KeepassXC version 2.4.3 github login OK. KeepassXC version 2.6.6 gihub login not ok

### ISSUE THREAD

**Issue by pgmer6809** [keepassxreboot/keepassxc#9605]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Using KeepassXC 2.4.3 to login to my github account using firefox works fine. I can either use the Keypass autofill (with FFOX extension) or I can cut and paste from the Keypass entry password filed.
With version 2.6.6 neither of these approaches works.
FFox shows the green Keypass icon, and it autofills the field but the login fails. Also cutting and pasting from the keypass entry (even before the clipboard is cleared) also fails.

This problem occurs on only ONE of my two github accounts; the one with the superlong, github generated, password.(40 chars). For the account which has only a normal 14 char password works OK using either method.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. ask github to create a 'PFA' ? i.e. a 40 char password.
2. enter that password into the KeypassXC data base.
3. use the cut and paste feature of KeypassXC to try to login.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Login should succeed.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Error message from github, Incorrect username or password

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am not sure this is reproducible or if it is just my particular setup. It may be related to the version of Firefox I am using. But I have the same issue cutting and pasting into Chromium as well.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Debugging mode is disabled.

Operating system: Linux Mint 21.1
CPU architecture: x86_64
Kernel: linux 5.15.0-76-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint (Ubuntu 22.04 Jammy)
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
We are on version 2.7.5. Use the flatpak or ppa to update. This is most likely not our program if even cut/paste doesn't work.

**Comment by droidmonkey** [comment]
> This problem occurs on only ONE of my two github accounts

This points to you having the wrong password in your database.
