### ISSUE TITLE
KeepassXC doesn't follow system theme

### ISSUE THREAD

**Issue by laundromad** [keepassxreboot/keepassxc#9608]
## Overview
I've set the system theme as "adwaita-dark" using the qt5ct utility, so that Qt applications could blend with GTK ones. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download qt5-wayland and qt5ct
2. Set environment variable in .bashrc QT_QPA_PLATFORMTHEME=qt5ct, then source .bashrc
3. Launch qt5ct and set theme as "adwaita-dark" via UI
4. Launch keepassxc

## Expected Behavior
KeepassXC with dark background.

## Actual Behavior
KeepassXC with light background. However, only sometimes I managed to make it dark by setting environment variable QT_STYLE_OVERRIDE=adwaita-dark. This however is not the proper way to configure, as qt5ct tells you at launch if you do that. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC v2.7.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Display Server: Wayland
Window Manager: Sway

**Comment by droidmonkey** [comment]
You need to set the theme to "classic" in the view menu of KeePassXC to use the system theme.
