### ISSUE TITLE
With some entries the Autotype changes '^' for '&'

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#9613]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use auto-type as it comes by default {USERNAME}{TAB}{PASSWORD}{ENTER}

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Autotype the '^' no matter the entry or the auto-type mode.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
With some entries, when I auto-type the password, it changes the '^' for '&'. By example, one password contains "Ob^NH" but when I auto-type it writes "Ob&NH". But also an strange thing is that this doesn't happen with all the entries, because another one got "LN^*" and it works fine.

It seems to happen only when I auto-type the username and password, because when I only auto-type like {PASSWORD}, it works fine for all the entries.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I'm using Ubuntu 23.04, and already tried the auto-type with several apps (like Firefox and the gnome-text-editor), and the bug keeps the same.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 23.04
Desktop Env: Gnome 44.2

Thanks for your answers.

**Comment by droidmonkey** [comment]
What keyboard layout are you using?

**Comment by ghost** [comment]
Spanish. Where the '^' is at the right of the letter 'P' and under the '?' key.

**Comment by droidmonkey** [comment]
Does it require hitting a dead key to type?

**Comment by ghost** [comment]
If I only want to type '^' I have to keep SHIFT and then press two times the '^' key, or also works if I keep SHIFT as I press '^' and then press SPACE.

If this information helps, also if I press SHIFT +  '^' and then another key, it can give different results. For example, if I keep SHIFT as I press '^' and then '¡' it writes: ^¡ or if I keep SHIFT as I press '^' and later press 'e' it writes an special character ê.

**Comment by droidmonkey** [comment]
You are experiencing #7881.

**Comment by ghost** [comment]
Oh, okay, I'll take a look. Thank you very much. c:

**Comment by lyallp** [comment]
I found that when I used VirtualBox hosted on Linux, running Windows as a guest, that keepassxc within the windows guest sending autotype strings to a remote host in Azure, the SHIFT 5 times Sticky settings in the windows guest was getting in the way. 
Turning off anything to do with SHIFT multiple times seemed to fix the problem.
