### ISSUE TITLE
Chrome is not detected in browser integration

### ISSUE THREAD

**Issue by shenghsi** [keepassxreboot/keepassxc#9614]
## Expected Behavior

There should be a checkbox for chrome in browser integration.

## Current Behavior

No chrome checkbox

## Steps to Reproduce (for bugs)

1. Install chrome and keepassxc
2. open keepassxc and go to settings -> browser integration

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: 22.04.1-Ubuntu
Browser: Chrome Version 114.0.5735.198 (Official Build) (64-bit)

**Comment by varjolintu** [comment]
Can you show a screenshot? What does the About -> Debug Info window looks like?

**Comment by shenghsi** [comment]
The one installed from ubuntu software doesn't work.

But this version works:
[Ubuntu PPA](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc)

**Comment by shenghsi** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/3663436/52b7b313-ed5b-4e97-9397-05dd6eda90bd)

**Comment by varjolintu** [comment]
The page clearly says that if you are running KeePassXC as a Snap, you'll need to run a separate script to enable browser integration because of the sandboxing.
You can download the script from here: https://raw.githubusercontent.com/keepassxreboot/keepassxc/latest/utils/keepassxc-snap-helper.sh

**Comment by shenghsi** [comment]
The Ubuntu PPA version works.
But the message should be something like 
"The current version doesn't support browsers installed as snaps. Install the PPA version instead from [Ubuntu PPA](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc)"

**Comment by varjolintu** [comment]
"Browsers installed as Snaps" is a different thing from KeePassXC installed as a Snap.

**Comment by shenghsi** [comment]
The message is confusing because I don't find a script on that page that can make the snap keepasxc version work.

**Comment by varjolintu** [comment]
The script is linked here: https://keepassxc.org/download/#linux and the link in KeePassXC goes to that URL.
And I already provided you a direct link for it.
