### ISSUE TITLE
Portion of Password gets Repeated when using AutoType

### ISSUE THREAD

**Issue by Linkinwater** [keepassxreboot/keepassxc#9615]
## Overview
A portion of my password gets typed in twice when I use AutoType (but not clicking the button).

## Steps to Reproduce
1.  Navigate to desired webpage
2.  Click into the password box
3.  Press the AutoType hotkey

## Expected Behavior
The password to be entered as it appears in KeePassXC.

## Actual Behavior
A portion of the password gets typed in twice.
This issue is 100% repeatable for this website, but not on other websites (so far, at least)
This issue ONLY happens if I use the keyboard AutoType hotkey. If I click the KeePassXC button on the webpage, it enters the password correctly.

## Context
I'm pasting the actual output for clarity (don't freak out - this is only part of the password, you have no idea what website it's for, and I'm changing it right now anyway).
Actual ending of password: ... SE#2m4DWYn-9-@3
What KeePassXC types:        ... SE#2m4DWYn-9-@3m4DWYn-9-@3
As you can see, the characters after the "#2" get repeated. But strangely, if I change the password to use "#3" instead of "#2", here's what happens:
Actual ending of password: ... SE#3m4DWYn-9-@3
What KeePassXC types:        ... SE#3m4DWYn-9-@3WYn-9-@3

Whereas using a "#2" repeats everything after it, a "#3" skips 3 characters before repeating.    

So my guess is that somehow the hash character has something to do with causing it to flake out?

I can confirm that after changing my password and disallowing hashes, it works just fine. Possibly just a coincidence, too, I suppose.

[NOTE]:
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]:
Operating System: Windows 10

**Comment by droidmonkey** [comment]
The website is screwing you, probably some dumb javascript validation thing they have implemented. You'll have to increase your typing delay for this website. Use `{DELAY=500}` at the beginning of the Auto-Type sequence for this entry.
