### ISSUE TITLE
KeepassXC crashes when I open old keepassx database or try to open new one

### ISSUE THREAD

**Issue by beeswaxbear** [keepassxreboot/keepassxc#9617]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )When I try to open an old keepassX database or try to create a new database KeepassXC crashes.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Try to open an old keepassX database or create a new one on an acer aspire one laptop.
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )After I type in the password for an old database the program crashes. Also when I try to create a new KeepassXC database the program crashes.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Running Debian 12 Bookworm on Acer Aspire One Laptop.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION: 
Revision: REVISION:KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
CPU architecture: i386
Kernel: linux 6.1.0-10-686-pae

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Try running flatpak or snap distribution. Without a crash log we cannot do anything. Certainly the application doesn't crash for anyone else in this situation.

**Comment by beeswaxbear** [comment]
I downloaded and installed the snap version and that one seems to work ok. Thanks for the tip.
