### ISSUE TITLE
Something crazy is happening

### ISSUE THREAD

**Issue by HiBoU974** [keepassxreboot/keepassxc#9618]
Hello,

I have used my database for 6 or 7 years until yesterday.

I can't open it and i know the password.

There is no key file.

I have 3 PCs.

I have many backup based on duplicity on different cloud and i have restored these backup on many PCs/Fresh install and it was working great.

I have 2 linux system on 2 externals hard drives that were offline for months with the database in it.

I have tried on Linux, Windows and live USB Linux, KeepassXC and Keepass (different version).

I have tried with another keyboard.

I managed to open once the database on a PC that i haven't use for some times right after the boot but like an idiot i have closed the database to re test the opening and it was over...

I can't open any of my iteration of the database on any PC from any hard drive.

I see 2 possibilities:

1. I'm mad and i think i know my password
2. There is a kind of expiry date on my database

Any help appreciated :)

![Capture d’écran du 2023-07-09 17-52-37](https://github.com/keepassxreboot/keepassxc/assets/29167639/92df9b94-cef9-4e27-8522-78e274b9f8db)

KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.10
Debugging mode is disabled.

Operating system: Fedora Linux 38 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.3.11-200.fc38.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Only option 1 is possible, you have forgotten or are systematically mistyping your password. Take it slow. Once you do it right change your password to something else.

**Comment by droidmonkey** [comment]
Only option 1 is possible, you have forgotten or are systematically mistyping your password. Take it slow. Once you do it right change your password to something else.

**Comment by JohnLGalt** [comment]
Also verify it in a notes app first - it could be some sort of keymapping error for your keyboard.

**Comment by HiBoU974** [comment]
Thanks for your replies guys.

If i reveal the password in KeepassXC it's the good one.

If i copy/paste the password from a note app it's the same, i can't open the database.

It's crazy what happen... I'm not "the guy who mistype his password" everyday. I have a very very very low "bad pwd count"

**Comment by droidmonkey** [comment]
If you cannot open "cold backups" that have the same password then the only explanation is that the password is wrong. There is no such thing as a database expiring.

**Comment by HiBoU974** [comment]
Hello,

My brain was hacked by me :/

I have convince myself that the actual password was an old partial variant...

Human brain is tricky. Don't trust your brain.

Thanks all and long life to KeepassXC :)
