### ISSUE TITLE
"Remember last databases" setting not working

### ISSUE THREAD

**Issue by jsha** [keepassxreboot/keepassxc#962]
I can't figure out a way to clear the list of previously opened databases. There seems to be a setting for this, but as far as I can tell it doesn't work retroactively.

## Expected Behavior
1. Create a database and save it.
2. Close & reopen KeePassXC.
3. Note that the database shows up in the "Recent databases" list.
4. Go to Settings and uncheck "Remember last databases" and "Load previous databases on startup".
5. Close & reopen KeePassXC.
6. See an empty "Recent databases" list.

## Current Behavior
6. "Recent databases" list still contains list of recent databases, even after disabling those settings.

As a side note, I'm not sure why there are two settings for this behavior. Perhaps I'm misunderstanding one of them? If not, it seems like there should be a single checkbox that controls the behavior of both storing the list of recent databases, and loading the list on startup. And unchecking that checkbox should clear whatever internal storage is present.

It might also be nice to have a right-click delete option to delete a single database from the saved list.

## Context
This affected me because I was trying to produce screenshots of a "clean" KeePassXC install. However, I can imagine real users wanting to clear their list of databases for privacy reasons, especially on a shared computer.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.10240

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment]
Those are two "unrelated" options.
*"Remember last databases"* -> enable the recent list in the Welcome page
*"Load previous databases on startup"* -> remembers the database that were loaded when you last closed KeePassXC and reload them again on next startup

The problem here is that the first option (*"Remember last databases"*) delete the recent-list but the Welcome page doesn't update.

The easier way to clear the recent-list:
![istantanea_2017-09-19_13-03-44](https://user-images.githubusercontent.com/686894/30589568-3cd7dfa4-9d3b-11e7-9d6e-fdf96116b5a8.png)

**Comment by droidmonkey** [comment]
I did notice that there is no mechanism for most of these storage settings to clear the existing list when they are disabled. I believe this to be a bug (perhaps security related)

**Comment by jsha** [comment]
Ah, I think part of the problem is that "load previous databases on
startup" should say "database" (singular).

On Sep 19, 2017 4:13 AM, "TheZ3ro" <notifications@github.com> wrote:

Those are two "unrelated" options.
*"Remember last databases"* -> enable the recent list in the Welcome page
*"Load previous databases on startup"* -> remembers the database that were
loaded when you last closed KeePassXC and reload them again on next startup

The problem here is that the first option (*"Remember last databases"*)
delete the recent-list but the Welcome page doesn't update.

The easier way to clear the recent-list:
[image: istantanea_2017-09-19_13-03-44]
<https://user-images.githubusercontent.com/686894/30589568-3cd7dfa4-9d3b-11e7-9d6e-fdf96116b5a8.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keepassxreboot/keepassxc/issues/962#issuecomment-330507359>,
or mute the thread

**Comment by TheZ3ro** [comment]
@jsha but what if I have multiple database opened at once?

**Comment by jsha** [comment]
Ah, I didn't realize KeePassXC could have multiple databases opened at once. Maybe "Re-open previously open databases at startup"?

**Comment by droidmonkey** [comment]
Closing this in favor of a different issue that better describes the problem... there is a wording and ordering issue in the settings that makes this confusing.
