### ISSUE TITLE
Question about the invocation of keepassxc-proxy

### ISSUE THREAD

**Issue by kmille** [keepassxreboot/keepassxc#9621]
Hey,
I have a question. I'm using Firejail sandbox. I want to update the rules for the proxy tool. To use it, `/usr/local/bin/keepassxc-proxy` needs to be started instead of `/usr/bin/keeassxc-proxy`. I changed the `path` value in `org.keepassxc.keepassxc_browser.json` but still `/usr/bin/keepassxc-browser` gets executed by Firefox. 

```json
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/local/bin/keepassxc-proxy",
    "type": "stdio"
}
```
``` bash
kmille@linbox:native-messaging-hosts ls -l /usr/local/bin/keepassxc-proxy 
lrwxrwxrwx 1 root root 17 Jul 10 10:23 /usr/local/bin/keepassxc-proxy -> /usr/bin/firejail

kmille@linbox:projects ps aux | grep /bin/keepassxc-proxy | grep -v grep
kmille     96957  0.0  0.1 155108 19352 ?        SLl  10:28   0:00 /usr/bin/keepassxc-proxy /home/kmille/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
```

Do you have an idea why? If I set path to gargabe, nothing/garbage gets executed (so it uses this config file). Also [the docs](https://developer.chrome.com/docs/extensions/mv3/nativeMessaging/) say that a full path is required. Same problem for Chromium

**Comment by droidmonkey** [comment]
Since you symlink the local/bin proxy to firejail, doesn't firejail start the real proxy to make things work? I'm confused.

**Comment by kmille** [comment]
The symlink needed. It's basically how firejail sandbox work. If I run Keepass (either from .desktop file or console), I run /usr/local/bin/keepassxc. Then firejail starts a sandboxed KeepassXC

```bash
kmille    109818  0.2  0.0   4500  2620 ?        S    12:04   0:00 /usr/bin/firejail /usr/bin/keepassxc
kmille    109819  0.0  0.0 229112  5268 ?        Sl   12:04   0:00  \_ /usr/bin/xdg-dbus-proxy --fd=4 --args=5
kmille    109822  0.2  0.0   4520  2164 ?        S    12:04   0:00  \_ /usr/bin/firejail /usr/bin/keepassxc
kmille    109839  1.6  0.7 759136 120504 ?       SLl  12:04   0:00      \_ /usr/bin/keepassxc
```

I just wonder why the browser executes /usr/bin/keepassxc-proxy instead of /usr/local/bin/keepassxc-proxy...

**Comment by droidmonkey** [comment]
Based on the information you provided I am not convinced it isn't starting the local symlink. Do the same heirarchy printout for the proxy. Either way, we don't control this part of the equation, the browser is doing all the work starting and owning the proxy.

You really should just wrap Firefox itself with firejail and not the sub proxy process that Firefox starts.
