### ISSUE TITLE
Can't open attachment since 2.7.4 Linux

### ISSUE THREAD

**Issue by alsd** [keepassxreboot/keepassxc#9623]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Advanced > Attachments

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
In previous versions, either clicking "open" or on the attachment without saving will open up the file.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Since v2.7.4 and v2.7.5, the only way to see the file is to save it. The "open" button is not working.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v2.7.4 and v2.7.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux

**Comment by droidmonkey** [comment]
Switch to snap or flatpak, the appimage is broken due to various circumstances.
