### ISSUE TITLE
Attachments - temp storage not overwritten - cannot "import" edits

### ISSUE THREAD

**Issue by ravogel65** [keepassxreboot/keepassxc#9627]
## Overview
All quoted text is from the KeePassXC: User Guide Attachments section, the KeePassXC Attachments UI or the "default application associated with the file type" of the file being attached to the database entry.

I cannot attach a source file "name" to a database entry, edit the entry "name" without having the source file affected and have the /tmp file used in this process securely overwritten.

## Steps to Reproduce
1. Attach file "name" to a database entry.
2. "Open" it.
3. Within the "default application associated with the file type," edit and save  the file.
4. "Open" the attached entry "name" and find it has not been edited.
5. Within Debian examine the /tmp file used during this process and find it has not been securely overwritten but includes the edits.

## Expected Behavior
I expect to attach file "name" to an entry, open it, edit it, save it, find that the attached entry "name" has been edited, and have the /tmp files used for this process securely overwritten. I expect to have all of this happen within the UI of KeePassXC, except for the editing and saving done within the "default application associated with the file type." I understand that my expectation may be difficult to satisfy without an additional button in the Attachments UI. The action of the additional button could be to import the edited file into the attached entry "name" and optionally overwrite the /tmp files used in this process.

## Actual Behavior
I can attach a cleartext file "name" to a database entry. When file is opened within KeePassXC, using the "default application associated with the file type," it is stored as cleartext in the /tmp directory with a 6-character prefix to the file name (the "pname"). When the edited file is "save"d, the file is saved to /tmp file pname as cleartext. Upon closing the file editor, control is returned to Attachments UI of KeePassXC. The attached entry "name" does not reflect the edits, and I can't find a way, within KeePassXC, to import the edited file to the attached entry "name." The temporary file pname in /tmp has not been securely deleted by overwriting it, nor has the /tmp file created when the attached entry "name" is opened to verify the edits. I would need to use the Gnome shred utility to do so.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System:Linux
Desktop Env: Gnome
Windowing System:
Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.10.0-23-amd64

**Comment by droidmonkey** [comment]
You need to update to 2.7.5
