### ISSUE TITLE
Undergoing -but left- editing keeps the database open, over the inactivity timeout (dataloss-prevention vs secourity conflict) [undecided category]

### ISSUE THREAD

**Issue by ledgeri** [keepassxreboot/keepassxc#9629]
Many times when i edit my database, i need to leave the program to gather info what i want to save. I already filled some info, but not yet saved the update. Sometimes, either because i am disctracted, or the info coming slower than expected, i forget i have my database open, and when i come back, after 2-4 times the inactivity-timeout, i see the database is still open, and asks me to discard the changes, or cancel the closing process.
It is clear to me what are the consequences of each end of the spectrum (currently): Closing forcibly> dataloss, keeping open> potential unvanted access...

Could something like an upgraded history, or sound notification, or a temporal(but saved-into-file)-history implemented so i can keep my database safe, yet not loosing my active edits, what solves this confilct? E.g. when i open the database or enty, i get a warning about state-conflict, or a split screen with the last normally-, and the new temporal state, so i have to chose one, or continue the edit.

[kinda bug, because it is in confilct with its own setting, and reasoning (inactivity time-out), kinda feature request, because a new kind of implemention would be good]

**Comment by droidmonkey** [comment]
Please see #721

**Comment by ledgeri** [comment]
K thanks! (sorry for dupl)
