### ISSUE TITLE
Check for updates functionality

### ISSUE THREAD

**Issue by jsha** [keepassxreboot/keepassxc#963]
As far as I can tell, appears that the Windows version of KeePassXC does not have a way to check for updates or keep itself updated. Is that accurate? If so, I'd recommend providing some sort of update mechanism (perhaps provided by the OS, if applicable).

**Comment by droidmonkey** [comment]
+1 also requested by the Complete Privacy and Security podcast guys.

**Comment by TheZ3ro** [comment]
Note: This will not be available if you compile with XC_HTTP disabled (enabled by default)

**Comment by weslly** [comment]
Duplicate of #694
