### ISSUE TITLE
Low priority idea: e.g. "Obsidian's canvas" like relation map for entries, folders, tags

### ISSUE THREAD

**Issue by ledgeri** [keepassxreboot/keepassxc#9630]
I know this is way off the core usecase, but would be a nice addition

I would like to have and use a dyinamic flowchart/graphical ui, to overview my entries, visually similar like this picture: https://obsidian.md/images/canvas/demo-help-vault.png
Would be helpfull to see relations like what email-provider's what alias is used to how many and what saved accounts/entires, and in case one step fails, what are the affected entries. I know there are caregories, and tags, but this is also could be usefull (for some at least).
I would not like to have much depth for the graphical part, just dinamic arrows, and some colors, maybe minimal relation.

And the main reasoning: it would stay inside the password manager.  Also maybe A first in PW managers.

(Again: i know this is unnececary, and dev-expensive... but a happy user can dream a bit)

**Comment by droidmonkey** [comment]
I'm sorry but we would not spend time implementing something like that. We offer database reports and an extensive search feature that you can use to find various issues and relations between entries.
