### ISSUE TITLE
TOTP stopped working

### ISSUE THREAD

**Issue by jneidel** [keepassxreboot/keepassxc#9645]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Keepass is no longer generating valid TOTP codes for some websites.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

TOTP to generate valid codes.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Generates invalid codes.

## Context
[NOTE]: # ( Give us any additional information you may have. )

This happend for a few websites (Heroku, Namecheap, npm). When I registered not too long ago the setup was fine. Now the codes are not being accepted anymore.

Plugging the otpauth:// url into [FreeOTP+](https://github.com/helloworld1/freeotpplus) works fine for npm.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: i3
Windowing System: X11

**Comment by varjolintu** [comment]
Your computer's time is probably not correctly set.

**Comment by jneidel** [comment]
Yeah, my computers time is 2min off. That should be it. Thanks
