### ISSUE TITLE
Auto-Type should have ready to pick Actions References and Entry Placeholders References

### ISSUE THREAD

**Issue by GitHubinatrix** [keepassxreboot/keepassxc#9646]
Currently in **Auto-Type** there is only that ``?`` icon which is a link to https://keepassxc.org/docs/KeePassXC_UserGuide#_configure_auto_type_sequences

I propose adding two drop down lists with ready to use [i.e. for pasting in by picking them] items, one from the _Auto-Type Actions Reference_ section of that help page and the other from _Entry Placeholders Reference_

For comparison: **Mp3tag** under its ``▶`` icon on the right edge of its **Filter** feature gives user to access  list with names of tag fields [both user made-up and "legit" ones], thus saving them time on checking things

**Comment by droidmonkey** [comment]
#8276
