### ISSUE TITLE
Add option for browser integration to not use passwords for HTTP Basic Auth by default

### ISSUE THREAD

**Issue by Romich777** [keepassxreboot/keepassxc#9649]
## Summary
Add option for browser integration to not use passwords for HTTP Basic Auth by default

## Examples
A lot of subdomains (as it possible to add wildcard password), few passwords per site (basic auth, front user, backend user etc.)
In such cases, you have to find basic-auth-only password among other passwords

## Context
In dev/stage and some production areas, basic auth used to hide site from indexing/visitors

**Comment by droidmonkey** [comment]
We have this feature already. Go to the browser tab when editing an entry. To exclude groups of entries, go to the browser tab when editing said group.

**Comment by Romich777** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/14110152/4583eb10-bf3d-4c5a-9be1-3f297e17d32a)
Per entry, it is possible to hide the entry from browser extension, use it for basic auth only, hide from basic auth.
But by default all entries passed to browser extension for basic auth.
Proposal to add global option to send to browser extension for basic auth only items with `Use this entry only with HTTP Basic auth`

**Comment by droidmonkey** [comment]
Set it on the root group.
