### ISSUE TITLE
Defective .desktop file

### ISSUE THREAD

**Issue by alexknop** [keepassxreboot/keepassxc#9651]
## Overview
.desktop file inside of the 2.7.5 AppImage is defective.

## Steps to Reproduce
1. Extract AppImage (./Keepass.AppImage --appimage-extract)
2. Check if .desktop file is valid (desktop-file-validate ./squashfs-root/org.keepassxc.KeePassXC.desktop)
3. Observe Errors with .desktop file.

## Expected Behavior
Valid .desktop file.

## Actual Behavior
./squashfs-root/org.keepassxc.KeePassXC.desktop: error: value "1.5" for key "Version" in group "Desktop Entry" is not a known version
./squashfs-root/org.keepassxc.KeePassXC.desktop: hint: value item "Security" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: Settings, or System
./squashfs-root/org.keepassxc.KeePassXC.desktop: error: file contains key "SingleMainWindow" in group "Desktop Entry", but keys extending the format should start with "X-"

## Context
Refer to this https://specifications.freedesktop.org/menu-spec/latest/apa.html

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
CPU architecture: x86_64
Kernel: linux 6.1.0-10-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This has more to do with the version of your desktop file scanner than the desktop file. Note your scanner is unaware of version 1.5. There isn't a problem here. 

https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/issues/59
