### ISSUE TITLE
blur Notes field in General tab

### ISSUE THREAD

**Issue by shtalinberg** [keepassxreboot/keepassxc#9653]
## Summary
It would be good if there was an opportunity when viewing (clicking on the record) the record to optionally blur the text information that we add to the record with a login and password - Notes field in General tab. 
## Examples
![Screenshot 2023-07-20 at 12 12 05](https://github.com/keepassxreboot/keepassxc/assets/7803600/077dce28-a357-42a0-ac8f-b9387647c013)
## Context
Sometimes it can be some short instruction with sensitive information as well

It might also be worth adding some sort of separate safe field for text type data like RSA PRIVATE KEY ?

**Comment by droidmonkey** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/9fc3c116-c73b-4494-8ddc-60bcf030110a)

You can put data in advanced attributes as well.
