### ISSUE TITLE
Autotype only fills the login field on the iDrac HTTPS page

### ISSUE THREAD

**Issue by sebma** [keepassxreboot/keepassxc#9655]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Define the Autotype sequence as "{USERNAME}{TAB}{PASSWORD}{ENTER}" in the KeePassXC entry
2. Click OK
3. Go to the iDrac URL
4. In the "KeePassXC - Browser Access Request" window : tick "Remember" and click "Allow Selected" button
5. Then, in the iDrac tab of firefox, click on the KeePassXC icon next to the login field 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The login and password fields get automatically filled.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The login field in the browser window gets filled automatically but nothing happens for the password field.
But double clicking on the login field and the pressing TAB fills up the password field.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Browser: Firefox 102.13.0esr (64-bit)

**Comment by droidmonkey** [comment]
Auto-Type is a completely separate feature then the browser extension of browser integration. Go to the browser tab when editing an entry to set the HTTP basic auth settings.

**Comment by sebma** [comment]
@droidmonkey Where do I `set the HTTP basic auth settings.` ?

Are these defined in the KeePassXC browser add-on options ?

**Comment by droidmonkey** [comment]
Go to the browser tab when editing an entry in KeePassXC to set the HTTP basic auth settings.
