### ISSUE TITLE
Multi-part passphrase generation

### ISSUE THREAD

**Issue by aperturekubi** [keepassxreboot/keepassxc#9656]
## Summary
In some instances, a more "user friendly" password is required, such as firmware passwords.
Instead of X random words of random size, let us be able to combine different elements of different wordlists.

## Examples
Generator can take X words from one wordlist (of long words), Y words from another (of short words), and Z standard password RNG-ed characters, and randomly combine those elements into a string.
e.g. selected "Generator" from X, "Some" "Such" "Way" from Y, and "112233" Z. Then assembled them into: 112233SomeWayGeneratorSuch

## Context
For Firmware and other low level instances where a somewhat memorable password by users/technicians is needed where KeepassXC cannot run.
This also somewhat matches a method used by Charter for default wifi passwords; two short words and 3 random numbers. Other ISPs or Vendors may do the same, but I haven't seen it.

**Comment by droidmonkey** [comment]
Use the passphrase generator already in KeePassXC. You can provide your own word lists if you prefer.
