### ISSUE TITLE
macOS: Not possible to use auto-type, requesting permissions that are active already

### ISSUE THREAD

**Issue by foss-** [keepassxreboot/keepassxc#9657]
## Overview
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 9d72d8d
macOS 13.4.1 (c)

## Steps to Reproduce
1. open TextEdit
2. press keyboard shortcut for auto-type

## Expected Behavior
Open KeePass auto-type interface.

## Actual Behavior
info message shows: KeePassXC requires the Accessibility and Screen Recorder permission in order to perform global Auto-Type. Screen Recording is necessary to use the window title to find entries. If you already granted permission, you may have to restart KeePassXC.
Besides that KeePassXC dialog macOS Dialog shows: Accessibility Access: "KeePassXC" would like to control this computer using accessibility features. Grant access to this application in Privacy / Security settings, located in System Settings.

However `System Settings > Privacy & Security > Accessibility` shows KeePassXC enabled as well as `System Settings > Privacy & Security > Screen Recording`

To test this, I removed both entries and re-added them and KeePassXC auto-type is working again. Maybe this is related to the fact that I switched from 2.7.5 to nightlies to test something out. Not sure if there is a better way to handle this more gracefully. If not, feel free to close this issue.

**Comment by droidmonkey** [comment]
You need to remove keepassxc from both manually. Close keepassxc. Then either add keepassxc back manual in the settings dialog. This is a macOS bug or security feature when you move from a notarized application to one that isn't.
