### ISSUE TITLE
Provide better hint when SSH agent cannot add key if auto-deleting is enabled

### ISSUE THREAD

**Issue by OSPanel** [keepassxreboot/keepassxc#9659]
## Overview

Error adding key to SSH agent if auto-deleting key from agent is enabled
If you turn off auto-deleting the key from the SSH agent, then everything works well.

Since the procedures for adding and deleting a key manually work well, it is not clear why deletion does not work as a timer, because it is the same function. The error is clearly in the program, and the agent is not involved here.

## Steps to Reproduce

1. Add key to agent
2. Turn on auto-deleting the key from the SSH agent in the recording settings (30s)
3. Save settings and remove key from the SSH agent
4. Next, try to add the key to the SSH agent and get an error (as in the picture)

## Expected Behavior

Normal key addition to the agent

## Actual Behavior

Error adding key to SSH agent

![image](https://user-images.githubusercontent.com/44536631/247187600-50bcf6ff-88f4-4e53-a049-ca9ae57add14.png)

## Context

Windows 10 22H2
KeePassXC - v 2.7.5
Rev: 9d0537b

Agent is enabled, agent working fine.

OpenSSH Authentication Agent (win service) + [Proxy Pageant](https://github.com/ndbeals/winssh-pageant)
This bunch of two services allows you to simultaneously add a key to two agents. Without a checkmark of auto-deleting, everything works well. When using only OpenSSH Authentication Agent, the problem is similar.

A similar problem (with the option "Require user confirmation"): https://github.com/keepassxreboot/keepassxc/issues/9568

**Comment by droidmonkey** [comment]
This isn't our bug, per say. We would just provide a better error message if we can. Unfortunately it is impossible to tell WHY there is an error just from the ssh agent protocol.

**Comment by OSPanel** [comment]
Why the error is not in your program? In manual mode, the key is deleted normally. Why the program cannot perform the same timer operation. What does the agent have to do with this?

**Comment by OSPanel** [comment]
Most likely you do not use the timer inside the program (why? simple solution), and use the -t option for ssh-add. Apparently this is the agent’s bug, it needs to be updated. But it would be better if you made a simple timer inside the program.

**Comment by OSPanel** [comment]
Since 2018 :( no progress. https://github.com/PowerShell/Win32-OpenSSH/issues/1056
