### ISSUE TITLE
Windows client not recognizing updates to synced kdbx

### ISSUE THREAD

**Issue by stratacast** [keepassxreboot/keepassxc#966]
## Expected Behavior

I maintain a kdbx file on my Linux computers, and the file will sync to my Nextcloud server, which then syncs the file to Windows as well. On my Linux clients, my kdbx files are identical as expected. I expect the up-to-date kdbx file to open as well on the Windows client.

## Current Behavior

When I sync from Nextcloud to Windows, I will see the file sync to my Windows client and when I open the database in KeePassXC, there appears to be multiple weeks of data missing. But, if I replace the same file by downloading it directly from Nextcloud instead of letting it sync, KeepassXC uses the updated file. This leads me to believe the Windows client is not seeing the newest version by default on Windows (both clients are using the same default settings and the current version of KeePassXC)

## Possible Solution

Since I see no issues syncing other files to Windows, and my files open successfully on my Linux computers, I assume this has to deal with KeePassXC not recognizing the current database on Windows when the files are synced

## Steps to Reproduce (for bugs)

1. Create and save a file on Linux
2. Let the file sync via Nextcloud (perhaps other sync services?)
3. See if the file synced successfully to Windows.
4. Make edits to the kdbx file on Linux, then let it sync to Windows
5. Check to see if the updates synced. In my case, the file syncs but KeePassXC doesn't recognize it.

## Context

I am unable to tell if I am using a recent version of my database file on Windows. I also worry this will cause database conflicts eventually

## Debug Info

KeePassXC - 2.2.0
Revision: REVISION

Operating system: Windows
CPU architecture: x86_64

Enabled extensions:
- whatever Windows comes out of the box with its precompiled binary

**Comment by droidmonkey** [comment]
Is KeePassXC running while the sync is happening? Does it have the database open during the sync? Is your database really large (ie megabytes)?

**Comment by stratacast** [comment]
I had the database sync while KeePassXC was closed, I haven't tried doing a sync while I have KeePassXC open. My database is only 27KB, not sure what large means in respect to KeePassXC :)

**Comment by droidmonkey** [comment]
I am not too convinced this is necessarily a KeePassXC problem. I use Google Drive without any issues to keep my database synced. We don't cache anything between uses so the program is always loading directly from disk.

**Comment by stratacast** [comment]
Yeah I'm starting to do more work on Windows and it's starting to appear as though files are no longer being synced. I had some files sync alongside my kdbx file and they came down successfully, but now it appears to be All my files are "syncing" when they're actually not. So this no longer appears to be a problem with Windows KeePassXC not seeing file changes, and more a sync issue
