### ISSUE TITLE
Option to disable entry level Auto-type

### ISSUE THREAD

**Issue by kraoli** [keepassxreboot/keepassxc#9660]
## Summary
I like global Auto-type with a confirm dialog. It's working great. 

But even though entry level Auto-type has a confirmation dialog too against accidental triggers, I would much prefer to disable it completely. 
- That includes the shortcut ctrl+shift+v. 
- But also triggering it in the ui by drop-downs or buttons. 

## Examples
I would like to have an option to disable entry level Auto-type in KeepassXC (shortcut plus ui buttons and drop-downs) while keeping global Auto-type active. 

## Context
We all have been there, tired or stressed in front of the computer making a mistake. I think a function that you usually don't use is much more likely to be triggered by accident because you're not so aware about it. I often forget that ctrl+shit+v triggers entry-level Auto-type or example. 

My global shortcut is well known due to the daily usage. I'm always aware about it. 

But clicking at a wrong place in a drop-down or in the toolbar or pressing shift by accident (shift is directly above ctrl) when you wanted to paste with ctrl+v and clicking on "Yes" instead of "Cancel" after that is something that is very unlikely and stupid, but a possible human error. 

KeePass has an option to disable the whole entry-level Auto-type. Isn't is better to disable everything you don't need? Keeping the attack surface small by removing unnecessary things is a common recommendation. Why not apply it here too?

**Comment by varjolintu** [comment]
This could be expanded to the group level too. EDIT: Oh, ther group setting is already there. My bad.

**Comment by droidmonkey** [comment]
I suppose you could disable it if the group has autotype disabled.
