### ISSUE TITLE
Ability to use wildcards * in the URL field

### ISSUE THREAD

**Issue by jackbelmore** [keepassxreboot/keepassxc#9662]
## Summary
Ability to use wildcards * in the URL field

## Examples
https://account.sainsburys.co.uk/* compared to https://account.sainsburys.co.uk/gol/login?login_challenge=a185fe32b1004272bf7d37e0f02facda

## Context
I will visit a website and the url on keepass will be slightly different than the one in my keepass database, For example the website is https://account.sainsburys.co.uk/gol/login?login_challenge=a185fe32b1004272bf7d37e0f02facda but the url on keepassxc is https://account.sainsburys.co.uk/gol/login and the browser extension doesn't see that I have a password saved due to the url being different. Is it possible to add a wildcard so that even if the url is slightly different keepass can still find my username and password? Thank you so much for all the work you do and the amazing program. Have a great day!

**Comment by droidmonkey** [comment]
We don't care about anything past the base url for matching. It is likely the page has the login information embedded in an iframe that has a different url.
