### ISSUE TITLE
Support for a second (backup) Yubikey

### ISSUE THREAD

**Issue by DinantVoortman** [keepassxreboot/keepassxc#9664]
It's not possible to add a Backup Yubikey. This makes it the use of Yubikeys in KeepassXC no a cording to the Yubikey standaard. VrGr Dinant

**Comment by droidmonkey** [comment]
When you setup your first key, just use the same secret on the second key (ie, both keys are identical). We also recommend printing out the secret and storing it in a safe place if you ever needed to make another one.

**Comment by DinantVoortman** [comment]
Hi Jonathan,

That works thanks.
