### ISSUE TITLE
Clipboard doesn't clear on Debain KDE Plasma

### ISSUE THREAD

**Issue by denppa** [keepassxreboot/keepassxc#9666]
## Overview
The clipboard does not get cleared after the time designated in the keepassxc GUI.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set clear clipboard sec to 10 secs
2. Copy an entry, wait 10 secs
3. Check clipboard, contents are still there

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The copied content should be absent from the clipbaord, along with other history.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The password and previous history is still present.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Debian Bookworm, KDE Plasma wayland session, KeepassXC installed via apt.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4

This command clears the clipboard content, that means the API is available, could it be that keepassxc implemented it incorrectly?
```qdbus org.kde.klipper /klipper org.kde.klipper.klipper.clearClipboardHistory```
Credit: https://forum.endeavouros.com/t/clear-kde-clipboard-klipper-n-seconds-after-something-was-last-added-to-it/13535

**Comment by droidmonkey** [comment]
Update to 2.7.5, this was fixed

**Comment by denppa** [comment]
It is not available in the Debian repo yet, does that mean my options are compile or flatpak?

**Comment by droidmonkey** [comment]
Yes
