### ISSUE TITLE
Global Auto-Type error with Window Association Auto-Type

### ISSUE THREAD

**Issue by MedusaEXE** [keepassxreboot/keepassxc#9667]
## Overview

Using Global Auto-Type for one of my entries. Settings are as follows:
 [Y] Enable Auto-Type for this entry
 [Y] Inherit default Auto-Type sequence from the group
 [N] Use custom Auto-Type sequence

Window Associations - I have 2 here depending on where I am on the site login page
1. {website} -- LibreWolf
2. Login :: {website} -- LibreWolf

Now these both have separate "Specific sequence for this association:". They are as follows:
1. {TAB 2}{ENTER}{DELAY 500}{USERNAME}{TAB}{PASSWORD}{ENTER}
2. {TAB}{USERNAME}{TAB}{PASSWORD}{ENTER}

The issue is when I'm on the tab with title "Login :: {website} -- LibreWolf" it's executing the specific sequence for Window title "{website} -- LibreWolf"

## Expected Behavior

I'd expect it to auto-type with correctly matched window titles.

## Actual Behavior
Incorrectly matches window title leading to the auto-type performing the wrong sign in sequence. 

## Context
Other settings of note. All 5 boxes on the auto-type settings are unselected. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
OS: Windows

**Comment by droidmonkey** [comment]
Doesn't the auto type selection popup come up and let you choose which window association sequence to use? Are you sure the window title is as you say it is?

**Comment by MedusaEXE** [comment]
The auto-type selection box doesn't come up since the matching of the window title works mostly. I've tried reproducing today but having issues doing so. 

Will close for now and reopen once I can reproduce it.
