### ISSUE TITLE
Request: Adding Support to Epiphany (Gnome Web Browser)

### ISSUE THREAD

**Issue by sallyhaj** [keepassxreboot/keepassxc#9668]
Hello there,
I would like to thank you all developers.

Is there a plan to support [Epiphany](https://gitlab.gnome.org/GNOME/epiphany)?
The Gnome Web Browser is a promising app, specially it's far a way from Chrome/Chromium based.

Thank you.

**Comment by droidmonkey** [comment]
If they support web extension framework, it will happen naturally. If not, well good luck to them.

**Comment by spaette** [comment]
@sallyhaj, @droidmonkey

`https://gitlab.gnome.org/GNOME/epiphany/-/blob/master/src/webextension/README.md`

43.0 was released Sept. 15, 2022

The infrastructure appears to be here — to add a downloaded .xpi file —- but perhaps some testing could be done.

A GUI checkbox entry for "Gnome Web" might be considered.

The browser, officially GNOME Web, was renamed  12 years ago, where the former name is only retained as a code name.

And also adding a 'webextension' repo to this Organization as separate download address for such .xpi file.

```
$ grep webextensions -A 4 /usr/share/glib-2.0/schemas/org.gnome.epiphany.gschema.xml
                <key type="b" name="enable-webextensions">
                        <default>false</default>
                        <summary>Enable WebExtensions</summary>
                        <description>Whether to enable WebExtensions. WebExtensions is a cross-browser system for extensions.</description>
                </key>
                <key type="as" name="webextensions-active">
                        <default>[]</default>
                        <summary>Active WebExtensions</summary>
                        <description>Indicates which WebExtensions are set to active.</description>
                </key>
$ file ~/.config/dconf/user
/home/soeren/.config/dconf/user: GVariant Database file, version 0
$ dconf write /org/gnome/epiphany/web enable-webextensions true
$ 
```
![web](https://github.com/keepassxreboot/keepassxc/assets/111918424/e271910a-2b72-4604-aeb5-106b06ea5808)
