### ISSUE TITLE
keepassxc sometimes unresponsive after suspend-to-ram

### ISSUE THREAD

**Issue by cipitaua** [keepassxreboot/keepassxc#9669]
## Overview
I keep keepassxc in the tray and suspend-to-ram at night. Sometimes the main window becomes unresponsive, so that clicking or typying has no effect. However, I can close and reopen the main window by clicking on the tray icon. This does not solve, I have to close and restart the app.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open KPXC and leave it in the background
2. standby and resume some times
3. try to use KPXC

## Expected Behavior
one can use the app, search for passwd and so on

## Actual Behavior
main window does not respond to keys or mouse

[NOTE]: #
KeePassXC - 2.7.4
Revision: 63b2394
Qt: 5.15.10
Operating System: Linux (debian sid)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Update to 2.7.5, this was fixed

**Comment by cipitaua** [comment]
thank you. I thought I was on the latest release...

**Comment by cipitaua** [comment]
I have upgraded this morning to 2.7.5 but I've just stepped again into this bug, *without any suspend-to-ram in between*. 

KeePassXC - Versione 2.7.5
Revisione: 9d0537b

Qt 5.15.10

Sistema operativo: Debian GNU/Linux trixie/sid
Architettura CPU: x86_64
Kernel: linux 6.3.0-2-amd64

Estensioni abilitate:
- Completamento automatico
- Integrazione browser
- Agente SSH
- KeeShare
- YubiKey
- Integrazione del servizio segreto

Librerie crittografia:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
You'll need to provide a core dump or run keepassxc through a debugger. This is likely something unique to your computer. 

I recommend switching to the flatpak distribution to avoid using your system libraries. This would better isolate the problem.

**Comment by cipitaua** [comment]
doesn't a core dump require the app crashing?

I'll try the flatpak

**Comment by cipitaua** [comment]
I've actually encountered the same behavior (freezed interface) using the Appimage. I think this bug should be reopened.

**Comment by droidmonkey** [comment]
Leaving a vague freeze issue open is unhelpful. You need to provide gdb stacktrace or core dump to enable any chance of fixing whatever is wrong here.

**Comment by cipitaua** [comment]
is it possible to get a gdb stacktrace or core dump using the flatpak?

**Comment by cipitaua** [comment]
I attach the core dump extracted during the hang, occurrred using the 2.7.5 appimage.

[core.3400.zip](https://github.com/keepassxreboot/keepassxc/files/12335190/core.3400.zip)

**Comment by cipitaua** [comment]
@droidmonkey
I attach the core dump extracted during the hang, occurrred using the 2.7.5 appimage.

[core.3400.zip](https://github.com/keepassxreboot/keepassxc/files/12344334/core.3400.zip)

**Comment by droidmonkey** [comment]
That core dump doesn't contain any usable info:
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/f48650b9-d654-4503-a3e0-691c63203ff7)

**Comment by michaelk83** [comment]
> You'll need to provide a core dump or run keepassxc through a debugger. I recommend switching to the flatpak
> ...
> That core dump doesn't contain any usable info

@droidmonkey If you know you need debug symbols for a useful core dump, why are you not pointing at the dev snapshots? You know the regular Flatpak or AppImage don't have debug symbols in them.
https://snapshot.keepassxc.org/

**Comment by droidmonkey** [comment]
I did not mean to use appimage or flatpak to _provide a core dump_. I pointed him there to use a different production deployment method to solve the apparent problem.

**Comment by cipitaua** [comment]
@michaelk83
thank you for the useful information and for pointing me in the right direction
