### ISSUE TITLE
Unable to set additional URL to a value set in any additional attribute

### ISSUE THREAD

**Issue by gxtu** [keepassxreboot/keepassxc#9670]
## Overview
When adding a URL to the *Additional URLs* section in the *Browser Integration* tab of an entry, you can't set the URL to a value which is already the value of an *Additional attribute*.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new entry
2. In the *Advanced* tab, create a new *Additional attribute* for the entry with an arbitrary name and set its value to some URL (or any arbitrary value really)
3. Save the entry by clicking *OK*
4. Open up the entry again
5. In the *Browser Integration* tab, try to add a new *Additional URL* with the same content as the value you set in step (2)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A new *Additional URL* entry is created with the entered value.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The *Additional URL* entry can't be added with the entered value. For a new entry it will fall back to `<empty URL>` instead. When editing an existing entry it will revert to its previous value.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Wow that is super weird, reproduced and now super curious on the code here. @varjolintu

**Comment by varjolintu** [comment]
I'm gonna check this against https://github.com/keepassxreboot/keepassxc/pull/9635 and add any fixes to that PR.

**Comment by varjolintu** [comment]
Found one bug on the new PR and fixing it solves this issue.
