### ISSUE TITLE
KeepassXC No Minimize Or Maximize Option

### ISSUE THREAD

**Issue by rlaroseII** [keepassxreboot/keepassxc#9671]
## Overview
No minimize or maximize option at top right of window

## Steps to Reproduce
Open KeepassXC

## Expected Behavior
Minimize and maximize option should be available

## Actual Behavior
No minimize or maximize option

## Context
All other applications have minimize and maximize option available

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Debugging mode is disabled.

Operating system: Pop!_OS 22.04 LTS
CPU architecture: x86_64
Kernel: linux 6.2.6-76060206-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4

Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

Desktop Env: Gnome

Windowing System: Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF

**Comment by droidmonkey** [comment]
We don't control that, you will have to figure out why your desktop manager isn't showing those controls. 

https://unix.stackexchange.com/questions/705254/minimize-and-maximize-buttons-missing-only-for-certain-programs-in-pop-os

**Comment by CRCinAU** [comment]
I notice this with Fedora 39 when KeepassXC is started automatically on user login.

Exiting and starting Keepass XC again will restore the min/max icons again.
