### ISSUE TITLE
'Only One Instance' Setting Not Applied

### ISSUE THREAD

**Issue by kud** [keepassxreboot/keepassxc#9673]
Sure, here is how you could fill out the template to report the issue:

## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )
When using the "only one instance" setting and my database is locked, if a software asks to open the database with the fingerprint, KeePassXC opens a new window specifically for the fingerprint. This is redundant and inefficient. It would be preferable to have only one window. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set KeePassXC to "only one instance" mode.
2. Lock the database.
3. Have a software request to open the database via fingerprint.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When a software requests to open the database via fingerprint, I expect KeePassXC to handle this within the already existing instance, rather than opening a new window.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Instead of utilizing the existing instance, KeePassXC opens a new window solely for the fingerprint verification.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This behavior causes unnecessary clutter and consumes system resources. Simplifying this process by using only a single window would improve user experience.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 13.4.1 22F82 arm64
Desktop Env: KeePassXC - Version 2.7.5 Revision: 9d0537b
Windowing System: Qt 5.15.8

**Comment by droidmonkey** [comment]
A new instance is not opened. The original instance must be surfaced/visible to show dialogs. This is a macOS limitation.

**Comment by CerebralFreeze** [comment]
**Update**
Now, it seems to be working fine.  I have no idea why this occurred.

**Previous comment**
_This is suddenly happening to me.  I don't know if it's due to a recent update to KeePassXC._

_Previously, if I execute a shortcut to open KeePassXC, it would simply open the current KeePassXC.  Now, it tries to open a new instance.  Maybe, I'm doing something wrong..._

**Comment by kud** [comment]
I still have two "windows" but at least I've got the macOS fingerprint window directly now, so that's ok-ish.
