### ISSUE TITLE
Login Window @Windows app too big

### ISSUE THREAD

**Issue by GonzoHJK** [keepassxreboot/keepassxc#9674]
At starting the KeePassXC windows app to log into tha database, the application window opens to it's size, used for seraching and managing the key databayse.
<img width="1205" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/140903476/7f622d56-883d-4da7-8a22-75dabbbf449b">

## Examples
Just limit the size to the below shown content / frame - for login purpose only, I'd really appreshiate.
<img width="416" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/140903476/a973b935-b894-4277-bfaa-11d7c6776b7f">
after login successfully done, the initial window size for managing and editing the key-database could be enlarged ...

an additional feature could be define the log in window pop up at a certain area of the screen ...
- at top (center, left, right)
- left, right side
- directly above the TaskBar Icon
<img width="440" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/140903476/b60b589f-822b-4966-b187-93d43ff8a8d0">

additionally an option could be that after successfull login the dialog disapears and the open KeePassXC app just disapears into the TaskBar ... not  opening at all fully ...

## Context
this would help easing up my workflow at startup  ..

**Comment by droidmonkey** [comment]
This doesn't make sense for us, we won't be making changes to the startup behavior.
