### ISSUE TITLE
Database does not remember yubikey

### ISSUE THREAD

**Issue by Mikilio** [keepassxreboot/keepassxc#9676]
## Overview
Initial login using `keepassxc --pw-stdin db.kdbx  < pwd`  fails, because the is no challenge response slot selected.

## Steps to Reproduce
1. create db.kdbx and secure it with a yubikey using challenge response
2. `keepassxc --pw-stdin db.kdbx  < pwd` in posix shell

## Expected Behavior
It should unlock db.kdbx with the password and my yubikey

## Actual Behavior
It fails and I have to manually select the slot each time.

## Context

The command is executed in systemd

KeePassXC - 2.7.5

Operating System: Linux
Desktop Env: Custom
Windowing System: Wayland

**Comment by Mikilio** [comment]
Maybe I am expecting a different behavior than is intended. In that case I would formulate this as a feature request for a startup option to specify the HMAC slot on the startup command.

**Comment by droidmonkey** [comment]
#6018
