### ISSUE TITLE
Use the Meta/Super Button as Modifier Key in Linux

### ISSUE THREAD

**Issue by denppa** [keepassxreboot/keepassxc#9677]
## Summary
Users like myself that switch between macOS and Linux are very likely accustomed to the convenience of using the `Cmd`/`Super`/`Meta` key to copy and paste. I have managed to configure my KDE environment to largely use `Meta`, can KeePassXC expose the settings that lets the user change the modifier key, making the `Meta` behavior even more consistent?

Thank you.

## Examples
Pressing Meta+c copies the password of an entry in Linux.

## Context
Should be answered above.

**Comment by droidmonkey** [comment]
Watch #9643
