### ISSUE TITLE
how to get a password from cli?

### ISSUE THREAD

**Issue by ystyle** [keepassxreboot/keepassxc#9678]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I want to get password in shell script

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I want to get password in shell script， like this
```shell
# myapp -token ${keepass-cli getpwd path-to-mydb  myapp_token}
```

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Read the man page. Or use `keepassxc-cli help`

Generally it would be: `echo "[db password]" | keepassxc-cli show -a Password -q [entry path] [db  file]`

The -q ensures only the entry password is printed.
