### ISSUE TITLE
Document the code for automatic documentation

### ISSUE THREAD

**Issue by elgesl** [keepassxreboot/keepassxc#968]
Although large portions of the code seem to be quite self explained, it would be great to have a real, full code documentation, e.g. compatible with doxygen.
That would make it far easier for new developers to join the group. The main reason is that I saw quite many open source (actually closed source, too) projects die, because (some of) the main developer(s) left for some reason and then part of the code were not fully understood by anyone left.

## Expected Behavior
Each class, function, etc. should be introduced by a suitable comment. Preferable compatible to doxygen (mostly as this ensures a full documentation). In the end classes/functions should be understood without reading the header file (as e.g. it is the case for almost everything in the Qt library).

## Current Behavior
Some classes/functions can be understood by reading the full header file, most parts of the code are self  explaining if you read the source file and some parts are a bit hard to understand.

## Possible Solution
For example Doxygen comments.
I am happy to help with the first time documentation if some of the developer understanding the code better than I do help and if it gets part of the coding style rules to write a/update the documentation (otherwise it does not make any sense at all).

**Comment by droidmonkey** [comment]
This is tremendous amount of work for little gain. A more useful documentation feature would be a code map and overview of event sequences. There are a ton of signal/slot interfaces that are dynamically allocated and not very obvious which class is supposed to do what.
