### ISSUE TITLE
Benutzerdefinierte Autotype-Sequenz benutzen

### ISSUE THREAD

**Issue by c-atmbu** [keepassxreboot/keepassxc#9680]
Ich würde gerne eine benutzerdefinierte Autotype-Sequenz erstellen und habe jetzt schon alle möglichen Versionen versucht. Allerdings ohne Erfolg. Ich füge einen Screen-Shot meiner Bemühungen bei. Was mache ich verkehrt? Es funktioniert einfach nicht. Vielen Dank für die Unterstützung. 

![Bildschirmfoto vom 2023-07-31 20-54-04](https://github.com/keepassxreboot/keepassxc/assets/69669282/86165985-b62d-415d-a54b-a56acabb5ea3)

**Comment by droidmonkey** [comment]
Did you put the actual attribute name in the `{S: ...}` part?
