### ISSUE TITLE
KeePassXC only compares main domain / ignoring subdomain and path

### ISSUE THREAD

**Issue by Stefan-Olt** [keepassxreboot/keepassxc#9682]
I just started using KeePassXC, I'm not sure if this is a feature request or if I'm just too stupid to find the option:
I have a domain with various folders and subdomains with dozens of different passwords. Unfortunately the KeePassXC is useless for me: It gives me dozens of passwords ignoring the URL, just because the main domain matches.
The URLs for example look like:
https://www.company.org
https://employee.company.org
https://3rd-party-app.company.org
https://department.company.org/subsection/login
https://department.company.org/admin
https://project.department.company.org
KeePassXC will match all passwords for all URLs, this is terrible bad behavior (also security-wise, because some pages have low-security standards and I do not want to accidentally submit a import password there). How can I make it compare full URLs (only match password if the URL in KeePassXC matches the beginning of the opened URL exactly)? The same wrong behavior for favicons: It will download the one from company.org, even though the URL is project.department.company.org, why that?
Best regards
Stefan

**Comment by droidmonkey** [comment]
That is not how our program works, though. We match to the subdomain level by default (you actually cannot change that). Are you using the browser extension or Auto-Type? 

Also, what version of KeePassXC are you using and on what operating system?

**Comment by Stefan-Olt** [comment]
I'm using the Firefox extension (1.8.7) and the and KeePassXC that is provided by Ubuntu 22.04 LTS (2.6.6). The choice for using KeePassXC (open-source no-cloud is mandatory for me) that the same database can be used on different OSes, but so far I have only tested on Ubuntu 22.04.

**Comment by droidmonkey** [comment]
Not that 2.6.6 is broken in this way, but we are up to 2.7.5 and recommend using the flatpak distribution.

**Comment by Stefan-Olt** [comment]
I'm sorry, but if that behavior cannot be changed, that's a deal-breaker for me. If I cannot find a alternative I'll rather stick to the internal password manager of Firefox, it can kind-of do that (you can change a setting in the about:config so at least it doesn't ignore subdomains).

I haven't tried KeePassXC as flatpak, but other applications and my conclusion is that I won't use it: I have configured my system in a way I like it and that it is comfortable to use for me (themes etc.) and flatpak ignores all of that and the apps don't integrate at all. I do understand that this makes it independent from system libraries and easier for distribution, but for the user (at least for me) it's worse. After you have managed that GTK and QT apps both look fine and similar there is flatpak with flatpak-GTK and flatpak-QT and the mess starts again. No thanks. AppImages on the other hand are a good idea.

I'm sorry if this is negative, I know this is an open-source project and you're all doing the best you can and I really appreciate your work (and quick response here), but at least for now KeePassXC doesn't meet my requirements. If you implement more advanced matching option (for each entry there could be a selection "Compare only top/2nd-level domain", "Compare including subdomain(s)", "Compare full URL" and a wildcard to be able to match more advanced schemes), I'll be happy to build KeePassXC from source until there are packages available to try that.

**Comment by droidmonkey** [comment]
Please re read what I said. The behavior you are describing is NOT how our program works. We respect subdomains and enforce that as an explicit security measure in our program. I hate to blame the user, but it would really help if you showed your entries and their urls so we can find the error.

**Comment by Stefan-Olt** [comment]
I'm sorry, I misunderstood your answer, I thought you we're referring to my need to match subdomains. I'm probably not allowed to share all URLs here, as many of them are not public.
I think I isolated the problem: 95% of the passwords are either department.company.org/somewhere/login or  projectA.department.company.org, projectB.department.company.org etc. and KeePassXC will compare the 3rd-level domain, but not 4th-level and not the path. Sorry, all I saw was a long list of logins and I didn't verify that indeed all are the same 3rd-level domain, this is not ignored. Is there a setting to compare the entire domain and path?

**Comment by droidmonkey** [comment]
Yes there is. Go to the browser tab in the application settings (where you setup browser integration)  and there is a setting labeled "return best matching credentials", enable that one. Now the behavior of that setting was greatly improved in 2.7.0 so we do recommend updating. You can use our appimage located on our downloads page.

**Comment by Stefan-Olt** [comment]
Thanks for your help, I updated to 2.7.5 (from the PPA), enabled that option, but nothing has changed (I restarted both KeePassXC and Firefox, still the same). I'll get a list of logins and the correct is also not the first one.

**Comment by droidmonkey** [comment]
You'll still need to define your fourth level subdomain in the url. We match like this: `*.sub2.sub1.host.tld`

If you enable best matching then we also take the path and query string into account.

**Comment by Stefan-Olt** [comment]
I'm sorry, but I don't understand what you mean by I have do define the fourth level subdomain. I enter the full url that include the 4th level subdomain. If I set the URL for example as https://sub2.sub1.host.tld/admin I also get the login data from https://sub1.host.tld/admin and https://sub1.host.tld/somewhere/login etc. That's the issue.

**Comment by droidmonkey** [comment]
Ok, I was mistaken, we do match with all levels of a domain. That means sub2.sub1.example.com will send credentials with a url of sub1.example.com but not sub3.sub1.example.com.

If you enable "only send best matching credentials" then you will only see entries from the lowest level of matching and not "upper level" matches.
