### ISSUE TITLE
Auto-Type: ignore web browser name in window title

### ISSUE THREAD

**Issue by flux77** [keepassxreboot/keepassxc#9683]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
For the purposes of Auto-Type in KeepassXC, there should have a way to ignore web browser names in the window title of web browsers. For example, visiting https://keepassxc.org in Mozilla Firefox will cause the Firefox window to have this title: "KeePassXC Password Manager — Mozilla Firefox". If there is a password entry with title "Mozilla Firefox", it will match the "— Mozilla Firefox" suffix.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add a new password entry with title "Mozilla Firefox"
2. Open the Firefox web browser
3. Visit https://example.com
4. Auto-Type
5. Observe that the list of Auto-Type candidates includes the "Mozilla Firefox" password entry.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should not include the "Mozilla Firefox" password entry as an Auto-Type candidate.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC shows the "Mozilla Firefox" password entry as an Auto-Type candidate, with is incorrect because the website visited is https://example.com. KeepassXC is confused because the window title of the web browser is "Example Domain &mdash; Mozilla Firefox", which seems to match the "Mozilla Firefox" title of the password entry.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
No thank you, we will not arbitrarily filter window titles. Disable the option to match by entry title since it is not very secure anyway. Also you are running an extremely outdated version of KeePassXC.
