### ISSUE TITLE
Open "Auto-Type sequence selection" with program argument (e.g. hyprland wayland)

### ISSUE THREAD

**Issue by krei-del** [keepassxreboot/keepassxc#9684]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Show the "Auto-Type sequence selection" with specific program argument like
`keepassxc --show-autotype-window`

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Almost all desktop environments allow "Global Hot Keys". As there are currently problems registering Global Auto-Type within wayland this could be simple workaround. Furthermore there should be no security issues, when a "global hot key" is defined by the desktop environment, that have anyway the primer rights to do so (wayland specific issue).

**Comment by droidmonkey** [comment]
No thank you, this is also not the only blocker on Wayland
