### ISSUE TITLE
poor word choice "Entry(s)" on main screen

### ISSUE THREAD

**Issue by jack99999** [keepassxreboot/keepassxc#9686]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

on bottom right of main screen i see: "58 Entry(s)"

this is rather clunky wording. nicer would be:  "Entries: 58"

that construction is good enough to get around the singular/plural mess and does look neater.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Thank you but not going to change this

**Comment by phoerious** [comment]
Entry(s) looks like an incomplete English translation to me. Those things are handled on Transifex.

**Comment by JohnLGalt** [comment]
Entr(y|ies)?  lol

Sorry, couldn't resist. 

I do think the OP's suggestion has merit, though.
