### ISSUE TITLE
Copy password to clipboard when clicking on "Password generator"

### ISSUE THREAD

**Issue by MarkWieczorek** [keepassxreboot/keepassxc#9688]
## Summary
When clicking on the "Password generator" icon, the password generator panel is displayed, and a new password is generated and displayed in the password field. This password can be copied to the clipboard by clicking on the "copy" icon next to the password.

I propose that whenever a user clicks on the "password generator" icon that the new password is automatically copied to the clipboard. Most users don't change the characteristics of the password after they are set (such as the length, password vs passphrase), so this would just make the user's life easier.

**Comment by droidmonkey** [comment]
I disagree, you are assuming user intent which we try not to do throughout our program. We would never want to auto-copy a sensitive data field to the most insecure place (clipboard). I often create entries with passwords that are then used to auto-type the password into a field.

This won't be implemented as a result of our explicit intent requirement.

**Comment by MarkWieczorek** [comment]
Hi @droidmonkey. Just out of curiosity, how do you create a password from the "Password generator" panel, and then add this to an entry without using the clipboard? I think that you might have misunderstood my feature request, so I am copying a screen shot of the "Password generator" panel. (I wasn't referring to the "Generate password" popup window, and for that window I totally agree with you.)

<img width="1310" alt="Screenshot 2023-08-02 at 13 36 16" src="https://github.com/keepassxreboot/keepassxc/assets/8697285/d5915601-492e-49cf-b3b1-dc1360a85b16">

**Comment by droidmonkey** [comment]
Oh you were referencing just the stand alone password generator. I still don't like inferring user intent here. Is this really a time saver? I'm not convinced that it just introduces a bunch of unintended consequences for people's workflow

**Comment by MarkWieczorek** [comment]
I think that it is a time saver: now you need to (1) click password generator, (2) click copy password, and (3) close the window. Ideally, there would be a quick way to do this in one click. For example, one could entertain the possibility of doing something like control-click on "Password generator" to copy a new password to the clipboard *without* opening the Password generator panel at all.

In any case, for future reference, I think that you are referring to the following situation:

* A user might want to generate a password with an application, and then write it down on paper. Automatically copying it to the clipboard is a possible attack vector for obtaining such a password that is generated online, but never stored online.

**Comment by JohnLGalt** [comment]
In counterpoint, though, if you copy the password to the clipboard, and enter it into whatever application or webpage you want to use it at, but then **don't** enter it also into a KPXC entry, or KPXC abruptly terminates for whatever reason, you now have said entity protected by a password that you have no access to in any manner. And it is made even worse because any accidental addition to the clipboard without extended clipboard services enabled would then mean it is gone from even the clipboard at that point.

For the sake of preventing this sort of problem from ever happening to any user, I believe that the current methodology is a much better way to go.
