### ISSUE TITLE
KeePassXC always asking for permission

### ISSUE THREAD

**Issue by Evil2000** [keepassxreboot/keepassxc#9691]
## Overview
When opening a program which needs a password from the Database KeePassXC asks for access. When "Allow all & Future" is clicked, KeePassXC asks again after it was completely closed and reopened or the system was rebooted. In older versions of KeePassXC the behavior was as expected and changed some versions ago.

## Steps to Reproduce
1. Open KeePassXC and enable Secret-Service integration with Gnome Keyring
2. Open a program which asks for permission to access the password database
3. Set the "Remember" checkbox and permit the access by clicking  "Allow all & Future"
4. Close KeePassXC completely or reboot your system and reopen KeePassXC
5. Open the same program which you opened in step 2.

## Expected Behavior
KeePassXC just allows the access to the database without asking again.

## Actual Behavior
KeePassXC denies the access to the database and asks again for permission.

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Diagnosemodus ist deaktiviert.

Betriebssystem: Kali GNU/Linux Rolling
CPU-Architektur: x86_64
Kernel: linux 6.3.0-kali1-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.3

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a duplicate report, please search for issues with the secret service label.

**Comment by Evil2000** [comment]
Thanks for the hint.
For reference, this is a duplicate of #8784
