### ISSUE TITLE
KeepassXC truncates database when it tries to open it

### ISSUE THREAD

**Issue by gamelaster** [keepassxreboot/keepassxc#9695]
# NOTE: This problem can be caused by some other component of my system, although, I can't fully confirm it wasn't KeepassXC

I am using on my Arch KeepassXC for more than a year. Today, I disabled automatic lock of the database after usage. My database file is located on folder mounted to cifs share point. Today, after I put my computer to sleep, and then woke it up and tried to log in to my database, it shown that the file cannot be read (or something similar, I don't remember exact message and I did not captured it). So I take look to mount, it was working OK, I am checking out database file... And it was 0 bytes. So I copied backup and replaced old file, tried to open it... And file was truncated again to 0 bytes. So I restarted KeepassXC, again replaced the default database with backup/copy, tried to open, and it worked out just fine.

I wasn't able to reproduce it, but I will update this issue if it will happen again...

# KeepassXC Info

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.10
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.3.9-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0

Operating System: ArchLinux
Desktop Env: KDE Plasma
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You ran out of space on the drive you had your database on. We don't write to the file unless you save (ie make a change) so just opening a database will absolutely not truncate a file.

**Comment by gamelaster** [comment]
@droidmonkey I am sure that the drive (in this case CIFS mount point) did not ran out of the space. And yes, it makes sense that the app does not write anything to the database file during opening it, although I am sure that always it tried to open the db, it truncated the file, until I did not restarted the KeepassXC. I don't think or confirm that this is really the app's issue, in the end, I am using this setup and work flow (KeepassXC with db file on CIFS mount point) for more than year, just some weird situation happened. If it will happen again, I will try to more document and test it, so I can try to figure out why it happens.

Thank you for your time.

**Comment by droidmonkey** [comment]
What is your save settings set to? In other words are you using safe saves, temporary file, or direct write.

**Comment by gamelaster** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/1665373/ac219b5a-4221-4a06-bb2e-a20a3b967d7c)
Those are my settings. Also, I noticed one interesting thing, which can explain a little bit, what happened.
Before yesterday, I had automatic lock enabled after 3 minutes of inactivity. I turned it off, worked on PC, and the put it to the sleep. After wake up, the db file was truncated. My theory is, that when PC started sleep procedure, I had some unsaved changes to DB file. I am not sure when the PC is locked, if before sleep or after waking up, but anyway, at the moment when it was locked, KeepassXC tried to save the database, but since the CIFS mount point was not working at the moment, the writing of the database got into weird state, potentially confusing the app, and instead of writing the file, it only created "new handle" but did not written the content (Just my speculation).

Both of the files truncated files (I only renamed them for reference) have last modify date the time, when PC was put in sleep. Also, I found CIFS fail messages in dmesg, so something weird really happened.

Anyway, as I mentioned in original post, it can be combination of faults also from my system, which according to dmesg, happened. Thus, solution is to have backups and enabled alternate saving method.

Thanks!

**Comment by droidmonkey** [comment]
Interesting, this situation should be "impossible" with safe saves. The only reason I can think of is the safe save procedure completes but the write cache did not flush (ie actually write) prior to the cifs container being closed.
