### ISSUE TITLE
Snap Support

### ISSUE THREAD

**Issue by lhhel9l3** [keepassxreboot/keepassxc#9696]
The snap page for keepassxc reads:

> NOTE: KeePassXC no longer supports this distribution method. Snaps have a lot of bugs across distros and are difficult for us to maintain a satisfactory experience. We recommend switching to the flatpak distribution instead. https://flathub.org/apps/details/org.keepassxc.KeePassXC

Source: https://snapcraft.io/keepassxc

My question is: what happens to people who are still using the snap package? Since the distribution method is not supported, will they no longer receive updates? What about critical security updates? If security updates are not guaranteed, who will notify the current snap users that their distribution method is now unsupported, so that they can stop using it and migrate to a supported method? Thanks.

**Comment by droidmonkey** [comment]
Not supported means we aren't going to fix snap specific issues. We are still distributing updates through snap, however.

**Comment by lhhel9l3** [comment]
Thanks. If I may ask one follow up question, what if there is a snap-specific _security_ issue? Would that be fixed?

**Comment by droidmonkey** [comment]
That would only really be related to the bundled packages which would ostensibly be updated with the next app update anyway. This is one of the main problems with snaps, the dependencies are strongly bound to the snap and the specific distro used to build the snap.
