### ISSUE TITLE
Feature request: Add MariaDB/MySQL-Support

### ISSUE THREAD

**Issue by mkrsn** [keepassxreboot/keepassxc#97]
AFAIK is there only one "Storage-Backend" thats used by KeePassX - kdbx. It would be really great if KeePassX would support MariaDB/MySQL as an optional "Storage-Backend".

This would offer some new possibilitys like WebUIs (not sure if this is really useful), Teaming (yay!) and so on. This would also be an alternative to WebDAV, to use KeePassXC with multiple devices.

**Comment by droidmonkey** [comment]
This would be a good feature for [keeweb](https://github.com/keeweb/keeweb) project. It is not within the scope of KeePassXC as we are striving to be as disconnected and offline as possible.
