### ISSUE TITLE
Quick Unlock (Windows Hello) makes opening database slow

### ISSUE THREAD

**Issue by mchubby** [keepassxreboot/keepassxc#9703]
## Overview

Initial opening of database with quick unlock enabled, is slow.

## Steps to Reproduce

1. Install KeepassXC 2.7.5
2. Open a kdbx safe (KDBX 4.1 but does not matter)
3. Enter passphrase to unlock
4. Prompted by the OS, either use the fingerprint reader or enter PIN to proceed

## Expected Behavior

Database is open and ready for use

## Actual Behavior
The UI seems busy doing something, and after about 2-5 minutes, allows entry

## Context

It is not blocking : clicking cancel instead of fingerprint / PIN also works fine

**Workaround:** disabling "Enable database quick unlock (Touch ID / Windows Hello)" in Settings restores previous behavior (need to enter kdbx passphrase to unlock)

- Recently upgraded from v2.6.x branch
- 2.7.0 to 2.7.4 just terminated abruptly instead. Probably related to recently merged #9006
- No error reported by UI (#9697 should help when it's completed)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
This isn't a problem for anyone else so this must be related to something specific to your computer and windows hello. Recommend removing windows hello access entirely from your computer and re-registering it. There is nothing we would do to be able to solve this as it's not on our side.

**Comment by mchubby** [comment]
Feedback: Thanks, removing and registering the Windows Hello methods again did the trick.
