### ISSUE TITLE
Add Time Reminder Feature

### ISSUE THREAD

**Issue by Vinking-Yang** [keepassxreboot/keepassxc#9705]
Would like to add a time reminder feature. Because sometimes some products need to be renewed time before certain timeframe or point in time.

**Comment by Vinking-Yang** [comment]
Specify a time reminder.
Periodicity reminder.
Time period reminder.

**Comment by droidmonkey** [comment]
Use the expiration field when editing an entry.

**Comment by Vinking-Yang** [comment]
Thank you. I have used this feature, but this feature does have a system notification alert.

**Comment by droidmonkey** [comment]
If you are running 2.7.5 then you will see expired entries 3 days before they expire upon unlocking your database. This can be configured in the application settings.

**Comment by Vinking-Yang** [comment]
Okay. Thanks
