### ISSUE TITLE
Split up keepassxc.ini into 2 files for secrets configuration and general configuration

### ISSUE THREAD

**Issue by fire833** [keepassxreboot/keepassxc#9709]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Add an additional configuration/secrets file that is used for storing secret/sensitive values.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

`keepassxc.ini` could remain the same, and largely contain the same key-values for now.
`keepassxc-secrets.ini` could be created/stored in the same directory with specifically the `Keeshare.Own` key stored within. Both of these configuration files could be merged with each other at runtime, where both files support the same keys (for API compatibility), but keys could be moved over to `keepassxc-secrets.ini` that the user considers secret and doesn't wish to be within their main config file.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I would like to place my keepassxc configuration under version control/in a dotfiles repo, but I really don't want to version control sensitive data like my Keeshare private key, and any other sensitive values that may get added over time.

**Comment by droidmonkey** [comment]
KeeShare private key is worthless, doesn't do anything. It is also going to be completely eliminated in 2.8.0. No secrets are stored in ini files.

**Comment by fire833** [comment]
Alrighty, cool
