### ISSUE TITLE
Text input fields does not delete lines on Cmd+Backspace

### ISSUE THREAD

**Issue by JacksonChen666** [keepassxreboot/keepassxc#9710]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Text input fields does not delete *lines* on Cmd+Backspace.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Change focus to a text field (e.g. search bar)
2. Type some random alphanumeric characters
3. Type some random symbols
4. Repeat steps 2 and 3 a few times
5. Press Command+Backspace (not Delete (on internal keyboard: Fn+Backspace))

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Full lines are deleted.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Most text input fields: Words are deleted.

Some text input fields: Nothing happens.

Tags (in entry): 1 character gets deleted.

<details><summary>Fields that do not conform to macOS's behaviors (pretty much all of them, which is a lot)</summary>

- most input fields (deleting by word):
    - in entry creation/editing screen
        - entry section
            - title
            - username
            - URL
        - advanced section
            - attachment names
            - additional attribute name
        - icon section
            - favicon URL
        - auto type section
            - custom auto type sequence
            - window title (window associations)
            - "Use a specific sequence for this association" (window associations)
        - browser integration
            - additional URLs
    - main window screen
        - search
    - in settings screen
        - general settings
            - backup destination
        - SSH agent settings
            - SSH_AUTH_SOCK override
            - SSH_SK_PROVIDER override
        - browser integration
            - "custom proxy location" in advanced settings
        - KeeShare
            - "signer" in personal certificate
    - database settings (menu button) screen
        - general
            - database name
            - database description
            - default username
        - security
            - additional protection
                - key file
        - browser integration
            - stored keys
                - key
                - value
    - creating database screen
        - screen 1
            - database name
            - description
        - screen 3
            - key file
    - generate password screen
        - the password
        - passphrase settings
            - word separator
    - group creation/editing screen
        - entry
            - name
            - auto type sequence
        - icon
            - favicon URL
        - KeeShare
            - path
- some input fields (deleting nothing):
    - in entry creation/editing screen
        - entry section
            - notes
        - advanced section
            - attribute
    - group creation/editing screen
        - entry
            - description
- rarely any input fields (deleting 1 character):
    - entry creation/editing screen
        - entry
            - tags
- did not check:
    - importing (no test files)
    - exporting (no reason)

</details>

## Context
[NOTE]: # ( Give us any additional information you may have. )
macOS has different text deletion methods.

On macOS, Command+Backspace deletes full lines, while Alt+Backspace deletes words.

On Windows, it's not the same. However, it seems to function similarly to Windows.

macOS behaviors can be tested in TextEdit.app.

> \[NOTE\]:  ( Paste debug info from Help → About here )

(isn't it "KeePassXC" > "About KeePassXC" > "Debug Info" in macOS? anyways uh)

KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.8
Debugging mode is disabled.

Operating system: macOS 13.5
CPU architecture: arm64
Kernel: darwin 22.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Please head over to https://bugreports.qt.io and file this with Qt. We don't control the behavior of text input fields, except for the tags field which is entirely custom.
