### ISSUE TITLE
Clipboard doesn't clear on Fedora Linux 38 (Workstation Edition)

### ISSUE THREAD

**Issue by smalltheif** [keepassxreboot/keepassxc#9712]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The clipboard doesn't get cleared after the time designated in the KeePassXC GUI.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set "Clear clipboard after" to 10 sec
2. Copy an entry, wait 10 seconds
3. Paste, the content can still be pasted.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The copied content should be absent from the clipboard, along with the clipboard history.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The entry and previous history is still present.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.4.7-200.fc38.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
What clipboard manager are you using? The history part of this rests with the manager respecting the sensitive flag we place on the data. Also see you are using Wayland. Wayland does not let you set the clipboard when the application is in the background. This isn't anything we can control.

Still interested in knowing which clipboard manager you are using, but there is nothing for us to fix at this time.

**Comment by smalltheif** [comment]
I'm using [Pano](https://extensions.gnome.org/extension/5278/pano/) as clipboard manager but this issue is present even with it disabled, which a little bit more distressing.

I will explain how I discovered this issue, it will add some context.
After having installed Pano, configured it to send a notification each time I copy something and to exclude any text copied from KeePassXC, I log into various services and seldom I get a notifcation indicating a password from KeePassXC has been added to the manager. This doesn't happen everytime and I didn't identify the pattern. However it raised my concerns and I've investigated. First I tought it was the non-functionning in Wayland "Drop to background" option from the "Hide window when copying to clipboard" feature causing problem, yet the issue persisted. Therefore I completely disabled Pano from the Extensions menu but it didn't change anything, the last entry copied in KeePassXc is still in my clipboard.

If I'm understanding correctly, KeePassXC can't clear the clipboard from the background because of Wayland and the entry being added to Pano following that is a Pano issue.
I presume the Wayland issue has already been reported because it's a serious one, if not where could I fill a bug report for it ?

**Comment by droidmonkey** [comment]
Report it to Gnome (in your case), Wayland is a protocol that Gnome implemented. If you were using KDE you would report it to them.

**Comment by ldroege** [comment]
As this issue cannot be fixed within the keepassxc project, please provide a workaround instead.

There are at least [two types of clipboards](https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt): PRIMARY and CLIPBOARD.

At least on my system (Debian bookworm with GNOME/Wayland), keepassxc can safely clean the PRIMARY clipboard, even from the background. It cannot clear the CLIPBOARD from the background, though.

If there was a new hotkey to copy only to the PRIMARY clipboard, then users could safely use this new hotkey and avoid CTRL-C and the unsafe CLIPBOARD.

If you go one step further, you could disable CTRL-C by default and raise a warning when CTRL-C is hit, that points the user a new option in the preferences. This new option (disabled by default) in the preferences may be turned on to enable CTRL-C and the CLIPBOARD, with a safety warning next to it.

You may say, this is a feature request, not and issue, and I am wrong here. If this is the case, I apologize. I just don't feel like security belongs to the wish list.

**Comment by michaelk83** [comment]
Reading the linked document, PRIMARY has a completely different purpose than CLIPBOARD. It is meant to hold the current text selection. It's much more dynamic and passive than CLIPBOARD, which is intended for active copy-paste. Only CLIPBOARD has (or mimics) cross-platform behavior.

On top of that, there are various desktop-specific clipboard managers, which have their own behavior.

As for workarounds, there are several available:
- Use the browser extension for web passwords and Secret Service integration for desktop applications, bypassing the clipboard (and AutoType) entirely.
- Use XWayland and `QT_QPA_PLATFORM=xcb` to bypass at least some of the Wayland restrictions (such as for AutoType).
- Use a clipboard manager that respects the sensitive data flag, and thus avoids putting the passwords in its history.
- If that doesn't answer your use case, and you still insist on using the clipboard, remember to clear it manually after pasting the password.

edit: You could also submit a feature request to your favorite clipboard manager to respect the [`x-kde-passwordManagerHint` flag](https://github.com/keepassxreboot/keepassxc/blob/1919c23c097fd5f3e64ae6488aaaabd502db6afb/src/gui/Clipboard.cpp#L59C34), by avoiding saving sensitive data to its history. But this should be standardized at XDG for non-KDE desktops. You could also ask the clipboard manager to implement automatic clearing of sensitive data on their end. That would avoid the background app issue.
