### ISSUE TITLE
KeepassXC has corrupted my password file.

### ISSUE THREAD

**Issue by Welved** [keepassxreboot/keepassxc#9713]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlocking my database
2. It gives a mismatch error

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open my database like usual

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It gives me a mismach error.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have very important information stored on my password file. I can access a known good file on my phone, but I am unable to  open it on my PC. How do I fix this?!?!

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by Welved** [comment]
I am running Ubuntu 22.04. I am very anxious as to the state of my passwords and important information.

**Comment by Welved** [comment]
Holy shit... apparently all I had to do was update my ubuntu and it fixed KeepassXC. I legit almost saved over my password database, I nearly corrupted my password file. OMG. Please fix! No one needs this scare everytime their Ubuntu instance is out of date... Just popup a error saying that your OS version is out of date or something.... fuck...

**Comment by Welved** [comment]
Never mind. this error is still happening, even though I have inputted all my credentials correctly. It lets me in sometimes and other times it errors out.

**Comment by zachdecook** [comment]
I have had (what I think is) this issue before, using KeePassXC 2.6.6 on Pop!_OS 22.04 LTS.

What usually fixes it is if I just copy my password file to a different location, and then open the copy, it will work. (not really sure about it).

**Comment by Welved** [comment]
This is the first time it has ever happened to me... this error is now a very often occurrence. My heart skips a beat every time.

**Comment by droidmonkey** [comment]
If you are getting the error often then that means (most likely) your RAM is going bad. We have seen this before, especially if you set a high decryption time.

**Comment by Welved** [comment]
I just performed a 'sudo memtester 100M 1' It returned no issues.

**Comment by Welved** [comment]
> I have had (what I think is) this issue before, using KeePassXC 2.6.6 on Pop!_OS 22.04 LTS.
> 
> What usually fixes it is if I just copy my password file to a different location, and then open the copy, it will work. (not really sure about it).

Yea I've tried to copy my database file on to my Ubuntu's document directory and open it from there, the error HMAC is still showing.

**Comment by droidmonkey** [comment]
You should really try a different computer entirely or a mobile device to rule out your hardware. Also, if you have unicode or diactric characters in your master password, then you will need to type it in with the password visible. This is a Qt bug.

**Comment by Welved** [comment]
Yea, I can open my password file just fine on my phone via Keepass2Android. Is there really solutions that you could possibly provide? What is this Qt bug and how can I resolve it?

I've tried to open my password file via Keepass2, but... the plugin for the challenge response is non-existent.

**Comment by Welved** [comment]
Having to go to a completely different device is not a valid solution.

**Comment by droidmonkey** [comment]
Ok good to know you are using yubikey. Are you selecting the correct slot?

**Comment by Welved** [comment]
I am not having any issues with Keepass2Android. What issue I am having is with KeepassXC on Ubuntu 22.04. No matter what I do, the error HMAC shows up. I am very sure I inputed my master password and selected slot 2 for challege-response correctly.

**Comment by zachdecook** [comment]
@Welved `sudo memtester 100M 1` is only going to test 100M of your ram (which is probably close to 1% of your total ram).

I ran [Memtest86+](https://memtest.org/) over all 16 gigs of my ram (in bad ram mode), and it found a bad chunk (basically from `0x9f9c0000` to `0x9f9cffff`). (So if only 64KiB out of 16 GB was bad, you'd have to get lucky to detect it when only testing 100MB)

**Comment by Welved** [comment]
Ah... I contacted my laptop manufacturer of this issue... How do I resolve this?

sudo memtester 16000M 1
memtester version 4.5.1 (64-bit)
Copyright (C) 2001-2020 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 4096
pagesizemask is 0xfffffffffffff000
want 16000MB (16777216000 bytes)
got  16000MB (16777216000 bytes), trying mlock ...locked.
Loop 1/1:
  Stuck Address       : testing   3FAILURE: possible bad address line at offset 0x37a608c0.
Skipping to next test...
  Random Value        : ok
  Compare XOR         : ok
  Compare SUB         : ok
  Compare MUL         : ok
FAILURE: 0x4000000001 != 0x00000001 at offset 0x2ba808c0.
FAILURE: 0x4000000001 != 0x00000001 at offset 0x44a888c0.
  Compare DIV         :   Compare OR          : ok
  Compare AND         : ok
FAILURE: 0x3bb5614204649577 != 0x3bb5610204649577 at offset 0x2ba808c0.
  Sequential Increment:   Solid Bits          : testing   1FAILURE: 0x4000000000 != 0x00000000 at offset 0x2ba808c0.
  Block Sequential    : testing   0FAILURE: 0x4000000000 != 0x00000000 at offset 0x2ba808c0.
FAILURE: 0x4000000000 != 0x00000000 at offset 0x3b2608c0.
  Checkerboard        : testing   1FAILURE: 0xaaaaaabaaaaaaaaa != 0xaaaaaaaaaaaaaaaa at offset 0x29aa3900.
  Bit Spread          : testing   0FAILURE: 0x4000000005 != 0x00000005 at offset 0x2ba808c0.
FAILURE: 0x4000000005 != 0x00000005 at offset 0x396408c0.
  Bit Flip            : testing   1FAILURE: 0x4000000001 != 0x00000001 at offset 0x382a08c0.
FAILURE: 0x4000000001 != 0x00000001 at offset 0x3d2408c0.
  Walking Ones        : testing 125^C

**Comment by Welved** [comment]
Then can someone explain, how am I accessing my passwords when I dip into my backup and never again on the current copy?

**Comment by droidmonkey** [comment]
Luck. Sometimes you hit the bad RAM sometimes you don't. And/or you are saving the database and that saves a corrupted copy because of your RAM. 

Your only option is to replace your RAM. If you are overclocking then you need to stop doing that as well.

**Comment by Welved** [comment]
So, from what I understand. Either my RAM is broken or my decryption time is too damn high? How do I reduce my encryption/decryption time?

**Comment by Welved** [comment]
Nevermind. I just went ahead and exported via CVS and imported it, reducing my encryption to 3.

**Comment by droidmonkey** [comment]
1 second is more than enough, fwiw. You can change it from the database menu -> database security

**Comment by Welved** [comment]
Welp, reducing my encrypting didn't work. I am getting a 'Failed to read database' now.

**Comment by droidmonkey** [comment]
That would indicate a hard drive or file access issue.

**Comment by JohnLGalt** [comment]
> Ah... I contacted my laptop manufacturer of this issue... How do I resolve this?
> 


See all those `FAILURE` items in your report?

It's not a matter of either the RAM being bad  **or** your decryption settings are too high. 

You RAM **_does_** have issues. This is not something that will only affect KeePassXC, but any program that tries to make use of the bad areas.

You _really_ need to replace your RAM. If the computer is under warranty, the manufacturer can help. If not, you need to find other avenues to get it fixed.

But it needs replacing ASAP.

**Comment by Welved** [comment]
Yea I just ordered two sets of RAM from crucial, just incase. Is it normal for RAM to only last for 2 years?

**Comment by JohnLGalt** [comment]
Not in my experience. I've built my own desktop for decades, though, so I get to choose high quality components. And other than dummy overclocking I don't really OC anything.

In a laptop, though, as with pre-built systems, it depends upon what the OEM used for components, but that is only one of many factors.

**Comment by Dakhaasje** [comment]
godver. what is the use of a password database when it becomes unusable when it locks up !?
Used the damn thing for a month, when after a reboot after ubuntu update (yes, the first reboot in a month), the database becomes corrupt. I usually do that myself, not some program I have to trust with my passwords!!!!!(etc!)
I suppose there is no way to reconstruct a corrupt database? 
(I remember it used to be possible when I made a datawarehouse for Carglass, some 20 years ago. I cannot imagine ppl reinvented the way databases are constructed)
