### ISSUE TITLE
Cloned keys should be linked to their parent.

### ISSUE THREAD

**Issue by ventsyv** [keepassxreboot/keepassxc#9714]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add the ability to jump from a cloned entry to its parent.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Sometimes you have a password that can be used to login into multiple sites, for example, an LDAP password used for jira, conflunce, email, etc. 
To be able to auto-fill the password into multiple URLs, I've been cloning the main entry and changing the URL. This works well because the cloned entries ref the main one and if you have to change the password, you only have to change it for the parent.

However, if you have multiple "parent" entries, each with multiple "clones" it can get confusing which is the parent of which.

Say you try to login into your email and get a notification that you need to change your password because it's about to expire. You go to the email entry to find out it's a clone. Now you have to figure out which is its parent so you can change the password.
It would be nice be nice to be able to right click have "Go to parent' option.

**Comment by droidmonkey** [comment]
This is a duplicate request.

**Comment by ventsyv** [comment]
> This is a duplicate request.

I could've missed it, but I did search before I posted this.
Mind linking the duplicate request? I would like to keep an eye on this.

**Comment by droidmonkey** [comment]
#4449

Took me a while to find it as well, I properly tagged it now
