### ISSUE TITLE
VMware Remote Console

### ISSUE THREAD

**Issue by cdwebb0** [keepassxreboot/keepassxc#9715]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeepassXC does not recognize “VMware Remote Console” window. 

The default window title is “VM Name - VMware Remote Console”.

I’ve set up a Window Association using “* - VMware Remote Console” and a specific sequence of “{MODE=VIRTUAL}{USERNAME}{TAB}{PASSWORD}{ENTER}”.  

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open VMware Remote Console Window
2. Create the above mentioned configuration
3. CTRL + SHIFT + V to paste credentials hoping to use the window associated specific sequence which includes {MODE=VIRTUAL}. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Open VMware Remote Console Window, CTRL + SHIFT + V to paste credentials hoping to use the window associated specific sequence which includes {MODE=VIRTUAL}. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

KeepassXC sends “bbn n*” into the username field which is not part of the username saved. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: ?
Windowing System: ?

**Comment by droidmonkey** [comment]
Window title association is ONLY valid for global Auto-Type, not Ctrl + Shift + V (entry level) autotype. Setup the global Auto-Type shortcut in application settings. Also recommend reading the user guide for more information.
