### ISSUE TITLE
UI to handle EoL of hardware keys

### ISSUE THREAD

**Issue by Cqoicebordel** [keepassxreboot/keepassxc#9716]
## Summary
Hardware keys are awesome and can be used in more and more sites.  
But hardware never last forever. And sometimes you have to handle a dying HW key. That day, you need a list of sites you used the key on, to be able to prepare the migration/deletion of the soon to be retired HW key.
You can see an example of this on https://www.ctrl.blog/entry/security-key-decommission.html

What I'm proposing is an easy UI to store the fact that a key has been used on a particular site, like a checkbox in the first tab of an entry screen. Could be also potentially a textfield to store the name of the key if necessary.  
Also, a menu entry (or a new column in the main view) would be welcome to list the currents sites where a key was registered by the user.

I'm aware that it can already be done with tags, or with additional attributes.  
But I'd argue that ease of use is important. And in this particular case, it's also important to remind the user that they have to take note of that particular information. So an easy UI to store and display that info is a must.  
It'll also help promote the general use of hardware keys. This one is just a bonus though :)

**Comment by droidmonkey** [comment]
Use tags. One could argue we need a UI for everything, but that is not helpful and will lead to an overly complex program. We already have way too much complexity.

**Comment by Cqoicebordel** [comment]
Except that for this one, _nobody_ knows they have to keep a list.

And honestly, adding a checkbox and an _optional_ column, I don't really see the complexity here.  
It has been done for TOTP.

Oh and _I_ know how to do it, as I said. My preoccupation wasn't myself.
