### ISSUE TITLE
KeepassXC-Browser - No logins found for URL when a database entry exists

### ISSUE THREAD

**Issue by mgrandi** [keepassxreboot/keepassxc#9719]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I have a entry for the URL `https://idp.pima.edu` in my database, where the URL entry has the string `https://idp.pima.edu` (and in the extended info like KP2A_URL_1 or anything)
 
I go to `mypima.pima.edu` and it redirects to `https://idp.pima.edu/idp/profile/cas/login?execution=e2s1`

clicking the keepass button on the password field shows "no logins found"

![image](https://github.com/keepassxreboot/keepassxc/assets/802786/658fd211-c2b7-4b21-b2ad-7deb979a4a89)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  go to `mypima.pima.edu`
2.  click the keepassxc button in the password manager
3. observe `no logins found`

## Expected Behavior

it should have a login for `https://idp.pima.edu` and allow me to auto fill it

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it shows "no logins found" for `https://idp.pima.edu`

## Context
[NOTE]: # ( Give us any additional information you may have. )

Browser: Firefox (nightly, 116.0.1 (64-bit))
KeepassXC-Browser version: 1.8.7

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Worked perfectly for me. Make sure you are not blocking the entry from being seen by the browser extension. This could be a setting in your group structure or the entry itself. You could also have rejected the entry and remembered that... edit the entry, go to properties, then remove the custom data.

**Comment by mgrandi** [comment]
Hmm, i just checked all of that and I dont have any entries in the additional properties field for that entry, and then I checked the group settings for the 2 groups (and the root group) and "hide from browser extension" is set to inherit (disable)

As another test, i downloaded the extension for edge and it works perfectly for me in edge, so it seems to be an issue with firefox or something. Is there a way to debug this further on my side to see why firefox is not getting results back but edge is?

**Comment by droidmonkey** [comment]
The browser should be irrelevant since Firefox is sending the proper web address and keepassxc is responding. Do you have multiple databases open? The current active tab is important unless you enable search in all open databases.

**Comment by mgrandi** [comment]
I removed the keepassXC browser stored key for firefox and had it reconnect to the database and after that, it started working as expected

i still feel there is a bug somewhere with it getting into a bad state , but since i can't reproduce it at the moment, this bug can (remain) closed. I'll reopen a new one if i can figure out how to debug this if this happens again in the future
