### ISSUE TITLE
KeePassxc Reboot for RHEL 7/Centos 7

### ISSUE THREAD

**Issue by cobrakoral** [keepassxreboot/keepassxc#972]
Today it is impossible to build keepasxreboot on enterprise linux 7, because libgcrypt version is 1.5.3 and seems like at least version 1.6 is required to build keepassx.
## Expected Behavior

Would it be possible to backport some of the features to make keepassxreboot have a wider audience ?
If it is agreed on a version to be frozen and have its features backported to a specific branch maybe, I would be willing to help on that.

## Current Behavior

[ 26%] Building CXX object src/CMakeFiles/keepassx_core.dir/crypto/Crypto.cpp.o
Projects/keepassxc/src/crypto/Crypto.cpp: In static member function ‘static bool Crypto::checkAlgorithms()’:
Projects/keepassxc/src/crypto/Crypto.cpp:93:31: error: ‘GCRY_CIPHER_SALSA20’ was not declared in this scope
     if (gcry_cipher_algo_info(GCRY_CIPHER_SALSA20, GCRYCTL_TEST_ALGO, nullptr, nullptr) != 0) {
                               ^
make[2]: *** [src/CMakeFiles/keepassx_core.dir/crypto/Crypto.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/keepassx_core.dir/all] Error 2
make: *** [all] Error 2

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Your best bet would be to use a later version of libgcrypt by manually downloading it or building your own. Other than that you can try to comment out the salsa20 code.

**Comment by cobrakoral** [comment]
Newer libgcrypt has many dependencies, I tried to download manually an rpm and installing but the dependencies were too much that I gave up. I haven't tried to compile libgcrypt from source either, but I intend to actually build a package for keepassxc, I see that you already have another project for packaging, but centos dir is empty.

Commenting salsa20 code might work, but I am looking for a more elegant solution and a way to share it with the community. Maybe we could create a lib file for libgcrypt 1.5.3 missing features and if the environment is el7 we include this file in the build process as well, so like this it will seamlessly integrate and cause no issues on the project.

If we make this effort to support centos 7/rhel7 we can attract much more users to the project.

**Comment by droidmonkey** [comment]
The better solution would be to alter the cmake script with a build flag that removes the requirements for later versions of libgcrypt.

**Comment by hifi** [comment]
@cobrakoral This unofficial copr by @bugzy has builds for EL7: https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/

It also has a compatible libgcrypt package that installs side-by-side with the system one. The source is at https://github.com/hifi/libgcrypt-c7

You can rebuild the SRPMS if you feel inclined.

**Comment by cobrakoral** [comment]
@hifi thanks a lot!
I am using it and I restored my old backup and it just worked.
Nice work backporting libgcrypt !

Thank you guys.
