### ISSUE TITLE
YubiKey5 support on FreeBSD not working

### ISSUE THREAD

**Issue by greyghost509** [keepassxreboot/keepassxc#9720]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
YubiKey5 not detected by keepassxc 2.7.5 under FreeBSD 13.2.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. install FreeBSD 13.2 from freshly downloaded image
2. install keepassxc 2.7.5
3. install yubikey-manager and set up required services to make sure yubikey works
4. try to use yubikey with keepassxc

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The expected behaviour would be that keepassxc detects the yubikey and lets me use it.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The yubikey is not detected, selection stays greyed out even on rescan, the key is not usable.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The yubikey is detected by ykman (from py39-yubikey-manager-4.0.9_4 installed via pkg), appears to work just fine with it. Only keepassxc fails to detect it. There are no visible error messages or configuration options from keepassxc, so there is not much I can do to get more context information on this. A web search returned no further useful information on this setup.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: FreeBSD 13.2-RELEASE-p1
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
You either need to:

-  install some form of udev rules to allow users to access the yubikey raw.
- you didn't actually configure your yubikey to have challenge response in a slot

If you did properly configure challenge response then run keepassxc with sudo. If you see the key then you need udev rules.

**Comment by greyghost509** [comment]
The yubikey works fine under Linux with keepassxc, so it's setup should be correct.
Under FreeBSD, I just checked again that both hidraw and uhid devices and the hkbd device belong to the correct user (ykman works fine under that user). Is there anything else that needs to be accessible?

**Comment by greyghost509** [comment]
After reviewing the heap of devices created by the yubikey once more, I found that I also need to chown 5 devices belonging to the key under /dev/usb/x.y.z, then keepassxc finally detects the key.
Thank you very much for leading me into the right direction here!

**Comment by droidmonkey** [comment]
Awesome!

**Comment by greyghost509** [comment]
For the record: FreeBSD even offers a package named "u2f-devd" containing the automation rules needed for devd. After installing it and adding my user to the new "u2f" group created by it, all access rights are set up properly without manual intervention when plugging in the key.

**Comment by greyghost509** [comment]
Debugging issues like this would be much easier if keepassxc let me know which devices/paths it tried (without success) when looking for the key. Is that possible?

**Comment by droidmonkey** [comment]
We wouldn't even see the key at all in this circumstance, I believe. We could show when a key is found but no slots are configured, but that wasn't the problem here.

**Comment by greyghost509** [comment]
But how do you search for the yubikey in the first place? I cannot configure any device path for this, so there must be some kind of automatic discovery.

**Comment by droidmonkey** [comment]
The code that actually searches starts here https://github.com/keepassxreboot/keepassxc/blob/develop/src/thirdparty/ykcore/ykcore_libusb-1.0.c#L176

So yah we could get at least a list of usb devices that match the vid/pid of a yubikey and complain of we can't actually open it for communication

**Comment by greyghost509** [comment]
I guess that information would be a great help for debugging issues with access rights.

**Comment by droidmonkey** [comment]
#9728

**Comment by greyghost509** [comment]
Great, thanks!
