### ISSUE TITLE
Repeat password field missing both when password is visible and NOT visible

### ISSUE THREAD

**Issue by jmevel** [keepassxreboot/keepassxc#9721]
## Overview
I don't really know when this issue first appeared, at least it is present in version 2.7.5.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new entry
2. Leave the password field hidden

## Expected Behavior
The `Repeat Password` field is shown under the `Password` field

## Actual Behavior
The `Repeat Password` field is missing

![image](https://github.com/keepassxreboot/keepassxc/assets/2572775/f531714c-53ab-490f-ba15-ea9dcbb6e2ad)

## Context
I'm pretty sure this feature was existing in previous version of KeePassXC. It's been a few years I'm using this application and I never noticed this was missing before.

Moreover in the application settings, under the `Security` section there's an option `Require password repeat when it is visible`.
Even when this option is checked, no `Repeat Password` field is shown both when the password is visible and hidden.
It seems this option does nothing actually.

![image](https://github.com/keepassxreboot/keepassxc/assets/2572775/d90ae644-a433-4743-aae7-593f16e60f43)

KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Operating System: Windows & Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This was removed 3 years ago. The password repeat option is only when setting up your database password.

**Comment by michaelk83** [comment]
Maybe change the text to "Require database password repeat when it is visible"?

**Comment by droidmonkey** [comment]
I'm just going to remove it

**Comment by jmevel** [comment]
Yeah this option is confusing if it's only for the database master password. Better removing it all together indeed.

Could I know what's the reason the feature to have a Repeat Password field was removed?

I know one of the main point of using KeePass(XC) is to generate random passwords but sometimes there're use cases when this isn't ideal (though I acknowledge those cases are quite rare).
Still I think it would be great if we could activate such feature in the settings.

**Comment by michaelk83** [comment]
Just noticed that it was "repeat when it is visible", which really doesn't make a lot of sense.

@jmevel This has been discussed at length before. Try searching the closed issues.

**Comment by jmevel** [comment]
> Just noticed that it was "repeat when it is visible", which really doesn't make a lot of sense.
> 
> @jmevel This has been discussed at length before. Try searching the closed issues.

Wow I didn't even notice it as well. Indeed it didn't make sense at all, anyway the PR to remove this option is already done.

Ok I'll search it. Thanks for your answer
