### ISSUE TITLE
Auto-type always locks the database, and there is no setting to control that

### ISSUE THREAD

**Issue by sjvudp** [keepassxreboot/keepassxc#9723]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I realized that using auto-type via Ctrl+Shift+V always locks the database.
Also searching the settings I found no setting to control that.
So I'm asking to add such setting (like "Lock database after auto-type")
I'm using version 2.7.5 of openSUSE Leap 15.5.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Using KeePassXC at home in my own room, locking the database after every auto-type is just overkill.

**Comment by JohnLGalt** [comment]
I just tried it and it all it did was minimize the window here. Granted, I'm on Windows, though.

In `Settings --> Security` do you have the setting `Lock database after minimizing the window` enabled? I don't.

**Comment by droidmonkey** [comment]
You must have the above setting enabled. We don't lock the database after Auto-Type unless you have the setting "Relock locked databases after Auto-Type" enabled.

**Comment by sjvudp** [comment]
Could it be that it was the default setting for some older version?
