### ISSUE TITLE
Allow opening links in any installed browser

### ISSUE THREAD

**Issue by Br0kenSilos** [keepassxreboot/keepassxc#9725]
## Summary
First, thank you creating and maintaining KeePassXC. I love it. I am not  developer. Just an average user. I really like the security key integration as so far it has worked flawlessly for me. But I do have a feature request. Its a feature in KeePass that I make heavy use of. And that is the ability to choose which browser to open a particular link with at the time of click. In KeePass this is done by right-clicking on an entry and then mousing over the URL(s) option. You are then presented with context menu of all the available browsers installed on the machine (including private mode).

## Examples
![example](https://github.com/keepassxreboot/keepassxc/assets/137440866/19ebaec7-05df-4c27-a551-53faaa024478)

## Context
I work in IT and have been a KeePass user for a long time. I learned to make heavy use of this feature for a couple of reasons. I like to open certain things in certain browsers generally for segmentation of tasks. I also frequently will use the private windows depending on what I m doing for security reasons. Or sometimes I just dont want the browser to remember what I am doing so next time I get a "clean" presentation of a site. This feature also makes it easy for me to test sites from various browser to see which one works better. I realize that this feature may not seem useful to a lot of people but I use it at least a few times a day. Perhaps there is another way to go about this in KeePassXC, but if so, I haven't found it. The way it is implemented in KeePass makes it so user friendly. But KeePass lacks the built in support for security keys. So I find myself torn.

**Comment by JohnLGalt** [comment]
I'm the same regarding being in IT and segmenting tasks. I use an app for Windows called Browser Chooser 2, which let's me segment all browser-related tasks, including those coming from other apps - Outlook, GMail, SMS, etc.

Though it has not been updated in quite a while, it works perfectly fine in Windows 11, and in settings has an option to add the executable to the system default programs list, so you can make it the default for all web browsing tasks with one tiny exception.

Maybe that could help? It works perfectly fine with KeePassXC, when called to load a URL from your database.

It would also then help keep the KPXC code from getting larger, to boot.

**Comment by droidmonkey** [comment]
Yes, that is the answer. We have rejected this request in the past because it involves not only code bloat buy also menu item bloat. This is best handled outside keepassxc. As it stands now we don't even know what browser you use at all, we rely on the system default browser.

**Comment by Br0kenSilos** [comment]
I appreciate the responses. I get that it would add a bunch of extra code to add the feature. I don't know if I would classify that as "bloat" per se. But then again, I'm not a developer and have no idea what it would take to add the feature. I guess from my non-dev perspective, I assumed that since kpxc is a fork of keepass that some of the underlying code was still in there or could be brought in from current keepass or at least used as a reference. Of course I also understand that is a lot of work and man hours and for a feature that is not heavily requested. So I can certainly respect your reasoning for not wanting to add it.

I looked at some of the browser choosers available and I am still in the process of looking around. But that also adds to system bloat. And  of the ones I have looked at so far, development is not current and that worries me from a security perspective somewhat.

Regardless, I appreciate the work that has been put into KeePassXC. Its a great program.

**Comment by JohnLGalt** [comment]
It's a fork of **KeePassX**. It uses the same principles and adheres to the some of the constraints of the original KeePass, but it not forked _directly_ from KeePass itself.

As for Browser Chooser 2 (I've tried a few others I've found / that have been suggested to me), I stick with it because it is also a semi-portable program, meaning I don't have to install jack.

It's literally a 4.8 MB executable, and the 31 byte (yes, byte, not KB or larger) .DLL to run it, and a 30 KB XML file in %APPDATA%\BrowserChooser2 (which, naturally, will vary with your settings).

**Comment by droidmonkey** [comment]
The biggest hassle with a browser chooser is finding all the browsers on your system OR having a UI in settings to define the custom browsers. This would need to be cross platform capable as well. It's not impossible but it's not something we want to spend time on. We do have an open request to allow defining 1 custom browser and a PR to support opening in private mode.

**Comment by Br0kenSilos** [comment]
I stand corrected about the fork. My apologies. I'm looking for a clean d/l of Browser Chooser now to give that a try.

**Comment by JohnLGalt** [comment]
BitBucket repo:  https://bitbucket.org/gmyx/browserchooser2/wiki/Home

Be sure to get the download under the Current release under the image, dated 2018 (told ya it hasn't been updated in a while 😄
