### ISSUE TITLE
Get rid of 'save on exit'.

### ISSUE THREAD

**Issue by Welved** [keepassxreboot/keepassxc#9729]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Remove 'save on exit/lock', it feels really redundant. It is also very annoying getting a prompt every time to either close without saving or saving.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Just get rid of 'save on exit/lock'.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The feature is very redudant when we have 'save on every change'. I would love to choose any other option, but... I can't choose it without enabling save on every chage, which... enables all the options.

**Comment by phoerious** [comment]
I don't know what kind of prompt you are talking about, but saving on exit is already disabled when you have save after every change enabled.

**Comment by phoerious** [comment]
Saving on exit is part of saving after every change. If there are changes, they will be saved before you close the application. If there are no changes, nothing will happen.

**Comment by Welved** [comment]
I would love to be able to just enable 'Automatically save after every change' without triggering the other options to be enabled.

**Comment by Welved** [comment]
How do I stop getting this prompt? https://imgur.com/a/sZRqNQm

**Comment by phoerious** [comment]
You will get this prompt if there are unsaved changes and you are trying to exit before autosave has completed.

**Comment by Welved** [comment]
Yea, I can't do that without having to disable 'Automatically save after every change', which I need. I straight up can't diable it because, the very action of enabling 'Automatically save after every change' enables all the others.

**Comment by phoerious** [comment]
I have no idea what you are talking about. Autosave will save immediately. Save on exit will autosave on exit only. One option does more than the other, so having autosave on, but autosave on exit off makes no sense. Having everything off will prompt all the time, you probably don't want that. If either option is on and you get the prompt, then something is preventing the save from completing.

**Comment by Welved** [comment]
I would love to only enable 'Save on every change', but... I legitemtly can not. https://vimeo.com/853756727?share=copy

How do I go about only enabling 'Save on every change'?

**Comment by phoerious** [comment]
Again, why? It makes no sense. Auto save is a superset of auto save on lock.

**Comment by Welved** [comment]
I just want to be able to do the 'Save on every change' and not enable all the other options.

**Comment by phoerious** [comment]
The prompt has nothing to do with the setting.

**Comment by Welved** [comment]
Then what exactly triggers this prompt? How do I disable it or have it default to YES?

**Comment by phoerious** [comment]
As I said. Something changed your database and you are trying to close it before it's fully saved. I cannot tell you what or why that is without more information.

**Comment by droidmonkey** [comment]
Are you getting an error messaging saying that saving failed?

**Comment by Welved** [comment]
yea, that is because i don't have my yubikey in to let it save.

**Comment by droidmonkey** [comment]
Well that is your problem then. You made a change but cannot save. We absolutely will not allow bypassing saving on close (this is really what you are asking for). That is a huge data loss problem.

**Comment by phoerious** [comment]
If you get the prompt, it means there are unsaved changes that would be lost if you just closed the application. We don't prompt you just for the fun of it. If you are using a YubiKey, saving those changes require the key to be plugged in. If it's not, KeePassXC will defer the save to later and you will see the save prompt.
