### ISSUE TITLE
1 click less?

### ISSUE THREAD

**Issue by EmilEmilchen** [keepassxreboot/keepassxc#9730]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Old workflow: clicking the symbol of the locked KeePassXC database in the login field, then clicking "Unlock Database" and using for example fingerpint unlock or face recognition to unlock the database.
improved workflow: only having to click on the symbol in the login field and having the windows dialog for face recognition open immediately.

I do realize that this might seem like a joke but its actually been really annoying to me and I even thought about trying to fix it on my own but I'm propably to incompetent.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
#9697 and #9030
