### ISSUE TITLE
Duplicate KPXC unlock window 

### ISSUE THREAD

**Issue by thxpian** [keepassxreboot/keepassxc#9735]
## Steps to Reproduce
1. Lock your database.
2. Go to a website and click on the KPXC icon in an input field to unlock the database.

## Expected Behavior
- The unlock request should bring the KPXC window to the front (same as if you clicked on the KPXC icon) asking you to enter your password etc.
- There should be only 1 KPXC window asking you to unlock your database.

## Actual Behavior
- KPXC displays a small second / duplicate and identical KPXC unlock window on top of the normal KPXC window (see screenshot).

KeePassXC - 2.7.5
Revision: 9d0537b

Operating System: macOS 13.5
Browser: latest Firefox 116

![kpxc](https://github.com/keepassxreboot/keepassxc/assets/141489205/97c59397-1697-4f74-9b62-de09b6de446f)

**Comment by thxpian** [comment]
Could you add a link to the duplicate please? Haven't been abled to find it on my own. Thanks.

**Comment by droidmonkey** [comment]
It's well discussed, this is a macOS limitation that the main window of an application must be visible to show a dialog.

**Comment by michaelk83** [comment]
Maybe don't bother with the dialog on MacOS, if you have to show the main window anyway?

**Comment by droidmonkey** [comment]
That is going to be the fix, yes
