### ISSUE TITLE
Add ability to match multiple URLs for the same website.

### ISSUE THREAD

**Issue by kickTiger** [keepassxreboot/keepassxc#9736]
### Summary
Add ability to match multiple URLs for the same website.

### Examples
Some websites have multiple domains that all serve the same content. For example:

example.org
www.example.com
example.net
Currently if one of these is blocked, the others will not be.

### Context
Many popular websites have multiple domains that lead to the same content. When one of the domains is blocked, it renders the tool unusable for those sites.

Adding support for matching multiple URLs to the same block would significantly improve the user experience and flexibility of the tool. It would prevent sites from becoming unblocked simply by using an alternate domain.

This is an important quality-of-life improvement that would make the tool more robust and effective at blocking distracting websites. The ability to specify multiple URLs to block for the same site would be simple to implement but provide immense value.

**Comment by phoerious** [comment]
You can add additional URLs in the entry's browser integration settings.

**Comment by leifadev** [comment]
I cannot find this feature, I have checked by browser integrations on KeePassXC 2.7.6 and my KeePassXC-Browser settings and cannot find any setting, especially with a keyword like "multiple" or even "URL (field)"

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_usage
