### ISSUE TITLE
Consider using XDG_STATE_HOME instead of cache folder for local config 

### ISSUE THREAD

**Issue by haarp** [keepassxreboot/keepassxc#9738]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Transient data such as last active database, GUI size/settings are stored in `~/.cache/keepassxc/kepassxc.ini`. This means this data is prone to being deleted (as cache directories might be cleared during logout/reboot or reside on volatile storage such as ramdisks to begin with. These settings are not caches, they should go into `~/.local/share/` or `~/.local/state/` (or rather XDG_DATA_HOME) instead.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KXC
2. Observe file created under `~/.cache/`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Use `~/.local` instead

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Uses `~/.cache`

## Context
[NOTE]: # ( Give us any additional information you may have. )
XDG_DATA_HOME is part of the [Freedesktop basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.10
Debugging mode is disabled.

Operating system: Gentoo Linux
CPU architecture: x86_64
Kernel: linux 6.1.41-gentoo-HH

Enabled extensions:
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

Thanks!

**Comment by phoerious** [comment]
.local/share is explicitly not the location we want to store these things in. XDG_STATE_HOME is new and might be worth considering. At the time we implemented this, .local/cache was the closest to a semi-persistent location. XDG_CACHE_HOME is *not* a temporary folder, so IMHO any distribution that deletes it automatically on reboot or puts the contents in a tmpfs does it wrong.

**Comment by haarp** [comment]
You're right, XDG_CACHE_HOME is not explicitely described as being volatile, but it is considered "non-essential". There *shouldn't* be any detrimental effects to deleting it, other than increased delays during app startup and runtime ;) Doing so requires me to e.g. setup my KXC window again tho, which shouldn't be the case.

XDG_STATE_HOME is probably the better place for it tho.

**Comment by jNullj** [comment]
I gave the spec a quick look, i think `XDG_STATE_HOME` is a better fit then `XDG_CACHE_HOME`, if you read in the spec it seems to be similar to what you described:

> The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
> 
> actions history (logs, history, recently used files, …)
> 
> current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

Should we consider XDG_CONFIG_HOME? as this looks much like a config file.

**Comment by haarp** [comment]
> Should we consider XDG_CONFIG_HOME? as this looks much like a config file.

There is a separate keepassxc.ini already in XDG_CONFIG_HOME. I assumed there was a reason for this separation.

**Comment by phoerious** [comment]
The INI under ~/.local/cache contains non-essential machine-specific state information, such as the window geometry. On Windows, this is under %LocalAppData%. Linux, so far, didn't have a location for it, but now apparently does.

**Comment by haarp** [comment]
Excellent, thanks a lot!
