### ISSUE TITLE
KeePassXC takes a long time to start

### ISSUE THREAD

**Issue by markrian** [keepassxreboot/keepassxc#974]
Starting KeePassXC takes 5 to 10 seconds to start the first time.

## Expected Behavior
I would expect KeePassXC to start almost instantly, even the first time.

## Current Behavior
The first time KeePassXC is started, it takes 5 to 10 seconds to start. After the first time, its loads almost instantly.

## Possible Solution
Perhaps a Qt thing? No doubt you're aware of this, but just in case: https://wiki.qt.io/Performance_Tip_Startup_Time

## Steps to Reproduce (for bugs)
1. Restart machine (so nothing is cached in RAM)
2. Start KeePassXC
3. See that it takes a long time to start.

## Context
I just wanna use KeePassXC as quickly as possible :)

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
I really only notice startup delays with the snap version on Ubuntu. A review of the high cost functions (perfmon) run at startup wouldn't be a bad thing though.

**Comment by tremby** [comment]
It's every time for me, not just the first time.

While it's starting that area of the screen is also not redrawn, and sometimes I'm not sure if something has gone wrong.

I'm on Ubuntu, and I'm not using the snap, I'm using the AppImage.

**Comment by tremby** [comment]
I'm now using the official PPA and the problem remains.

**Comment by droidmonkey** [comment]
This issue was corrected in #1205.
