### ISSUE TITLE
KeePassXC crashes when attempting to open group

### ISSUE THREAD

**Issue by methsmonker42zero** [keepassxreboot/keepassxc#9745]
When I open a specific group in my database, keepassxc freezes and crashes.
Notably, there is an entry in that group that contains a large amount of data in the Notes field.

Steps to reproduce:
Not sure, because that large entry used to work without problems, and i cannot access the group without KeepassXC crashing, so not sure how reliably it can be reproduced.

**Comment by droidmonkey** [comment]
This is either (or both) #9429 or #7158. Recommend downgrading keepassxc to v2.7.4 or below and removing anything in those notes that look like `{text here}`
