### ISSUE TITLE
Horizontal scrollbar appears while dragging multiple entries

### ISSUE THREAD

**Issue by feelingnothing** [keepassxreboot/keepassxc#9746]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Small visual bug with entry dragging, after testing it always appears, the size of the titles, be the title in the selection preview on the cursor or hidden, does not make scrollbar disappear.

## Current behaviour
![image](https://github.com/keepassxreboot/keepassxc/assets/47575622/df1c299e-ec7e-4a97-a86a-435de86dfc87)
(had to make the photo on my phone, neither lightshot or Win + Shift + S captured the cursor)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
OS: Windows 22H2

**Comment by Matthaiks** [comment]
Even with only one entry:
![KPXC](https://github.com/keepassxreboot/keepassxc/assets/3577122/f3596a77-60c2-4fea-8f75-b607e69c2fa5)

**Comment by droidmonkey** [comment]
Looks like you are on 1080p or lower resolution, correct?

**Comment by Matthaiks** [comment]
Yes, 1080p.

**Comment by droidmonkey** [comment]
Dang forgot to put in two lines of code to prevent that from happening, fix is posted. Shakes fist at Qt.
