### ISSUE TITLE
Able to bypass 2FA on KeepassXC ver 2.7.5

### ISSUE THREAD

**Issue by GrayVi02** [keepassxreboot/keepassxc#9749]
## Overview
Even with 'Enable database quick unlock (Touch ID / Windows Hello)' users are still able to bypass entering their Windows Hello Pin after entering their database Password. My org was under the assumption that after enabling this setting, User MUST enter both the database PW AND then their Hello PIN in order to gain access to the database. However, after entering the database PW, the Window for Hello Pin pops up, but user can simply hit 'Cancel' and still gain access to the database. 

## Steps to Reproduce
1. Make Sure "Enable database quick unlock (Touch ID / Windows Hello)' is enabled within keepassxc
2. Launch KeepassXC
3. Enter Database Password
4. Press Cancel at Windows Hello prompt
5. Continue to database

## Expected Behavior
Users should have to enter BOTH database password and Windows Hello Pin to gain access to the database. 

## Actual Behavior
User selects 'Cancel' during prompt for Windows Hello pin and are still able to access the database. 

## Context
We work with a lot of sensitive data and need to have 2FA working for PW solution. 

[NOTE]: #
KeePassXC - 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by phoerious** [comment]
The hello prompt is not 2FA. It's quick unlock. Pressing cancel is not a bypass, it just means you didn't enable quick unlock.

Also see: https://keepassxc.org/docs/#faq-yubikey-2fa

**Comment by GrayVi02** [comment]
Thanks for actually answering the question. Do you know if 2FA is possible with KeepassXC? Thanks

**Comment by phoerious** [comment]
Please read the FAQ I linked.
