### ISSUE TITLE
Autotype fails and triggers lockup

### ISSUE THREAD

**Issue by TempSpas** [keepassxreboot/keepassxc#975]
I had recently restarted my computer and opened my web browser to a site I needed to login to. I opened KeePassXC, used the search feature to find the the site, and used the shortcut Command-V to trigger autotype.  KeePassXC immediately became unresponsive; no UI elements were clickable, no keys did anything. I force-quit KeePassXC and opened it again, and the same problem occurred. After force-quitting and reopening it again, I clicked the entry a few times to make sure it was selected (as opposed to previous attempts using the keyboard only), and then using Command-V triggered autotype correctly.

## Expected Behavior

Autotype should have activated and the program shouldn't have frozen.

## Steps to Reproduce (for bugs)

This is the first and only time I've had this issue so far. If I find more precise steps to reproduce it consistently, I'll add them.

## Debug Info

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12.6)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
So same entry every time it crashes and no others?

**Comment by TempSpas** [comment]
It locked up on the same entry both times, and it hasn't done that for that entry in the past. (Even now I can access and interact with the entry without issue). Normally when an app crashes, if you command-click its icon in the dock, it will say "App is not responding" or something to that effect. For the record, it did not say that here; that menu was unchanged. It just became impossible to interact with any element of the UI, via keyboard or mouse.

**Comment by TheZ3ro** [comment]
Does KeePassXC crash with other entries as well? Can you screenshot the Autotype section of the failing entry?

**Comment by TempSpas** [comment]
Hasn't yet. Here's the screenshot:

<img width="1106" alt="screen shot 2017-09-21 at 9 18 56 am" src="https://user-images.githubusercontent.com/3801275/30746944-90389b3a-9f79-11e7-85d9-098da20afa09.png">

(There's no special reason why it would require a custom sequence, I just had it set to that before I set a group default).

**Comment by TempSpas** [comment]
I got this issue today and found a way to semi-reliably reproduce what's happening. I've attached a console log in hopes that it will help. The steps I made were as follows:

1. I had navigated to a page that required a login and made sure I was focused on the username field.
2. I hit command-space to open spotlight, and used that to open KeePassXC.
3. Once in KeePassXC, I searched for and found the corresponding website entry.
4. I pressed command-V to autotype.
5. Immediately after doing this, the Root folder on the sidebar collapsed and focus left the entry I had previously navigated to. At this point, however, I was still able to click and interact with the program.
6. I navigated once more (using either the mouse or arrow keys) to the corresponding entry and hit command-V to try the autotype again.
7. At this point, the lockup as described in my original post occurred. KeePassXC became completely unresponsive, and I had to force quit it.

I experimented a little and found that this only happened when I had to go through the intervening step of opening KeePassXC with spotlight. If it was already open, and I switched from my browser to the program with command-tab, auto-type would perform as expected.

The log:

[kplog.txt](https://github.com/keepassxreboot/keepassxc/files/1675297/kplog.txt)

**Comment by TempSpas** [comment]
Here is the debug info for my previous post:

Debug Info
------------

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This is likely happening because spotlight was the last used program and keepassxc is trying to find and type into that (now hidden) program. I bet the fix would be to add a timeout on the program search and/or detect if the program is visible before trying to type.

**Comment by TheZ3ro** [comment]
If you open KeePassXC from spotlight, the webpage loses the focus when you type in spotlight.

Currently Keepassxc fail silently if the window changes during autotype.
The hang isn't very normal, but I've fixed some autotype race-condition in #1390

**Comment by droidmonkey** [comment]
Closing this as I don't think it is an issue anymore.
