### ISSUE TITLE
Unlock/Main Window content enlarged after Win10 standby/hibernate

### ISSUE THREAD

**Issue by Igittihubby** [keepassxreboot/keepassxc#9750]
## Overview
If KeepassXC 2.7.5 is running, and after Win10 (22H2) restarts from standby and/or hibernate, the KeepassXC unlock screen does not fit into the given window. Only parts of the content are visible, the content is enlarged. Clicking the content with the mouse does not work anymore. Control by keyboard is still operational. 
When unlocking the screen (by navigating to the Unlock button by keyboard), the screen unlocks as usual. But the content of the database window is enlarged as well and only partly visible. Same effect. This effect cannot be reverted. The only workaround is to exit KeepassXC and restart it. After that the look and feel and the behavior is "normal" again.
See attached screenshots (as photo, screenshot is not allowed).

Expected unlock window:
![keepassxc_2 7 5_expected_unlock](https://github.com/keepassxreboot/keepassxc/assets/142495934/64d9bbf5-ed51-46fd-b784-45fc0c4a6fc6)

Erroneous unlock window, content clipped at bottom and right:
![keepassxc_2 7 5_error_unlock](https://github.com/keepassxreboot/keepassxc/assets/142495934/de9ac76b-08c2-4c45-8b71-b89febeda12f)

Expected main window (empty test data base!):
![keepassxc_2 7 5_expected_main](https://github.com/keepassxreboot/keepassxc/assets/142495934/34fce95e-9eae-4cfc-b463-8e03c9127318)

Erroneous main window (empty test data base!), content clipped at bottom and right:
![keepassxc_2 7 5_error_main](https://github.com/keepassxreboot/keepassxc/assets/142495934/5194f0f9-0f8f-4b75-8a95-ccd6e3b0f28e)

## Steps to Reproduce
Bug is not reliably reproducible. It happens often but not always after executing the following steps
1. Open KeepassXC
2. PC is actively forced to standby and/or hibernate by power button, or is going into one of these states automatically after timeout.
3. PC is started again via power button (to screen lock screen).
4. PC is unlocked.
5. Running KeepassXC window is opened again from system tray.

## Expected Behavior
No window content resizing, all visible, mouse click response working.

## Actual Behavior
Window content is enlarged, only partly visible. Mouse click to enlarged buttons/menus not working. No reaction as well by clicking to the estimated expected positions.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
This would be a Qt problem and not a KeePassXC problem. We do recommend updating to 2.7.6 as it has a newer Qt version. If you have two monitors with different resolutions then this can happen. Usually this can be fixed if you enable the tray icon, then hide to tray, then restore.

**Comment by JohnLGalt** [comment]
Another fix for me has been to drag from one monitor to another when qt display bugs like this manifest.

_Of course, this does assume using multiple monitors, and would be useless for those with a single monitor / screen._

**Comment by phoerious** [comment]
Monitors with different pixel densities are rather broken on Windows. Even Windows Explorer has problems like that.

**Comment by JohnLGalt** [comment]
True. I ran into that myself.

But this Qt bug manifests with multiple or single monitors, and regardless of varying or identical densities with multiple monitors, and particularly badly when using high DPI monitors, like my dual 4K monitors.

**Comment by Igittihubby** [comment]
> Another fix for me has been to drag from one monitor to another when qt display bugs like this manifest.

Thx! This "fix" works fine.
