### ISSUE TITLE
Database won't lock in Windows 11

### ISSUE THREAD

**Issue by ArtBrass** [keepassxreboot/keepassxc#9752]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # I walked away from my Windows 11 OS while editing in text in the "Advanced" > "Additional attributes" section of an entry. I didn't finish editing and didn't save. I came back and logged into my computer and there was a prompt to discard or cancel the editing. I clicked cancel and I had access to the database without entering my credentials to access the database. I believe the prompt prevented the database from locking and all I needed to do was log into my desktop to have access again.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new "additional attributes" entry
2. Label it
3. begin adding text into the field to the right
4. Lock the Windows account (Windows Key + L)
5. Log back into Windows
6. The prompt to Discard or Cancel should appear
7. Click Cancel to have access to everything again (Database doesn't lock)

## Expected Behavior
[NOTE]: # I expect the database to lock when I lock my session or if the system times out (screen saver activates).

## Actual Behavior
[NOTE]: # The Database is available to any user who logs in and clicks on "Cancel".

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Version: 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Duplicate #721
