### ISSUE TITLE
Tray/notification icon blurry after screen/dpi change

### ISSUE THREAD

**Issue by ygoe** [keepassxreboot/keepassxc#9756]
## Overview
The tray icon or notification icon (the small one next to the clock in the taskbar) gets all blurry after the screen settings have changed. My laptop has an internal screen that runs at 125% or 150% and an external screen that runs at 100% scaling. I only use one at a time so there's no multi-dpi scenario. But Windows gets confused every time I set it to sleep or resume or attach or unplug the screen when changing places.

## Steps to Reproduce
1. Make sure you see the tray icon
2. Change dpi scaling or switch to another screen with different dpi

## Expected Behavior
The icon should remain as clear as when starting the application at 100%.

![grafik](https://github.com/keepassxreboot/keepassxc/assets/868315/f38ae553-9057-4da6-9d1e-83bfef1f8212)

## Actual Behavior
The icon is blurry.

![2023-08-18 14_07_11-](https://github.com/keepassxreboot/keepassxc/assets/868315/18c4237f-0dff-4c46-bbdb-c86a9e22e159)

## Context
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.9
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by phoerious** [comment]
This is either a Windows or a Qt bug, which we can do nothing about. But anyway, upgrade to 2.7.6, we improved the icon a bit.

**Comment by ygoe** [comment]
It certainly has nothing to with Windows. KeePassXC's icon is the only one out of 14 icons that shows this behaviour. Can't say anything about Qt though. (As a programmer, I don't like it anyway.)

Maybe other applications just handle this and update their icon? Or it needs to be provided in more sizes? I'll try after upgrading.

**Comment by droidmonkey** [comment]
Qt handles the tray icon 100%, so if it is broken due to screen size change then Qt is not handling it and should.

**Comment by ygoe** [comment]
It's a little bit better in 2.7.6 but still not normal.

Unlocking/locking the database updates the icon and refreshes it again for the current screen resolution.

Other applications have no issues here, so KeePassXC has a defect here. I don't care what technological base it uses, the problem is definitely solvable. And it shouldn't be hard.

Suggestion: React to the global Windows message for screen resolution changes ([WM_DISPLAYCHANGE](https://learn.microsoft.com/en-us/windows/win32/gdi/wm-displaychange)) and refresh the tray icon in its current state, i.e. don't change it but just reset it just like when locking/unlocking the database. That will resolve the issue and make the icon readable at all times.

**Comment by phoerious** [comment]
> And it shouldn't be hard.

That's where you are wrong. This issue should be reported to Qt, not to KeePassXC.

**Comment by ygoe** [comment]
Thanks for the pointer. I found a [resolved issue there](https://bugreports.qt.io/browse/QTBUG-108641). You might want to upgrade the outdated Qt 5.15 in KeePassXC to a current version then.

**Comment by phoerious** [comment]
5.15 is the latest 5.x release. Qt6 is a whole new major version.
