### ISSUE TITLE
As in previous versions, attachments and URL's still cannot open from AppImage!!!!

### ISSUE THREAD

**Issue by nohing** [keepassxreboot/keepassxc#9758]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
It's incredible!!!
It's absurd!!!
It's shameful!!!
We have reached the sixth version, 2.7.6, yet also in this new version (KeePassXC 2.7.6) it's not possible to open attachments and URL's from the AppImage.
 It works only with 2.7.1. Why is that ???
 When will this bug be fixed ???
Will we Linux users be forced to use 2.7.1 forever ???

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. When I click on URLs, they don't work.
2. When I click on attachments, they don't work.
3. 
4. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Attachments and URLs should work.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Attachments and URLs don't work!!!

## Context
[NOTE]: # ( Give us any additional information you may have. )
They have stopped working since the version 2.7.3.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: AppImage

[NOTE]: # ( Pick choices based on your environment )
Operating System: /Linux/
Desktop Env: /Cinnamon
Windowing System: X11/Wayland

**Comment by michaelk83** [comment]
First, this is tracked in #8721. There's no need to open a duplicate issue.
2nd, this appears to be an upstream issue, so possibly not much the devs can do about it.
3rd, have a look at the number of open issues (hint: 601). This is a project run by volunteers in their spare time. You can't realistically expect them to attend to every open issue. They have to pick and choose. If you want something fixed more quickly, you're welcome to submit a pull request.
Finally, there are several other distribution channels for Linux if you can't live without this one particular feature.

**Comment by nohing** [comment]
I do not want something 

> First, this is tracked in #8721. There's no need to open a duplicate issue. 2nd, this appears to be an upstream issue, so possibly not much the devs can do about it. 3rd, have a look at the number of open issues (hint: 601). This is a project run by volunteers in their spare time. You can't realistically expect them to attend to every open issue. They have to pick and choose. If you want something fixed more quickly, you're welcome to submit a pull request. Finally, there are several other distribution channels for Linux if you can't live without this one particular feature.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


I do not want something fixed more quickly, I want someone to be interested in this issue, but everyone seems to not be interested in this issue.
I will continue to publish a request until this issue is solved. 
With each new release, until this issue is solved, I will continue to publish a request.

**Comment by varjolintu** [comment]
> I do not want something fixed more quickly, I want someone to be interested in this issue, but everyone seems to not be interested in this issue. I will continue to publish a request until this issue is solved. With each new release, until this issue is solved, I will continue to publish a request.

Intentional spam is not going to help. Just a small hint.

**Comment by droidmonkey** [comment]
We do not like your spam. No sir we do not like it spam you am. We do not like it on github, we do not like it with a snub. We do not like it spam you am, no thank you.

In all seriousness, nothing is preventing you from staying on 2.7.1 if it works for you. Also nothing is preventing you from using flatpak or ppa. Well maybe nothing but your stubbornness.

Honestly I am in favor of not offering an appimage at all, it's a legacy deployment technology and doesn't offer automatic updates. @phoerious

**Comment by phoerious** [comment]
AppImage is still the only way to offer some sort of portable Linux build. I use it every now and then, though not on my main work machines. I think Flatpak and Snap need to sort out their beef and a bunch of issues before we can finally retire AppImages.

**Comment by droidmonkey** [comment]
https://github.com/OpenChemistry/avogadroapp/pull/318/files

This was fixed by someone else by directly calling xdg-open instead of the qt call

**Comment by phoerious** [comment]
We know when our app was compiled as an appimage. Perhaps we could substitute all file open calls with xdg-open <cmd>.
