### ISSUE TITLE
Installing TOTP entries via camera, screenshot, or file?

### ISSUE THREAD

**Issue by tromlet** [keepassxreboot/keepassxc#9759]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

It would be really nice if we could add TOTP entries to KeePassXC not just manually, but by using a webcam on the machine to take a picture of a QRcode in the real world, or by directing KeePassXC to an image file of a QRcode, or by selecting an area of the screen with the QRcode. As this is how most users interact with QRcodes in the first place, it would be useful to have KeePassXC follow this behavior.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Most people do not get the details of the TOTP in a manner in which they can enter it in manually into KeePassXC - they get it via QRcode. Allowing KeePassXC to follow this behavior, as well as extend it further for the circumstances one might encounter in a desktop scenario, would be super useful.

**Comment by droidmonkey** [comment]
#4825
