### ISSUE TITLE
Using already open KeePassXC (GUI) with keepassxc-cli

### ISSUE THREAD

**Issue by tohn** [keepassxreboot/keepassxc#976]
## Expected Behavior
Is it possible to use an already open instance of the GUI for the CLI version?

My idea was that one can open a database in the GUI and then connect to the database via CLI **without** unlocking the database first (so no password is needed).
The main advantage is now that the passwords can be used in scripts etc.

Is this even possible (maybe apart from security concerns)?

**Comment by droidmonkey** [comment]
No because they are completely separate processes.

**Comment by lydell** [comment]
Is this completely impossible to do, or just something that does not work with the current architecture? I'm thinking about the ssh and gpg agents, which "remembers" your password for a while.

**Comment by TheZ3ro** [comment]
@lydell if you have a background running daemon, with some socket communication you can do something (like the keepassxc-browser extension) but it's too much hassle and will impact heavily on the program codebase of both -core and -cli.

IMHO, keep it simple and lightweight it's the way to go :wink:

**Comment by phoerious** [comment]
That being said, you can actually use the keepassxc-browser API (or KeePassHTTP for 2.2.4) to connect to a running KeePassXC proces. You only need to write a client script that handles the protocol.
