### ISSUE TITLE
Keychain's password with deadkey accents/characters only works when showing its content 

### ISSUE THREAD

**Issue by rcapp** [keepassxreboot/keepassxc#9760]
Related: 
https://github.com/keepassxreboot/keepassxc/issues/2452
https://github.com/keepassxreboot/keepassxc/issues/428

## Overview
When using passwords with deadkeys/accents (i.e.:  é, ã, ô) the password text input does not register  the deadkey, only computing the vowel: `é` will become `e`, `ã` will become `à`  and so on. This wasn't happening on previous versions I have used, so it could be a Qt bug or something. 

Since above topics are years old, I thought it was worth reporting. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new database. 
2. Set its password to use any letter that can receive a deadkey. Save it and lock it.
3. Try to open it with the above password. 

EDIT:
4. Now, click on the eye icon on the password field and try again.

## Expected Behavior

They database will be opened.

## Actual Behavior

It does not open, prompting a password error message. If you re-enter the password and click on the eye icon, everything will work as expected.

## Context

KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.3

Extensions:
- Auto-typing
- Browser integration
- Agent SSH
- KeeShare
- YubiKey
- Secret Service integration

Cryptography library:
- Botan 2.12.1

Operating System: Ubuntu 22.04.2 LTS
CPU: x86_64
Kernel: linux 6.2.0-26-generic

Desktop Env:  KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a qt bug

**Comment by rcapp** [comment]
> 

Thank you for the reply! I will see if I can run a previous version without this issue.

Cheers!

**Comment by HoffmannP** [comment]
@droidmonkey as the [qt bug](https://github.com/keepassxreboot/keepassxc/issues/2452) is marked as "Won't fix" since end of 2022, is there a plan for an alternative solution?

PS: There is a work around: `QT_IM_MODULE=xim keepassxc`

**Comment by droidmonkey** [comment]
Qt6 maybe?

**Comment by Elaborendum** [comment]
> @droidmonkey as the [qt bug](https://github.com/keepassxreboot/keepassxc/issues/2452) is marked as "Won't fix" since end of 2022, is there a plan for an alternative solution?
> 
> PS: There is a work around: `QT_IM_MODULE=xim keepassxc`

I'm a bit new to this, where do we put this in?
