### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Foro38** [keepassxreboot/keepassxc#9761]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The last time translations were updated was over a year ago, since then I and many other people have added more translations which aren't reflected in the stable release of the program because the translations in use currently are over a year old. As a result, the program will appear incomplete for many people using non-English languages

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Update to 2.7.6 to have the latest translations. We pull the latest translations for every release for all languages that are more than 60% complete.
