### ISSUE TITLE
Password numbering

### ISSUE THREAD

**Issue by utenus** [keepassxreboot/keepassxc#9762]
## Summary
Sometimes some sites, after setting a password when logging in, tell you to enter only specific characters from the password, e.g. 2nd digit password, 3rd digit, 6th digit and 9th digit.
It would be useful if you could enable password splitting in KeePassXC to better see what is in the 2nd place and what is in the 6th.

## Examples
https://postimg.cc/0z0Z0fkt

**Comment by michaelk83** [comment]
Use AutoType with `{PICKCHARS}`

![](https://user-images.githubusercontent.com/2809491/103098110-9d0b9800-45d7-11eb-8f80-e28229122075.png)

**Comment by MS-89** [comment]
Hey, Ubuntu 24 user. I'm having issues to runt pickchars window on google chrome. Any help?

**Comment by droidmonkey** [comment]
Please read our user guide: https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type
