### ISSUE TITLE
does not open url

### ISSUE THREAD

**Issue by nlime** [keepassxreboot/keepassxc#9763]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # Tell me why do you release versions of AppImages that do not open URL?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # normal operation

## Actual Behavior
[NOTE]: # it doesn't open on any version url

## Context
[NOTE]: # 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4 2.7.5 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by michaelk83** [comment]
> Tell me why do you release versions of AppImages that do not open URL?

https://github.com/keepassxreboot/keepassxc/issues/9758#issuecomment-1684192515
