### ISSUE TITLE
Empty password generation form in current nightly

### ISSUE THREAD

**Issue by rextheleopard** [keepassxreboot/keepassxc#9764]
In current nightly password generation form just empty.

![keepass](https://github.com/keepassxreboot/keepassxc/assets/26321641/34bd7309-0abf-4216-a564-4e3547a989c4)

testing env:
Windows x64 10.0.25391.1000
KeepassXC 2.8.0-snapshot 6f14bec

**Comment by droidmonkey** [comment]
This will be fixed by #9743
