### ISSUE TITLE
Incorrect tab navigation ordering in application security settings

### ISSUE THREAD

**Issue by nelson2tm** [keepassxreboot/keepassxc#9765]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The tab ordering of checkboxes in some settings pages is incorrect.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open settings and open the security section.
2. Use tab to try to navigate to _Enable database quick unlock (Touch ID / Windows Hello)_.
3. The checkbox below, _Lock databases when session is locked or lid is closed_, will be reached first.
4. After reaching the last checkbox, the selection will jump up again and finally select the first checkbox.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The checkboxes should be navigated over from top to bottom.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The checkboxes are selected in an incorrect order, making it difficult to select these out of order items.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
DOH, good catch
