### ISSUE TITLE
SECURITY BUG: Copying Database removes Hardware Key Challenge-Response requirement to open database.

### ISSUE THREAD

**Issue by dull-kiwi** [keepassxreboot/keepassxc#9766]
## Overview
Copying Database removes Hardware Key Challenge-Response requirement to open database.

## Steps to Reproduce
1. Set up Database with (yubikey) hardware challenge response key, keyfile, and master password (all three).
2. Lock Database
3. Reopen database and confirm Hardware Key is required.
4. From Linux bash 'cp database ./database_backup'
5. Open database in keepassXC 
6. Log in with Master-Password and Key (no challenge-response hardware key)

## Expected Behavior
Unlocking the database should fail.

## Actual Behavior
Database unlocks without hardware key.

## Context
I was trying to copy my database and set up a second hw key for the backup since I can't add two keys for one account **(please add this feature, if we lose our main hw key we can be locked out of our entire life).** Upon doing this I noticed the copy of the database doesn't need a hw key at all anymore. I expected to have to unlock it with my 1st hw key and then remove that key and add the backup key.

KeePassXC - 2.7.5
Revision: 

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 22.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
What you describe is literally impossible. That means you must have opened a copy of the database _before_ you added challenge response. Or you are actually using your hardware key and misread the ui or something. 

Either way this is totally impossible if you did the steps correctly that you wrote here. 

As for backup hw keys. Make two duplicate keys. When you setup the first one save the secret seed and use that to setup the second one.

Take a deep breath and try to replicate your steps and pay attention to your files. I guarantee you cannot replicate it.

**Comment by dull-kiwi** [comment]
Appologies. I was burning the midnight oil and as you suspected yes I was doing something silly. I had a very similar dir with a copy of the database which was not yet secured with a yubikey and so that was the one I was duplicating. Thank you for the quick response, as I was concerned I found something big! (oops)

As far as the duplicate keys, correct me if I am wrong but those can only be setup when you initially setup your first yubikey challange response, yes? As in, I can't at a later point set up a duplicate becuase I no longer have the secret seed. The issue with that is for those of us who already have a yubikey setup with a number of other accounts would have to etheir buy a new set of keys or retroactively track down all the other accounts we have setup a challange response authentication method with, remove it, reconfigure the keys to be duplicate, and then re-setup all our other acounts again with the new challange-response. Of course, that is doable but not ideal, so being able to store two keys would be a nice feature (though as you point out not 100% necessary).

Anyway, thank you guys for your work. We appreciate it.

**Comment by droidmonkey** [comment]
> As in, I can't at a later point set up a duplicate becuase I no longer have the secret seed.

Correct

Yubikeys have two slots and I am not aware of many applications that use challenge response. Can you elaborate if possible?

**Comment by dull-kiwi** [comment]
Sure. I use it on multiple devices to log in such as my windows desktop / Linux desktop.  Also with a laptop. Then there are email services like google, proton, anonaddy, etc which can use it as well. I think amazon also supports it? I may be forgetting a few others that I use at least.

**Comment by droidmonkey** [comment]
Those use FIDO not challenge response, if I am not mistaken.
