### ISSUE TITLE
Wrong menu location in user alert

### ISSUE THREAD

**Issue by genseirin** [keepassxreboot/keepassxc#9767]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When trying to fetch a favicon and the settings are not enabled, you see
`Unable to fetch favicon.
You can enable the DuckDuckGo website icon service under Tools -> Settings -> Security`
On a Mac this location is not correct.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Make sure that "Use DuckDuckGo service to download website icons is disabled"
2. Edit an entry
3. Go to Icon tab
4. Click "Download favicon"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The user expects to find the menu at the indicated location.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The menu location is under „Preferences“.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating system: macOS 11.7
CPU architecture: arm64
Kernel: darwin 20.6.0

**Comment by droidmonkey** [comment]
It should just say "Application Settings -> Security"

**Comment by 8manz** [comment]
Do I have to edit the files in share/translations to change the message? If so, I assume I just change the sources since you would need someone more qualified for proper translations or for someone else to take this on.

**Comment by droidmonkey** [comment]
Just the sources

**Comment by hsm2k3** [comment]
has this been fixed? Looks like #9783 didn't merge

**Comment by droidmonkey** [comment]
No the PR is still open...
