### ISSUE TITLE
The "Launch app on startup" button does not work as intended

### ISSUE THREAD

**Issue by K4LCIFER** [keepassxreboot/keepassxc#9769]
## Overview
The launch app on startup button, I would assume, should add the app to the autostart list, and should then autostart when the user logs in; however, it doesn't appear to do either of these things.

## Steps to Reproduce
1. Enable `Settings>Automatically launch KeePassXC at system startup`
2. Observe that the app is not added to the autostart list
3. Observe that the app does not autostart when the user logs in

## Expected Behavior
I would expect that the app gets added to the autostart list, and automatically starts when the user logs in.

## Actual Behavior
The app does not automatically start, and it is not added to the autostart list.

## Context
none

KeePassXC - 2.7.6
Revision: dd21def

Operating System: Arch Linux, Kernel v6.4.11-arch1-1
Desktop Env: KDE Plasma v5.27.7
Windowing System: Wayland

**Comment by droidmonkey** [comment]
How is keepassxc installed? Native, snap, flatpak, appimage?

**Comment by K4LCIFER** [comment]
> How is keepassxc installed? Native, snap, flatpak, appimage?

Flatpak

**Comment by droidmonkey** [comment]
#8668
