### ISSUE TITLE
PW Generator will not open from main interface

### ISSUE THREAD

**Issue by JohnLGalt** [keepassxreboot/keepassxc#9770]
## Overview
On Windows 11, using the last 5 portable snapshot builds (that is as far back as I've tested thus far), when at **the main screen** (IOW, **_NOT_** inside an entry), tapping on the PW generator button / using the menu item `Tools --> Password Generator` hides the entire UI, and nothing else shows as long as it is active.

Testing with stable 2.7.6 release, the PW Gen UI shows perfectly fine via the same methods.

Additionally, testing from _inside an entry_ works fine as well across all snapshot builds tested.

## Steps to Reproduce
1. Extract any of the last portable snapshot builds to a directory not in `\Program Files` (I use `E:\Programs` to store all my portable apps):

- build-233014/	2023-08-15 12:28 	- 	 
- build-232956/	2023-08-15 03:55 	- 	 
- build-232789/	2023-08-10 14:34 	- 	 
- build-232678/	2023-08-07 04:37 	- 	 
- build-232567/	2023-08-06 23:15 	- 	 

2. Open any database or create a new one.
3. Press the PW generator button / go to `Tools --> Password Generator` and enable it.

## Expected Behavior
I expect to see the password generator, as shown below from stable version 2.7.6:

<img width="602" alt="Screenshot 2023-08-20 195455" src="https://github.com/keepassxreboot/keepassxc/assets/7432512/0ee87634-77a0-4e37-b131-b9ee320d28b1">

## Actual Behavior
No PW generator, UI is blank as long as setting / button is active. UI returns when setting / button is deactivated.

<img width="602" alt="Screenshot 2023-08-20 194647" src="https://github.com/keepassxreboot/keepassxc/assets/7432512/4ddc1555-6014-4f42-b7ee-880540160f6e">

<img width="602" alt="Screenshot 2023-08-20 194652" src="https://github.com/keepassxreboot/keepassxc/assets/7432512/c194f5ec-cd27-45e2-a560-6a72a1d23841">

## Context
I use the snapshot releases daily (don't judge, I _like_ testing!), and I cannot recall the last time I actually tried to use the PW gen features when not inside an entry, so I don't know how long this may have been broken. The only reason I discovered it is that I wanted to generate a dummy (but strong) PW to use for my Personal VM logins, and that was going to be added as an Advanced attribute to an existing entry that already has another password associated with it, so I tried opening the UI from the Advanced tab, and it fails. I then exited the entry and tried again and it failed again. 

To verify it was not my settings, I have made 5 additional portable folders corresponding to the last 5 snapshot builds, and tested them with a new database as well as brand new settings - same behavior across the board.

<img width="231" alt="Screenshot 2023-08-20 200259" src="https://github.com/keepassxreboot/keepassxc/assets/7432512/3c81cbb9-8f82-4d81-ad60-98865f367d5a">

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 6f14bec

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro 22H2 build 22621.2134
~~Desktop Env: ~~
~~Windowing System: ~~

**Comment by droidmonkey** [comment]
#9743

**Comment by JohnLGalt** [comment]
@droidmonkey So this bug is related to that fix?

I thought it was not related (as I'm following that one pretty closely) because that conversation started last week, but build build-232567/ is from 2 weeks ago. I went back that far just to make sure I was beyond the scope of that fix.

**Comment by droidmonkey** [comment]
That PR fixes the bug, we reverted the change on the 2.7.x baseline so as not to break 2.7.6.

**Comment by JohnLGalt** [comment]
Gotcha. My bad.
