### ISSUE TITLE
KeeShare not syncing automatically after programatic changes to shared group

### ISSUE THREAD

**Issue by afg137** [keepassxreboot/keepassxc#9776]
## Overview
I have two databases, DB1 and DB2, and a shared group between them. If I open both DB1 and DB2 and add an item to the shared group in DB1 using the GUI, then DB2 automatically syncs this changed, as expected. However, if I add an item to the shared group **programatically** (using, for example, keepassxc-cli or [pykeepass](https://pypi.org/project/pykeepass/)), DB2 does not sync the new change automatically, even if if have both databases open in the GUI.

## Steps to Reproduce
1. Open DB1 and DB2 using the GUI. They have a shared group DB3 between them.
2. Use keepassxc-cli to add an item to DB1, using the command "keepassxc-cli add DB1.kdbx DB3/[item name]"

## Expected Behavior
Since both databases are open and are configured to automatically sync updates, the GUI should show the new item in both databases. At the minimum, I would expect to see both KDBX4 files modified.

## Actual Behavior
Confusingly, **neither** DB1 nor DB2 show the new item in the GUI. However, at least the database file DB1.kdbx grows in size, indicating the item got added, but **DB2.kdbx is not modified whatsoever**.

## Context
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.8
Debugging mode is disabled.

Operating system: macOS 12.4
CPU architecture: arm64
Kernel: darwin 21.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
The CLI does not support KeeShare. However in this case it looks like the gui doesn't detect the file changed.

**Comment by afg137** [comment]
I see. Is there a way to update shared groups programatically?

**Comment by afg137** [comment]
Following up on this. All I am interested in is for the second database to import the (programatically) modified items. That database will not edit the items, only import them, so I am not concerned with concurrency issues or merge conflicts. Is there a simple way to do this? For example, some simple HTTP request I can send using curl?

**Comment by afg137** [comment]
Can you at least clarify how KeeShare works under the hood? If the database is simply observing the container for changes, why would it not import the new items? That is, if I add an item via the CLI to the shared database, should this modification to the container not trigger an import into the database -- isn't this conceptually equivalent to adding this item manually through the GUI?

Or does KeeShare trigger some sort of request (HTTP?) when adding a new item through the GUI, which the CLI does not do?

**Comment by droidmonkey** [comment]
It just monitors the underlying file for changes to the file itself. When the database is first unlocked it should force a pull of the file and a merge.

**Comment by afg137** [comment]
Right. So if the database is unlocked, why would it not sync the changes made to the shared group, even if these are done through the CLI? I am not sure what "the CLI does not support KeeShare" even means -- if you can modify the file through the CLI, that should be sufficient to trigger an update from the database monitoring this file.

The way you describe it, KeeShare should be agnostic to *how* the file was modified, and just care that the file *was* modified. However, this does not seem to be the case, as programatic changes (through the CLI or PyKeePass) do not trigger a pull+merge. Can you please clarify what is happening? Seems like the GUI is doing something else when the shared file is modified.

Thanks for the help.

**Comment by droidmonkey** [comment]
I can't speak to your setup and file arrangement. Could be any number of reasons.

**Comment by afg137** [comment]
I do not think this is an issue with file arrangement. All files are local in my machine, so this issue is orthogonal to my directory structure. Further, KeeShare works as expected when modifying the container through the GUI, so it should behave the same when using the CLI; if my file arrangement is indeed an issue, then the GUI also should not work, but it does.

My setup is extremely simple; please see the reproduction steps above. More concretely, I have two databases (DB1 and DB2) that have a shared container (DB3) between them. All three files are in the same computer and in the same directory. I have DB1 and DB2 open in separate windows of the KeePassXC GUI. Then, I add an item to the shared container in DB2 through the CLI (or PyKeePass). The end result is that **neither DB1 nor DB2 show the new item in the GUI**. In addition, while DB1.kdbx4 increases in size, **DB2.kdbx4 remains unchanged**.

Can you list some of those "number of reasons" that could result in this problem? More importantly, do you see the same behavior on your end? I think this is an issue with KeeShare or the CLI itself, and not something on my end (hopefully I am wrong). It seems to me like KeeShare is not truly agnostic to the mechanism through which the container is modified (GUI or CLI), and that it does not just simply pull+merge whenever the container changes, as you claim. Can you clarify this?

Thanks.

**Comment by droidmonkey** [comment]
I cannot reproduce this at all. I made changes to a synced database using the CLI and the changes showed up immediately in the primary database in the GUI. The most likely explanation is that you are not actually modifying the correct database when you are using the CLI.

![2023-08-24_23-35-34](https://github.com/keepassxreboot/keepassxc/assets/2809491/c6e5eb5b-eeb5-4336-9b7d-59b36f3902f3)

**Comment by afg137** [comment]
I am doing the exact same steps as in your video. Just like you, I am modifying the shared container directly (demo_sync.kdbx in your example). However, my GUI is not syncing!

Further, when I **then** try to modify the shared container through the primary database using the GUI, I get an error saying that "Export to [path of container] failed (Existing file [path of container] is not writable)". I was able to modify the container through the GUI before attempting to modify through the CLI; this error starts appearing after I attempt to use the CLI. So, not only does the CLI not sync with the GUI, but it somehow breaks the container (?!).

(BTW, this error confirms I an indeed modifying the right database, so "you are not actually modifying the correct database when you are using the CLI" is not the source of the issue).

Could it be an issue with my application settings? Did you change any of these?

**Comment by afg137** [comment]
Can this issue be reopened in the meantime?

**Comment by droidmonkey** [comment]
I'm 100% certain this is something specific to your setup and you need to just clean up or reestablish your shares in the respective databases. Could it be that you ran the cli tool as root and locked out your user account for access?

**Comment by afg137** [comment]
To be clear, I am no longer claiming this is an issue with the CLI; after your experiments, I am also convinced this is an issue with my local setup.

Reestablishing the shares did not work (I have tried to do this _many_ times already). Indeed I think it is something regarding permissions/settings (either in the application itself or my machine more broadly), so I will keep investigating. Once I figure it out, I will update this ticket with an update.

Thank you for all the help (and for being so patient...)!

**Comment by afg137** [comment]
This is so strange... I downloaded KeePassXC on a different laptop (same OS), and the CLI+GUI works here?! Even though I am using the exact same files, which I ported over from one machine to the other....

Do you have any ideas as to why this could be happening? I know it could be infinitely many things; just wondering if you have a hunch. I am using the exact same files with the exact same application settings. I also tried deleting KeePassXC (and all associated files) on the faulty machine and re-installing it, which did not work.

**Comment by droidmonkey** [comment]
I am not too familiar with macOS security models for files, applications, etc. You can try eliminating some variables by not using network storage on the affected machine.
