### ISSUE TITLE
Automatic switch from light to dark MacOS interface does not work on Database open dialog

### ISSUE THREAD

**Issue by daniel-volz** [keepassxreboot/keepassxc#9777]
## Overview
If you remain in the login dialog when opening a database and the MacOS user interface changes from light to dark, then the background color in the login dialog does not change

## Steps to Reproduce
1 Open a database
2 Don't unlock the database / stay in the database login dialog
3 Let the system switch automatically from light to dark surface

## Expected Behavior
The login dialog should turn dark like the rest of the program area

## Actual Behavior
Parts of the surface remain white

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Operating System: macOS 
![Screenshot 21 08 2023 um 21 47 31 PM](https://github.com/keepassxreboot/keepassxc/assets/31667349/f79bbd8d-9b12-4c2d-bf38-b567d9713a42)

**Comment by varjolintu** [comment]
See: https://github.com/keepassxreboot/keepassxc/issues/7615

**Comment by droidmonkey** [comment]
You have classic theme set, change the theme to automatic to take advantage of our theming fixes. Otherwise you are at the mercy of raw Qt (which sucks on macOS).
