### ISSUE TITLE
Passphrase language support

### ISSUE THREAD

**Issue by GCamp6** [keepassxreboot/keepassxc#978]
Despite the possibility to choose different general language than English in KeepassXC settings, if I want to create a new passphrase only English words are proposed.
## Current Behavior
The default language is English, the passphrase suggested is composed by English words.
If I change the default language the passphrase is still formed by English words

## Expected Behavior
Changing the language should also change the relative dictionary for the word selection. In this way KeepassXC would provide a passphrase in the selected language. 
I suppose having passphrases in different languages for non English mother-language users would be much easier to remember/use.

## Possible Solution
a. Maybe it is necessary to synchronize the dictionary in some config files?
b. Adding a drop-down button nearby the passphrase icon for the selection of the preferred language if it differs from the default one (example: a non native English user working on a common PC with other users - the default language is English but for the passphrase can be "user-specific").

**Comment by TheZ3ro** [comment]
This is already possible. 
You have to place your desired wordlist file (you can download it) and place it in the KeePassXC data folder on your system (for example on linux it's `/usr/share/keepassxc/wordlists/`)

**Comment by GCamp6** [comment]
Super! Thanks for the tip, I did not know

**Comment by TheZ3ro** [comment]
Maybe in the next version I will add a button to the generator/in the settings to load custom worlist easily :wink:

**Comment by droidmonkey** [comment]
We need a task to remind us of all the documentation that needs to be written for these off center features.

**Comment by TheZ3ro** [comment]
There is #696

**Comment by TB1234** [comment]
Here is a large germand wordlist for free use: https://github.com/davidak/wortliste

**Comment by carlosm2** [comment]
I put here also a wordlist for the main indigenous language of mexico: nahuatl

https://github.com/carlosm2/lista-nahuatl/blob/main/nahuatl-lista.txt
