### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by daVe55w** [keepassxreboot/keepassxc#9781]
I upgraded from v 2.7.4 to v2.7.5 and after a few days the version number changed back to 2.7.4 and an upgrade window popped up. I upgraded again and the same thing repeatedly occurred. I just upgraded to v2.7.6 x64 and the same thing is occurring with KeePassXC showing version in About as v 2.7.4.

When I re-run the install file only Repair and Remove options are available. I have been running Repair each time.

What is causing this bug and what is the solution?

This has been occurring for several weeks, through at least 2 Windows 11 upgrades.
Running Windows 11 22H2 (OS Build 22621.2215)

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by phoerious** [comment]
We do not downgrade your installation, you probably just reinstalled 2.7.4 thinking it is actually 2.7.6.

**Comment by daVe55w** [comment]
No, I most definitely did not mistakenly reinstall 2.7.4. This has happened many times and each time I download and reinstall the latest version, only to have it go back to v2.7.4 after a few days. This just happened again after installing 2.7.6.

**Comment by phoerious** [comment]
This is 100% an error somewhere on your end. We don't even have an up or downgrade routine. Your specs dump also shows 2.7.4.

**Comment by droidmonkey** [comment]
You definitely have TWO installs, one is likely a portable install you did of 2.7.4 and created desktop or start menu shortcuts for that installation. You also need to possibly restart your system to complete the install of 2.7.6.

**Comment by JohnLGalt** [comment]
There is no repair / reinstall option for the portable mode, though.

@daVe55w verify that the link you're loading from points to the installed version, that will eliminate the possibility of loading a portable version.

Also, could it be some sort of system / security software reverting the installed version to the one it has been set to 'accept' (from user settings of some sort)?

**Comment by daVe55w** [comment]
It was a 2nd, portable install and the shortcut kept reverting to that location. It's fixed now. Thanks everyone.
