### ISSUE TITLE
Question : How to setup an internal keepassxc password server for multiple users ?

### ISSUE THREAD

**Issue by sebma** [keepassxreboot/keepassxc#9788]
Hi, my team connects to the same servers as I do.

We would like to share one keepassxc database for the members of that team with read and write access.

I was first thinking of a network share with read/write access to the database but I'm not sure it's the best solution.

Is there another solution ?

**Comment by droidmonkey** [comment]
Recommend using onedrive or similar technology. You can use a network drive but then you don't get the benefit of version history (unless you enable that) and conflict detection.

**Comment by sebma** [comment]
@droidmonkey Onedrive stores the files on the Internet, is there another versioning system (possibly opensource) that could store files in my network ?

**Comment by phoerious** [comment]
Use Nextcloud, or Syncthing, or plain Git if your users can work with it.

**Comment by michaelk83** [comment]
IIRC, git doesn't handle binary file versioning well (maybe good enough on the user-facing end, but poorly under the hood). But there are git extensions and similar tools for binary files.

**Comment by sebma** [comment]
Maybe [vaultwarden](https://github.com/dani-garcia/vaultwarden/wiki) or [passbolt](https://github.com/passbolt/passbolt_docker) ?
