### ISSUE TITLE
On Windows 10, the password of any entry is not copied

### ISSUE THREAD

**Issue by solisgb** [keepassxreboot/keepassxc#9790]
## Overview
On Windows 10, version 2.7.6 downloaded from portable apps. When I press the copy password button, it does not copy anything and instead of this action I get a message that it is emptying the recycle garbage can.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open the database
2. Select any entry
3. Click the copy password to clipboard button

## Expected Behavior
The password is copied 

## Actual Behavior
The password is not copied. It display a message that the recycle garbage can is being cleaned with indication of cleaning percentage

## Context
Windows 10, version 2.7.6 downloaded from portable apps

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION  2.7.6 from portable apps

Operating System: Windows 10 Pro, version 22H2

**Comment by droidmonkey** [comment]
I have no idea what you are referring to regarding the garbage can and a percentage but that is definitely not what we are doing. Make sure you don't have some crazy clipboard app on your computer.

**Comment by solisgb** [comment]
I apologize for the poor wording of my notification and the time I have caused you to waste.
