### ISSUE TITLE
Windows Store version remains on old version

### ISSUE THREAD

**Issue by weiw11** [keepassxreboot/keepassxc#9795]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Windows Store version does not auto-update to version `2.7.6` despite being installed. There is also no "update" button available, only "Installed".

Version either does not update properly, or Windows Store determined there is no update.

Had to reinstall to be on latest version `2.7.6`.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have existing `2.7.5` KeePassXC version from Windows Store
2. Update `2.7.6` available, and based on Windows Store, appears to be updated.
3. Open KeePassXC and check for version, but still remains on `2.7.5`.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
App should reflect the latest version `2.7.6` after updating.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
App version remains on `2.7.5`, with no "Update" button available on Windows Store.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Below debug information is **after updating**, as I do not know if it's possible to download older versions from Windows Store.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by phoerious** [comment]
This is a Windows store problem, not a KeePassXC problem. Win32 apps cannot auto-update via the store.

**Comment by bdbai** [comment]
Hi @phoerious, CMIIW Win32 apps themselves are responsible for self-upgrading even if it is distributed via the store, see https://github.com/microsoft/winget-cli/discussions/2875.

**Comment by phoerious** [comment]
Yes and that's stupid. We have no automatic self-update on any platform. What's the point of a store if not a) ensuring authenticity and b) just as importantly, performing automatic updates?

**Comment by bdbai** [comment]
@phoerious I think automatic updates will be possible, given we manage to publish KeePassXC as a MSIX package. Some related discussion here https://github.com/keepassxreboot/keepassxc/issues/2367.

**Comment by phoerious** [comment]
Yes, I am aware, but thanks. 😉

**Comment by phoerious** [comment]
Yes, I am aware, but thanks. 😉
