### ISSUE TITLE
Add ">" character to the Math Symbols button in the Password Generator

### ISSUE THREAD

**Issue by An-anonymous-coder** [keepassxreboot/keepassxc#9796]
## Summary
[NOTE]: Each button in the Password Generator Character Types (Advanced) displays each character (or a reasonable abbreviation) that the generator will include. For whatever reason, the only exception to this is the Math Symbols button, which has every character except for the greater than symbol (>). This should be included. Even though it isn't displayed on the button, it still appears in passwords.

## Context
[NOTE]: It makes it more clear as to which characters are actually being included. I was trying to create a list of these characters for my own project, and was thrown off by the missing character.

**Comment by droidmonkey** [comment]
Update your KeePassXC please. This has been done. https://github.com/keepassxreboot/keepassxc/pull/7921
