### ISSUE TITLE
Windows MSI Installer 2.7.6 doesnt install zlib1.dll

### ISSUE THREAD

**Issue by FiLeonard** [keepassxreboot/keepassxc#9798]
## Overview
WindowsMSI Installer doesnt contain zlib1.dll

## Steps to Reproduce
1. Install  [KeePassXC-2.7.6-Win64.msi](https://github.com/keepassxreboot/keepassxc/releases/download/2.7.6/KeePassXC-2.7.6-Win64.msi)

## Expected Behavior
Install zlib1.dll with file. 

## Actual Behavior
zlib1.dll doesnt get installed

## Context
I actually updated via winget but got the same behavior with the downloaded msi file. Fixed the missing dll with the files from the local install zip ([KeePassXC-2.7.6-Win64.zip](https://github.com/keepassxreboot/keepassxc/releases/download/2.7.6/KeePassXC-2.7.6-Win64.zip))

Operating System: Windows

**Comment by droidmonkey** [comment]
#7870 #9773

**Comment by droidmonkey** [comment]
Can you please at least provide a very detailed report of your system? What exact version of windows? What virus scanner are you using? What version did you upgrade from?
