### ISSUE TITLE
Segmentation fault upon unlocking when using --pw-stdin option

### ISSUE THREAD

**Issue by simonmarwitz** [keepassxreboot/keepassxc#9799]
## Overview
When starting keepassxc with the --pw-stdin option the program segfaults after unlocking the database. Let me know, if/how I can provide more details, etc.

## Steps to Reproduce
1.  `echo P4s5w0rd | usr/bin/keepassxc "/path/to/keyfile.kdbx" --pw-stdin`
(it also happens without the pipe and manually entering the pw into the commandline)

## Context
eePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 6.4.11-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Works perfectly fine for me, you will need to run this through a debugger to figure out what is wrong on your end. Also check to make sure you don't have any circular references in your entries (ie, one entry references a field from another entry that references the same field from the first)

**Comment by simonmarwitz** [comment]
OK, although I don't have any cpp experience I gave it a try and installed gdb and tons of recommended `*-debuginfo*` packages. Segfaults now happen irregularly and seem to be related to how fast I enter my password. (With piping in the password it still always segfaults). 

However, I managed to get a full gdb output. Maybe you can make any sense of it or give some recommendations for getting further debugging data:
```
gdb --args /usr/bin/keepassxc "/path/to/keyfile.kdbx" --pw-stdin
GNU gdb (GDB; openSUSE Tumbleweed) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/keepassxc...
Reading symbols from /usr/lib/debug/usr/bin/keepassxc.debug...
(gdb) run
Starting program: /usr/bin/keepassxc /path/to/keyfile.kdbx --pw-stdin
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff1f2b6c0 (LWP 11663)]
[New Thread 0x7ffff172a6c0 (LWP 11664)]
[New Thread 0x7fffebfff6c0 (LWP 11665)]
[Thread 0x7fffebfff6c0 (LWP 11665) exited]
[New Thread 0x7fffebfff6c0 (LWP 11666)]
[New Thread 0x7fffea8b16c0 (LWP 11667)]
[Thread 0x7fffebfff6c0 (LWP 11666) exited]
[New Thread 0x7fffebfff6c0 (LWP 11668)]
[New Thread 0x7fffe9ef76c0 (LWP 11669)]
[Thread 0x7fffebfff6c0 (LWP 11668) exited]
[Thread 0x7fffea8b16c0 (LWP 11667) exited]
[New Thread 0x7fffea8b16c0 (LWP 11670)]
[New Thread 0x7fffebfff6c0 (LWP 11671)]
[Thread 0x7fffe9ef76c0 (LWP 11669) exited]
[Thread 0x7fffea8b16c0 (LWP 11670) exited]
[Thread 0x7fffebfff6c0 (LWP 11671) exited]
[New Thread 0x7fffebfff6c0 (LWP 11672)]
[New Thread 0x7fffea8b16c0 (LWP 11673)]
[New Thread 0x7fffe9ef76c0 (LWP 11674)]
[New Thread 0x7fffe95f56c0 (LWP 11675)]
[New Thread 0x7fffe8df46c0 (LWP 11676)]
Couldn't load translations.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
[New Thread 0x7fffcffff6c0 (LWP 11677)]
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
[Thread 0x7fffe95f56c0 (LWP 11675) exited]
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Database password: 
[New Thread 0x7fffe95f56c0 (LWP 11680)]
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
Error while mapping shared library sections:
/proc/11662/ns/mnt: Permission denied.
[New Thread 0x7fffc9bff6c0 (LWP 11681)]
[New Thread 0x7fffc13fe6c0 (LWP 11682)]
[New Thread 0x7fffc93fe6c0 (LWP 11683)]

Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
0x00007ffff77e3719 in qobject_cast<QWidget*> (o=0x555557913fe0) at kernel/qwidget.h:755
755	kernel/qwidget.h: No such file or directory.
(gdb) 

```

Edit: Now (10 minutes later), it's always segfaulting again, even though I did not install/remove any packages.

**Comment by droidmonkey** [comment]
You should try reinstalling your Qt. You likely have a corrupt package somewhere. 

When gdb halts, type in `bt` to show the backtrace and paste that here. 

You also have a lot of permission denied, have you done something with your system that could have locked out critical files from read access?

**Comment by simonmarwitz** [comment]
First of all, thanks for helping me on this issue. I can live without the `--pw-stdin` option, if that behaviour is specific to my environment. My system might be messed up to some extent: I set it up in 2015 and installed, removed and updated many things since then, no fresh install just regular updates. I now reinstalled all Qt libraries -> no change

I found, that the most (but not all) contents of `/proc/<pid>` are owned by root, which explains the `Permission denied` errors. If i start any other regular user process its `/proc/<pid>` is owned by the user. Running `sudo /usr/bin/keepassxc "/path/to/keyfile.kdbx" --pw-stdin` avoids the segfault, but of course that is not a feasible long-term solution. I cannot `chmod`/ `chown` on the contents of `/proc/<pid>` and have no other idea on how to solve this.

Here is the backtrace:
```
(gdb) bt
#0  0x00007ffff77e3719 in qobject_cast<QWidget*>(QObject*) (o=0x555557918910) at kernel/qwidget.h:755
#1  QWidgetPrivate::showChildren(bool) (this=this@entry=0x555555d25b60, spontaneous=spontaneous@entry=false)
    at kernel/qwidget.cpp:8193
#2  0x00007ffff77e389f in QWidgetPrivate::show_helper() (this=this@entry=0x555555d25b60) at kernel/qwidget.cpp:7794
#3  0x00007ffff77e6813 in QWidgetPrivate::setVisible(bool) (this=0x555555d25b60, visible=<optimized out>)
    at kernel/qwidget.cpp:8137
#4  0x00007ffff77e3809 in QWidgetPrivate::showChildren(bool) (this=this@entry=0x555555df69f0, spontaneous=spontaneous@entry=false)
    at kernel/qwidget.cpp:8209
#5  0x00007ffff77e389f in QWidgetPrivate::show_helper() (this=this@entry=0x555555df69f0) at kernel/qwidget.cpp:7794
#6  0x00007ffff77e6813 in QWidgetPrivate::setVisible(bool) (this=0x555555df69f0, visible=<optimized out>)
    at kernel/qwidget.cpp:8137
#7  0x0000555555649805 in MainWindow::show() (this=0x7fffffffd7b0) at /usr/src/debug/keepassxc-2.7.6/src/gui/MainWindow.cpp:1768
#8  MainWindow::bringToFront() (this=0x7fffffffd7b0) at /usr/src/debug/keepassxc-2.7.6/src/gui/MainWindow.cpp:1903
#9  0x000055555562b3f7 in main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/keepassxc-2.7.6/src/main.cpp:211
```

**Comment by phoerious** [comment]
Looks very much like a Qt bug. You should try reinstalling Qt.

**Comment by droidmonkey** [comment]
Agreed this is definitely not with our code base. I would absolutely strongly recommend rebuilding your system, it's been too long.

Otherwise, you could try using the flatpak or appimage distributions we offer. Those isolate the program from your system to a large extent.

**Comment by simonmarwitz** [comment]
Thanks for your help. For now, the flatpak image works fine. I guess I should find some time to rebuild my system soon; will save me more such headaches.

**Comment by Pleune** [comment]
I'm running into this with latest builds from develop. system installed keepass works fine.

the /proc permissions seem like a red hearing, both system and new keepass have files owned by root for me, and I see permission errors from both, even when it works.

All of the release appimages are ok, but the latest 2.8.0 snapshot crashes on my ubuntu22 install.
