### ISSUE TITLE
add build dependencies to Readme

### ISSUE THREAD

**Issue by ftes** [keepassxreboot/keepassxc#98]
I want to suggest adding required libraries to the Readme for widely used platforms.
I couldn't find this information elsewhere, and it is a tedious process of `cmake`ing and figuring out what to install from the errors.

For ubuntu 16.10 this would be
`sudo apt install libmicrohttpd-dev libgcrypt20-dev qttools5-dev-tools qtbase5-dev libqt5x11extras5-dev`

**Comment by TheZ3ro** [comment]
Citing the Readme

> More detailed instructions are available in the INSTALL file or at the [Wiki page](https://github.com/keepassxreboot/keepassx/wiki/Install-Instruction-from-Source).

And if you are using Linux (ubuntu) this is the page [wiki/Building-Environment-on-Linux](https://github.com/keepassxreboot/keepassxc/wiki/Building-Environment-on-Linux)

**Comment by ftes** [comment]
Sorry, I totally missed that (even though it's printed in bold). Thanks for the answer!

**Comment by TheZ3ro** [comment]
No problem :smiley:
