### ISSUE TITLE
Exporting Challenge-Response XML

### ISSUE THREAD

**Issue by MyWay** [keepassxreboot/keepassxc#980]
Hello,
I'm not sure this is an issue. I have read somewhere that an XML file, it is supposed to be in the same directory as the DB (kdbx) file when using Challenge-Response. I'm using Challenge-Response, but I can't see this file, which would be needed on Keepass2Android (called Auxiliary File).

**Comment by droidmonkey** [comment]
Keepass2android does not use hmac challenge response like keepassxc does. We do not require a shared xml file because the secret is stored on the yubikey which performs the challenge response.

**Comment by droidmonkey** [comment]
Keepass2android does not use hmac challenge response like keepassxc does. We do not require a shared xml file because the secret is stored on the yubikey which performs the challenge response.
