### ISSUE TITLE
Quick unlock no longer works, and "Enable database quick unlock" is greyed out

### ISSUE THREAD

**Issue by Echaleon** [keepassxreboot/keepassxc#9800]
## Overview
After updating KeepassXC and Windows 11 to the latest versions, the option to enable quick unlock is now greyed out, and I am no longer prompted for Windows Hello when unlocking the database. This has happened on both my desktop and gaming laptop.

## Steps to Reproduce
1. Update KeepassXC to 2.7.6
2. Update Windows 11

## Expected Behavior
When unlocking the database, a Windows Hello prompt appears to save the credentials for future quick unlock.

## Actual Behavior
It pauses for a moment to unlock, and no prompt appears

## Context
Nothing from what I can tell is showing up in event viewer, and Windows Hello still works to log in or for other applications. I'm using a local account and not a Microsoft one. This is occurring on both my desktop and my gaming laptop, but oddly enough not my small laptop, and all three devices are configured nearly identically.

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey

Cryptographic libraries:
- Botan 2.19.3

Operating System: Windows 11 Pro
Version: 22H2
OS Build: 22621.2134
Experience: Windows Feature Experience Pack 1000.22659.1000.0

**Comment by droidmonkey** [comment]
Did you use winget to install?

**Comment by Echaleon** [comment]
> Did you use winget to install?

Yes I did.

**Comment by droidmonkey** [comment]
They are using the legacy windows installer for some reason. Get the normal installer off our website and you'll be fine.
