### ISSUE TITLE
Application cannot run due to missing dll files

### ISSUE THREAD

**Issue by safval** [keepassxreboot/keepassxc#9802]
## Overview
If the application is installed on a freshly reinstalled Windows system, it cannot launch. The system shows the error message:

`KeePassXC.exe - System Error.`  
`The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem.`

The same message is repeated for `VCRUNTIME140.dll`, `VCRUNTIME140_1.dll`, and `VCRUNTIME140.dll`.
Installing on Windows Sandbox gives the same result.

## Steps to Reproduce
1. Enable the Windows Sandox and open it.
2. Copy KeePass installator (KeePassXC-2.7.6-Win64.msi) into the sandbox window.
3. Install KeePass.

## Expected Behavior
KeePass starts.

## Actual Behavior
Error messages are shown.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro 22H2 OS build 22621.2134

**Comment by phoerious** [comment]
Duplicate of #7564. You need to install the MSVC Runtime library.

**Comment by safval** [comment]
Installers have that duty, don't they?

**Comment by phoerious** [comment]
MSI installers cannot piggyback third-party dependencies. Thank Microsoft for this.

**Comment by safval** [comment]
There is a tool in Qt5 called `windeployqt.exe`. It intends to gather all necessary files. It's possible that its `--compiler-runtime` flag can help to fix this problem.

**Comment by droidmonkey** [comment]
No, that's not how that works, but thank you

**Comment by phoerious** [comment]
We could ship the DLLs as part of KeePassXC, but since Windows cannot keep those up to date, it is explicitly discouraged by the MSVC docs.

**Comment by safval** [comment]
Okay, I understand now. I didn't assume it was done on purpose.
