### ISSUE TITLE
Overall search performance issues on Gnome 44 + Wayland 

### ISSUE THREAD

**Issue by mzenz** [keepassxreboot/keepassxc#9804]
## Overview

When using KeepassXC's search box on Gnome the UI slows to a crawl and freezes the OS momentarily.

## Steps to Reproduce

- Install KeepassXC via either Flatpak or RPM Fusion (Fedora Linux).

## Expected Behavior

- Searching shouldn't freeze OS.

## Actual Behavior

- UI becomes unresponsive and freezes OS temporarily, including cursor.

## Context

This is NOT reproducible on KDE + Plasma (Wayland).

## Debug info

```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Fedora Linux 38 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.4.12-200.fc38.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

Operating System: Linux
Desktop Env: Gnome v44.4
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Very very unlikely a problem with our program explicitly. 

> This is NOT reproducible on KDE + Plasma (Wayland)

There is literally no difference in our code between the two environments you mentioned. Please file a bug report with Gnome.

**Comment by mzenz** [comment]
@droidmonkey I am not familiar with KeepassXC's codebase but saying that the  code is identical for separate platforms doesn't mean the problem is not in the codebase itself. You can have the same code produce different results on different platforms, even if both are running on Linux. Just saying.

**Comment by droidmonkey** [comment]
I guess I can say that since I do know our codebase. 🤷‍♂️

Either way, between linux desktop environments there really isn't a difference at our level unless we explicitly make a difference (we don't). Qt handles all the particulars with integrating with various desktop envs.
