### ISSUE TITLE
Black windows when using Windows dark Theme in a RDP or Teamviewer session

### ISSUE THREAD

**Issue by Craftonix** [keepassxreboot/keepassxc#9805]
## Overview
When connecting to a RDP or Teamviewer computer, when opening keepassxc (logged or not)
the main windows is not displayed but a complete black windows appear.
I'm using windows 10 dark Theme, when switching to light theme windows appear but not each time.
The windows work correcly (menu displayed etc ..) but you are like a blind clicking

![image](https://github.com/keepassxreboot/keepassxc/assets/13018186/e3b6e2da-69ac-4671-b13a-6e1e9befc52e)

## Steps to Reproduce
1.  switch to Windows black theme
2. connect from another computer using RDP or teamviewer
3.  Open keepassXC (try to switch windows theme  dark/light) and also keepass xc theme

## Expected Behavior
Display normal windows in a RDP/teamviewer session

KeePassXC - 2.7.6 and previous
Revision : dd21def
Operating System: Window 10

**Comment by michaelk83** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by Craftonix** [comment]
Thanks did not know this feature.
