### ISSUE TITLE
Error on Windows 7

### ISSUE THREAD

**Issue by pkrumins** [keepassxreboot/keepassxc#9806]
Hi all,

I downloaded the installation but when I run KeePassXC on Windows 7, I get the following error:

![image](https://github.com/keepassxreboot/keepassxc/assets/41087/a979af7c-3f49-4b17-ba6e-b4bf8342529b)

Does it work on Windows 7? Thanks!

**Comment by droidmonkey** [comment]
Use the legacy windows installer
