### ISSUE TITLE
Access opened database from command line.

### ISSUE THREAD

**Issue by Pflyg** [keepassxreboot/keepassxc#9807]
## Summary
I want to be able to use keepassxc with openconnect on the command line, by having it input the password automatically (via a shell script). For that I would prefer the open database be used without having to re-type the password, similar to the way the SSH Agent or the browser integration is working.

The only way  I can see on how to do this is by using the browser integration feature, which seems rather complex to implement in a shell script.

It would be great if you could access the open database with `keepassxc-cli` or something similar, maybe by passing in a predefined token.

**Comment by droidmonkey** [comment]
#5069 there are also scripts available elsewhere on github that kind of do that without the keepassxc cli in it middle.
