### ISSUE TITLE
add maximum number of backups (based on age, not on count limite) / options to clean up old db backups

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#9808]
## Summary
kxc allows to create new kxdb backups for every change however - unless i seriously overlooked it - it does not have a maximum number of backups that are maintained (ex: on startup or via menu entry) and/or maintains these files. The number of backups can get out of hand rather fast this way.
Proposal is to add optional management for the backup files; once triggered (or could be set to automatic even?) show a dialog with the files, their age and allow selecting/purging old backups. search criteria could be the existing backup destination template definition and file creation time. It does not make sense to utilize a count/limit as numerous changes could happen leading to overflowing the backup limit; however i propose to utilize the age (ex: auto-remove backups older than 30 days).

## Context
- reduces clutter on drive and uncontrolled growth of large number of backups;
-  keeps maintenance in the program loop and not outside hopefully reducing potential (human) errors

**Comment by droidmonkey** [comment]
We have decided to NOT add this feature. We never want to be in a position of deleting files. If you need backup file management then implement that outside the program using scripts or other options.
