### ISSUE TITLE
KeePassXC crashes on accent color change in MacOS

### ISSUE THREAD

**Issue by sbotnickusgs** [keepassxreboot/keepassxc#9810]
## Overview
App crashes on system configuration change

## Steps to Reproduce

1. Go to System Settings -> Appearance 
2. Change Accent color

## Expected Behavior
Not give me a KeePassXC quit unexpectedly message.

## Actual Behavior
App disappears and I get a KeePassXC quit unexpectedly system message.

## Context
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 13.5.1
CPU architecture: arm64
Kernel: darwin 22.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Duplicate #9527
