### ISSUE TITLE
Keyboard and mouse unresponsive in Keepass after locking and unlocking the desktop

### ISSUE THREAD

**Issue by jirikoudelka** [keepassxreboot/keepassxc#9811]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # After locking the screen and unlocking, the keyboard and mouse in Keepass are unresponsive. It is necessary to maximize the window and then return to the original size. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Let KeepassXP opened
2. Lock the Desktop
3. Unlock the Desktop (password)
4. Keepass is unresponsive, need to maximize the windows and then return to the original size
5. It works fully again
6. (more last versions, it is not new bug in 2.7.6)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )
Windows 11 Pro

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro, fully actualized

**Comment by orcas-mgleich** [comment]
Same here. But here only mouse do not work any more. Keyboard works. And this problem is only from time to time and not on every unlock. Often after come back from standby. And this is not a problem for the specific version. In versions before a have the same behavior.

    KeePassXC - Version 2.7.6
    Revision: dd21def
    Qt 5.15.10
    Windows 11 Version 2009
    CPU-Architektur: x86_64
    Kernel: winnt 10.0.22621

**Comment by droidmonkey** [comment]
Hmmm just seeing this issue now. This is most definitely not a KeePassXC bug, per say. It is either a windows runtime issue or a Qt issue. I personally have never experienced this problem and I use Win11 and multiple monitors. Recommend reinstalling the visual studio runtime environment: https://aka.ms/vs/17/release/vc_redist.x64.exe
