### ISSUE TITLE
Feature: importing Mac keychains

### ISSUE THREAD

**Issue by RJVB** [keepassxreboot/keepassxc#9813]
## Summary
Mac computers have long had a proprietary keychain feature, using a database format that can only be read under the proprietary OS.

There is however example code (the "security utility") which shows how to export the entire information in a given keychain.

It would be very salutary to be able to import the information into a KeePass database (at least the representable bits).

## Examples
Think of a user who considers to migrate away from the Mac universe after decades, and who has thus accumulated a large quantity of passwords, certificates and other secure notes in keychains, which he would like to take along.
The logical implementation would provide a Mac-specific action in the Import menu, allowing to import one or possibly more keychains, preferably into the current(ly open) database.
This feature would depend only on platform SDKs so there is no strict reason to make it optional (but CMake makes that easy enough of course).

## Context
I am in the example situation above.

I was also thinking of tackling this problem myself. I was under the impression that plugins were supported but apparently I was mislead by the FdoSecrets feature. Bummer, because this would undoubtedly have helped me getting started (and the lay of the land, etc), so I'd appreciate if someone could give me some pointers with this.

**Comment by droidmonkey** [comment]
Is there an API for this? Can you export the Keychain to CSV?

**Comment by RJVB** [comment]
On Thursday August 31 2023 06:00:02 Jonathan White wrote:
>Is there an API for this? Can you export the Keychain to CSV?

IIRC Apple's existing utility does indeed allow that, but I'm sure you'd have to rewrite that feature so it exports CSV that KPXC knows how to import. With all the caveats related to binary data. I'd rather have a direct import that doesn't require to save an unencrypted file first.

**Comment by menkej** [comment]
Actually I was thinking about the same and found this feature request googling for it. I searched for the possibility to export csv, as suggested by @droidmonkey and it is actually possible. See here: https://www.aiseesoft.com/how-to/export-icloud-keychain.html#part2 - I tried it and was able to import export/import the passwords. So my exit strategy (if it comes to that somewhen) is existing. IMHO this feature request could be closed, @RJVB .

Or another option/item for my whichlist for Santa: actual sync between KeepassXC and Apple keychain. So one could use keychain on a Mac/iPhone and sync to KeepassXC to use that on other platforms... But this would definitively require additional coding and I had no time to look into that by now.

**Comment by RJVB** [comment]
> IMHO this feature request could be closed, @RJVB .

Nope, hard disagree. It shouldn't be necessary to figure out how to export to CSV in a way that KPC can import. I know that probably means I'll have to do it myself (so be it) but until I actually get around to work on it I'm leaving this open in hope someone will actually post some pointers to get me started.

> Or another option/item for my whichlist for Santa: actual sync between KeepassXC and Apple keychain. So one could use keychain on a Mac/iPhone and sync to KeepassXC to use that on other platforms... But this would definitively require additional coding and I had no time to look into that by now.

I have already written a Keychain backend for KDE's Wallet so I can confirm that it wouldn't be that much more work to implement an export feature too. A sync however is something else; that requires logic that has in itself nothing to do with the importing or exporting, but rather with comparing entries and deciding which has to be synced and in what direction.

**Comment by droidmonkey** [comment]
There is little need for a dedicated import feature since exporting to csv is supported by Mac Keychain. I assume importing by csv is also supported by the Mac Keychain. The more beneficial thing to work on is "selected export" from KeePassXC. 

With limited resources and time this would only be implemented by a code contribution of high quality. I think that syncing will be way to hard to get right.

**Comment by RJVB** [comment]
Of course there is 0 chance that the two utilities do *not* speak the same CSV dialect, that the Keychain CSV export does not contain only a subset of the data ... or that I'm going to check decades worth of accumulated Keychain items for import glitches.

Apparently there's also little need for me to bother trying to respect the official coding style ^^

**Comment by droidmonkey** [comment]
The CSV format is not complicated, username, password, url, title. I'm fairly certain any keystore would export those columns. The csv importer is very easy to use in keepassxc.

**Comment by droidmonkey** [comment]
I checked the apple documentation and this is simply not possible. An app cannot just scrape the keys out of the keychain. Each app only has access to the keys that app placed in the keychain. You would have to go entry by entry and grant access to KeePassXC, even that is dicey. We are not going to expend any time on this.

Example: https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps

**Comment by RJVB** [comment]
This is not true. What good would a keychain be if credentials stored in 1 browser can't be accessed through another browser? Typically you just get a dialog to grant access in such a case.

As stated in my original description Apple even provide the code to dump an entire keychain. I've done that once to test if it works (it does); I cannot remember if I had to OK the reading of each entry or if I just had to unlock the keychain.

Also: I was NOT asking to HAVE THIS FEATURE IMPLEMENTED FOR ME. The biggest "expenditure" I asked for is to give me some pointers on how to get started. I understand that was too much to ask so whatever I come up with will be explicitly off-limits to upstreaming.

**Comment by droidmonkey** [comment]
Are we talking about the same keychain? There are icloud stored passwords which is what you can export to csv. Then there is the actual keychain which generally doesn't have an export functionality unless it is a public key from a certificate. 

You didn't provide any example api that I can see in the chat above. 

> Apple even provide the code to dump an entire keychain

Where is this code? Did you need to be root?

**Comment by RJVB** [comment]
I was talking about the actual, local keychain (of course, I'm tempted to add). It indeed doesn't provide an export feature, or only a very limited one (for certificates, I think).

I'd have to look at the SDK documentation again, I don't recall how well the APIs are documented but Apple's C APIs tend to be tedious but straightforward. The utility I plan to get the relevant code from can be found online as "SecurityTool-55115".

**Comment by droidmonkey** [comment]
The code you are hoping to use is using api that has been deprecated since 10.7...

https://developer.apple.com/documentation/security/1396821-secidentitysearchcreate

https://opensource.apple.com/source/SecurityTool/SecurityTool-55115/keychain_export.c.auto.html

**Comment by RJVB** [comment]
I'm not seeing any information about a replacement API (you'd expect that on https://developer.apple.com/documentation/security/secidentitysearchref) so I'm guessing the deprecation doesn't mean much (certainly not on the OS version I'm using). I'll look into that further though, thanks for the heads up.

**Comment by ralphw** [comment]
I user a browser with KeepassXC and passkeys.

I have set this up for my linkedin account (only)

I'd like to be able to import a passkey from my Mac ecosystem, into KeepassXC.

My user expectation is that I can use the "import Passkey" function.  Should I expect this function to appear in a different part of KeepassXC?

**Comment by droidmonkey** [comment]
Given the state of passkeys portability, you should not have that expectation for any program.

**Comment by RJVB** [comment]
On Monday February 03 2025 15:34:14 Jonathan White wrote:
>Given the state of passkeys portability, you should not have that expectation for any program. 

A passkey is presumably something quite different from a traditional ID/password pair?
