### ISSUE TITLE
option to display passwords, notes in main window

### ISSUE THREAD

**Issue by MissouriSpiff** [keepassxreboot/keepassxc#982]
Previous versions of KeePass allowed showing any of the fields in the main window, including passwords. Passwords could be displayed as "*****" with a toggle in the menu to allow for viewing. Field order could be re-arranged.

## Expected Behavior

Suggest: Right-click on title bar should bring up menu to add/remove fields. Click and drag should allow for re-ordering.

## Current Behavior

I don't see any way to add or remove fields from main window display.

## Context

I would like to be able to see the password before I copy it. I need the reminder for times when I don't have KeePass available to tell me what it is.

**Comment by TheZ3ro** [comment]
There is already a PR open #849
