### ISSUE TITLE
2.7.6 installs but does not run on Win7

### ISSUE THREAD

**Issue by crogonint** [keepassxreboot/keepassxc#9824]
I would have just simply added this to #7599 but it's locked out because I'm not a collaborator.

I get a successful install of 2.7.6 on Win7, but when I try to run the program, I get the "Missing ms-api-------.dll that tells me that that version was built for Win10.

PLEASE do reconsider and continue building for Win7! I own an HP Elitebook with GOBS of horsepower, but it won't run Win10, and I have zero inclination to hammer it in to working, because I suspect it will run on WIn7 just fine for about another decade. I'm obviously not alone, since it's reported in the other thread that 15% of your users are still on Win7. These are high-end machines with a LOT of life left in them, PLEASE don't drop support!

**Comment by droidmonkey** [comment]
Use the legacy windows installer....

**Comment by crogonint** [comment]
AH! I see that now! I see where I got confused.. The current webpage reads like that's a link for previous version.. Perhaps change it to read "Legacy Windows users click here." ..or some such thing to indicate that there is a current version for Win7 at that link.. Might be easier just to link the Win7 installer.

**Comment by phoerious** [comment]
See more options -> Legacy Installer.
