### ISSUE TITLE
Icon Size far to big

### ISSUE THREAD

**Issue by tituskurth** [keepassxreboot/keepassxc#9825]
As of today, all icons far to big

![2023-09-05_19-57](https://github.com/keepassxreboot/keepassxc/assets/24211001/5adae7fe-08de-423d-8eca-8f2dce3e5e46)

## Steps to Reproduce

1. Open KeePassXC

## Expected Behavior
Small Icons like before

## Actual Behavior
Big Icons

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 22.04.3 LTS
CPU-Architektur: x86_64
Kernel: linux 6.2.0-31-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- libgcrypt 1.9.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome

**Comment by varjolintu** [comment]
First, update KeePassXC to the latest version.

**Comment by tituskurth** [comment]
Done, but same as before, icons are far to big.

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 22.04.3 LTS
CPU-Architektur: x86_64
Kernel: linux 6.2.0-32-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Please search the issue board, there are plenty of these with solutions listed. You need to adjust your qt environment variables.
