### ISSUE TITLE
Colorful tray icon type shows monochrome icon and monochrome icon type shows colorful icon

### ISSUE THREAD

**Issue by Adikso** [keepassxreboot/keepassxc#9827]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I'm setting "Tray icon type" because I want my tray icon to match monochrome style, it is actually not changing to monochrome style. It is showing monochrome icon only when I select "Colorful" option. There is also no difference between light and dark versions.

![image](https://github.com/keepassxreboot/keepassxc/assets/1407751/daa38f59-57d4-44eb-9364-68c5c211a274)

![image](https://github.com/keepassxreboot/keepassxc/assets/1407751/482fb448-04e8-459c-a4a6-c1e094a3d4a9)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Change tray icon type to "Monochrome (light)"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Style of the tray icon should change to monochrome.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Tray icon is not set to monochrome light style, it is colorful.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by Adikso** [comment]
I just noticed that after some time, even "Colorful" option doesn't work. It switches back to color version and I can make it work again only by restarting the app.

**Comment by droidmonkey** [comment]
Those are not our icons. You need to uninstall or remove whatever has placed incorrect alternate icons in place.

**Comment by Adikso** [comment]
> Those are not our icons. You need to uninstall or remove whatever has placed incorrect alternate icons in place.

But I guess that there is still a problem with icons switching by themselves without changing the settings?

**Comment by droidmonkey** [comment]
Not sure what you mean, but this isn't related to our program. You have something else that is overriding our icons.

**Comment by Adikso** [comment]
I don't think that something is overriding the icons while Keepass is running. When I have these white icons as on screenshot, it sometimes changes to green color ones. In settings, nothing change and I have to restart the app to make it respect my choice.

**Comment by droidmonkey** [comment]
Niether of the icons in your screenshots are KeePassXC icons.
