### ISSUE TITLE
CTest failed due to SegFault:A crash occurred in F:\gitP\keepassxreboot\keepassxc\build_amd64\tests\Release\testgroup.exe

### ISSUE THREAD

**Issue by Eva-An** [keepassxreboot/keepassxc#9828]
## Overview
ctest failed due to SegFault:A crash occurred in F:\gitP\keepassxreboot\keepassxc\build_amd64\tests\Release\testgroup.exe

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. git clone https://github.com/Microsoft/vcpkg F:\gitP\Microsoft\vcpkg
2. git -C "F:\gitP\Microsoft\vcpkg" rev-parse --git-dir
3. git -C "F:\gitP\Microsoft\vcpkg" clean -xdf
4. git -C "F:\gitP\Microsoft\vcpkg" fetch --recurse-submodules=no --force
5. git -C "F:\gitP\Microsoft\vcpkg" reset --hard 3f6e8e9
6. git -C "F:\gitP\Microsoft\vcpkg" remote prune origin
7. git clone https://github.com/keepassxreboot/keepassxc F:\gitP\keepassxreboot\keepassxc
8. git -C "F:\gitP\keepassxreboot\keepassxc" rev-parse --git-dir
9. git -C "F:\gitP\keepassxreboot\keepassxc" clean -xdf
10. git -C "F:\gitP\keepassxreboot\keepassxc" fetch --recurse-submodules=no --force
11. git -C "F:\gitP\keepassxreboot\keepassxc" reset --hard 1919c23
12. git -C "F:\gitP\keepassxreboot\keepassxc" remote prune origin
13. cd F:\gitP\keepassxreboot\keepassxc\utils\vcpkg_ports
14. xcopy "F:\gitP\keepassxreboot\keepassxc\utils\vcpkg_ports" F:\gitP\Microsoft\vcpkg\ports/k/r/e/i/s/c/h/f/y
15. cd F:\gitP\Microsoft\vcpkg
16. bootstrap-vcpkg.bat
17. vcpkg.exe install --recurse argon2 botan zlib minizip libqrencode readline --triplet x64-windows --clean-after-build
18. cd F:\gitP\keepassxreboot\keepassxc\build_amd64
19. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;%PATH%
20. gem install asciidoctor
21. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22000.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows ..
22. msbuild /m /p:Platform=x64 /p:Configuration=Release KeePassXC.sln /t:Rebuild
23. ctest --build-config Release --output-on-failure -E "testautotype|testcli|testpassphrasegenerator"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
ctest pass

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Test project F:/gitP/keepassxreboot/keepassxc/build_amd64
      Start  1: testgroup
 1/29 Test  #1: testgroup ........................***Exception: SegFault  0.65 sec
A crash occurred in F:\gitP\keepassxreboot\keepassxc\build_amd64\tests\Release\testgroup.exe.
Function time: 8ms Total time: 9ms

Exception address: 0x00007FFD5CC93278
Exception code   : 0xc0000005
Nearby symbol    : Thrd_yield
Stack:
1: QTest::toString() - 0x00007FFD5052B390
2: UnhandledExceptionFilter() - 0x00007FFD6895F8F0
3: memset() - 0x00007FFD6AEA6D80
4: _C_specific_handler() - 0x00007FFD6AE8EF50
5: _chkstk() - 0x00007FFD6AEA4ED0
6: RtlVirtualUnwind2() - 0x00007FFD6AE315A0
7: KiUserExceptionDispatcher() - 0x00007FFD6AEA3FC0
8: Thrd_yield() - 0x00007FFD5CC93140
9: Botan::Memory_Pool::allocate() - 0x00007FFD398C0C30
10: Botan::allocate_memory() - 0x00007FFD398C00D0
11: Botan::MDx_HashFunction::MDx_HashFunction() - 0x00007FFD3972BD40
12: Botan::SHA_256::SHA_256() - 0x00007FFD39726BF0
13: Botan::HashFunction::create() - 0x00007FFD39728F10
14: AutoTypeExecutor::~AutoTypeExecutor() - 0x00007FF746090FB0
15: AutoTypeExecutor::~AutoTypeExecutor() - 0x00007FF746090FB0
16: AutoTypeExecutor::~AutoTypeExecutor() - 0x00007FF746090FB0
17: Unable to obtain symbol
18: QMetaMethod::invoke() - 0x00007FFD39268550
19: QTest::ignoreMessage() - 0x00007FFD50525020
20: QTest::qRun() - 0x00007FFD50529710
21: QTest::qExec() - 0x00007FFD505274E0
22: AutoTypeClearField::~AutoTypeClearField() - 0x00007FF74608B330
23: argon2id_verify_ctx() - 0x00007FF7461C0180
24: BaseThreadInitThunk() - 0x00007FFD68E74DD0
25: RtlUserThreadStart() - 0x00007FFD6AE7EC20

The following tests FAILED:
	  1 - testgroup (SEGFAULT)
	  2 - testkdbx2 (SEGFAULT)
	  3 - testkdbx3 (SEGFAULT)
	  4 - testkdbx4 (SEGFAULT)
	  5 - testkeys (SEGFAULT)
	  6 - testgroupmodel (SEGFAULT)
	  7 - testentrymodel (SEGFAULT)
	  8 - testcryptohash (SEGFAULT)
	  9 - testsymmetriccipher (SEGFAULT)
	 10 - testhashedblockstream (SEGFAULT)
	 11 - testkeepass2randomstream (SEGFAULT)
	 12 - testmodified (SEGFAULT)
	 13 - testdeletedobjects (SEGFAULT)
	 14 - testkeepass1reader (SEGFAULT)
	 15 - testopvaultreader (SEGFAULT)
	 16 - testentry (SEGFAULT)
	 17 - testmerge (SEGFAULT)
	 18 - testpasswordgenerator (SEGFAULT)
	 20 - testhibp (SEGFAULT)
	 21 - testtotp (SEGFAULT)
	 26 - testcsvexporter (SEGFAULT)
	 27 - testdatabase (SEGFAULT)
Errors while running CTest

## Context
[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Couple things:

1. You don't need to copy the argon port file anymore, argon is included with the base vcpkg now. 
2. Typically we use Ninja and not the VS project format. So use that instead.

This issue isn't a problem with KeePassXC itself. Looks like a build problem.

We have setup instructions here: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows
