### ISSUE TITLE
Powershell module for KeepassXC

### ISSUE THREAD

**Issue by Wolvverine** [keepassxreboot/keepassxc#9829]
Powershell modules to be handled in powershell scripts - KeepassXC along the lines of those for Keepass:

https://github.com/PSKeePass/PoShKeePass

https://www.powershellgallery.com/packages/SecretManagement.KeePass/0.9.2

**Comment by droidmonkey** [comment]
Just use the one you linked, we are not going to make anything beyond our CLI tool already.

**Comment by Wolvverine** [comment]
@droidmonkey Only that then you need to install keepass original and the environment for it. These modules do not work with KeepassXC cli and API.
