### ISSUE TITLE
wayland GDK issue

### ISSUE THREAD

**Issue by okias** [keepassxreboot/keepassxc#983]
with default GDK_BACKEND=wayland it SIGSEGV when calling open file dialog.
with GDK_BACKEND=x11 it works

I tried gdb but it gives me LWP 8138:P generic error when tried to run it.

I run gnome-desktop 3.26 on Gentoo amd64

EDIT: I have feeling I missing qtwayland support... waiting for compile

**Comment by droidmonkey** [comment]
did you resolve this?

**Comment by okias** [comment]
I compiled in "wayland" and "wayland-egl" (qtwayaland package for 5.7) být with it it looks pretty ugly.. Not fully yet :(

**Comment by droidmonkey** [comment]
Closing since this was a Qt bug that is addressed.
