### ISSUE TITLE
Unlock Database for Browser automatically

### ISSUE THREAD

**Issue by mattiwilde** [keepassxreboot/keepassxc#9830]
## Summary
As browser-user I want to autofill login-forms without unlocking the database manually.

## Examples
If I want to fill in a PW-form I have to unlock the database. I want the browser to be able to unlock the database automatically. If I deactivate the automatic locking of the database, then the database is completely open to everyone on my desktop. This would not be acceptable for me.

## Context
Many users need convenience for PW-management (e.g. my parents). The don´t want to use every time a PIN for unlocking. Instead they save passwords without a masterpassword.

**Comment by droidmonkey** [comment]
That completely defeats our security model and won't be implemented. We do have quick unlock for this purpose and that is being expanded to Linux in 2.8.0.
