### ISSUE TITLE
Initial database unlock triggers unnecessary Windows Hello prompt

### ISSUE THREAD

**Issue by platformer** [keepassxreboot/keepassxc#9834]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
If quick unlock is enabled, when unlocking the database for the first time after initial computer startup, a Windows Hello popup will trigger after the master key is entered. This prompt is unnecessary, as the database will become unlocked even if the popup is closed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable quick unlock in database settings (under security)
2. Reboot computer
3. Complete first-time database unlock

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Since unlocking the database for the first time requires the master key regardless, the database should be immediately unlocked after entering the master key and shouldn't trigger Windows Hello.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Windows Hello is unnecessarily triggered when unlocking the database for the first time.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Read the user guide please.
