### ISSUE TITLE
Fehler beim Öffnen der Datenbank: Ungültige Anmeldedaten, bitte versuchen Sie es noch einmal. Falls dies wiederholt passiert, könnte Ihre Datenbank beschädigt sein. (HMAC stimmt nicht überein)

### ISSUE THREAD

**Issue by Schmaule** [keepassxreboot/keepassxc#9836]
Hallo zusammen, ich kann KeePassXC-Datenbank nicht mehr entsperren. Passwort ist korrekt. Was kann ich tun? Es kommt folgende Fehlermeldung:
Fehler beim Öffnen der Datenbank: Ungültige Anmeldedaten, bitte versuchen Sie es noch einmal.
Falls dies wiederholt passiert, könnte Ihre Datenbank beschädigt sein. (HMAC stimmt nicht überein)

## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Hello, unfortunately there is nothing we can do to help you. You are _most likely_ entering your password incorrectly. 

Due to a Qt limitation, if you have diactrics or unicode characters in your password then you must make it visible to type them.
