### ISSUE TITLE
Is there a way to disable key rotation after every save?

### ISSUE THREAD

**Issue by afg137** [keepassxreboot/keepassxc#9838]
By inspecting my decrypted XML file, I noticed that the key that is used to encrypt the passwords changes after every save, and all credentials are re-encrypted. (I believe this key is called the "inner random stream key" per the [documentation](https://keepass.info/help/kb/kdbx_4.html) of the file format).

For performance reasons, is there a way to change this setting, and have the key rotate less frequently? (For example, after every X saves, where X > 1?).

**Comment by droidmonkey** [comment]
No there isn't since it is a core security feature.
