### ISSUE TITLE
Malicious files in macOS arm64 installer

### ISSUE THREAD

**Issue by SeyhaSoun-LeanIX** [keepassxreboot/keepassxc#9839]
VirusTotal is flagging KeePassXC-2.7.6-arm64.dmg as being malicious from Google and Ikarus, https://www.virustotal.com/gui/file/432350131e9b0e47cba6d2f9d3233224a06af941ff5e7a7345c25e6325b21d2f.

**Comment by droidmonkey** [comment]
No, it doesn't have malicious files in it. Those scanner sites are unreliable.

**Comment by SeyhaSoun-LeanIX** [comment]
Okay, thanks.
