### ISSUE TITLE
upgrade 2.7.5 to 2.7.6

### ISSUE THREAD

**Issue by Strzkrk** [keepassxreboot/keepassxc#9841]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
WIN10: Cannot upgrade from 2.7.5 to 2.7.6. Popup shows new version available. Download works but installation says "Change, repair or remove...". Tried to repair but stays on 2.7.5

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Version 2.7.5 installed
2. Download 2.7.6
3. Try to install --> not working

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
upgrade to v 2.7.6

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Change, repair or remove... --> stays on v 2.7.5

## Context
[NOTE]: # ( Give us any additional information you may have. )
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS

**Comment by guenxmuerfel** [comment]
Had the same problem, but a reboot solved it. After that 2.7.6 is correctly showing.

**Comment by droidmonkey** [comment]
Either you need to reboot, or you are actually running a "portable" version (2.7.5) while still installing 2.7.6.
