### ISSUE TITLE
Clearing clipboard after timeout does not work

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc#9842]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Clearing clipboard after timeout does not work.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Copy a password into clipboard
2. Check clipboard within timeout time
3. Check clipboard after timeout time

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The copied password should have been deleted

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Password is still there.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I'm using parcellite-1.2.1 as clipboard manager on Xfce.
On Parcellite I have set
[x] Use Copy (Ctrl-C)
[x] Use Primary (Selection)
[ ] Synchronize clipboards

Can keepassxc deal with primary and secondary clipboard?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Xfce
Windowing System: X11

**Comment by droidmonkey** [comment]
> I'm using parcellite-1.2.1 as clipboard manager

This is likely your problem. Please file a bug with them, they are clearly ignoring an "empty"/clear clipboard request. 

They also seem to be ignoring the freedesktop.org standard to indicate not to store an entry in the clipboard history.

**Comment by Massimo-B** [comment]
I like to file a bug to parcellite...
Is that an official standard API how to send empty/clear clipboard request?
Does that provide deleting single entries? How should clipboard managers deal with the case that the current primary clipboard has already been replace with new content, while the password goes down in the persistent history? How do other clipboard managers deal with that?

**Comment by droidmonkey** [comment]
They can figure all that out, it's not a secret. If they can't then.... you should find a different clipboard manager. Many of them already do all this.

**Comment by Karl-Knorr-GitHub** [comment]
Hi!
I have the same issue with Ditto Clipboard manager. The password is not cleared after timeout time.
I am also using KeePass 2.56 and could not reproduce this issue. The password is cleared after timeout time.
The difference I noticed is that KeePass copied password does not appear in Ditto but in the "standard" windows clipboard and is then deleted/cleared after timeout time.
BR, Karl

**Comment by Massimo-B** [comment]
I can't follow you. You are on Windows? Clipboard handling is completely different there.
You are using some 3rd party software named "Ditto Clipboard Manager" on Windows? There the password is not cleared? Then you say, the password is cleared? Cleared or not cleared?

**Comment by Karl-Knorr-GitHub** [comment]
Hi!
Sorry for my unclear posting. First the facts concerning my environment:
- OS Windows 11
- KeePass Version 2.56
- KeePassXC Version 2.7.6
- Same database used with KeePass and KeePassXC 
- Ditto Version 03.24.246.00 64bit / "Ditto is an extension to the standard windows clipboard"

Procedure
-- Copy a password from an entry using KeePass Version 2.56
- Password can be pasted using Ctrl+V
- The password is deleted after the timeout period is reached.
- No entry is created in Ditto

-- Copy a password from an entry using KeePassXC
- Password can be pasted using Ctrl+V
- The password is deleted after the timeout period is reached.
- But: **AN** entry is created in Ditto

So there must be different procedures how KeePass and KeePassXC are creating clipboard entries. In my opinion the KeePass procedure is the safer one. Hope my posting brings some light into this issue.
BR, Karl

**Comment by droidmonkey** [comment]
We use the windows standard way to declare a clipboard item shouldn't be stored in history or synced. Ditto needs to implement respecting that standard. 

https://github.com/keepassxreboot/keepassxc/blob/develop/src%2Fgui%2FClipboard.cpp#L61

**Comment by Karl-Knorr-GitHub** [comment]
Ok! For sure I respect your answer and I am not a programmer but anyhow KeePass seems to have a safer implementation handling clipboard functions.
Thx for your answer and KeePassXC is a great program.
BR, Karl

**Comment by droidmonkey** [comment]
KeePass is also written on .NET which exposes different options for clipboard control. I'm not aware of another option we can use on windows from c++.

**Comment by gcolpart** [comment]
I understand KeePassXC sends "clear clipboard" request AND "do no store" request for clipboards with freedesktop.org standard.

But it's really hard to find a compliant clipboard (I use Debian/XFCE).

Clipman, Diodon, Parcellite ignore these requests :(

Is there a chance you add a workaround for Parcellite with using Parcellite FIFO to stop/start capturing during copy?

```
echo 'stop_all' > ~/.local/share/parcellite/fifo_cmd
COPY
echo 'run_all' > ~/.local/share/parcellite/fifo_cmd
```

**Comment by droidmonkey** [comment]
If you are using wayland, you might need to install `wl-clipboard`

**Comment by gcolpart** [comment]
> If you are using wayland, you might need to install `wl-clipboard`

I run X.org. Do you suggest clearing Clipman/Diodon/Parcellite could work better with Wayland?

**Comment by droidmonkey** [comment]
Not familiar with any of those programs
