### ISSUE TITLE
Can`t edit attribute KeePassXC-Browser Settings

### ISSUE THREAD

**Issue by don-andruha** [keepassxreboot/keepassxc#9843]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When you have many sites with similar URLs, like:

- site.com
- dev.site.com
- stage.site.com
- test.site.com
- demo.site.com
- etc.

and each of them have own credentials - it's very difficult use **KeePassXC** to login. 
I get credentials for all of similar group in browser extension and need manually choose right entry.
But if you have more, than 1 entry for 1 site - it makes your life unbearable.

It will be useful if i can manually set settings for each credentials on which sites it can be shown or not.

As I know attribute `KeePassXC-Browser Settings` can make it.
In another app (older KeePass) I could do it, but in KeePassXC i can't.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Simplest solution - make attributes in "Properties" section editable.
Showed it on **[screenshot](https://i.imgur.com/M67tebe.png)**
Of course you can offer better solution for this problem .

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
As a developer I got much number of credentials (with different roles) for many similar site and every day I need manually choose right entry in browser extension.

KeePassXC - 2.7.6
Revision: `dd21def`

Operating System: Linux Mint 21
Architecture CPU: x86_64
Kernel: linux 5.15.0-83-generic

**Comment by droidmonkey** [comment]
It's hard to tell what settings/configuration you have setup with your report, but if each entry has _only_ the url list you posted above then _at most_ you would see the credentials for site.com and whatever subdomain you are on. 

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/1daef4b6-4238-4318-9e45-0dc573c826c8)


If you want to further restrict entries with exact matching then you can enable this setting:
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/8cc73f9b-0969-4711-9d39-07611e4e493d)

**Comment by don-andruha** [comment]
Second screenshot help me a lot. Cheers!
