### ISSUE TITLE
After update, mac can only past to the main latop screen

### ISSUE THREAD

**Issue by dansdrivers** [keepassxreboot/keepassxc#9846]
## Overview
I have a second monitor connected to the laptop. When I try to login on a site with the page open on the second screen, the text pastes into a browser on the main laptop screen. I have to drag the window that need to paste into over the main laptop screen in order for the paste to work.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open browser window on laptop screen.
2. Open second window with login site on second screen.
3. Put cursor on login form
4. Use keepasx short cut
5. Test jumps to first screen window.
6. Close first screen window, or drag login window to first screen
7. Use keepassx shortcut
8. Login works

## Expected Behavior
Expecting that the paste will go to the window with the form and cursor in the field.

## Actual Behavior
Text pastes into the window on the main laptop screen.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Qt 5.15.8
Debugging mode is disabled.

Operating system: macOS 13.3
CPU architecture: x86_64
Kernel: darwin 22.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Paste as in clipboard? Or are you talking about Auto-Type?
