### ISSUE TITLE
Need x86 build of 2.7.6

### ISSUE THREAD

**Issue by sbliven** [keepassxreboot/keepassxc#9850]
## Overview

The [2.7.6](https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.6) release only provides a apple silicon build. I hope this is an oversight and that x86 will continue to be supported on MacOS.

## Steps to Reproduce
1. https://keepassxc.org/download/#macos offers Apple Silicon, even for x86-based macs

## Expected Behavior

The download link should either provide the correct architecture or link a universal binary.

## Actual Behavior

Only arm64 builds are available.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Click on "Show more options" below the download button

**Comment by sbliven** [comment]
Derp. Indeed, x86 is there below the fold (also on github below the "show all 29 assets" link). This can be closed.

Well done, carry on!
