### ISSUE TITLE
Shutdown/Reboot doesn't delete .lock & .socket in /tmp

### ISSUE THREAD

**Issue by sinclair-m** [keepassxreboot/keepassxc#9855]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]:
Keepassxc upon a system shut down or reboot doesn't remove the 
/tmp/keepassxc-$user$.lock
/tmp/keepassxc-$user$.socket 
files.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open keepassxc
2.  Initiate a reboot
3.  Attempt to open Keepassxc -> "Keepassxc is already running"

## Expected Behavior
[NOTE]: keepassxc gui should display

## Actual Behavior
[NOTE]:  Keepassxc fails to start

## Context
[NOTE]: Deleted / reinstall keepassxc but didn't do anything

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.15.128-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
And you don't have it starting automatically on login? It's not hidden on another desktop? You checked your running processes? You closed keepassxc manually and saw the lock file and socket file remain? 

Just FYI, having those files in place doesn't prevent keepassxc from starting, it does a live check to see if another process responds to the single instance request.

**Comment by michaelk83** [comment]
On most modern Linux, `/tmp` is mounted as `tmpfs`, which means it's stored entirely in RAM and completely discarded when the system shuts down. You can confirm this by running `grep '/tmp' /etc/mtab` or `df | grep /tmp`.

Also, if you're running KDE, it's `ksmserver` (KDE Session Manager) will automatically restart whatever you had running when the previous session was ended (i.e. just before the reboot).
