### ISSUE TITLE
Error keepassXC 2.7.6

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#9859]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Error auto-entry does not work I have to enter manually

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. When I press auto-entry there should be a name and then a password, but it's all the other way around, and sometimes it just enters the login and no password
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
should be username tab password enter

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
enter on the reverse password tab
or enter username tab and that's it.
## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
I'm sorry but there just isn't enough information to be able to begin helping you. Add more context and we'll reopen.
