### ISSUE TITLE
Cannot open window and cannot configure

### ISSUE THREAD

**Issue by LazerDickMcCheese** [keepassxreboot/keepassxc#9860]
## Overview
Fresh install (using both the installer and portable), cannot access the program. Once downloaded and installed, there is a KeePassXC icon on the taskbar, however there are no windows to select. If there is supposed to be a tray icon, it is not showing either. I deleted the config file to see if that would make a difference, but it did not.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download and install on Windows 10
2. Open KeePassXC

## Expected Behavior
It works

## Actual Behavior
Nothing happens outside of showing the icon in the taskbar

[NOTE]: # ( Paste debug info from Help → About here )
The version is whatever is most recent at time of posting.

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10/Windows 11

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

You are using a remote desktop capability and need to add the command line flag to allow screencapture.

**Comment by LazerDickMcCheese** [comment]
I wasn't using a remote desktop.
