### ISSUE TITLE
On Lid Close or Locked Session, SSH Agent Still Persists 

### ISSUE THREAD

**Issue by AustinFoss** [keepassxreboot/keepassxc#9863]
## Steps to Reproduce
1. Have a remote ssh server already setup with ssh authorized keys, and keepassxc already working with the ssh agent enabled and working. Sign in successfully using KeepassXC's ssh agent. 
2. Enable "Lock databases when session is locked or lid is closed" under Settings -> Security
3. Close laptop lid or lock session, return to locked Keepass database & DO NOT unlock it. Attempt to open a new session  

## Expected Behavior

Instead of a successful session over ssh you should be prompted for a password instead or the request is simply dropped (depending how the ssh server is configured)

## Actual Behavior

Successful ssh session is created without unlocking the KeepassXC DB.

## Context

KeePassXC - 2.7.6
Revision: ?
Distribution Method: AppImage & Flatpak

Operating System: Linux, Pop OS 22.04
Desktop Env: Gnome
Windowing System: Wayland

What I'd expect would work as an implementation would be to call remove from agent for all added keys just before the DB gets re-encrypted.

**Comment by droidmonkey** [comment]
Did you enable "Remove key on database lock" when setting up the entry for ssh agent?

**Comment by AustinFoss** [comment]
> Did you enable "Remove key on database lock" when setting up the entry for ssh agent?

Nope, that I do not.

Odd, I just assumed that would be default behavior of a locked DB. Should this not be set as the default rather having to remember to tick that box for every ssh key we have in the DB?

**Comment by droidmonkey** [comment]
Hmm that is a 50/50 problem. Half the users want them to persist by default, half want them to get removed by default. Either way those settings are right at the top of the ui when you setup ssh agent for an entry.
