### ISSUE TITLE
First entry is not selected when a search is performed

### ISSUE THREAD

**Issue by Colfenor** [keepassxreboot/keepassxc#9865]
## Overview

When searching for a database entry in keepassxc, it is not intuitive why and which entry is set active. This default behaviour is also not yet documented in the user guide.

On inspection of the code base, I found the logic of setting an entry active [here](https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/entry/EntryView.cpp#L233) and it seems to have to do with entries being associated to a Group.

The function `EntryView::setFirstEntryActive()` implies that a "first" entry is set active, however I would understand, "first" as in the first entry in a entire list for instance. 

## Steps to Reproduce
1. open a populated .kdbx database with entries associated to root and child groups
2. search for a desired entry where multiple entries are returned as a list
3. observe which entry is set active visible to the user by a light green entry coloration in the GUI

## Expected Behavior
The first entry in the list is set active

## Actual Behavior
An entry of a child group gets selected as the one which is set active

## Context
I realized this behaviour, when having a heavly populated .kdbx database and searching that somehow a child child group entry is set active where I needed to scroll down quite some time in the returned list to actually see which one it was.

## Example
![keepassxc-search](https://github.com/keepassxreboot/keepassxc/assets/34011017/7d9e5283-98d6-4c7f-985e-18567fe3929c)

KeePassXC - Version 2.8.0-snapshot
Revision: 27c5c5d

Operating System: Linux
Desktop Env: Gnome/
Windowing System: X11

**Comment by droidmonkey** [comment]
Oh geez that is a bug and also present in 2.7.6.
