### ISSUE TITLE
Database search results are always empty

### ISSUE THREAD

**Issue by katewapo** [keepassxreboot/keepassxc#9867]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Database search results are always empty.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. type search expression into top search bar
2. type enter
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
all entries with that expression contained  in their database entry should be filtered and show up in main window frame

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
no such entry shows up in main window frame, even if such entry idefinetely exists

## Context
[NOTE]: # ( Give us any additional information you may have. )
see below

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 23.04
CPU-Architektur: x86_64
Kernel: linux 6.2.0-33-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux 
Desktop Env: KDE Plasma 
Windowing System: X11

Operating System: Ubuntu 23.04
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-33-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: Quadro P1000/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C94
System Version: 1.0

**Comment by katewapo** [comment]
I managed to resolve the issue:
I realized it was a database problem. Therefore I created a new and empty database from sratch. Then I "merged" the original <old_DB>.kbdx file with my <new_DB>.kbdx file. This seemingly repaired the database index. Thus, now I can search entries again. :-)

**Comment by droidmonkey** [comment]
You likely had search disabled on one or more of your groups.
