### ISSUE TITLE
Unable to set up 2FA on GitHub

### ISSUE THREAD

**Issue by onet4** [keepassxreboot/keepassxc#9869]
## Overview
Unable to set up 2FA on GitHub. Has anyone been able to successfully configure this with the TOTP code generated by KeePassXC?

## Steps to Reproduce

1. Install KeePassXC on Windows
2. Create a new KeePassXC database in KeePassXC
3. Login to GitHub and navigate to the profile icon (at the top right) > Settings > Password and authentication > [Enable two-factor authentication](https://github.com/settings/two_factor_authentication/setup/intro)
4. Copy the secret key by clicking on the secret key link below the QR code
5. Create an entry named GitHub in KeePassXC
6. Right click on the created entry and select TOTC > Set up TOTP
7. Enter the secret key copied on GitHub with the default settings (RFC 6238) and press OK
8. Copy a TOTP code by right clicking the entry and select TOTC > Copy TOTP
9. Paste the TOTP code to the input field on the GitHub 2FA set-up page

## Expected Behavior
GitHub should accept the code generated by KeePassXC.

## Actual Behavior
Error on GitHub: Two-factor code verification failed. Please try again.

![image](https://github.com/keepassxreboot/keepassxc/assets/5302867/1acd50f4-a605-44d9-a21d-5c01f8998bf4)

## Context
Set-up guides:
- [Instructions](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-totp-mobile-app) on GitHub
- [Instructions](https://stackoverflow.com/a/77013766) on StackOverflow

According to the GitHub guidance, there seem to be several parameters including `Label` and `Issuer`. Are these configurable with KeePassXC? 

> If you wish to setup a TOTP app manually, and require the parameters encoded in the QR code, they are:
> 
> - Type: TOTP
> - Label: GitHub:<username> where <username> is your handle on GitHub, for example monalisa
> - Secret: This is the encoded setup key, shown if you click"setup key" during configuration
> - Issuer: GitHub
> - Algorithm: The default of SHA1 is used
> - Digits: The default of 6 is used
> - Period: The default of 30 (seconds) is used

### Debug Info
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by varjolintu** [comment]
Check your computer's time. If it's a little off, TOTP codes will not work properly.

**Comment by onet4** [comment]
@varjolintu That was it! Thank you so much.
