### ISSUE TITLE
2.2.0 crashes on start on OSX 10.7.x

### ISSUE THREAD

**Issue by hrk** [keepassxreboot/keepassxc#987]
Sorry for running a legacy platform :)
The following appears when I try to launch the app (from the DMG, but the same happens when I launch it after copying it from the hard drive)

Process:         KeePassXC [1012]
Path:            /Volumes/VOLUME/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:      org.keepassx.keepassxc
Version:         2.2.0 (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [227]

Date/Time:       2017-09-24 14:26:23.823 +0200
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          4574648 sec
Crashes Since Last Report:           22
Per-App Crashes Since Last Report:   4
Anonymous UUID:                      D385952A-74B9-4843-B16F-7212150EB81D

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
  Referenced from: /Volumes/VOLUME/KeePassXC.app/Contents/MacOS/../Frameworks/QtNetwork.framework/Versions/5/QtNetwork
  Reason: image not found

Binary Images:
       0x101f1a000 -        0x1021dffff +org.keepassx.keepassxc (2.2.0 - ???) <A81D6E75-E6F4-34FB-80FA-4268FB908F0C> /Volumes/VOLUME/KeePassXC.app/Contents/MacOS/KeePassXC
       0x102230000 -        0x102330ffb +org.qt-project.QtNetwork (5.9 - 5.9.0) <8350A5C7-0830-3CED-9B68-2CA3C8603EC7> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10237a000 -        0x10237bff7 +libyubikey.0.dylib (2.7.0 - compatibility 2.0.0) <E13F810A-E9BA-32C0-9A49-AEAC9394A626> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/libyubikey.0.dylib
       0x102381000 -        0x102389fff +libykpers-1.1.dylib (20.0.0 - compatibility 20.0.0) <A36FDB8F-CC30-3776-A51C-F50BD91A9A66> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/libykpers-1.1.dylib
       0x102392000 -        0x102396ffb +org.qt-project.QtConcurrent (5.9 - 5.9.0) <8131D267-3E90-31A3-8FDB-07C6BD1CFD22> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x10239d000 -        0x1027eafff +org.qt-project.QtWidgets (5.9 - 5.9.0) <A43A606B-E26D-3A2D-BF6B-979D4C828D56> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10294b000 -        0x102d4efff +org.qt-project.QtGui (5.9 - 5.9.0) <8CA1DD81-06D5-33EE-988D-722AED8752B3> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x102e49000 -        0x103310ffb +org.qt-project.QtCore (5.9 - 5.9.0) <A5362279-2F05-3CAD-853E-E04AB3472EF3> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1033c6000 -        0x103460fff +libgcrypt.20.dylib (22.7.0 - compatibility 22.0.0) <7BFE97FE-EB63-3DF1-87FD-1EE36D24E2A3> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/libgcrypt.20.dylib
       0x103481000 -        0x10348effb +libgpg-error.0.dylib (23.0.0 - compatibility 23.0.0) <2CFB76D2-A060-32D4-81E2-5503988B6D22> /Volumes/VOLUME/KeePassXC.app/Contents/Frameworks/libgpg-error.0.dylib
    0x7fff61b1a000 -     0x7fff61b4ebaf  dyld (195.6 - ???) <C58DAD8A-4B00-3676-8637-93D6FDE73147> /usr/lib/dyld
    0x7fff8210d000 -     0x7fff82113fff  com.apple.DiskArbitration (2.4.1 - 2.4.1) <CEA34337-63DE-302E-81AA-10D717E1F699> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff842e1000 -     0x7fff8432dff7  com.apple.SystemConfiguration (1.11.3 - 1.11) <131780ED-E8DD-3153-81F2-5FEC4F6554C2> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff85b23000 -     0x7fff85e18ff7  com.apple.security (7.0 - 55148.6) <4535E500-973A-3BA7-AF65-DF5CF0658F02> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff861e5000 -     0x7fff86212fe7  libSystem.B.dylib (159.1.0 - compatibility 1.0.0) <6E5C8AC3-DBB7-31CB-BEB7-D6ED8E6DE0CE> /usr/lib/libSystem.B.dylib
    0x7fff866cc000 -     0x7fff866deff7  libz.1.dylib (1.2.5 - compatibility 1.0.0) <30CBEF15-4978-3DED-8629-7109880A19D4> /usr/lib/libz.1.dylib
    0x7fff86b82000 -     0x7fff86bf8ff7  libc++.1.dylib (28.4.0 - compatibility 1.0.0) <A24FC3DA-4FFA-3DD2-9DCC-2B8D1B3BF97C> /usr/lib/libc++.1.dylib
    0x7fff8aec2000 -     0x7fff8af2dff7  com.apple.framework.IOKit (2.0 - ???) <FE838BB6-D42E-3291-A1A0-6F53FC970261> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff8ba24000 -     0x7fff8ba24fff  com.apple.CoreServices (53 - 53) <043C8026-8EDD-3241-B090-F589E24062EF> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff8ec70000 -     0x7fff8ee44ff7  com.apple.CoreFoundation (6.7.2 - 635.21) <62A3402E-A4E7-391F-AD20-1EF20236CE1B> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8ee45000 -     0x7fff8f15efff  com.apple.Foundation (6.7.2 - 833.25) <22AAC369-B63C-3C55-8AC6-C3ECBA44DA7B> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

**Comment by hrk** [comment]
FWIW a similar issue happens with 2.1.4, with a different framework. The MBP was cleanly updated from 10.6.8 to 10.7.5. Let me know if I should provide further information.

**Comment by weslly** [comment]
KeepassXC uses Qt 5.9, which requires at least 10.10 or later. You can try [compiling from the sources](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC) using Qt 5.2 instead of 5.9.

**Comment by hrk** [comment]
Thanks for the reply. FWIW, the download page links "Binary bundle for macOS 10.7 and later" to the 2.2.0 DMG file, and the official documentation claims 5.2 is the minimum Qt required.
I will try the build instructions and report back.
Do you know if it is possible to make a "universal" DMG working for 10.7-10.12?

**Comment by TheZ3ro** [comment]
The binary bundle is compiled with Qt5.9, the latest Qt version, that unfortunately supports only 10.10+. 
If you compile the source code with an older version of Qt (minimum 5.2) you can make it run on 10.7+.
I hope it's clear now

**Comment by droidmonkey** [comment]
Touché, the website is misleading and needs to be fixed!

**Comment by hrk** [comment]
Innocent question: what about compiling it against Qt 5.2 instead of deprecating 10.7-10.9? What would be required/lost?

**Comment by weslly** [comment]
@hrk Wouldn't be impossible, but 5.9 is noticeably more stable than 5.2 on macOS regarding to random crashes and bugs.

This has been recently discussed here:  https://github.com/keepassxreboot/keepassxc/issues/745
