### ISSUE TITLE
add the username {enter}password {enter} function

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#9871]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
it's just that this function works faster

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
there is no layout and no image

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
this function works faster

**Comment by droidmonkey** [comment]
You can define that per entry, read the user guide for more information
