### ISSUE TITLE
keepassxc-cli.exe: System Error: libreadline8.dll was not found

### ISSUE THREAD

**Issue by ackalker** [keepassxreboot/keepassxc#9873]
## Overview
When I try to run `keepassxc-cli.exe` at a Command Prompt, I get the following error:
![image](https://github.com/keepassxreboot/keepassxc/assets/429567/f7ff0907-5f97-40af-b7d1-00532bb4ee27)

## Steps to Reproduce
1. Open a Command Prompt.
2. Run `cd C:\Program Files\KeePassXC`
3. Run `keepassxc-cli.exe --help`

## Expected Behavior
Running `keepassxc-cli.exe --help` should show command line help.

## Actual Behavior
Running `keepassxc-cli.exe` produces a System Error as shown in the screenshot.

## Context
KeePassXC installed using `winget install --id=KeePassXCTeam.KeePassXC  -e`

KeePassXC - Version 2.7.6
Revision: dd21def

Operating System: Windows 11 Home edition
Desktop Env: Windows
Windowing System: Windows

**Comment by ackalker** [comment]
I am aware that there have been several issues regarding missing DLLs after installations or upgrades using Winget, and I would like to ask the developers to try out the installer used by Winget (especially in 'quiet' or 'silent' mode) in a VM or container such as Windows Sandbox.

I would have liked to try and reproduce this on a clean installation, but I don't have access to Windows Sandbox because that requires at least a Pro edition of Windows, nor do I have the disk space to use the free Windows Developer VM provided by Microsoft.

**Comment by droidmonkey** [comment]
Perform a reinstall. Nothing about our installer changed between 2.7.5 and 2.7.6. I could not reproduce missing DLL's in any testing scenario. Without reproduction there cannot be a fix.

**Comment by yoda65** [comment]
Hi,
I have the same issue with a Portable ZIP (64-bit, Windows 10 / 11)  install 2.7.6 on W10 pro (libreadline8.dll is missing...)
I just unzip file to local folder. The dll seems not exist in the zip.

Regards

**Comment by droidmonkey** [comment]
It's in there.

![Screenshot_20231015_082142_FX.png](https://github.com/keepassxreboot/keepassxc/assets/2809491/3aa196f7-9e8e-4da8-9a61-1ec1fcdf7122)

Libreadline8.dll would be a MSYS dll, I will note that it is NOT in the legacy windows zip.

**Comment by yoda65** [comment]
Thanks a lot. It 's better now . My first install (some weeks ago) has not this file.

Regards
