### ISSUE TITLE
Performance issues with Mac ARM version

### ISSUE THREAD

**Issue by hackpak0o** [keepassxreboot/keepassxc#9875]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Performance for the ARM version of the program began to resemble the Intel version. It takes forever to load, and it's not snappy anymore. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open Typeform's form
2. Type in answers
3. Each question took super long for the text from the moment I began typing to show fully

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should be instantaneous. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Think you got the wrong program here.

**Comment by hackpak0o** [comment]
Oh! Isn’t this the pale moon browser?  On Mon, Sep 25, 2023 at 6:22 PM, Jonathan White ***@***.***> wrote:  
Think you got the wrong program here.

**Comment by phoerious** [comment]
No.
