### ISSUE TITLE
Browser Extension: Provide database picker when requesting credentials

### ISSUE THREAD

**Issue by Neuro-NX** [keepassxreboot/keepassxc#9876]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Show a database picker window when selecting the KeepassXC icon in the text field, in order to choose which database to request credentials from.

The application would detect if there are more than one database files present. If true, then it will display a database picker.  This should not be default, but an optional feature. Enabled either in 'Browser Integration' or maybe 'Security > Convenience'.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Note: These mockups are to illustrate the applications flow, and not the graphical UI appearance.

![database_picker_1](https://github.com/keepassxreboot/keepassxc/assets/12788578/1bc67815-6717-49c6-a203-a05161a2f495)
![database_picker_2](https://github.com/keepassxreboot/keepassxc/assets/12788578/5381a31c-2a74-45fa-b1a4-1ebe21225047)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

This would solve the problem of first having to close the active database, then opening their desired database, before returning back to the browser.

**Comment by droidmonkey** [comment]
> This would solve the problem of first having to close the active database, then opening their desired database, before returning back to the browser.

This isn't required, simply switching the active tab is all that is necessary to pick from another unlocked database. If you want to search all open databases, then enable that option in the application settings, browser section. 

As it stands, this request is already existing behavior so closing unless you can be more specific.

**Comment by Neuro-NX** [comment]
> This isn't required, simply switching the active tab is all that is necessary to pick from another unlocked database. If you want to search all open databases, then enable that option in the application settings, browser section.
> 
> As it stands, this request is already existing behavior so closing unless you can be more specific.

Sorry, I was not clear.

I am wanting to select from another **'closed'** database, but from within the history of previously used ones - from within the browser window - as you can see from my mockup. Due to security reasons, many users will want to lock the database immediately when not in use - So the option 'Search in all opened databases' would not work.

Currently, in order to switch to another closed database you would need to

1. Go into the application
2. Close the active database
3. Select the other database
4. Then unlock it
5. Then return back to the browser

That's 5 steps which requires navigating out of the browser window.

Edit: Okay it's working now. When clicking the text field icon it asks for a password, and because I previously opened both databases (but have since timed out), I can then select it and re-enter the password.

**Comment by droidmonkey** [comment]
Your steps 2 and 3 above are unnecessary as you may have just found out. KeePassXC can have multiple databases open at the same time.
