### ISSUE TITLE
Browser integration not working with Brave Nightly realease (and likely other Beta versions of browsers) 

### ISSUE THREAD

**Issue by FreshwaterShrimp** [keepassxreboot/keepassxc#9877]
## Overview

Enabling browser integration doesn't support Brave Nightly (and likely other Beta releases of browsers) because of the way config data is stored. The json data that's needed by KeePassXC-Browser is written to prespecified paths depending on which browsers you enable integration for, for Brave this is:
`~/.config/BraveSoftware/Brave-Browser/`
But the Brave Nightly release's config path is 
`~/.config/BraveSoftware/Brave-Browser-Nightly/`

The work around is literally as simple as moving 
`~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json`
to
`~/.config/BraveSoftware/Brave-Browser-Nightly/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json`
by running
`mv ~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json ~/.config/BraveSoftware/Brave-Browser-Nightly/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json`

I get that Beta releases are unstable so if this is intentional for security reasons then I understand, but it would be nice for there to be an option to specify that you're using a Beta release and to give the user a warning (If it's really a security issue).

## Steps to Reproduce

1. Install the KeePassXC-Browser extension on Brave Nightly 
2. Go into the KeePassXC settings and enable browser integration for Brave
3. KeePassXC-Browser can't connect to the database.

## Expected Behavior

KeePassXC-Browser should connect to the database

## Actual Behavior

It can't connect to the database, returning
`Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

## Context

I guess this is the same for other Beta version of browsers, unless they handle config data differently than Brave.

## Version
KeePassXC - Version 2.7.6
Revision: dd21def

Operating System: Linux Mint 21.2 x86_64
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to define a custom browser in the advanced browser settings (within application settings) to point to the beta/nightly folder for native messaging.
