### ISSUE TITLE
Gvd wat een meuk programma. DB locked on Ubuntu AND w11 !!!! total noobs. 

### ISSUE THREAD

**Issue by Dakhaasje** [keepassxreboot/keepassxc#9878]
both my computers have keepassxc for about 2 months. 1 ubuntu 22,  1 win11. both running  iot servers like Home Assistant , mqtt Domoticz... 24/7 on, Reboot very rarely. like once in 2 months.
Last week Ubuntu machine had to reboot.
after boot: shitassXC db locked /corrupted, 
 Today win11 machine had to reboot, 
same issue. hiac error, db corrupted.
Sure, it is safe to the outside world if you do not have backups of databases.
This way is extremely safe. Even I cannot get in.

It feels like someone added sugar to my gas in my motor.

Suggestion: stop all development, go back to school and learn database management before anything else.

**Comment by droidmonkey** [comment]
So you didn't keep any backups? You also made sure that you were using the correct password to unlock the database?
