### ISSUE TITLE
Entries/search list: don't cycle/wrap around entries

### ISSUE THREAD

**Issue by Gittyperson** [keepassxreboot/keepassxc#9879]
When using the cursor keys, please add an option to NOT allow the selection to cycle i.e. move from bottom to top again (and vice versa).

In the common situation where the user knows what the bottom (or top) entry will be in a list, this can easily cause the wrong entry to be selected. Having this option can also speed up workflow.

**Comment by droidmonkey** [comment]
There is no need for such an option (yet another setting). Use the Home key to select the top of the list, End key to select the end. Page Up and Page Down will also not cycle the list.

**Comment by Gittyperson** [comment]
Ok, thank you in any case - hardly a major issue. Since you seem to dislike adding further settings, perhaps making this the default behaviour could be considered instead. I obviously cannot know how many people are actually using or prefer the current 'cycle' mode.

**Comment by droidmonkey** [comment]
It was a specific request a few years back
