### ISSUE TITLE
Keepassxc - Auto Type Fills In Username - No Longer Password

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#9881]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I try to log into Github, the Auto Type is only filling in my username, then the ```F`orgot password?``` link is now getting activated, and the password is not getting filled in.

This only started happening today, yesterday I logged into Github without any problems.

Here's a screen shot of the login page, showing the ```Forget password?``` link that's getting activated below the User/Email section.

![GitHub_signin](https://github.com/keepassxreboot/keepassxc/assets/36190223/51f7a62d-f234-4c2d-ab5c-1e4f89189590)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to Github, sign in using Auto Type shortcut key

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Auto Type should fill in the password

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

keepassxc clicks the ```Forgot password?``` link, instead of filling in the user's login password.

I also tested this several times, closing Firefox, cleaning out the cache, cookies etc., I use Bleachbit to clean it, and I was also not using any FF addons.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Slackware 15.0
Desktop Env: Openbox 3.6.1
Windowing System: X11
Browser: Firefox ESR 115.3.0

**Comment by droidmonkey** [comment]
You will need to add an extra {TAB} in your auto-type sequence. This would be a "bug" in GitHub's login page since pressing tab from the username field should focus on the password field for maximum usability.

**Comment by 0pLuS0** [comment]
Hi,

Ahhh, I see, sorry about the post, I thought there was a bug here, as I've never changed this setting from the Default for any of my entries.

I'm now using the Custom as; ```{USERNAME}{TAB}{TAB}{PASSWORD}{ENTER}``` and it's working.

THANKS

**Comment by 0pLuS0** [comment]
@droidmonkey 

This stopped working again today with two tabs; ```{USERNAME}{TAB}{TAB}{PASSWORD}{ENTER}```

**Comment by droidmonkey** [comment]
Then they likely fixed the issue on the website, remove the second tab. This isn't a problem with KeePassXC.

**Comment by 0pLuS0** [comment]
I did try it yesterday with one Tab, and it wasn't working, but today it is...

Oh well, guess whatever was going on with Github is working now.

THANKS
