### ISSUE TITLE
How to Disable Export option in KeepassXC GUI

### ISSUE THREAD

**Issue by satyasure** [keepassxreboot/keepassxc#9882]
## Summary

Hello All,

We are using KeepassXC as our password manager and we would like to disable export option in KeepassXC, could someone guide us how to disable this option?

**Comment by droidmonkey** [comment]
There is no way to disable it and no reason to do so either. Nothing is stopping someone with access to a database file from copy/pasting, auto-typing, or  saving as a new kdbx file.
