### ISSUE TITLE
The password is "changed" according to the keyboard layout chosen in the virtual machine

### ISSUE THREAD

**Issue by sebma** [keepassxreboot/keepassxc#9883]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Define this auto-type sequence : `{MODE=VIRTUAL}{PASSWORD}{ENTER}` in a KeepassXC entry associated to a VM
2. Change the keyboard layout in the VM to spanish
3. Return to the KeepassXC entry associated to the VM
4. Type CTRL+SHIFT+V

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password is forwarded as is to the VM (example : test2023)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The password is "changed" according to the keyboard layout in the VM (the password becomes : test"=".).

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10-22H2

**Comment by droidmonkey** [comment]
This is because keys are translated by the VM client and you need to force sending input as "virtual input". Please see our user guide for some more info on defining custom auto-type sequences: https://keepassxc.org/docs/KeePassXC_UserGuide#_configure_auto_type_sequences

**Comment by sebma** [comment]
@droidmonkey I used this auto-type sequence `{MODE=VIRTUAL}{PASSWORD}{ENTER}` but still the keys get translated.

I just updated my first post with this information which I forgot to give in the first place, sorry.

**Comment by droidmonkey** [comment]
I don't think there is anything we can do about this. Your keyboard needs to match both host and guest. KeePassXC cannot know which keyboard layout to use in a guest vm.
