### ISSUE TITLE
nm-applet fails to retrieve credentials on every second attempt

### ISSUE THREAD

**Issue by haarp** [keepassxreboot/keepassxc#9884]
## Overview
When NetworkManager's nm-applet access secrets over libsecret, it only seems to succeed every second time. This often inadvertendly leads to nm-applet purging "empty" secrets, which can be very detrimental.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set up KeepassXC as the libsecret provider
2. Add a new VPN in nm-applet, e.g. Wireguard
3. Enter some value for the `Private key` and set it to `Store the password for only this user`
4. Save, and when prompted by KeepassXC, select `Remember` and `Allow All & Future` (it'll ask again when nm-applet is restarted anyway, so it doesn't matter)
5. Press the edit button on the newly-created connection -> Private key was retrieved and is there
6. Close
7. Press the edit button on the newly-created connection -> Private key was not retrieved, is missing
7.5 If you save now, nm-applet will nuke the private key from the db :(
8. Close
9. Press the edit button on the newly-created connection -> Private key was once again retrieved and is there
10. Close
11. Press the edit button on the newly-created connection -> Private key is once again missing
12. etc...

## Expected Behavior
Secrets should always be retrieved

## Actual Behavior
Secrets are only retrieved on every second opening of the properties

## Context
It's possible this is an nm-applet bug. NetworkManager has a quite buggy or gnome-specific libsecret implementation. See e.g. #4921

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Gentoo Linux
CPU architecture: x86_64
Kernel: linux 6.1.53-gentoo-r1-HH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

Thanks!

**Comment by droidmonkey** [comment]
Please file this with network manager, it isn't our bug. It would be ours if you had _random_ failure to retrieve or inability to retrieve in all applications.

**Comment by haarp** [comment]
https://gitlab.gnome.org/GNOME/network-manager-applet/-/issues/188
