### ISSUE TITLE
Username generator and dowloading icons by Brave Search

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#9885]
First suggestion is about downloading icons by duckduckgo. There Is another private web search - Brave Search. Is it possible to add possibility to downloading icon by Brave Search?

And the second is add to PC app an username generator (they are existing in BitWarden and imho it's pointless to make account in that app or another only for username generator)

**Comment by droidmonkey** [comment]
There is already an open request for username generator so this is a duplicate. We are not going to implement another icon downloading service unless DDG stops working.
