### ISSUE TITLE
Prune history of all entries

### ISSUE THREAD

**Issue by 3point14159** [keepassxreboot/keepassxc#9887]
When you open an entry, there is a "History" tab that saves the past changes to that entry. There is a button/option to "Delete All" history of the entry. This is nice because it will reduce the size of your database, which improves performance.

Is there a way to delete all of the history from all entries in one function? If not, can we add this function for database maintenance?

**Comment by droidmonkey** [comment]
Go to database menu -> database settings. Then uncheck the history items checkbox. Press ok.

**Comment by 3point14159** [comment]
That works. Thank you for the quick pointer. Love the application.
