### ISSUE TITLE
Texts compressed into one char

### ISSUE THREAD

**Issue by koncaq** [keepassxreboot/keepassxc#9888]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # Mac version 2.7.6 - after unlocking cannot read content. All texts are compressed into one char

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Lock app
2. Unlock app 
3. Content is unreadable

## Expected Behavior
[NOTE]: # I would like to see and read content of my database without restarting the app

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After unlocking content is unreadable
<img width="1049" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/53078488/28598f58-f463-4364-bb45-0d54d5cafc62">

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Wersja 2.7.6
Rewizja: dd21def

Qt 5.15.8
Tryb debugowania jest wyłączony.

System operacyjny: macOS 12.6
Architektura procesora: x86_64
Jądro: darwin 21.6.0

Włączone rozszerzenia:
- Autowpisywanie
- Integracja z przeglądarką
- Agent SSH
- KeeShare
- YubiKey
- Szybkie odblokowanie

Biblioteki kryptograficzne:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
This is a macOS/Qt bug that was fixed in later versions of macOS.

**Comment by Nokius** [comment]
What needs to be updated to get out of this issue, it's very annoying

**Comment by droidmonkey** [comment]
Unknown, it just went away for people and never happened to us ourselves.

**Comment by Nokius** [comment]
strange have it daily mutliiple times

**Comment by Nokius** [comment]
found away to reproduce it.

requirements:
YubiKey to use as login smartcard setup in macOS (User X)
YubiKey setup as Hardwarekey to unlock your keepassdb
multiple user setup in macOS (min 2 user)

- login as your user  X (using a YubiKey as smartcard)
- open your keepassdb
- lock screen of your user session in macOS
- unattach the YubiKey
- login as user Y
- use KeyPass (not sure if this is really needed; do it anyway) 
- lock screen as user Y
- login as User X
- use the open KeePassXC application 
--> KeyPassXC has the char issue
