### ISSUE TITLE
Sonoma : Application freezes after entering password

### ISSUE THREAD

**Issue by pleinechope** [keepassxreboot/keepassxc#9889]
## Overview
Application freezes after entering password on macos sonoma

## Steps to Reproduce
1. open app
2. open database
3. choose file
4. enter password
5. click unlock
6. infinite loading and freeze

## Expected Behavior
opens the database almost instantaneously

## Actual Behavior
infinite loading and freeze, database can't be opened

## Context
the issue arose only after updating macos to sonoma

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.0
CPU architecture: arm64
Kernel: darwin 23.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Please go to application settings, security tab, and disable quick unlock. See if that makes a difference.

**Comment by pleinechope** [comment]
It doesn't change anything, even after restarting the app.
I tried quickly on other keepass clients and I have the same problem. Is it possible that this problem affects all keepass apps? https://github.com/MacPass/MacPass/issues/1283

**Comment by droidmonkey** [comment]
We have nothing in common (code wise) with macpass so this must be a bug with Sonoma. Could be at the crypto layer (random numbers, kernel call, special cpu instructions). Hard to tell but certainly not a KeePassXC bug at this time.
