### ISSUE TITLE
Easily import custom wordlists for the passphrase generator

### ISSUE THREAD

**Issue by jonazc** [keepassxreboot/keepassxc#989]
I dont know if I that feature already exists and I missed it somewhere. But I would like to add and choose custom wordlists for the passphrase generator.

I expect to have an option in settings where I can add several lists (for example simple txt files with one word each line)

Further I expect at the passphrase generator page to have a dropdown menu (if more than one list is available) where I can choose the lists multiple lists where the words are taken from. That menu could also be shown with only one list and an "add lists" field.

**Comment by TheZ3ro** [comment]
This is already possible https://github.com/keepassxreboot/keepassxc/issues/978#issuecomment-331441600

I will leave this open as:
> Maybe in the next version I will add a button to the generator/in the settings to load custom worlist easily :wink:

**Comment by phoerious** [comment]
We should add this to the FAQ

**Comment by affinityv** [comment]
How about an option to choose which wordlist to use on the generator page?

**Comment by TheZ3ro** [comment]
@affinityv this is already implemented

**Comment by affinityv** [comment]
Is it in 2.2.1 ?  If so, I can't see how to choose the list.

**Comment by TheZ3ro** [comment]
It will apper only if you have more than 1 wordlist in the folder

**Comment by affinityv** [comment]
Okay, so it only reads the files at app startup time and won't recheck after.  If I have extra files and then remove them or add others, the selection list doesn't change.  The generate button greys out if the chosen selection has been removed though.  Could you make it check the folder each time you go to the password generator, so that it can update in real time?

**Comment by phoerious** [comment]
May I ask why you need to change the word list so frequently? This should rather be a one-off.

**Comment by affinityv** [comment]
I'm sure you are right, it isn't a big deal.  But I think it would be easy to do... but I've got another idea.  Why not have it as a database entry, that way you have it encrypted in your database; just attach files that are wordlists to a special entry.  What do you think?

**Comment by Cor-J** [comment]
Hello,
Import of a wordlist should allow user to specify source encoding. For example, using an utf8 wordlist, keepassXC on Windows doesn't show properly accentuated french letters. The wordlist is opened using system encoding (cp1252).

People looking for a french Windows compatible version of a wordlist see the following issue:
https://github.com/redacted/XKCD-password-generator/issues/115#issuecomment-870584515

**Comment by droidmonkey** [comment]
Implemented in 2.7.0
