### ISSUE TITLE
Copy Notes instead of Password

### ISSUE THREAD

**Issue by Allain18** [keepassxreboot/keepassxc#9891]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Copying password doesn't work after having copied a note

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select Notes of an entry and copy it (either with CTRL-C or right click)
2. Click on the "Copy password to clipboard" button
3. Paste the password (either with CTRL-V or right click)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password is paste

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The note is paste

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
You must unselect the notes before you can copy a password. This is a technical limitation due to occupying the standard copy to clipboard shortcut.  This is reported elsewhere in this issue board.
