### ISSUE TITLE
Add "email" field

### ISSUE THREAD

**Issue by freedriven** [keepassxreboot/keepassxc#9894]
## Summary
Add an email field, same as "username", "URL", etc.

## Context
Many websites do not use email as the username.  Most folks use and manage multiple emails for their online accounts. While I can put the email I used in the notes section, having a unique field for the email would make finding a particular email and sorting on the email much easier.

**Comment by droidmonkey** [comment]
#8228

**Comment by freedriven** [comment]
Thanks, I thought I'd searched for that type of request. But yes!!!
