### ISSUE TITLE
The "Open" button on an attachment does not do anything

### ISSUE THREAD

**Issue by facundobatista** [keepassxreboot/keepassxc#9895]
**NOTE**: names may vary, I see the interface in Spanish, don't know how to put it in English.

## Overview

I have an entry with attachments in the "advanced" tab.

 I select a file (jpeg, pdf, etc), click on the "Open" button, and nothing happens.

## Steps to Reproduce
1.  Create an entry
2. Go to "advanced"
3. in the lower half, "attachments", click on "Add"
4. select a file from your disk, click in OK, the name and size of the file will appear in the attachment list
5. "select" the file (click on it, the row will highlight)
6. click on the "Open button"

## Expected Behavior

It should start an external program passing the selected file, probably `xdg-open` so the file is opened with whatever is configured in the system.

## Actual Behavior

Nothing happens. It doesn't even print something to stdout or stderr.

## Context
```
KeePassXC - Versión 2.7.5
Revisión: 6165975
Distribución: Snap

Qt 5.15.8
Modo de depurado deshabilitado.

Sistema operativo: Ubuntu Core 22
Arquitectura de CPU: x86_64
Núcleo: linux 5.15.0-84-generic

Extensiones habilitadas:
- Autoescritura
- Integración con navegadores
- Agente SSH
- KeeShare
- YubiKey
- Integración con servicio de secretos

Librerías criptográficas:
- Botan 2.19.1
```

**Comment by droidmonkey** [comment]
This is broken at the snap level and there is not much we can do to fix it. Please switch over to the Flatpak distribution.
