### ISSUE TITLE
TOTP doesn't work with GitHub 2FA

### ISSUE THREAD

**Issue by alphapapa** [keepassxreboot/keepassxc#9897]
## Overview
I found https://github.com/keepassxreboot/keepassxc/issues/9869, and I've followed all of the steps, but the TOTP code generated by KeePassXC is not accepted by GitHub, while the one generated by Google Authenticator is.

I've double-checked all of the TOTP settings, including the `otpauth://` URL in the Additional Attributes, and everything matches what GitHub requires: `otpauth://totp/GitHub:alphapapa?secret=DEADBEEF&period=30&digits=6&issuer=GitHub`

I've double-checked that my system time is correct:
```
$ timedatectl
               Local time: Wed 2023-10-04 17:01:59 CDT
           Universal time: Wed 2023-10-04 22:01:59 UTC
                 RTC time: Wed 2023-10-04 22:01:59
                Time zone: America/Chicago (CDT, -0500)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

I don't know what else to do.  Any help would be appreciated.

Thanks for your work on KeePassXC.  It's one of those indispensable programs!

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.10.0-25-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
If you time is absolutely correct, then your secret is wrong.

**Comment by alphapapa** [comment]
I copied and pasted the secret directly from the browser into KeePassXC several times, and visually verified it multiple times.  The secret was entered correctly.

**Comment by droidmonkey** [comment]
I can guarantee to you that there is not a fundamental bug in calculating totp values. The only two errors are system time and secret/digits selection.

**Comment by alphapapa** [comment]
I don't doubt that you're right about there not being a fundamental bug here.  I can't imagine what the problem is, having verified that my system time is accurate and that the secret is entered correctly.  If you can think of anything else I could do to debug this, please let me know.  I would very much like to use KeePassXC for my 2FA codes.

**Comment by droidmonkey** [comment]
Can you try setting up 2fa on another site?

**Comment by rafaelazvdo** [comment]
> I don't doubt that you're right about there not being a fundamental bug here.  I can't imagine what the problem is, having verified that my system time is accurate and that the secret is entered correctly.  If you can think of anything else I could do to debug this, please let me know.  I would very much like to use KeePassXC for my 2FA codes.

Install the Authenticator by myminstorm extension on Firefox and see if the generated OTP code will work.

**Comment by Funami580** [comment]
I wonder if it's a GitHub issue? I can log in fine with TOTP. But if I go to https://github.com/settings/security and want to edit "Authenticator app", the TOTP does not work there.
