### ISSUE TITLE
AutoOpen Functionality Issue with Special Characters in URL

### ISSUE THREAD

**Issue by SamirSaidani** [keepassxreboot/keepassxc#9899]
**Bug Description:**

When utilizing the autoopen functionality in KeePassXC, I have encountered an issue related to special characters, specifically accented characters, within the URL section. The bug prevents proper recognition and processing of accented characters, resulting in failed autoopen attempts.

**Steps to Reproduce:**

1. Open KeePassXC.
2. Use the AutoOpen feature
3. Create an entry into the AutoOpen folder with a URL containing accented characters (e.g., /système/fichier.kdbx).
4. Use the AutoOpen functionality by restarting KeepassXC.

**Expected Behavior:**

The autoopen feature should correctly recognize and process accented characters within the URL, allowing for successful autoopen operations.

**Actual Behavior:**

The autoopen functionality fails to recognize accented characters in the URL section, leading to incorrect autoopen behavior.

**Additional Information:**
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Debug mode is disabled.

Operating System: Ubuntu 22.04.3 LTS
CPU Architecture: x86_64
Kernel: linux 6.2.0-26-generic

Enabled Extensions:

    Auto-Type
    Browser Integration
    SSH Agent
    KeeShare (signed and unsigned sharing)
    YubiKey
    "Secret Service" Integration

Cryptographic Libraries:

    libgcrypt 1.9.4

**Comment by droidmonkey** [comment]
I could not replicate this as all on Windows. Make sure you path is correct.

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/6fca3ad1-219d-4df4-a2cc-af32a9200f28)

You also should update to version 2.7.6
