### ISSUE TITLE
Error Perform auto-enter in a previously opened window does not work

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#9902]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
#[NOTE]: # ( Give a BRIEF summary about your problem )
Error Perform auto entry in a previously opened window does not work instead of auto entry in a previously opened window appears Root Edit Record

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I click on the down arrow, the window for selecting the auto-entry mode appears.
2. A window appears Perform Auto Enter in a previously opened window I click Yes
3. The Root Edit Record window appears

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I was expecting the auto-input function to work correctly

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Not a single auto-input function works, you have to copy it all and paste it manually using copy icons

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
What do you mean by "root edit record "?

**Comment by ghost** [comment]
root<name>change entry 

> Что вы подразумеваете под «корневой записью редактирования»?

root<name>change entry KeepassXC 2.7.6 Applemage Linux Debian

**Comment by droidmonkey** [comment]
That doesn't clarify. Please provide a screenshot

**Comment by gfghjjk** [comment]
![Снимок экрана от 2023-10-06 09-47-12](https://github.com/keepassxreboot/keepassxc/assets/104568809/9ffba454-fc0c-44a4-9b3c-83243431e80f)


> Это не проясняет. Пожалуйста, предоставьте скриншот

**Comment by gfghjjk** [comment]
> ![Снимок экрана от 2023-10-06 09-47-12](https://user-images.githubusercontent.com/104568809/273091217-9ffba454-fc0c-44a4-9b3c-83243431e80f.png)
> 
> > Это не проясняет. Пожалуйста, предоставьте скриншот

![Снимок экрана от 2023-10-06 09-51-07](https://github.com/keepassxreboot/keepassxc/assets/104568809/b8355ca8-422b-4e72-b5c1-266059354206)

**Comment by gfghjjk** [comment]
> > ![Снимок экрана от 2023-10-06 09-47-12](https://user-images.githubusercontent.com/104568809/273091217-9ffba454-fc0c-44a4-9b3c-83243431e80f.png)
> > > Это не проясняет. Пожалуйста, предоставьте скриншот
> 
> ![Снимок экрана от 2023-10-06 09-51-07](https://user-images.githubusercontent.com/104568809/273091614-b8355ca8-422b-4e72-b5c1-266059354206.png)

![Снимок экрана от 2023-10-06 09-52-58](https://github.com/keepassxreboot/keepassxc/assets/104568809/6165a85d-6846-4b1f-ad33-0c3462cca308)

**Comment by droidmonkey** [comment]
Ok, unfortunately I have no idea why your problem is happening or any way to fix it. We explicitly prevent auto type into the KeePassXC window. 

Are you using Wayland?

**Comment by gfghjjk** [comment]
> Это не проясняет. Пожалуйста, предоставьте скриншот

![Снимок экрана от 2023-10-06 09-53-12](https://github.com/keepassxreboot/keepassxc/assets/104568809/e8995b48-9c54-4d9a-8907-7da9a808eef1)

**Comment by gfghjjk** [comment]
> Хорошо, к сожалению, я понятия не имею, почему возникает ваша проблема или как ее исправить. Мы явно запрещаем автоматический ввод в окно KeePassXC.
> 
> Вы используете Вейланд?

![Снимок экрана от 2023-10-06 09-57-26](https://github.com/keepassxreboot/keepassxc/assets/104568809/a0652a71-83f3-47ac-9808-e29156cba454)

**Comment by michaelk83** [comment]
Make sure the github window is the last one that was focused before you try to Auto-Type.
You can also try global Auto-Type: https://keepassxc.org/docs/KeePassXC_UserGuide#_performing_global_auto_type
(What you are doing is entry-level auto-type.)

Lastly, please post here your debug info content from the Help -> About menu.

**Comment by JohnLGalt** [comment]
> Make sure the github window is the last one that was focused before you try to Auto-Type. 

This is why I finally started using the browser add-ons, because with so many windows open, I had to continuously make sure this was the case for manual auto-type to work.

**Comment by ghost** [comment]
> Это не проясняет. Пожалуйста, предоставьте скриншот

![Uploading Снимок экрана от 2023-10-06 09-51-07.png…]()

**Comment by ghost** [comment]
![Снимок экрана от 2023-10-06 09-52-58](https://github.com/keepassxreboot/keepassxc/assets/104568809/2f361dc1-658e-40d4-a907-1e7455830603)
![Снимок экрана от 2023-10-06 09-53-12](https://github.com/keepassxreboot/keepassxc/assets/104568809/c68450e2-2183-4bbf-b69a-9523217564b1)
![Снимок экрана от 2023-10-06 09-47-12-1](https://github.com/keepassxreboot/keepassxc/assets/104568809/53df9d00-91af-4394-8551-7ab4e287e678)
