### ISSUE TITLE
imported keys did not work

### ISSUE THREAD

**Issue by cyberXarmenta** [keepassxreboot/keepassxc#9903]
I imported the public keys to verify the signatures but this is what GPG gave me:

$gpg --verify KeePassXC-*.sig
gpg: no signed data
gpg: can't hash datafile: No data
==========

I even tried it this way too and still did not work:
$gpg --verify KeePassXC-2.7.6-Win64.msi.sig

**Comment by droidmonkey** [comment]
Please follow the instructions here: https://keepassxc.org/verifying-signatures/

**Comment by cyberXarmenta** [comment]
yes. i did. and i tried verifying through Kleopatra as well before i posted this as an issue

**Comment by cyberXarmenta** [comment]
i always do these steps when updating KeePassXC. and never had a problem.

**Comment by droidmonkey** [comment]
The error you are getting is saying that the downloaded data (the msi file) is missing.

**Comment by cyberXarmenta** [comment]
........ xD wow, and it was missing! double checking back and forth thinking i've has everything already downloaded.

thank you! My apologies for wasting your time. lol
