### ISSUE TITLE
Plaintext dates in ISO 8601 instead of base64-encoded binary timestamp in exported XML file

### ISSUE THREAD

**Issue by roomcays** [keepassxreboot/keepassxc#9906]
## Summary

Why timestamps are binary data?

When exporting XML from KeepassXC timestamps are Base64-encoded binary data representing seconds since epoch (and not the Unix Epoch, but the AD, so since `0001-01-01 00:00:00`). Why so?

## Examples
I can imagine exporting one's passwords safe to an XML file to migrate it to other application or some other tasks (like mine: removing entries that I have not used for a year). All, or almost all, data is represented as plain, human-readable text, as it should be for XML file. But there is an exception! Timestamps! I have spent 3+ hours to find out how to decode this (thank you @droidmonkey for help @ matrix channel).

## Context
It is about having XML format as plain as possible.

**Comment by droidmonkey** [comment]
You'll have to take that up with KeePass (original), we didn't invent this XML specification.
