### ISSUE TITLE
Database does not shrink in size when attachments are removed

### ISSUE THREAD

**Issue by snooppr** [keepassxreboot/keepassxc#9907]
I encountered a problem: my database began to weigh in MB, I found what was taking up the size and deleted the file in the 1 MB database, the database should have weighed KB, but it continued to have the same but unreasonably large size in MB, although the file disappeared.

I downloaded this database in my Android and keepass2Android also showed huge size in MB.

I tried (GNU/Linux keepassXC v2.64) to add several more large files to the attachments in the database, saved them, and then deleted them from the database again, the files were deleted, but the size of the database did not decrease.

I tried to resave the database to a new file (where there were no large files), but the new file also weighs a lot (as if deleted files are not deleted, but become invisible). For me it is critical if there is a way to shrink the database.kdbx to its actual size?

**Comment by michaelk83** [comment]
https://github.com/keepassxreboot/keepassxc/issues/9857#issuecomment-1725214199

**Comment by snooppr** [comment]
Thank you It helped, I will close the problem, but something needs to be done about this, this is not an obvious hack for the user.

**Comment by R13e** [comment]
I had the same problem. Thanks for the tip @michaelk83.

**Comment by skyofwing** [comment]
I also had the same problem.Thank you! @michaelk83.
