### ISSUE TITLE
KeePassXC crashes when changing macOS theme colors in System Preferences

### ISSUE THREAD

**Issue by easimon** [keepassxreboot/keepassxc#9908]
## Overview

When changing the highlight color in macOS "System Preferences / Appearance" while KeePassXC is running, KeePassXC crashes instantly. The setting in question is highlighted in the following screenshot:

![image](https://github.com/keepassxreboot/keepassxc/assets/1749657/e6860253-1bf6-46fa-92b3-11ff9a43a746)

## Steps to Reproduce

1. Open KeePassXC
2. Open macOS System Preferences
3. Navigate to "Appearance"
4. Change the Highlight color to something else than it is currently
5. -> Crash

## Expected Behavior

KeepassXC does not crash.

## Actual Behavior

KeepassXC crashes immediately, and the following dialog appears.

<img width="372" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/1749657/00d4c4c2-69e5-4157-b9ee-623303d46b6a">

## Context

About KeepassXC:
```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.0
CPU architecture: arm64
Kernel: darwin 23.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3
```

Operating System: macOS 14.0 (Sonoma)

**Comment by droidmonkey** [comment]
This is a duplicate report. Search for "highlight color"

**Comment by easimon** [comment]
Sorry, I did not find this for some reason. For the record: Duplicate of #9527
