### ISSUE TITLE
Tools → Settings → Auto-Type tab Missing

### ISSUE THREAD

**Issue by spinkyspider** [keepassxreboot/keepassxc#9909]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # Auto-Type tab Missing v2.7.6 Flatpak install (Alpine Linux)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Flatpak install of v2.7.6
2. (distro apk install of v2.7.5 had the tab)

## Expected Behavior
[NOTE]: # Isn't there.

## Actual Behavior
[NOTE]: # Should be there.

## Context
[NOTE]: # Removed v2.7.6 apk, installed v2.7.6 flatpak, lost my global autotype keystroke

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.1.55-0-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Alpine Linux 3.18.4
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Auto-Type is not supported under Wayland

**Comment by spinkyspider** [comment]
So, is this from the flatpak in KDE?  Because 2.7.5 worked in Wayland/Gnome from my OS repository.

**Comment by droidmonkey** [comment]
It must have been running using X11.

**Comment by spinkyspider** [comment]
My system is gnome/wayland.  Literally uninstalled one version and installed the other.  So, XWayland?  And if so, why not build the flatpak that way?

**Comment by droidmonkey** [comment]
You would have to run the flatpak using X11 instead of Wayland. It is not built that way, just how your environment is setup. 

`--socket=x11` should do the trick
