### ISSUE TITLE
Default folder opening

### ISSUE THREAD

**Issue by rcmsoftwaredevelopment** [keepassxreboot/keepassxc#9913]
When I open my keepass I have all my folders on the left and if I have no accounts selected as is the case when I first open keepass, the right side is blank.  On my partners keepass every time she opens it all of her accounts are listed in the right window, even though none are selected.  What is the option for the accounts to not be listed.

**Comment by droidmonkey** [comment]
You would need to put your entries (accounts) into the root group (the one on the top left).
