### ISSUE TITLE
KeePassXC Flatpak issues

### ISSUE THREAD

**Issue by Querzion** [keepassxreboot/keepassxc#9914]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install Flatpak/Snap KeePassXC & KeePassXC-Browser(in a flatpak or snap based browser)
2. Try to connect KeePassXC to a network storage. 
3. Try to connect KeePassXC-Browser to KeePassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
In a perfect world, the containers (Flatpak & Snap), will have automagic capability to access a network storage, and to the browser extension, but in this reality, containers have just been created and the same problem have been persisting for years. I love flatpak's logically, but they are not ideal, I end up always installing other versions, when it comes to browsers and KeePassXC in order to walk around the problems that aren't fixed. It's like you don't even test out the different releases. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
As I said, in a perfect world they just connect to each other, regardless if it's a bin/snap/flatpak etc. browser release, and it should also not have access issues into network storages. I use fedora 39 beta now, and I only got it to work with Firefox and if KeePassXC was installed as an RPM. The flatpak wouldn't get granted access to where I actually have my password databases. Brave that is a flatpak can't connect with the database at all, but if it hadn't been a container install, I'm pretty sure it would had worked, since it has always worked in the past. 

This might be a Flatpak/Snap container only problem, since it seems as though that they are just unable to get the needed access granted to them respectively. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - EVERY VERSION IS LIKE THIS, as I wrote it's been like this for years. Regardless of which 2.x version I have used.
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Any Linux based distro. Doesn't matter. 
Desktop Env: Any Linux GUI. Doesn't matter.
Windowing System: Anyone of them. 

It's a access granting issue with containers between containers regarding Snap and Flatpak, update the requirements in the package, and if you can't do that, then give people information through the stores, that explicitly states it's a problem and tell them what to install and what to change in order to grant the access between the chosen containers, Brave browser is the one that I have the most problems connecting too, but I don't think it's brave in itself, but rather the container access/communication limitations.

**Comment by droidmonkey** [comment]
It's written on here many times, flatpak browsers _do not support_ native messaging. That is not our fault.

Only Firefox as a snap (and maybe only on ubuntu) supports native messaging. Of course native installed browsers work fine as well. 

Welcome to Linux, where there are standards that no one follows.

**Comment by droidmonkey** [comment]
Can you provide more information on your network storage issues?

**Comment by Querzion** [comment]
I share space on my HDD's through unRaid as Network Shares. 
In Windows it works fine. In ArcoLinux the network share keeps getting a new name so I have to add the database after every reboot, in Fedora I noticed this isn't a problem the path doesn't change, but I had another problem which was that when I browse for the database, go to the network and my shares there's no prompt popping up stating I need to login to the share, but just stated an error message. If I used the distro file explorer instead and connected to the share that way, I was able to set my credentials, save them and connect, then I thought I would be able to connect to the network share, I ended up using a USB instead in my frustration. 

I thought it worked now, but no. 

I have to first open the native file explorer, open the share, log in, then bookmark it. I can now through KeepassXC access the folder, but when I try to use the password database, KeepassXC locks up. First time I have gotten that response from it. I thought the ARCH giving me different network share file path's with every reboot was irritating, but this is worse.

**Comment by Querzion** [comment]
I use btop, so when I search for keepass i get tree processes, 1 keypassxc & 2 bwrap's and there's 0.0 CPU % usage.

**Comment by MarkWieczorek** [comment]
Could someone please let me know how it is that you get KeepassXC and Firefox to work on a Fedora system? There is no documentation about this on the website.

I started by installing the flatpak versions of each, but as noted above, this doesn't work. I then uninstalled the flatpak versions, and instead installed the fedora RPM versions for both, but this doesn't seem to work either. When I try to connect the database in Firefox, it says "No connected databases found." (yes, I enabled browser integration in the app).

Once we have a solution, we should add this information to the the documentation and FAQ web page (https://keepassxc.org/docs/).

**Comment by droidmonkey** [comment]
Works right out the box following these instructions: https://keepassxc.org/docs/KeePassXC_GettingStarted#_setup_browser_integration

I just tested this in Fedora 38.

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/26b3fc6a-d511-4fb0-9aa3-b9aaac45698e)

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/c6457437-49d5-4f74-85c4-da872adb1ed5)

KeePassXC installed as Flatpak.

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/ea5c45f9-bf49-4f1f-badb-c8d3bca19cb1)

**Comment by MarkWieczorek** [comment]
Well, its not working for me. (This works fine for me on macos, so I know how to configure everything, in principle...)

KeepassXC debug
```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Fedora Linux 38 (Thirty Eight)
CPU architecture: x86_64
Kernel: linux 6.5.7-200.fc38.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

KeepassXC dfn info
```
Name         : keepassxc
Version      : 2.7.6
Release      : 2.fc38
Architecture : x86_64
Size         : 26 M
Source       : keepassxc-2.7.6-2.fc38.src.rpm
Repository   : @System
From repo    : updates
```
Firefox
```
Name         : firefox
Version      : 118.0.2
Release      : 1.fc38
Architecture : x86_64
Size         : 194 M
Source       : firefox-118.0.2-1.fc38.src.rpm
Repository   : @System
From repo    : updates
```

**Comment by droidmonkey** [comment]
You might have a Firefox apparmor profile being applied? It's impossible to tell without you doing some deep debugging. Unfortunately Linux let's you shoot yourself in the foot about 200 ways. 

See here: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
