### ISSUE TITLE
Can't use two security keys

### ISSUE THREAD

**Issue by AirFlowW** [keepassxreboot/keepassxc#9917]
## Overview
I have to yubikeys and want to encrypt my database with both of them.
I have encrypted my database with a strong password and with challenge-response on the yubikey side.
I gave both yubikeys the same secret key in the challenge-response interface.

But when I try to unlock the database with the 'second' key, keepassxc disclaims that it has to be the same key. It is looking for a yubikey with the serial number of the 'first' yubikey. That's not necessarily a bug. It would be great if one is able to enable or disable this feature. 

Because now I have to always do a backup of my database and change the yubikey to the 'second' there by my own, to be prepared if I lose the 'first'.

**Comment by droidmonkey** [comment]
We only block _saving_ a database using the same serial numbered key. Unlocking does not have a key affinity. Are you sure you programmed both with the same secret?

**Comment by AirFlowW** [comment]
You are completely right, thanks I guess I somehow did not put the right thing into the clipboard.
