### ISSUE TITLE
Always see pop-up window with Entries during Global Auto Type on MacOS 14.0 Macbook M1

### ISSUE THREAD

**Issue by Dobrinia13** [keepassxreboot/keepassxc#9918]
## Overview
I have configured Global Auto type shortcut  (in my case ⌥⌘A)and tried to use it but everytime I see the pop-up window when I have to choose the correct entry. I have configured entry and have chosen Window Association in the Entry Auto-type configuration but somehow it can't detect the window. 
I have left the only one Entry which suits this Window but I have to click on the necessary Entry. I have disabled "Always ask before performing Auto-Type" option in the configuration but it didn't help. I always see it. 

## Steps to Reproduce
1. Install KeepassXC on MacOS 14.0 Macbook M1
2. Configure Global Auto type shortcut in the settings
3. Disable "Always ask before performing Auto-Type" option in the Settings. 
4. Configure "Window Association" in the Entry config
5. Press Global Auto type shortcut and wait for the pop-up window with Entry list
6. Double click on Entry and auto type is working

## Expected Behavior
Don't expect to see pop-up window with Entry list

## Actual Behavior
After Global Auto type shortcut I see the pop-up window with Entry list

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.0
CPU architecture: arm64
Kernel: darwin 23.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
If you are seeing the entry selection list, then that means your window associations are not working. You likely need to add a wildcard (*) to account for window titles that change.

**Comment by Dobrinia13** [comment]
Hi @droidmonkey ,

I guess you are right, the problem is thet my window associations are not working. How to get additional logs and identify the reason for this? I have added "*" for Window ssociation and I don't see any difference. 
Before on MacOS 13.5 it worked as expected.

**Comment by droidmonkey** [comment]
This could be an issue with MacOS 14. I'll have to test now that my upgrade is finished.

**Comment by droidmonkey** [comment]
I have can see no issue with window associations in macOS 14. Closing unless you can specify how to reproduce the problem.
