### ISSUE TITLE
Setting `RememberLastKeyFiles`=`true` only taken into account for `OpenPreviousDatabasesOnStartup`, not AutoOpened databases

### ISSUE THREAD

**Issue by knobhead** [keepassxreboot/keepassxc#9920]
## Overview
Last used key files and security keys (yubikey etc) are not always remembered and considered, even if this setting is active.
In fact, it is only remembered and used when "Load previously open databases on startup" is checked.

## Steps to Reproduce
1. I aactivate the checkbox "Load previously open databases on startup" in settings.
2. I activate the checkbox "Remember database key files and security dongles".
3. I manually open and unlock databases, one of them requires a hardware security key.
4. I close KeePassXC.
5. Open KeePassXC (hardware security key is plugged in).
6. All databases are opened again, when I enter my password the security key is preselected.
7. I DEactivate the checkbox "Load previously open databases on startup" in settings.
8. I close opened databases.
9. I restart KeePassXC.
10. I manually open and unlock a database that references other databases in the "AutoOpen" folder.

## Actual Behavior
The referenced database is auto-opened, the password field prefilled but the "Hardware Key"-field is populated, but not pre-selected (see yellow circled section in animated screenshot). My hardware security key is plugged in. The Database is not auto-opened, instead KeepassCX gives an error notification about wrong HMAC.

![KeepassXC AutoOpen HMAC Yubikey](https://github.com/keepassxreboot/keepassxc/assets/6553961/13e8daa5-8937-4541-a326-ef76668052f8)

## Expected Behavior
The separated checkboxes indicate that the second setting will be considered indepently of the first.

Hence, when manually opening a database that KeePassXC remembers a hardware security dongle for, the security key should be preselected, if the hardware security key is plugged in. 

## Note

If fixing this would not be intended behaviour for one or the other reason, the checkboxes in settings would have to be linked to each other and labelled more clearly. I'd prefer the expected behaviour, though.

## Context

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Please note this is NOT a duplicate of #8745.

🙏 Thanks for your work for KeePassXC, really appreciated! 👍

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/4351
