### ISSUE TITLE
Add ability to control order of additional attributes

### ISSUE THREAD

**Issue by nobody7356** [keepassxreboot/keepassxc#9925]
## Summary
Add ability to control order of additional attributes

## Examples
<img width="978" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/147700309/21d1b9c1-8db3-4713-b55c-065c521d6dcc">

## Context
For example, I want change order and set "Recovery Code" first and "Credit Card Used" must be second

**Comment by droidmonkey** [comment]
There is no ordering of attributes, this would be a breaking change to the program and is not part of the kdbx specification. If you want to order them in the user interface, choose names that are in alphabetical order. We won't be able to implement a forced ordering.

**Comment by JohnLGalt** [comment]
> choose names that are in alphabetical order. We won't be able to implement a forced ordering.

^^^^^^ this.

- 01 Recovery Code
- 02 Credit Card Used

This is how I've always named my additional attributes, allowing me to list them in the order I define.
