### ISSUE TITLE
Character spacing gone wrong after some time

### ISSUE THREAD

**Issue by paulsantek** [keepassxreboot/keepassxc#9926]
## Overview
After several days not closing KeePassXC character spacing doesn't work any more. Characters in fields e.g. username, URL, search are written on top of each other instead of next to each other. After closing and reopening everything looks normal again.
![2023-10-12-11-59-20-555](https://github.com/keepassxreboot/keepassxc/assets/117314523/709fc09b-2a48-4910-a654-17ba1e32218c)

## Steps to Reproduce
Have the application running for several days, only lock the screen over night. At some point the text formatting is no more.

## Expected Behavior
Text is kept readable

## Actual Behavior
All user input text is the width of a single character

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating system: macOS 14.0
CPU architecture: arm64
Kernel: darwin 23.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare

- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
This is a qt bug on macos, nothing we can do about it unfortunately. #8758

**Comment by paulsantek** [comment]
Thank you for that info - appreciate your fast reply
