### ISSUE TITLE
Database won't unlock after pkcs certificate renewal 

### ISSUE THREAD

**Issue by Heyji2** [keepassxreboot/keepassxc#9928]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have a database that I used to open with a gemalto usb key (Pkcs11 Key) and an empty password. After having renewed the certificate within my usb key, the database does not open anymore and I get an error message.  

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new empty database
2. Do not provide a password
3. Select a token to be used to unlock the database
4. Save the database
5. Check you can open it correctly (without providing any password, but the PIN of the token)
6. Close the database
7. Renew the certificate (validity period) of your token
8. try opening the database again with your token

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I am expecting to be able to open the database with the same token, eventhough the validity period of the token has been extended. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
A pop-up ask for the PIN of the token. then I get a red banner stating: Encrypted data is invalid. 

Another pop-up appears with a message (in french in my case) stating that the database could not be unlocked and that no password has been typed (in the title). The core of the message is (my translation): 

Unlocking the database has failed and you have not provided any password. Do you want to try again without password. 

Whatever option I choose, the database does not unlock. 

Then a second red banner says that invalid credentials have been provided (which is wrong) and that the database could be corrupted (which is not likely) and finally that HMAC does not correspond (which is not something I can act on). 

If, intentionally, I provide a wrong PIN for the token, I get a different message: "The specified PIN is incorrect. Enter PIN for xxxx:". 

## Context
[NOTE]: # ( Give us any additional information you may have. )
The first time that happened, I created a new database. One year later, I fill a ticket as I believe this is a bug. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0-snapshot
Revision: 5a73d47

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
We don't support PKCS#11 so not sure how this was ever possible. However I have terrible news for you, if you don't have a backup of the old private key then you will never be able to open your database again.

**Comment by Heyji2** [comment]
I see. I may run a fork that have been adapted for pkcs11 certificates. I had not noticed you would not support pkcs11. I will then ask to the right people.
