### ISSUE TITLE
Hide Groups in View Menu no there?

### ISSUE THREAD

**Issue by Nou4r** [keepassxreboot/keepassxc#9933]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I have my groups hidden in a older update of KeepassXC and now i wanted to see them again but KeepassXC doesn't have that option anymore it seems
![image](https://github.com/keepassxreboot/keepassxc/assets/12816677/dffaf774-b940-4493-8431-2551a25624b8)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Drag from the left hand side to show the group panel again

![2023-10-14_10-57-52](https://github.com/keepassxreboot/keepassxc/assets/2809491/79beeb8e-6f2b-41b1-9872-870dfd4b87c7)
