### ISSUE TITLE
Better intergration with alt-tab MacOS

### ISSUE THREAD

**Issue by huyhoang8398** [keepassxreboot/keepassxc#9934]
## Summary

KeepassXC does not work well with alt-tab application on MacOS
Forward from this issue: [this](https://github.com/lwouis/alt-tab-macos/issues/2884)

**Comment by droidmonkey** [comment]
By design, we block screenshots.

**Comment by huyhoang8398** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/25379882/9e417fde-18be-4443-88bc-a36466784eb6)
But it is working on Linux

**Comment by droidmonkey** [comment]
There is no screenshot protection possible on linux.
