### ISSUE TITLE
History's Difference Column Not Properly Updated/Refreshed on Delete

### ISSUE THREAD

**Issue by zellchristensen** [keepassxreboot/keepassxc#9936]
## Overview
When deleting entries in the History section, the Difference column is static and just has the lowest entries removed from the bottom no matter which entry is deleted.  The Last Modified, Age, and Size columns all update properly.

See video:

https://github.com/keepassxreboot/keepassxc/assets/38737447/68100964-620a-4d9b-9474-3742ff1f84c2

## Steps to Reproduce
Delete History lines from an entry.

## Expected Behavior
Column updates like the rest.

## Actual Behavior
Column does not update.

## Context
The column is updated properly once the entry is saved and you open the history again so there doesn't seem to be any loss of data, but there was a moment of panic when first removing some entries and seeing key changes in the past no longer being displayed.

## Debug info, Win7 and Win10
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock (Win10 only)

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Nice find, this is an easy fix
