### ISSUE TITLE
KeePassXC Unable to Browse Within Google Drive folder

### ISSUE THREAD

**Issue by jneuls** [keepassxreboot/keepassxc#9937]
## Overview
Cannot browse to folders or files contained in one's Google Drive folder and, as a result, cannot open my database file that is sync'd via the Google Drive for Windows application.

## Steps to Reproduce
1. Open KeeePassXC
2. Attempt to browse to your Google Drive folder (configured in the Google Drive app).
3. Receive error message: `The path cannot be traversed because it contains an untrusted mount point.`

![KeePassXC-GoogleDriveFolderErrorMessage](https://github.com/keepassxreboot/keepassxc/assets/8327077/7af45b6c-a86c-4195-a3b3-e7f8e2c1be60)

## Expected Behavior
I expected KeePassXC to browse to my database file.

## Actual Behavior
KeePassXC is not able to browse to my database file.
Current Workaround: Via Windows Explorer, have made a copy of the database file and placed it outside of the Google Drive folder hierarchy, which KeePassXC is able to open without issue.  No changes will propagate to or from other devices, though, so this definitely isn't a 100% functionality workaround.

## Context
Recently updated KeePassXC from v2.7.4 to v2.7.6.  As a troubleshooting step, I did uninstall and reinstall KeePassXC, as well.  2.7.4 did not exhibit this behavior.  Windows Explorer exhibits no difficulty browsing within my Google Drive folder before or after changing KeePassXC versions.

Google Drive for Windows version: 82.0.1.0

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
This isn't an issue with our application. You need to either move your Google drive to the same drive where keepassxc is installed (like your user folder where it usually goes) or you need to reinstall using the msi or zip distribution. I suspect you installed with the windows store.

**Comment by jneuls** [comment]
You are partially correct in that I did, briefly, have the Microsoft Store version installed.  In researching this issue, I came across a mention of a similar issue someone had with an entirely different app.  I promptly uninstalled the Microsoft Store version, downloaded the MSI installer, and reinstalled from that.  The issue persisted.  I uninstalled again - even going as far as to check via PowerShell if it had record of any package name containing "kee", "pass", or "xc" that I could nuke.  I found noothing.  So, having no other options, I went through and cleared the Registry of every mention of "KeePass".  Reinstalled from MSI again... the issue persists.

I guess the moral of the story is don't install things from the Microsoft Store which, I guess... fair enough, right?  I visited that accursed place, I get what I get.  The Microsoft Store never leads to hugs and puppies, after all.

**Comment by droidmonkey** [comment]
I don't necessarily think this is a Microsoft store problem, per say. It seems to pop up in the Google search. 

I actually don't think this is on our side anyway. However, you installed Google Drive it is using some other drive mounted in some weird way. Does that drive use NTFS?

**Comment by JohnLGalt** [comment]
Hmmm.

I use the portable version of KeePassXC, and have Google Drive FS installed with the Drive folder mapped to the drive G: by default - and I Have 0 issues navigating it from inside the KeePassXC app. The Google Drive FS installer automatically allows the user to select a drive letter to map during setup, defaulting to G:, but any available drive letter can be selected.

<img width="416" alt="Screenshot 2023-10-16 134841" src="https://github.com/keepassxreboot/keepassxc/assets/7432512/fc8d164b-098b-498e-a8bf-fdee454623a5">

I've been using Google Drive FS since Google released it for personal account use, and have no issues with it at all, both KeePassXC stable and KPXC snapshot builds.

Windows 11 22H2 build 22621.2428
Google Drive v 82.0.1.0

**Comment by jneuls** [comment]
I am using the "Folder" configuration option instead of the "Drive Letter" configuration option, though, I have never had a single problem with KPXC accessing that folder prior to (foolishly) installing the Microsoft Store version.  Now it seems like... I dunno?  It's just stuck in "Microsoft Store mode" or something?  I mean, I *literally* scrubbed the Registry in addition to reinstalling fresh.  I don't even know where else one would look to try to resolve this.  Maybe I'll try the portable version, I guess?

![GoogleDriveConfig](https://github.com/keepassxreboot/keepassxc/assets/8327077/4f7547d7-1b5d-4ec6-9e4f-9551e278d3f8)

**Comment by JohnLGalt** [comment]
Do you actually have a `G:\` drive on your system? That's like the 5th letter after B, so ....

Also, have you tried running at admin? And checked the permissions on that folder?

**Comment by droidmonkey** [comment]
Was going to ask what the heck your G drive actually is? Sounds like a USB drive or a veracrypt mount.

**Comment by JohnLGalt** [comment]
Lol - uh, _maybe_?

https://valid.x86.fr/20gzlc

I have 3 internal + 3 external (all NVMe) drives, along with Google Drive occupying `G:` and my BDRW occupying `F:`.

So I can have `C:` though `J:` populated at any given moment if I attach all three externals lol.

But it does seem odd - most people don't go drive happy like I am.

Could also be drive letter assigned partitions, for all we know.

**Comment by droidmonkey** [comment]
That question was for @jneuls

**Comment by JohnLGalt** [comment]
No, I know it was - I'm just saying it is possibly a legitimate location.

**Comment by jneuls** [comment]
> Was going to ask what the heck your G drive actually is? Sounds like a USB drive or a veracrypt mount.

> Do you actually have a `G:\` drive on your system? That's like the 5th letter after B, so ....
> 
> Also, have you tried running at admin? And checked the permissions on that folder?

I do actually have a G drive on my PC.  It's an SSD that I, long ago, had completely dedicated to just Google Drive (which is why it's the G drive - G for Google).  It isn't exclusively for Google Drive anymore but I do still have a lot of stuff that I keep available offline, which is why I keep it off on it's own SSD.

As for running KPXC with elevated privileges, I _had not_ tried that.  I just did and **_it frickin' worked._**

New workaround discovered!  Big ups to @JohnLGalt for thinking of the thing to make the thing do the thing.  😁

**Comment by droidmonkey** [comment]
We don't recommend running as administrator (which is why we don't mention it). That does indicate that this is not a KeePassXC problem, but a permissions issue on your system. Likely completely unrelated to your use of Microsoft store.

**Comment by JohnLGalt** [comment]
Yeah, I suggested it as a test - which means there is nothing wrong with the file, but something wrong with your access to the file / folder when _not_ running as admin. So, that is what you need to look at next.
