### ISSUE TITLE
Nitrokey not reliably detected as hardware key

### ISSUE THREAD

**Issue by mepi0011** [keepassxreboot/keepassxc#9941]
## Overview
KeePassXC only detects the Nitrokey if I have already plugged it in before the user logged in.
I can also unplug the stick and plug it back in, KeePassXC finds it again (sometimes only after the second search).

## Steps to Reproduce
1.  connect Nitrokey bevor/after user login

## Expected Behavior
Nitrokey will be detected by KeePassXC even if it is connected after the user has logged in.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC only recognizes the Nitrokey if I have already plugged it in before the user logs in. Afterwards I can also unplug the stick and plug it in again, KeePassXC finds it again (sometimes only after the second or third search).  

When I plug in the Nitrokey after the user login, KeepAssXC does not find the Nitrokey even after searching several times

## Context
[NOTE]: # ( Give us any additional information you may have. )
Nitrokey Firmware - v1.5.0

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro LInux
Desktop Env: KDE

**Comment by droidmonkey** [comment]
I assume you are using Flatpak or Snap, unfortunately that is a problem with the portals of the sandbox environment and not something that KeePassXC can control. You can try quitting KeepassXC and restarting the application to enable use of the hardware key.

**Comment by mepi0011** [comment]
I can exclude this, because I do not use flatpack or snap packages. Everything is installed "normally". I assume that it is a problem with the timing and the nitrokey does not respond fast enough. I would like to contribute more information (log file etc.)  to solve the problem, but have no idea how.

I am surprised that the ticket was closed immediately without any further questions.

**Comment by droidmonkey** [comment]
Startup problems are always timing related. Mostly the nitrokey may not be registering properly with udev or similar service. We don't support specific device or interface issues if it works "sometimes". That is almost always a local environment problem.

**Comment by droidmonkey** [comment]
> When I plug in the Nitrokey after the user login, KeepAssXC does not find the Nitrokey even after searching several times

This would indicate a udev or similar device registration to the os problem. It would be a keepassxc problem if it didn't work at all.

**Comment by mepi0011** [comment]
In the meantime, I investigated the problem further. The problem is that the Nitrokey must be plugged in before KeePassXC starts. Only then it will be found and can be used. I was able to replicate the behavior on three different computers (2x Manjaro / 2x Kubuntu). The behavior is also reported [in the Nitrokey forum by others](https://support.nitrokey.com/t/nitrokey-3-not-detected-by-keepassxc-on-arch-linux/5507/16). 

The Ticket #8213 describes a similar behavior.

**Comment by kevin0t** [comment]
For me i tried a bunch of fixes with the App-image of latest keepassxc version on linux mint and fedora  but nitrokey 3 wasn't detect. I tried setting udev rules , pcscd service etc but none worked.

Then somebody suggested me to use flatpak and it just worked ! Not sure what the problem with appimage is as no matter what i try it won't detect.
