### ISSUE TITLE
Integration problems with Gnome DE on Wayland

### ISSUE THREAD

**Issue by joshas** [keepassxreboot/keepassxc#9943]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Considering that KeepassXC is Qt application, it is expected to see a few minor issues when running it on Gnome desktop environment and especially on Wayland. I assume that issues are not the fault of KeepassXC, and I hope to get help finding projects where they should be reported, e.g. shell, compositor or styling library.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeepassXC
2. Try switching to another application with Alt+Tab and getting back using same combination to KeepassXC.
3. Open "About" dialog.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Application window is styled like other applications in Gnome desktop environment: close button on window titlebar has icon, main window has shadow like other applications, menus do not have too big margins, about dialog has shadow and window title bar.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Switching back to KeepassXC using Alt+Tab doesn't work, as it is missing from applications list; it appears in task switcher after some time, though. Window shadow looks strange, seems to be shorter and darker compared to other no-Qt applications. Close button in window title bar is missing an icon, menus open with big margins around them, and about dialog does not have neither shadow, nor title bar.

![Screenshot from 2023-10-19 19-02-58](https://github.com/keepassxreboot/keepassxc/assets/79141/6e818e24-126e-481d-86a0-6eb404f213cf)

![Screenshot from 2023-10-19 19-04-35](https://github.com/keepassxreboot/keepassxc/assets/79141/021b5427-56a0-4ec2-84d4-0e33b54abc18)

## Context
[NOTE]: # ( Give us any additional information you may have. )
Starting application from Terminal displays several warnings:
````
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.qgnomeplatform.theme: The desktop style for QtQuick Controls 2 applications is not available on the system (qqc2-desktop-style). The application may look broken.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
````

I've tried installing `qqc2-desktop-style` package, but then only KDE like looking close button icon appeared in title bar.

![Screenshot from 2023-10-18 19-49-59](https://github.com/keepassxreboot/keepassxc/assets/79141/17d31b64-a4df-4f7d-bb00-09947dfade78)

> xcb.patch [...] in the Fedora keepassxc repository is in fact disabled

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

CPU architecture: x86_64
Kernel: linux 6.5.6-200.fc38.x86_64

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora Linux 38 (Workstation Edition)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
All of these issues are either gnome or qt

**Comment by ericzolf** [comment]
I have the issue with the missing window button icon, other Qt5 applications (vlc and chromium) don't have the issue though, so there is also something specific to KeepassXC. Any hint?
(also Fedora, exactly the same specs)

**Comment by joshas** [comment]
I've tried running VLC in Terminal, and it too displays same error message about `qqc2-desktop-style`, but titlebar and window decorations looks decent, while still not absolutely in line with either GTK 3 or Adwaita theming.
````
qt.qpa.qgnomeplatform.theme: The desktop style for QtQuick Controls 2 applications is not available on the system (qqc2-desktop-style). The application may look broken.
````
After a bit of looking around, it turns out VLC is using XWayland, that's why it has different window decorations than KeepassXC. Same probably for other applications that appear to be working on Wayland.

**Comment by droidmonkey** [comment]
This isn't a problem with KeePassXC, you'll have to direct your concern with either Qt or Gnome.
