### ISSUE TITLE
Firefox has intermittent connection to KeePassXC via extension

### ISSUE THREAD

**Issue by ferenczy** [keepassxreboot/keepassxc#9944]
## Overview

I have just installed a new system so I have been setting up fresh browser integration in Vivaldi and Firefox. Not very successfully. 

## Steps to Reproduce

1. [Install the Vivaldi browser](https://help.vivaldi.com/desktop/install-update/install-the-vivaldi-browser/)
2. Install the [KeePassXC-Browser extension](https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk)
3. Install KeePassXC (`apt install keepassxc`)
4. Run KeePassXC, navigate to the _Settings_ > _Browser integration_
5. Check _Enable browser intergation_ and _Vivaldi_ under _Enable integration for these browsers_
6. Open a KeePass database
7. Open KeePassXC-Browser _Settings_ and select _Connected databases_
8. Click _Connect_ - **nothing happens**

## Expected Behavior

A database connection is set up.

## Actual Behavior

Nothing.

## Workaround

1. In KeePassXC _Settings_ > _Browser integration_, check _Google Chrome_ under _Enable integration for these browsers_
2. Restart both KeePassXC and Vivaldi
3. Repeat the database connection set up again, **it should succeed now**

## Firefox issue

I have uninstalled the Firefox snap package that's installed by default on Ubuntu and installed it from a DEB package (see [this howto](https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04) for details), because snaps are supposed to be unsupported in the browser integration.

I have enabled _Firefox_ under _Enable integration for these browsers_ in KeePassXC _Settings_ > _Browser integration_ and restarted both KeePassXC and Firefox.

I have tried to set up the database connection in KeePassXC-Browser the same way as described, but nothing happens when I click _Connect_. I haven't found any way to successfully connect the Firefox browser to KeePassXC.

## Info

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu 22.04.3 64bit)
Desktop Env: XFCE4
Windowing System: X11

**Comment by ferenczy** [comment]
I think I just found a workaround for Firefox also. I had to enable also _Chromium_ under _Enable integration for these browsers_ in KeePass _Settings_ > _Browser integration_.

So, in my case, to enable the browser integration for Vivaldi, I actually need to check _Google Chrome_ and for Firefox, I need _Chromium_. Actually, both are needed - _Firefox_ and _Chromium_. If any of those is not checked, then I'm unable to connect a database in Firefox. Vivaldi works even when _Vivaldi_ is unchecked, so only _Google Chrome_ is needed for that browser.

Currently, those settings in KeePassXC make the whole process very confusing, it took me many hours to figure out the working configuration.

**Comment by droidmonkey** [comment]
There is no way that the chromium checkbox makes firefox work. They use an entirely different extension id for the native messaging manifest file.

Also, Firefox snap supports native messaging.

**Comment by varjolintu** [comment]
Sometimes browsers are not using their own config file paths for Native Messaging (don't ask me why), and things get confusing. There's nothing KeePassXC can do.

Firefox cannot connect if Chromium is checked. The whole script file differs between Firefox and Chromium based browsers. So there's definitely something else going on here.

**Comment by droidmonkey** [comment]
I just instantiated a new Ubuntu 22.04 with Gnome and installed Vivaldi and Firefox. I was able to connect to Flatpak KeePassXC with Vivaldi instantly. I was unable to connect to Firefox, it looks like Firefox may have changed the way they interact with native messaging clients. The instance of KeePassXC just keeps popping into the foreground which means the invocation of the proxy is failing (it is actually invoking the main application).

**Comment by IceTrayz** [comment]
https://discourse.ubuntu.com/t/call-for-testing-native-messaging-support-in-the-firefox-snap/29759/120

Apologies if i've got the wrong end of the stick and this has nothing to do with the issue but there are few posts from August onwards in the above thread about native messaging with mixed results.

**Comment by droidmonkey** [comment]
So there is a bug in stable release but not beta?

**Comment by IceTrayz** [comment]
Not sure to be honest, I vaguely remember in the past that sandbox permissions were being tested in the beta version but i thought that was resolved?

Sorry i can't help with trying the Beta as i'm not currently running snap,maybe someone else can try it and see.

**Comment by user23498723452** [comment]
Hey,  I just had to rebuild my Brave browser (on Ubuntu 20.04) and I found that when trying to re-setup the plugin (and entire Brave profile),  it would not connect to my database,  no matter what.

I even tried to manually create the 'org.keepassxc.keepassxc_browser.json' file, based on my old Brave browsers config.  I ensured the file path was accurate. (it was a new version of the snap)

  I had to go into KeepassXC settings and uncheck/recheckmark the Brave Browser Integration entry.  

It now seems to be working normally.

**Comment by ferenczy** [comment]
> There is no way that the chromium checkbox makes firefox work. They use an entirely different extension id for the native messaging manifest file.
> 
> Also, Firefox snap supports native messaging.

Of course, sorry. I have been so frustrated by messing with it and not being able to make it work that I didn't think about that a bit when it has finally started to work.

Currently, it (sometimes) works in both the Firefox and Vivaldi, but I'm not exactly sure what has helped where and I don't want to mess with it any more to prevent it from breaking again.

Anyway, I have both the Firefox and Vivaldi installed from a DEB package and I have the following browsers checked in the _Browser Integration_ settings: Google Chrome, Chromium and Firefox. The rest including the Vivaldi are unchecked.

But it's very unreliable. Without changing any configuration regarding the browser integration, it starts and stops working randomly. Currently, it doesn't work in Firefox, the browser extension reports the following error message when I open it for the first time:

    Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

When I click _Reload_, the error message changes to:

    Key exchange was not successful.

Occasionally, it also shows this:

    Cannot decrypt message

And it has also happened, that after clicking the _Reload_ button several times, it just successfully connected and started to work. I didn't change anything meanwhile, just clicked _Reload_.

Any idea how to debug this/what to look for, please?

**Comment by varjolintu** [comment]
@ferenczy Any logs from the JavaScript console (both background and content scripts) would help. See instructions from [here](https://github.com/keepassxreboot/keepassxc-browser/wiki/HowTo:-Special-situations-and-debugging) how to debug both of them and getting the console visible. It has its own tab.

**Comment by droidmonkey** [comment]
I find Firefox has been shipping with a restrictive AppArmor policy lately and it is totally unknown to the end users.

**Comment by ferenczy** [comment]
@droidmonkey Sorry, but why have you changed the title of this issue? I not using Snap either Flatpak. I have everything - the KeePassXC, Firefox and Vivaldi - installed from DEB packages as I mentioned in my original post. I didn't want to introduce other potential sources of issues.

OK, it's irrelevant now.

**Comment by varjolintu** [comment]
> @droidmonkey Sorry, but have you changed the title of this issue? I not using Snap either Flatpak. I have everything - the KeePassXC, Firefox and Vivaldi - installed from DEB packages as I mentioned in my original post. I didn't want to introduce other potential sources of issues.
> 
> OK, it's irrelevant now.

AppArmor can still prevent DEB packages to work.

**Comment by ferenczy** [comment]
> I find Firefox has been shipping with a restrictive AppArmor policy lately and it is totally unknown to the end users.

Wouldn't it prevent the integration from working completely? In my case it works for a while, then it doesn't for a while and then starts again.

> Any logs from the JavaScript console (both background and content scripts) would help.

I'll check it, but it's working now so it may take some time.

@varjolintu 
> AppArmor can still prevent DEB packages to work.

My concern was regarding the Snap and Flatpak. My issue doesn't have anything to do with either. But it's irrelevant now as the issue title has been changed already.

**Comment by droidmonkey** [comment]
> In my case it works for a while, then it doesn't for a while and then starts again.

This would indicate to me that you are maybe not keeping KeePassXC running. The connection is very deterministic, there isn't any randomness associated with the connection.

**Comment by ferenczy** [comment]
> This would indicate to me that you are maybe not keeping KeePassXC running.

Please, skip such obvious suggestions. I'm a software engineer for about 20 years already so I have enough experience to make sure that everything is set up correctly.

I'll describe it more clearly:

1. I navigate to some login form in the Firefox and notice the browser extension is signalling that the connection is inactive even though the KeePassXC is running
2. I click on the browser extension icon - it shows some error
3. I click on the _Reload_ button several times with just a few seconds between each click (just to read the error message), I don't do **anything** else meanwhile
4. It shows various errors after each _Reload_ and let's say after the fourth or fifth reload, it connects and starts working

There's just a few seconds between 1. and 4. and the only activities I'm doing meanwhile is clicking the _Reload_ button.

But it's unpredictable. Sometimes reloading doesn't help at all.

**Comment by droidmonkey** [comment]
It's always important to point out the obvious, as it is often overlooked. After you reload 4 or more times, does the connection remain stable? Your previous statements made it sound like it stopped working again randomly.

**Comment by ferenczy** [comment]
Well, I need to log in somewhere quite sporadically, so it may be several days or even weeks between those actions.

But one case I just found:

1. KeePassXC running, DB locked, extension reports disconnected
2. I click the extension, it says "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."
3. I click the _Reload_ button, it says "Key exchange was not successful."
4. Sometimes, the item 3 repeats a few times
5. I click the _Reload_ button, it says "Database not opened"
6. I click the _Reopen database_ button and the _Database unlock dialog_ is opened

It looks it happens in 100% of cases. Both the Firefox and Vivaldi.

**Comment by ferenczy** [comment]
Regarding the connection stability: I was creating another [issue](https://github.com/keepassxreboot/keepassxc/issues/10017) I have found during the current testing. I have opened a new tab, created a new issue, locked the database, unlocked it using the browser extension, finished the issue, posted it and noticed that the browser extension is disconnected again. And again, 3 reloads with 3 error messages followed by a successful connection (everything took maybe 2 seconds).

**Comment by varjolintu** [comment]
@ferenczy I'd suggest you provide some logs from these situations (told you the instructions before). Also monitor how `keepassxc-proxy` behaves. Is it still active when this happens, or is it killed for some reason? Does it make any difference if you close KeePassXC and reopen&reconnect it again?
