### ISSUE TITLE
Add {Group} placeholder

### ISSUE THREAD

**Issue by bonomani** [keepassxreboot/keepassxc#9945]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
As describe in Keepass:

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
example: user name = {REF:U@T:{Group}-ssh}

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Allow to make a group that use a password and another group that use another password and all entries are the same (my use case)

**Comment by droidmonkey** [comment]
Groups are just containers. You need to reference a specific entry when using references. This won't change, it is also part of the kdbx specification and we are not going to deviate from that.

**Comment by bonomani** [comment]
Not only container there is also a placeholder in keepass
