### ISSUE TITLE
HMAC mismatch after I do apt upgrade in ubuntu 23.04

### ISSUE THREAD

**Issue by rmntrvn** [keepassxreboot/keepassxc#9946]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Hello.
After running `apt upgrade` on Ubuntu 23.04 and rebooting the system, I can't unlock the keepassxc database, I enter the correct password, but I get the following error:
> Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

The packages that were upgraded when running the `apt upgrade` command are:
>Start-Date: 2023-10-19  22:15:55
Commandline: apt upgrade
Requested-By: rmntrvn (1000)
Install: linux-modules-extra-6.2.0-35-generic:amd64 (6.2.0-35.35, automatic), linux-headers-6.2.0-35:amd64 (6.2.0-35.35, automatic), linux-modules-6.2.0-35-generic:amd64 (6.2.0-35.35, automatic), linux-image-6.2.0-35-generic:amd64 (6.2.0-35.35, automatic), linux-headers-6.2.0-35-generic:amd64 (6.2.0-35.35, automatic)
Upgrade: linux-headers-generic:amd64 (6.2.0.34.34, 6.2.0.35.35), ubuntu-drivers-common:amd64 (1:0.9.7.1.1, 1:0.9.7.1.2), alsa-ucm-conf:amd64 (1.2.6.3-1ubuntu9.1, 1.2.6.3-1ubuntu9.2), linux-generic:amd64 (6.2.0.34.34, 6.2.0.35.35), vagrant:amd64 (2.3.7-1, 2.4.0-1), terraform:amd64 (1.6.0-1, 1.6.2-1), linux-image-generic:amd64 (6.2.0.34.34, 6.2.0.35.35), redis-tools:amd64 (6:7.2.1-1rl1~lunar1, 6:7.2.2-1rl1~lunar1), linux-firmware:amd64 (20230323.gitbcdcfbcf-0ubuntu1.6, 20230323.gitbcdcfbcf-0ubuntu1.8), virtualbox-6.1:amd64 (6.1.46-158378~Ubuntu~jammy, 6.1.48-159471~Ubuntu~jammy), linux-libc-dev:amd64 (6.2.0-34.34, 6.2.0-35.35)
End-Date: 2023-10-19  22:41:40

When updating packages, a UEFI password was requested.

For my database I did not use a hardware key or a key file. Only password. The password I am entering is 100% correct.

Please tell me how I can access the database.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. `apt upgrade` in ubuntu 23.04 with UEFI update
2.  reboot
3.  Try to unlock the base.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Unlock the base.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The database is not unlocked. Error:
> Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394
Qt 5.15.8
OS: Ubuntu 23.04
Arch: x86_64
Kernel: linux 6.2.0-35-generic

Enabled extensions:
- Автоввод
- Интеграция с браузером
- SSH-agent
- KeeShare
- YubiKey
- Интеграция со службой Secret Service

Криптографические библиотеки:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
If your password contains non-ascii characters then you need to show the password before typing them in. Otherwise, a simple apt upgrade would not have any bearing on the ability to unlock your database. The only explanation is a wrong password, or your database file is actually corrupted somehow. This is incredibly rare if not impossible. You do have a backup, right?
