### ISSUE TITLE
Support of the thorium browser

### ISSUE THREAD

**Issue by proofy** [keepassxreboot/keepassxc#9948]
## Summary
Thorium Browser is one of the fastest browsers on the market. It is based on Chromium and will probably soon be available for all operating systems. I use it for Linux. The only thing missing is the integration of KeePassXC, otherwise I would have switched already. 
When you try to connect, nothing happens. It may also be because I am doing something wrong. I use KeepassXC as a flatpak installation. It works together with Firefox installed via Debian deb.

## Sources
* https://thorium.rocks/
* https://github.com/Alex313031/thorium

**Comment by varjolintu** [comment]
Use the Custom Browser feature to add the browser to KeePassXC.
