### ISSUE TITLE
deepin,AppImage lacks "libfcitx5platforminputcontextplugin.so" and cannot enter Chinese

### ISSUE THREAD

**Issue by yaoyingkeji** [keepassxreboot/keepassxc#9949]
## Overview
[NOTE]: #KeePassXC.AppImage  FCITX5 cannot switch input methods and input Chinese
![录屏_选择区域_20231021234203](https://github.com/keepassxreboot/keepassxc/assets/93997433/3baed760-2232-44ac-9970-95d672823225)

## Steps to Reproduce
[NOTE]: #
1. Download: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.6/KeePassXC-2.7.6-x86_64.AppImage
2.Open KeePassXC-2.7.6-x86_64.AppImage
3. Create a database, enter the database name,Input method cannot be switched,Unable to enter Chinese
，Or anywhere you can enter text

## Expected Behavior
[NOTE]: # The input method can be switched normally
，can enter Chinese normally

## Actual Behavior
[NOTE]: # Anywhere you can enter text, you can't switch input methods, and you can't enter Chinese

[NOTE]: # KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Deepin 23
CPU architecture: x86_64
Kernel: linux 6.1.32-amd64-desktop-hwe

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # 
Operating System: Linux
Desktop Env: deepin
Windowing System: X11

**Comment by yaoyingkeji** [comment]
Picture: Everything is normal
![录屏_选择区域_20231022001214](https://github.com/keepassxreboot/keepassxc/assets/93997433/777d4d52-9b10-4f2d-8c4a-0ee2c81c7a52)

**Comment by droidmonkey** [comment]
We don't have that as a dependency so it would never be bundled with the appimage. You'll have to either get that library in your library load path or use an alternative distribution like snap or flatpak.
