### ISSUE TITLE
SSH Agent / Selecting 'Require user confirmation when this key is used' causes failed ssh login attempt

### ISSUE THREAD

**Issue by rolling-thundar** [keepassxreboot/keepassxc#9955]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new key
ssh-keygen -t ed25519 -a 100
2. Add the generated private key to keepassxc as attachment
3. Add the chosen password into the 'Password' field
4. Deselect these options:
- 'Add key to agent when database is opened/unlocked'
- 'Remove key from agent when database is closed/locked'
5. [IMPORTANT] Select the option 'Require user confirmation when this key is used'
--> this is the option causing trouble
6. Save the entry
7. Add key to SSH agent
8. Go to terminal and try to ssh into your server:
$ssh user@server

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A pop-up message asking me whether I want to login with this key to my server.

Once I click on 'Ok', I successfully connect to my server.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

I don't see the prompt message. Instead I get the following error message:

$ssh user@server
sign_and_send_pubkey: signing failed for ED25519 "user@client" from agent: agent refused operation
user@server: Permission denied (publickey).

## Context
[NOTE]: # ( Give us any additional information you may have. )

This problem only appears with the following SSH agent settings selected:

'Require user confirmation when this key is used'

As soon as I deselect the option, I can successfully ssh into my server.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Pop_OS)
Desktop Env: Regolith Desktop (3.0)
Windowing System: X11

**Comment by rolling-thundar** [comment]
The same behaviour happens when I login to Pop_OS with the default Gnome Desktop Env, instead of Regolith Desktop.

**Comment by droidmonkey** [comment]
This is on your ssh agent, if it doesn't support the setting then it generally fails to accept the key from us. Just disable the setting or use an ssh agent that supports this feature.

**Comment by rolling-thundar** [comment]
Gotcha. Thanks for the quick response.
