### ISSUE TITLE
Generate password right when user opens the entry creation page.

### ISSUE THREAD

**Issue by Yawan-1** [keepassxreboot/keepassxc#9956]
## Summary
Create a feature which generates the password right when users clicks on "**Add**" icon to add a new entry, so user don't have to extra click on "**Generate Password**" Icon to generate the random password and then "**Apply**" the password for the currently creating entry.

## Context
When I click on "**Add**" icon to create entry then every time I have to click on that Password generation icon and then "**Show password icon"** icon to see and copy it, then "**Apply password**" button to use it for the current entry and if it generates the password right when I open the entry creation page then it will take only one click which will be to see password.
It will save some seconds of the user if it generates the password right when user opens the entry creation page.

**Comment by droidmonkey** [comment]
#626

**Comment by Yawan-1** [comment]
.

**Comment by dhyanKaro** [comment]
> not planned

 \>:(
