### ISSUE TITLE
Entering password from stdin (--pw-stdin) breaks quick unlock

### ISSUE THREAD

**Issue by jayribkituse** [keepassxreboot/keepassxc#9957]
## Overview
I'm trying to set up KeePassXC to unlock from stdin (--pw-stdin) for the first unlock, and then use the quick unlock (Touch ID / Windows Hello) functionality for all subsequent unlocks.

This only works for the first unlock, i.e. when launching KeePassXC from the command line with the --pw-stdin option, entering the password, then unlocking via quick unlock.

Once the database locks, manual password entry is required again from the Unlock Database prompt before the separate quick unlock prompt.

The second prompt for the password should not be necessary.

## Steps to Reproduce
1. Enable quick unlock.
2. Launch KeePassXC from the command line with the --pw-stdin option, enter the password, then unlock via quick unlock.
3. Allow the database to lock on timer, or lock manually.
4. Trigger an unlocking of the database. Manual password entry is required again from the Unlock Database prompt before the separate quick unlock prompt.

## Expected Behavior
If KeePassXC is launched normally with quick unlock enabled and the password is entered normally from the Unlock Database prompt, the user is never prompted to enter the password again after the database locks the first time. All subsequent unlocks are handled by quick unlock.

This should be the expected and desired behavior when the password is entered from stdin, i.e. KeePassXC treats a password entered from stdin exactly the same as a password entered from the Unlock Database prompt.

## Actual Behavior
KeePassXC with quick unlock enabled and launched with the --pw-stdin option requires the password to be entered again from the Unlock Database prompt after the database locks for the first time.

## Context
KeePassXC - 2.7.6 (current), and several prior versions
Revision: dd21def
Operating System: Windows

**Comment by droidmonkey** [comment]
This is by design to accommodate both cli users and auto open users. This behavior is unlikely to be changed. 

The idea is of you are using cli to unlock your database then you are likely opening from a script and you don't want quick unlock. Why not just drop the --pw-stdin flag? It is literally same amount of work to just type it once keepassxc opens. 

#7612 and #9023

**Comment by jayribkituse** [comment]
Yes, the setup does involve piping in the password from a batch script that is stored securely.

It's for elderly people with various cognitive issues, and I'd like for them to be able to easily launch KeePassXC using a very strong password from a script, and then quick unlock subsequently with biometrics.

I want the password to be very strong since the databases are synced in the cloud.

This is how I have their password managers set up on their other devices, and it already works well for their purposes. So I purchased a bunch of biometric readers and set them up with KeePassXC on their personal computers only to discover this behavior.

How about either: 1) a configuration option; or 2) a separate flag to accommodate my suggested behavior?

Based on their threat model, this would not be any less secure, and certainly not any less secure than otherwise using a weak password or storing the password on a piece of paper or in a file. But the great tradeoff would be their being much less discouraged from using a password manager in the first place.

Thanks

**Comment by droidmonkey** [comment]
The proposed --quick-unlock flag in one of the above linked issues is the way, I'll prioritize that for implementation. We also need to fix passing pw-stdin and keyfile to the running instance, right now you have to quit keepassxc to successfully run the batch script again.

**Comment by jayribkituse** [comment]
Thanks so much for your consideration on this!
