### ISSUE TITLE
Option forcing KeePassXC to completely rewrite to original database location

### ISSUE THREAD

**Issue by Currrupted** [keepassxreboot/keepassxc#9958]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Most users will use their preferred way of synchronizing their databases to a remote location and/or across devices. This requires a database file to be updated to the preferred location immediately. To make sure that the location of saved databases is not obscured, the application should be able to be forced to work with a database file in the original directory only.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I could think of a option in the settings of KeePassXC (for example in _Basic settings_) which tells it to be orthodox about the original location of the database file. Perhaps there could even be a visualization which shows users how a file is being "transferred" (so to speak) from KeePassXC to the destination (and where that is).

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I have had problems with KeePassXC and file-based synchronization using Nextcloud. The changes were sometimes not written to the location of my hard disk (the directory, which translates to the Nextcloud server). They must have been written to a temporary location or somewhere else. Unfortunately I noticed only after I tried opening the database file after a reinstall. Nextcloud should (in theory) synchronize files as soon as they are changed, so it must have been either Nextcloud or KeePassXC.

**Comment by droidmonkey** [comment]
Use the alternative saving strategy of "direct write" to make sure you are editing just the current kdbx file on save. Generally this is unnecessary unless there is an actual problem with saving. https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_save_options
