### ISSUE TITLE
Keep the attachment file, Modify the properties of the time

### ISSUE THREAD

**Issue by yaoyingkeji** [keepassxreboot/keepassxc#9959]
Keep the attachment file, Modify the properties of the time.

Now after the attachment file is added, when saving to the local file, the modification time of the file will be changed to the time saved to the local time

**Comment by droidmonkey** [comment]
If you are referring to the temporary file made when opening the attachment, then that doesn't make sense to adjust modified time. If you are referring to the "save" button for attachments then modify created or modified time also doesn't make sense. Not sure what you are really asking for. Without clarity, this won't be considered. Thank you.

**Comment by JohnLGalt** [comment]
I read it as when extracting an attachment to local drive for use, adjust the time of the file to whatever it is as an attachment in the database. But this has to be a niche use case, for sure.

**Comment by yaoyingkeji** [comment]
> I read it as when extracting an attachment to local drive for use, adjust the time of the file to whatever it is as an attachment in the database. But this has to be a niche use case, for sure.

Yes, when we extract attachments to local disk, the modification time of the file is changed
