### ISSUE TITLE
Gnome 3: .desktop file needs to be named exactly like the binary

### ISSUE THREAD

**Issue by hkockerbeck** [keepassxreboot/keepassxc#996]
When KeePassXC is running, there's no option to add it to my favorites in the context menu of the Gnome 3 dash. When I added the app to my favorites in another way and start it, a second entry is added to the dash.

## Expected Behavior
When KeePassXC is running and I right-click on its entry in the Gnome dash, I should be able to add KeePassXC to my favorites.

When KeePassXC is a favorite and it is started, the existing dash entry should be used.

## Current Behavior
When KeePassXC is running, there is no option to add it to my favorites in the context menu of its dash entry.

When KeePassXC is favorite and it is started, a second dash entry is added.

## Possible Solution
Gnome 3 seems to be a bit particular with the name of the `.desktop` file. The file needs to be named _exactly_ like the executable. When I create a symbolic link from `.local/share/applications/keepassxc.desktop` to `/var/lib/snapd/desktop/applications/keepassxc_keepassxc.desktop`, everything works as intended. When I rename the symbolic link to `keepassxc_keepassxc.desktop`, the problems reappear.

So I'd suggest to rename `keepassxc_keepassxc.desktop` to `keepassxc.desktop`.

## Steps to Reproduce (for bugs)
1. Start KeePassXC
2. Right-click on entry in dash

## Debug Info
KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.4.0-96-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

Ubuntu 16.04 LTS, Gnome Shell 3.18.5

**Comment by droidmonkey** [comment]
Huh i never saw the desktop file named like that. Did you compile this yourself?

**Comment by hkockerbeck** [comment]
@droidmonkey I've installed the snap. I've got the following files

$ locate keepassxc.desktop
/home/henning/.local/share/applications/keepassxc.desktop
/snap/keepassxc/23/meta/gui/keepassxc.desktop
/snap/keepassxc/23/share/applications/keepassxc.desktop
/snap/keepassxc/23/snap/gui/keepassxc.desktop
/var/lib/snapd/desktop/applications/keepassxc_keepassxc.desktop

The first one is the symbolic link I described above, the others are as far as I know from the snap. Maybe snapd installs `.desktop` files to the collective `snapd/desktop/applications` dir with a scheme like "appname_filename.desktop"? That's just a guess, though.

**Comment by droidmonkey** [comment]
Snaps strike again!
