### ISSUE TITLE
Window header style in Gnome

### ISSUE THREAD

**Issue by devkornev** [keepassxreboot/keepassxc#9960]
KeePassXC 2.7.6 flatpak
Debian 12 (bookworm)
Gnome 43.6
Wayland

The style of the control icons in the window title does not match the system style.
Screenshot KeePassXC compared to other windows:

![keepassxc](https://github.com/keepassxreboot/keepassxc/assets/20462581/f983cf59-59c3-4874-a7ae-7cd7b2d88105)

I first installed the .deb version from official repository Debian, but it was older. That's why I chose flatpak.

I did the uninstallation KeePassXC 2.7.6 flatpak. Cleaned all directories and files using search mask keepass*. Then I installed KeePassXC 2.7.6 flatpak again. The problem persists.

**Comment by phoerious** [comment]
That's your window manager doing something differently. Perhaps a problem with XWayland.

**Comment by michaelk83** [comment]
Gnome is GTK, KeePassXC is Qt. You need to make sure your system is configured to style Qt apps the same way as Gtk apps. Also might be a Flatpak limitation in this case.
