### ISSUE TITLE
Password generator screen is blank

### ISSUE THREAD

**Issue by egglessness** [keepassxreboot/keepassxc#9961]
## Overview
Building from the commit 378c2992cd43811fec53e969c978fb710dcd3e01 of the `develop` branch, the password generator screen seems to be corrupted.

When clicking on the dice icon to open the password generator, the whole window becomes blank (except the menu bar).
![image](https://github.com/keepassxreboot/keepassxc/assets/14147983/34d006fa-8de7-409e-bda5-990bfecede95)

Opening it to generate a password in a entry works, though.

## Steps to Reproduce
1. Click on the dice icon in the main toolbar

## Expected Behavior
Password generator screen should appear (as in the 2.7.6 release)

## Actual Behavior
The password generator screen is blank

## Context
Build from 378c2992cd43811fec53e969c978fb710dcd3e01 in the `develop` branch

KeePassXC - Version 2.8.0
Revision: 378c299

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
We have a PR in place to fix this, thank you
