### ISSUE TITLE
Strikethrough capability in editor

### ISSUE THREAD

**Issue by bakoontz2** [keepassxreboot/keepassxc#9962]
## Summary
Ability to strikethrough text in Notes editor (sometimes it's useful to keep old deprecated info around).

## Examples
I tried to do a screenshot but the UI disappears each time the Snipping Tool is invoked in Windows (a security thing?)

## Context
I keep lots of notes in my application.  It's useful for  me to be able to clearly show stuff that has been deprecated but might still be useful to refer to in the future.

**Comment by michaelk83** [comment]
#1057
You can already use the markdown syntax, it just won't be rendered as striked-through yet.

**Comment by bakoontz2** [comment]
Awesome, thank you!
