### ISSUE TITLE
keepassxc-cli: show with non-unique entry names

### ISSUE THREAD

**Issue by matbech** [keepassxreboot/keepassxc#9963]
The show command is not able to display entries which do not have a unique name.

## Steps to Reproduce
1. Create a database with two entries, both having the same name.
2. Ensure 2 entries with the same name are present:
`keepassxc-cli.exe search "Database.kdbx" *`
```
/Test/test
/Test/test
```
3. call show
`keepassxc-cli.exe show "Database.kdbx" --all /Test/test`

## Expected Behavior
Error. Entry is ambiguous.

## Actual Behavior
Always the first entry is shown.

## Proposal
Add an option to the cli to show an entry by its uuid:
`keepassxc-cli.exe show "Database.kdbx" --all --uuid {ddf0b4c0-3218-2244-aa8a-22d86d5b7f97}

Related to this recent change:
https://github.com/keepassxreboot/keepassxc/pull/9571

**Comment by droidmonkey** [comment]
#3720
