### ISSUE TITLE
2.8.0-snapshot - Password generator draws a blanc

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#9965]
- Start the Password Generator (via menu or icon)
- Draws a blanc window contents

KeePassXC - Versie 2.8.0-snapshot
Bouwtype: Snapshot
Revisie: 6f2354c

Qt 5.15.6
De foutopsporingsmodus is uitgeschakeld.

Besturingssysteem: Windows 10 Version 2009
CPU-architectuur: x86_64
Kernelversie: winnt 10.0.22621

Geactiveerde extensies:
- Auto-type
- Browserintegratie
- Passkeys
- SSH-agent
- KeeShare
- YubiKey
- Snel ontgrendelen

Cryptografische bibliotheken:
- Botan 2.19.1

**Comment by Stephan-P** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/10008599/420a57e3-bc7b-4977-8b6a-89b43bf9f031)

**Comment by droidmonkey** [comment]
Yes we know, fix is in the pipeline right now. https://github.com/keepassxreboot/keepassxc/pull/9743
