### ISSUE TITLE
2.8.0-snapshot - deploy Transifex keepassxc_en.ts (develop) translations

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#9966]
It seems to me as if 2.8.0-snapshot does not yet deploy Transifex keepassxc_en.ts (develop) translations.
Or am I mistaken?

![image](https://github.com/keepassxreboot/keepassxc/assets/10008599/6095c22e-4f22-45ba-a029-3bb824cb4966)

**Comment by droidmonkey** [comment]
This is done prior to an actual release, we generally do not pull translations for snapshots. Doesn't hurt to do a pull and merge it now though

**Comment by Stephan-P** [comment]
O please do, as I'm getting along quite nicely with that translation branch.
I'm looking forward to the next snapshot to experience the results.

**Comment by Stephan-P** [comment]
Dutch language is ready for it.
All verified through export of .ts and conversion into .qm using Qt linguist

**Comment by droidmonkey** [comment]
Just pushed the latest batch of translations to develop
