### ISSUE TITLE
To change icon in taskbar when KeePassXC is locked

### ISSUE THREAD

**Issue by dnai05** [keepassxreboot/keepassxc#9969]
## Summary
Would it be possible to change the KeePassXC icon in the taskbar when the database is locked.

## Examples
Maybe like the icon that KeePassXC-Browser displays when the database is locked

## Context
I often have many windows open and it would help if I could quickly see if KeePassXC is locked or not.

**Comment by varjolintu** [comment]
Is this on Windows or Linux? At least in macOS the icon changes based on the database lock status:
<img width="30" alt="Screenshot 2023-10-27 at 7 21 21" src="https://github.com/keepassxreboot/keepassxc/assets/24570482/9bfd7825-904d-4283-9504-f053c10aef0f">
<img width="38" alt="Screenshot 2023-10-27 at 7 21 13" src="https://github.com/keepassxreboot/keepassxc/assets/24570482/14f54688-6a1c-4536-9042-b2c52d0b9098">

**Comment by dnai05** [comment]
My apologies. Details are:
- Windows 11
- KeePassXC 2.7.6

**Comment by phoerious** [comment]
Same there. Do you mean the application icon instead of the tray icon?

**Comment by droidmonkey** [comment]
He means the application icon. I don't think that can be changed once the app is launched on any platform. It is also extremely inconsistent capability between platforms. We already support this through the tray icon, we won't do the same for the app icon.

**Comment by phoerious** [comment]
At least macOS has dynamic icons. The calendar icon always showing the current date is one example.

**Comment by darkyoukon** [comment]
The default KeePass implementation on Windows has different icons displaying the current DB state (locked or unlocked).
If any platforms limit such a possibility - it shouldn't be cut out from the entire project (refer to the telegram app feature set on different platforms).

Also, the current tray icon design is hardly recognizable. The red colour is much more clear for the sight than the tinted yellow one.
