### ISSUE TITLE
Translate Templates?

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#9971]
The Database entry templates have English language titles.
It would be nicer if these could be in the selected locale as well.

![image](https://github.com/keepassxreboot/keepassxc/assets/10008599/641a6c31-6850-4535-a608-17899bcfee78)

**Comment by droidmonkey** [comment]
Those aren't from us, we don't create any template entries.

**Comment by Stephan-P** [comment]
Aha, must have come from KeePass, KeePassDX or KeeWeb.
Apologies for the confusion
