### ISSUE TITLE
2.8.0-snapshot - Deploy Transifex Pluralized translations?

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#9973]
In Transifex there's a range of strings that use the pluralized option.
[https://app.transifex.com/keepassxc/keepassxc/translate/#nl/share-translations-keepassxc-en-ts--develop/475486527?q=pluralized%3Ayes](https://app.transifex.com/keepassxc/keepassxc/translate/#nl/share-translations-keepassxc-en-ts--develop/475486527?q=pluralized%3Ayes)
The English language source strings however are all in the ambiguous form, e.g. %n column(s)
While they could have been made specifically singular (%n column) and plural (%n columns)

Is it the aim to deploy this option in Transifex (and possibly the code) and make proper distinction between singular and plural?

![image](https://github.com/keepassxreboot/keepassxc/assets/10008599/d32b16ae-a4aa-45b1-9926-68ea7de80507)

**Comment by droidmonkey** [comment]
That's how Qt works, it chooses the correct form based on a number provided to the translator function. 

In transifex you translate the singular. Click the other button you highlighted there, then translate the plural. This is standard ops for translations...
