### ISSUE TITLE
Unlock AutoType issue 

### ISSUE THREAD

**Issue by VictorVow** [keepassxreboot/keepassxc#9974]
Unlock https://github.com/keepassxreboot/keepassxc/issues/2281 as there's now a [global shortcut portal](https://github.com/flatpak/xdg-desktop-portal/pull/711) in Flatpak.

**Comment by droidmonkey** [comment]
That is not the main problem with Auto-Type on Wayland

**Comment by VictorVow** [comment]
The last post on that issue specifically pointed to the lack of this portal and even linked to this same issue upstream, which has now been resolved. 

What is the problem then if not this?

**Comment by droidmonkey** [comment]
That is a portal for flatpak, not for wayland. It is also one of 3 distinct problems with providing auto-type on Wayland. Read the entire issue thread.

**Comment by VictorVow** [comment]
My apologies then, I thought the last post before locking summarised the two issues that needed resolving and I saw that they had both been closed now.
