### ISSUE TITLE
Generates wrong TOTP after time switch

### ISSUE THREAD

**Issue by TGrade** [keepassxreboot/keepassxc#9975]
## Overview
Generates wrong TOTP after time switch. Tried another TOTP app and it generates correct one.

## Steps to Reproduce
Not sure.

## Expected Behavior
Generates correct time when switching to summer/winter time

## Actual Behavior
Generates wrong totp

## Context
I tried playing with time on my pc by changing time 1 hour less and more, but it didn't work. What did work is setting my timezone to UTC. For me it looks like TOTP works somehow only for summer time?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by ejdaly** [comment]
Just noticed something similar (summer time ended about 15 mins ago in Ireland..., thought I had messed up my TOTP set up 😂).

Just restarting KeepassXC fixed the issue...
(Same version / OS as above)

Related:
https://github.com/keepassxreboot/keepassxc/issues/8723

**Comment by TGrade** [comment]
I tried to restart it by clicking "Quit" on the program and it didn't help. But also noticed some background process was still running. Maybe I didn't restart it properly?
Anyway I think it should work regardless of client's or server's timezone. I'm not sure about implementation here, but maybe just take unix time or something?

**Comment by droidmonkey** [comment]
TOTP is calculated off of unix time based on your computer's clock. This could be a Qt glitch in the function that provides the unix time though.

**Comment by Remonli** [comment]
Looks like if system time zone changed，TOTP goes wrong.
