### ISSUE TITLE
"Distraction-free mode" for tray icon

### ISSUE THREAD

**Issue by QuAzI** [keepassxreboot/keepassxc#9976]
Please provide a new option to use a grayscale icon when app locked or when app locked and Focus Assist is on
![image](https://github.com/keepassxreboot/keepassxc/assets/1897605/8dd3ddbf-2f37-4545-97a4-be9a0cc9f0fc)
and to use colored icon when app active or DB unlocked
![image](https://github.com/keepassxreboot/keepassxc/assets/1897605/8e860b35-3803-449c-bfb5-cf582a7bf758)

**Comment by droidmonkey** [comment]
No thank you, we won't cross the monochrome and colored icons.
