### ISSUE TITLE
KeePassXC closes itself at random frequency

### ISSUE THREAD

**Issue by SBS-BAC** [keepassxreboot/keepassxc#9977]
Hello

## Overview

From time to time, but usually daily, the KeePassXC application closes itself. It is random and I can't identify the trigger.
I need to reopen my database.

## Steps to Reproduce

I can't provide steps to reproduce the issue. It is random and I haven't been able to find what triggers this closure.

## Expected Behavior

That the application remains open all day long and that it doesn't close itself.

## Actual Behavior

From time to time, but usually daily, the KeePassXC application closes itself.

## Context

This issue happens since the last release. It wasn't the case before.

KeePassXC - Version 2.7.6
Revision: dd21def

Operating System: Windows
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19045 Build 19045

Thank you for your help,
Kind regards,
Célien

**Comment by droidmonkey** [comment]
Unfortunately, it is impossible to do anything about this without a crash dump or obvious trigger.

Have you tried downgrading to the previous version to see if it still happens?  

Do you have an endpoint protection program that might be taking us down?

Are you actively using KeePassXC when this happens, or is it always "in the background"?

**Comment by SBS-BAC** [comment]
Do you have an endpoint protection program that might be taking us down?

> That's a professional computer so our internal IT has something in place but I don't think that's linked. KeePassXC is recommended by our IT.

Are you actively using KeePassXC when this happens, or is it always "in the background"?

> That's in the background - The application doesn't close itself in the middle of a copy paste.

**Comment by SBS-BAC** [comment]
I downgraded to the 2.7.5 version. I'll keep you informed if I still face the issue.

KeePassXC - Version 2.7.5
Revision: 9d0537b

Thanks for your quick answer.

**Comment by SBS-BAC** [comment]
Hello @droidmonkey ,

Since I downgraded to the 2.7.5 version, I don't have the issue anymore.
I propose to close this ticket.

Kind regards,
Célien
