### ISSUE TITLE
TOTP Code Doesn't Work

### ISSUE THREAD

**Issue by Major-Mike** [keepassxreboot/keepassxc#9978]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setting up a new TOTP for a website
2. Offers QR code and code (otpauth://totp/<redacted>?secret=XNZP2V7CRJEMLWRBNEIB4WPSALSVVU6SZXYSQ4TYQ3YU34IMTX5BFSCLMMPWXUI2RZD6SGV6SVH52CMFRPHILRRF4ULEC36HMHF4OYQ
3. Setup TOTP with the code
4. Enter the code and it doesn't accept
5. Setup on Microsoft Authenticator using the QR
6. Works immediately
7. Setup on 1Password on the same machine using the code
8. Works immediately

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
This should just work like any other TOTP that I have setup, there is nothing special about this one.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It will not work and will not accept the code that is generated.

## Context
[NOTE]: # ( Give us any additional information you may have. )
It cannot be the system time. Both 1Pass and KeePass are on the same machine. Additionally if it was the time then it would fail on all the existing ones too, they don't.

I am completely at a loss, this is the first time I am having an issue like this.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro
Desktop Env: 22H2 Build 22621.2428

**Comment by droidmonkey** [comment]
Your secret code is just XNZP2V7CRJEMLWRBNEIB4WPSALSVVU6SZXYSQ4TYQ3YU34IMTX5BFSCLMMPWXUI2RZD6SGV6SVH52CMFRPHILRRF4ULEC36HMHF4OYQ

Don't include the otpauth part

**Comment by Major-Mike** [comment]
I am aware how it is done, like I explained not my first time. I provided you what KeePassXC creates as the OTP. Are we ready in such a rush to close tickets that we don't even try?

**Comment by droidmonkey** [comment]
I added that to an entry and it made a TOTP code just fine. I cannot possibly test if it is the _correct code_....

**Comment by JohnLGalt** [comment]
Did you try removing and setting it up again?

**Comment by Major-Mike** [comment]
Sorry just got back into town. It adds and generates fine, that's not the issue, the issue is the code is not accepted. And other codes are generated and accepted fine, new codes setup and accepted, just not this one. If it was publicly accessible site, I would give it to you to try yourself. Yes John I have done that about 50 times so far, 30 years in IT, if it was that easy to fix, I wouldn't have reported the issue. Thanks.

**Comment by michaelk83** [comment]
If it's a private site, could it be that the server time is incorrect?

**Comment by JohnLGalt** [comment]
Having no idea who you are or what you have tried other than your report, my apologies for irking you, from another person with over 30 years in the IT industry.

But one thing you did not mention is if all three of your testbeds (KPXC, 1P and M$A) are producing the **same code** at the same time. 

Another idea would be to see if it still happens with a new test database, and compare the code it generates with the working ones too.

**Comment by Major-Mike** [comment]
@michaelk83 I thought about that, they insisted it is correct and it works with M$ Authenticator

**Comment by Major-Mike** [comment]
@JohnLGalt I'm sorry for being short with you, it has been a stressful time and this issue is not helping. I have not checked all three simultaneously, I suppose I should. Thanks.

**Comment by JohnLGalt** [comment]
All good. We're human.

I am curious to see if the same codes are produced, that would go a long way to figuring out if it is a problem with the settings for code creation or the settings for KPXC copying the resulting code.
