### ISSUE TITLE
KDE Bug: Polkit unlock dialog is not brought to front

### ISSUE THREAD

**Issue by rpedrica** [keepassxreboot/keepassxc#9981]
## Overview

(This behaviour started with the new 2.8.0-snapshot as of 26 Oct 2023). When using a global autotype shortcut to input credentials into a login form on a web page while the keepassxc db is locked, one normally sees an input dialog box for the keepassxc password. This dialog box is visually present in front of the keepassxc main window.

With the snapshot release, the input dialog box is now behind the keepassxc screen (which is greyed to infer it is not currently selected) and does not always take focus for the password input. This results in unusual behaviour where the password may not be taken at all, or is taken but focus is not taken back to the browser, or is taken, focus is taken back to the browser but the credentials are not input.

One often has to bring the password input box into focus first before inputting the password, and then use global auto-type for a 2nd time to get the credentials to input on the website login.

![keepassxc-main](https://github.com/keepassxreboot/keepassxc/assets/1016286/fad3baa9-3264-4d22-a0ae-b8e766926f2d)

This screenshot shows the main keepassxc window as in front but greyed (inferring it does not have focus). The password input box is behind this window.

![keepassxc-dialog](https://github.com/keepassxreboot/keepassxc/assets/1016286/95ce2621-d494-4e5e-9c9d-7acfed4ef1ee)

One can manually bring the password input box to the front and in focus.

## Steps to Reproduce

1. get browser focus to the login on a website page
2. input your global auto-type shortcut
3. keepassxc comes to the fore and the password input box is now behind the keepassxc window

## Expected Behavior
1. The password input box to unlock keepassxc should be visible and take focus so one can enter the password
2. the credentials for the specific site login should be input into the site login

## Actual Behavior
1. the keepassxc db unlock password may not be take at all
2. the keepassxc db unlock password is taken but focus is not taken back to the browser
3. or the keepassxc db unlock password is taken, focus is taken back to the browser but the credentials are not input.

## Context
upgrade from 2.7.6 to 2.8.0-snapshot (26/10/2023)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 6f2354c

Operating System: Linux (Slackware 15.0+ [current])
Desktop Env: KDE
Windowing System: X11

Full info:

```
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 6f2354c

Qt 5.15.11
Debugging mode is disabled.

Operating system: Slackware 15.0 x86_64 (post 15.0 -current)
CPU architecture: x86_64
Kernel: linux 6.1.60

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

**Comment by droidmonkey** [comment]
This is due to the new polkit integration. Your DE is failing to raise the polkit prompt to the top of the stack.

**Comment by droidmonkey** [comment]
@HexF

**Comment by michaelk83** [comment]
> This is due to the new polkit integration.

Specifically, QuickUnlock.

IIRC, there was an upstream bug in KDE that prevents PolKit from raising its window to the front. I don't know if it might be possible to work around that for this particular use case.

**Comment by rpedrica** [comment]
@droidmonkey  abd @michaelk83

1. thanks very much for the feedback
2. Just to clarify, are you saying there is new polkit integration in keepasscx 2.8 or in KDE?

**Comment by droidmonkey** [comment]
In keepassxc 2.8

**Comment by HexF** [comment]
The polkit dbus interface gives us very [minimal control over the polkit prompt](https://www.freedesktop.org/software/polkit/docs/0.105/eggdbus-interface-org.freedesktop.PolicyKit1.Authority.html#eggdbus-method-org.freedesktop.PolicyKit1.Authority.CheckAuthorization), so I don't think there is anything we can do from within KeepassXC.


[This KDE bug report](https://bugs.kde.org/show_bug.cgi?id=312325) seems relevant

**Comment by droidmonkey** [comment]
Yup looks completely relevant and also completely out of our control.

**Comment by rpedrica** [comment]
Wow, that polkit/kwin issue has been around a long time. I will try the focus stealing prevention control on the specific window and see if this resolves.

Forgive my ignorance if this is a stupid question (IANAP), but isn't it possible to just revert the "new polkit integration" or is this a dependency for something else in keepasscx?

**Comment by michaelk83** [comment]
> is this a dependency for something else in keepasscx?

It's needed for QuickUnlock. [#5991](https://github.com/keepassxreboot/keepassxc/issues/5991#issuecomment-1196247054)

PolKit should use your fingerprint reader if one is available and configured, otherwise it should fallback to some sort of password or PIN, as defined in your system settings. That's probably what that dialog is asking for, not your KeePassXC database password.

If you don't want to use QuickUnlock, you can disable it in the settings.

https://keepassxc.org/docs/KeePassXC_UserGuide#_quick_unlock

**Comment by rpedrica** [comment]
Thanks @michaelk83, QuickUnlock disabled and issue resolved. Closing this issue ticket.
