### ISSUE TITLE
"Start only a single instance of KeePassXC" option stops working after a long time

### ISSUE THREAD

**Issue by ion201** [keepassxreboot/keepassxc#9982]
## Overview
I open keepassxc when my pc starts and tend to never close it. I'm currently sitting at 24 days of uptime, so that's likely how long keepassxc has been open, along with suspending the system daily. It doesn't happen right away, but after some time I'll go to open keepass from the menu, and notice that it opens a second window even though there's already an active keepassxc window in the system tray.

Not sure if this is new behavior, but I've used keepassxc for several years now and have only first taken note of this maybe a few months ago.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open keepassxc
2. Wait for 2 weeks. Not sure how long it actually takes

## Expected Behavior
Keepassxc should never open more than one window.

## Actual Behavior
Running keepassxc opens a second window. If I run it from the command line, I get this error:

```
Existing single-instance lock file is invalid. Launching new instance.
```

## Context
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.11
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.5.6-arch2-1
Desktop Env: Cinnamon
Windowing System: X11

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.2.0

**Comment by droidmonkey** [comment]
I think you have two keepassxc's installed on your system. One from snap or flatpak and the other a native install. 

That's one idea, another is that the KeePassXC starting on startup is running too early and not able to write the lockfile used to manage single instance.

**Comment by ion201** [comment]
I don't have snap or flatpak anything installed on this system. Can confirm that both instances are identical
```
nate@spicy-tuna ~ > ps aux | grep keepass
nate        1649  0.0  0.8 1536552 143504 ?      SLl  Oct09   0:36 /usr/bin/keepassxc
nate       93390  0.6  1.1 1438388 194312 ?      SLl  19:55   0:00 /usr/bin/keepassxc
nate@spicy-tuna ~ > pacman -Qo /usr/bin/keepassxc
/usr/bin/keepassxc is owned by keepassxc 2.7.6-2
```

This lockfile does exist and is dated around 3 weeks ago as expected (I assume this is the right file, I just glanced at a quick strace to find it).
```
nate@spicy-tuna ~ > ls -l /tmp/keepassxc*
-rw-r--r-- 1 nate nate 96 Oct  9 21:39 /tmp/keepassxc-nate.lock
nate@spicy-tuna ~ > cat /tmp/keepassxc-nate.lock
1649
keepassxc
spicy-tuna
f129fae92458418ea38eab82c5ff1f74
e9259489-bfdd-47d8-a5b7-e50941324c06
```

I did also notice here that the file `/tmp/keepassxc-nate.socket` does not exist at the moment, but was created when the second keepassxc instance started; and removed when the second instance is closed. Not sure if that matters.

The strace of the second instance probably isn't too useful, but I've already got it so will upload here just in case - [strace-keepassxc-second-instance.txt](https://github.com/keepassxreboot/keepassxc/files/13255524/strace-keepassxc-second-instance.txt)

**Comment by droidmonkey** [comment]
Do you have a process that cleans up your tmp directory on a periodical basis?

**Comment by ion201** [comment]
I don't have anything like that which would clear out /tmp. I can set up a file watch though and find out when it's getting deleted. 
Looks like that socket file in /tmp the file to look out for?

**Comment by droidmonkey** [comment]
Yes

**Comment by ion201** [comment]
Going to close this because I haven't been able to reproduce it since my last comment. If it wasn't a fluke, I'll at least have better diagnostic information next time, it's not clear right now that this wasn't an external issue.
