### ISSUE TITLE
Password Generator window does not show

### ISSUE THREAD

**Issue by HexF** [keepassxreboot/keepassxc#9983]
## Overview

Password generator window isn't shown in latest snapshot builds.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open "Password Generator" menu

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Password Generator window should show

## Actual Behavior
Blank window is shown
![image](https://github.com/keepassxreboot/keepassxc/assets/11236933/75bc2551-0439-4697-8da3-801e679969a2)

## Context

Compiled with `-DWITH_XC_ALL=ON`

KeePassXC - 2.8.0-snapshot
Revision: 6f2354c0e94e79b0a87d9f116957df5a509149ed

Qt 5.15.10
Debugging mode is disabled.

Operating system: NixOS 23.05 (Stoat)
CPU architecture: x86_64
Kernel: linux 5.15.131

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

Operating System: Linux
Desktop Env: i3wm
Windowing System: X11

**Comment by droidmonkey** [comment]
We know, use the latest snapshot (available in about 20 min)

**Comment by HexF** [comment]
Can confirm it is fixed in 454dc7169da07793d9123f35a69e806e3073c9fd
