### ISSUE TITLE
[x86_64] Support

### ISSUE THREAD

**Issue by ThePredators** [keepassxreboot/keepassxc#9985]
## Summary
Hello, 

I saw that in the last release version 2.7.6 there is no more x86_64 dmg, are you going to upload one ? 

If not can we have at least the cmake script so that everyone who need it can generate it ?

Thanks a lot,
Have a nice day.

**Comment by droidmonkey** [comment]
Huh? It's right here: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.6/KeePassXC-2.7.6-x86_64.dmg
