### ISSUE TITLE
HMAC mismatch error

### ISSUE THREAD

**Issue by syntcom** [keepassxreboot/keepassxc#9986]
## Overview
I have a kdbx file protected with a password. Yesterday I was able to use the file on two different computers. Today both files on both computers do not work any more. I tried different backups back to one week ( I have daily incremental backups) none of them work any more. Installed keepass on android. Same thing. I know it is the correct password, because I have written it down somewhere else. Uninstalled keepass, restarted pc... nothing works.
Tried to turn the clock back in windows to yesterday, since this is the only thing that has changed I think. Did not work.
Very strange and not very confidence inspiring. Wanted to bring all my passwords that I use for clients to keepass soon. Fortunately I did not do that.
Does anyone have any ideas?

## Steps to Reproduce
1. install latest version of keepassxc on windows 10/11
2. make a new kdbx file with password protection
3. wait for x days and try to reopen it with the correct password

## Expected Behavior
File opens

## Actual Behavior
HMAC mismatch error

## Context
Keepassxc 2.7.6 on windows 10 and 11 with and without firefox connector
worked on 03.11.2023 and stopped working 04.11.2023 on all my machines. Tried different backups back to one week. Tried on a fresh installation on android and a virtual machine. Tried with the original keepass. no luck.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/Android
Windowing System: 10.0.19045 Build 19045

**Comment by droidmonkey** [comment]
Unfortunately there is nothing we can do, as you may have read in the other post. The only explanation, especially when you consider backups not opening, is that you are mistyping the password. If it doesn't even work on Android (which is a totally different application) then it's not a problem unique to keepassxc. 

Obviously there is no such thing as a timeout or time-based corruption. Time has absolutely nothing to do with a kdbx database. Hundreds of thousands of people (if not a million) use this program, there is no systemic problem that we are aware of that would cause repeatable corruption.
