### ISSUE TITLE
fix typo: s/SSH_AUTH_SOCKET/SSH_AUTH_SOCK/

### ISSUE THREAD

**Issue by Martin-Buchholz** [keepassxreboot/keepassxc#9988]
$ git diff -U0
diff --git a/docs/topics/UserInterface.adoc b/docs/topics/UserInterface.adoc
index b60b28a6..456c09ea 100644
--- a/docs/topics/UserInterface.adoc
+++ b/docs/topics/UserInterface.adoc
@@ -89 +89 @@ Additionally, the following environment variables may be useful when running the
-|SSH_AUTH_SOCKET                | Path of the unix file socket that the agent uses for communication with other processes (SSH Agent)
+|SSH_AUTH_SOCK                  | Path of the unix file socket that the agent uses for communication with other processes (SSH Agent)

**Comment by droidmonkey** [comment]
Can you submit a PR?

**Comment by Martin-Buchholz** [comment]
Thanks!  "Learn how to use github cli" has been on my TODO list for too many years!
