### ISSUE TITLE
Outdated links attached to question marks in the DB unlock view

### ISSUE THREAD

**Issue by KORraNpl** [keepassxreboot/keepassxc#9989]
## Overview
After launching KeePassXC, user can provide key file and hardware key. Next to these fields, there are question marks that open Docs:
* https://keepassxc.org/docs#faq-cat-keyfile
* https://keepassxc.org/docs#faq-cat-yubikey

Both links have outdated anchors (I think that's how it's called, the part after `#`), so browser does not scroll to the desired part.

## Steps to Reproduce
1. Open a DB that requires password/keyfile/hardware key.
2. Click question mark next to "Key File" or "Hardware Key".
3. Observe webpage opened in browser.

## Expected Behavior
Docs open and scroll to desired section.

## Actual Behavior
Docs are opened at the top of Docs page.

## Context
URL in docs changed in keepassxreboot/keepassxc-org@3f63988 I was thinking about simply creating a PR, but I'm not sure if it should be fixed in KeePassXC or in Docs (so older versions, potential links from 3rd part websites are fixed).

KeePassXC - Version 2.7.6
Revision: dd21def

Operating System: macOS

**Comment by droidmonkey** [comment]
This should be fixed in KeePassXC
