### ISSUE TITLE
Keepassxc crashes after minimizing to tray with browser integration enabled

### ISSUE THREAD

**Issue by mak448a** [keepassxreboot/keepassxc#9990]
## Overview
If I check the following: "Minimize instead of app exit", "Show system tray icon", "Hide window to tray when minimized", "Enable browser integration", and "Firefox" inside of the browser integration section, then it crashes when minimized to tray.

## Steps to Reproduce
See overview

## Expected Behavior
It doesn't crash

## Actual Behavior
Crashes

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.5.9-200.fc38.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.2.0

Windowing System: Wayland

**Comment by droidmonkey** [comment]
I cannot replicate this at all. I assume you are using KDE on Wayland. Please see #9979 for tips on how to debug flatpak issues.

**Comment by mak448a** [comment]
I reinstalled it and cleared the flatpak data and it fixed it

**Comment by droidmonkey** [comment]
Excellent
