### ISSUE TITLE
"Unsaved changes" in an unchanged entry block autolocking on system lockscreen activation - Linux

### ISSUE THREAD

**Issue by secretmango** [keepassxreboot/keepassxc#9992]
## Steps to Reproduce
1. In KeepassXC I have the option to automatically lock the vault when the screen is locked
2. I have disabled autosave as it always saves even without changes
3. I open up an entry and copy something from there, no changes
4. I lock my screen and unlock it again

## Expected Behavior
Lock the vault, as there where no changes.

If there where changes, save a copy of the vault somehow and lock it anyways.

It can't just stay open, this is a security issue

## Actual Behavior
There are two bugs here, I couldnt find them:

- KeepassXC doesnt detect that I didnt change anything. I dont know why, but it thinks I changed something when I open the entry. I have preview disabled so this is necessary
- Due to this, it doesnt lock but say "unsaved changes, save now?" This breaks the security benefit of autolocking when the screen is locked

So if the first issue was fixed, this would be kinda okay. But you may have edited a document and somebody stole your laptop, idk. If this "lock when system is locked" should work, then it has to save the currently edited vault in a backup file and lock it anyways.

```
Specified App:
keepassxc-2.7.6-3.fc38.x86_64

--- Software ---
OS: Fedora Linux 38.20231104.0 (Kinoite)
KDE Plasma: 5.27.8
KDE Frameworks: 5.110.0
Qt: 5.15.11
Kernel: 6.5.8-200.fc38.x86_64
Compositor: wayland
```

**Comment by droidmonkey** [comment]
This is covered by #721
