### ISSUE TITLE
Ctrl+Mouse Wheel no longer changes password text size in 2.7.6 on Windows 11

### ISSUE THREAD

**Issue by bhatwork** [keepassxreboot/keepassxc#9994]
## Overview
After upgrading from 2.7.5 to 2.7.6 on Windows 11, using ctrl+mouse wheel no longer changes the size of the password text.

## Steps to Reproduce
1. Click on an entry so that the General/Advanced/Autotype tabs appear.
2. In the General tab, click the eye icon next to Password so that the password text is displayed.
3. Move the cursor over the visible password text.
4. Press Ctrl and scroll the mouse wheel.

## Expected Behavior
The text changes size as a result of using the mouse wheel.

## Actual Behavior
The text size doesn't change.

## Context
This worked as expected in 2.7.5.  It also still works in other applications, such as Notepad, Chrome, etc.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Enterprise, Version 22H2
Desktop Env: Windows

**Comment by droidmonkey** [comment]
This was never a feature we (intentionally) had. I didnt even know this was possible. If anything this is a qt regression. Since we haven't implemented it we can't fix it.
