### ISSUE TITLE
Ignore of `Hide TOTP in the entry preview panel` option after restart

### ISSUE THREAD

**Issue by Yankes** [keepassxreboot/keepassxc#9996]
## Overview
As TOTP value is some how critical value I prefer is not show until I need use it.
But program some times do not respect this option.

## Steps to Reproduce
1. Set `Hide TOTP in the entry preview panel`
2. Restart APP
3. First entry selected after restart have set TOTP

## Expected Behavior
`Display current TOTP` is closed

## Actual Behavior
`Display current TOTP` is visible until clicked and then its work as expected.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
good find

**Comment by jolinux** [comment]
Info:  Linux Debian Bookworm same issue

use now cli     
oathtool  

(from Debian repositories/packages )

Info to use it
https://www.cyberciti.biz/faq/use-oathtool-linux-command-line-for-2-step-verification-2fa/


Jörg
