### ISSUE TITLE
"% 1" in various fields

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc#9997]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

![image](https://github.com/keepassxreboot/keepassxc/assets/133706/97694559-06ce-4bfa-a9aa-a784ad791b49)
 
![image](https://github.com/keepassxreboot/keepassxc/assets/133706/09b04d66-6446-46cb-a4e7-704ae90139f7)
(status bar, left-most)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

_Looks like a %-format string replaced wrong_

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Έκδοση 2.7.6
Αναθεώρηση: dd21def

Qt 5.15.10
Η λειτουργία debugging είναι απενεργοποιημένη.

Λειτουργικό Σύστημα: Windows 10 Version 1909
Αρχιτεκτονική Επεξεργαστή: x86_64
Πυρήνας: winnt 10.0.18363

Ενεργοποιημένες επεκτάσεις:
- Αυτόματη-Γραφή
- Ενσωμάτωση Προγράμματος Περιήγησης
- πράκτορας SSH
- KeeShare
- YubiKey
- Γρήγορο Ξεκλείδωμα

Κρυπτογραφικές βιβλιοθήκες:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
This needs to be fixed over at transifex for this language. The translator added an erroneous space
